### ISSUE TITLE
Clockwork engine broken

### ISSUE THREAD

**Issue by TheGameGeek** [FTBTeam/FTB-Continuum#10]
* **Modpack Version**: 1.0.0
* **Issue**: You cannot create the clockwork engine
* **link to image of the issue**: https://gyazo.com/4a88d315979afce18fac5fcde71dee5d
* **Is it Repeatable?**: yes just try to make a clockwork engine in the crafting table

**Comment by tfox83** [comment]
Update to 1.0.1

Duplicate of #3
