### ISSUE TITLE
Factorizer from TE gives 9 Nether Quartz from a quartz block

### ISSUE THREAD

**Issue by Kuktar** [FTBTeam/FTB-Continuum#101]
* **Modpack Version**: 1.0.2

* **Issue**: Factorizer from TE gives 9 Nether Quartz from a quartz block

* **Is it Repeatable?**:yes is repeatable. 

* **Mod/s Affected**: thermal expansion

* **Known Fix**: change factorizer recipe to only give the correct 4 nether quartz. so nobody is dupping nether quartz with it,

![2018-05-28_16 45 30](https://user-images.githubusercontent.com/24352734/40631998-173aa21e-6297-11e8-90c2-2464e824691b.png)

**Comment by tfox83** [comment]
Ended up removing the machine as it opens up a lot of issues that break more than fix (This machine was added by CoFH just before release of the pack)
