### ISSUE TITLE
Translocator voids item when built next to Presser from IE

### ISSUE THREAD

**Issue by Valerate** [FTBTeam/FTB-Continuum#103]
* **Modpack Version**: 1.02

* **Issue**: Translocator deleted items when giving them to IE's presser

* **Is it Repeatable?**:  Yeah sadly, lost tons of items before I notcied it

* **Mod/s Affected**: Translocator, Immersive Engineering, (Forge multipart?)

* **Known Fix**: None

This is my setup, I have have been noticing less output than input into the Presser but has allways thought it was my mind, but right now I needed electrum gear and put them into the chest, only for them to go into the translocator and not go out on the conveyor so its definitly not in my mind
https://i.imgur.com/J3duwJs.jpg

My guestimate is that it happens becouse it translocates one item at a time, but a gear recipe required 4, so it just fails and disapears

**Comment by tfox83** [comment]
Its a known issue and never been fixed.  I suggest using a manual method of placing on presser of test other automated means for now.  Thanks for the report.
