### ISSUE TITLE
Questbook is bugged. One Quest needs a completed Quest that isn't existent.

### ISSUE THREAD

**Issue by TheRealPonynja** [FTBTeam/FTB-Continuum#105]
So there is a Quest called "Here and There". You need to craft a Conveyor Belt in that Quest. I did that and the Quest was completed. But in several Quests after this Quest you need to complete a Quest called "Herer and Therer" and I'm pretty sure that's a mistake and it should be called "Here and There" just like in the Quest that I completed. I can't play the modpack further and that's not nice. =/ I hope you can fix this very soon! <3

**Comment by B14U2NV** [comment]
"Herer and Therer" is a quest line under the Industrial Rebirth section of the Quest book. Complete that and you should be free to continue.

**Comment by TheRealPonynja** [comment]
Oh thank you! I didn‘t See that there is this Quest because I needed to complete the Treejuice quest First. Thank you for your quick answer! <3
