### ISSUE TITLE
Spice of Life counter reset glitch

### ISSUE THREAD

**Issue by UkeArie** [FTBTeam/FTB-Continuum#109]
* **Modpack Version**: 1.0.2 and possibly later

* **Issue**: When hungry, if you travel to an alternate dimension and eat, then travel back to the overworld, your food counter is reset back to 10 before diminishing returns kicks in.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Spice of Life

* **Known Fix**: None

**Comment by Kuktar** [comment]
This also happens when using another mod not in the pack. Twilight forest dimension resets it to. We should probably let the mod author of spice of life know.

**Comment by tfox83** [comment]
fixed in 1.3.0
