### ISSUE TITLE
Crash with BetterQuesting "Quest Complete" onscreen popup.

### ISSUE THREAD

**Issue by dudeedud4** [FTBTeam/FTB-Continuum#11]
* **Modpack Version**:  1.0.1

* **Issue**:  Crashed when BetterQuesting "Quest Completed" shows up on screen.

* **Link to Log or Crash File Paste**:  https://gist.github.com/dudeedud4/91ceaa47a8a68c63cd3b2751d7155098

* **Is it Repeatable?**:  Probably? Didn't test because MC takes forever to load on here.

* **Mod/s Affected**:  BetterQuesting most likely.

* **Known Fix**:  N/A

**Comment by aaronhowser1** [comment]
I couldn't reproduce this, I completed a bunch of random quests in a test world without problem. I suggest posting that crash log to [the Better Questing issue tracker](https://github.com/Funwayguy/BetterQuesting/issues) as well.

**Comment by tfox83** [comment]
I was not able to reproduce this either, ill leave the issue open for now

**Comment by dudeedud4** [comment]
I've x-posted this report to the BetterQuesting issue tracker like @aaronhowser1 said. I'll update this when/if I get replies/solutions.

**Comment by tfox83** [comment]
I am going to leave this open for comments, but close the issue as I haven't had any other reports of this.  Could of been a one off bug
