### ISSUE TITLE
Reenable Ironchest upgrades

### ISSUE THREAD

**Issue by Mattizin** [FTBTeam/FTB-Continuum#111]
* **Modpack Version**: 
1.0.2
* **Issue**: 
Improvement:
Reenable the upgrades from 1 ironchest tier to the next higher one.
I read somewhere, that it got disabled because of the changes in the tier progression but the only thing i can see is the slightly larger chest between normal and copper chest. 
Cant we have the other upgrades though?
Its a pain in the ass to change the tiers atm.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 
Iron Chests
* **Known Fix**:

**Comment by tfox83** [comment]
It bypasses the intended upgrade progression in this pack.  So no.
