### ISSUE TITLE
Problem de generation des minerais sur les autre planète 

### ISSUE THREAD

**Issue by EspGCreunix** [FTBTeam/FTB-Continuum#112]
Je joue depuis un moment sur le Modpack continiumet sur serveur et j'ai un problème quand je visite des planète je ne trouve pas les minerais de type litherite ou autre pour temp je vais sur les planète indiquer avec le même nom des minerais je suis donc actuellement bloquer sur le Modpack prouver vous m'informer au plus vite si c'est une configuration serveur mal régler ou ci cela vien de votre coter merci de me répondre au plus vite, :)

**Comment by triggerfinger12** [comment]
S'il vous plaît, faites vos soumissions en anglais, merci.

**Comment by tfox83** [comment]
English only, have no idea what this is.
