### ISSUE TITLE
Game crashes after using cells in place of buckets inside of the Tree Fluid Extractor

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Continuum#113]
* **Modpack Version**: FTB Continuum 1.0.2

* **Issue**: Friend of mine loaded cells in place of buckets into a Tree Fluid Extractor, what followed was a crash for anyone who loaded the chunk. Fixed it by deleting the Tree Fluid Extractor.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/f0ad7f43

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Industrial Foregoing in combination with Tech Reborn.

* **Known Fix**: Add in Tree Fluid Cells to Tech Reborn, or disallow cells from being placed the machine.

**Comment by ThorVonAwesome** [comment]
Had the same problem, but I think it was fixed in 1.1.0 because it's working fine after we updated the server.

**Comment by drcrazy** [comment]
Duplicate for https://github.com/FTBTeam/FTB-Continuum/issues/52

**Comment by tfox83** [comment]
Fixed in 1.1.0
