### ISSUE TITLE
Work table from engineer's workshop reborn doesn't show pregress when smelting.

### ISSUE THREAD

**Issue by yuriondelagrion** [FTBTeam/FTB-Continuum#114]
as of the latest update, it seems that work table from engineer's workshop doesn't show smelting progress. Its a minor bug but I thought I would let it be known.

**Comment by tfox83** [comment]
@modmuss50 going to have you take a look when you have some free time, no rush.  Thanks

**Comment by modmuss50** [comment]
@yuriondelagrion are you playing on a server or in single player? As I cannot seem to reproduce this.

![java_2018-06-02_17-10-52](https://user-images.githubusercontent.com/4324090/40878364-ffa7a3fa-6687-11e8-818c-33226f426c2e.png)

**Comment by yuriondelagrion** [comment]
@modmuss50 yeah, single player. here is a screenshot
![bug](https://user-images.githubusercontent.com/39782328/40881824-0d8e0a74-669f-11e8-92b1-0a2d37b8e129.png)

**Comment by modmuss50** [comment]
You don’t appear to have any fuel such as coal in the bottom right slot (next to your inventory)

**Comment by yuriondelagrion** [comment]
Sorry, that was a mistake(about the fuel) but I assure you I don't get any progress bar regardless of fuel.

**Comment by yuriondelagrion** [comment]
@modmuss50 Sorry, here is the picture with fuel and everything.
![bug](https://user-images.githubusercontent.com/39782328/40888407-ac1ab90a-6724-11e8-9aee-3229671d51a0.png)

**Comment by modmuss50** [comment]
Humm, that is very strange. I honestly don't know what is causing it. When I get a chance ill load up the full mod pack to see if its to do with that. Thanks anyway.

**Comment by modmuss50** [comment]
Can confirm when running in FTB Continuum, doesn't happen when testing the mods on their own. This will need some more investigation into what is causing the issues in the mod pack.
