### ISSUE TITLE
Continuum Server Efab Crafting Grid Recipe Not Working

### ISSUE THREAD

**Issue by lewelstamp** [FTBTeam/FTB-Continuum#115]
* **Modpack Version**: 1.1.0

* **Issue**: <I made a Continuum server which works just fine, EXCEPT when I try to satisfy a quest by building the EFAB Crafting Grid, there is no output possible. I have the necessary materials (8 oak logs and 1 oak planks). I can place them in the grid as instructed by JEI or I can use the "plus" sign to auto place them into the crafting grid, but the output never shows anything and the item cannot be pulled out (if it were invisible).

This problem persists in a vanilla or tinkers crafting grid/table

I also tried with a variety of logs and planks

I tried this in a single player world and had absolutely no trouble; the Efab Crafting Grid was craftable. Which tells me this problem is with my server files somewhere

I looked for the recipe in the efab_recipe.json file but can't find it there.

I've copied my single player world over to the server but that didn't fix the issue. Which pretty well confirms it isn't a "world" or "saves" file issue.

I have updated/repaired the pack.

I have deleted and rebuild the server.

I have confirmed the CONFIG and MODS files are identical between the Server and the Client

* **Mod/s Affected**: EFAB 0.0.36

any help would be greatly appreciated.

**Comment by Kuktar** [comment]
What server version are you using? Does it have mcjcty installed

**Comment by lewelstamp** [comment]
I'm using minecraft_server.1.12.2.jar and forge-1.12.2-14.23.4.2703

**Comment by tfox83** [comment]
I am not able to reproduce this, nor are my testers.  I would try a fresh install
