### ISSUE TITLE
Reinforced Jetpack (Armored) [fixed in mod update]

### ISSUE THREAD

**Issue by jottafan** [FTBTeam/FTB-Continuum#117]
**Modpack Version:** 1.1.0

**Issue:** Reinforced Jetpack (with "soulbound I") + Invar Armor Plating does not give the "Reinforced Jetpack (Armored)" , [i was able to upgrade the hardened jetpack to reinforced while the enchant was on, changing the particles works fine aswell. Could be bugged at all tiers, i haven't tried it myself.

**Is it Repeatable?:** yes

**Mod/s Affected:** Simply Jetpacks 2

**Known Fix:**  im guessing a small change in the recipe would do it.

**Comment by jottafan** [comment]
Latest version of Simply Jetpacks 2 was out 23 may 2018, with the claim that this issue is fixed.

**Comment by tfox83** [comment]
that update will be in next version which is coming out soon.
