### ISSUE TITLE
Custom recipes missing or broken

### ISSUE THREAD

**Issue by Oreo12** [FTBTeam/FTB-Continuum#119]
* **Modpack Version**:    1.1.0

* **Issue**: 
Basically all custom recipes are missing or broken. This completely ruins the progression of the pack because you can craft projectE items from the get-go. Also none of the Efab items are craftable

* **Is it Repeatable?**: 
Yes

* **Mod/s Affected**: 
The entire pack

**Comment by tfox83** [comment]
Seems like you forgot the scripts folder... Please do a fresh install.

**Comment by Oreo12** [comment]
Fresh installed multiple times.

**Comment by Oreo12** [comment]
This was gotten from the launcher with 0 errors and installed on our server. Our players would very much like a fix because no one can progress properly.

**Comment by Grand-Trizmo** [comment]
@tfox83 scripts folder wasnt missed
