### ISSUE TITLE
Excavation not working

### ISSUE THREAD

**Issue by Avi-E-Koenig** [FTBTeam/FTB-Continuum#12]
latest continuum release:

I cannot get excavation to work right.
If i try to vein mine ore/dirt/stone...
trees don't work either

**Comment by pxoxd** [comment]
Did you try with the excavate modifier?

**Comment by Avi-E-Koenig** [comment]
I tried with excavate modifier applied to tools.
tried regular hit and holding grave.
excavate not applied

**Comment by 016Nojr** [comment]
Ore Excavation is set to be always active, and will only work on ores when the excavate modifier is applied or the correct enchantment (Not sure what it's called) is applied.

**Comment by Avi-E-Koenig** [comment]
I fail to see why you would deny the user the ability to play as they wish by disabling the mod config settings.

**Comment by 016Nojr** [comment]
The mod config settings hasnt been disabled, if you really want to change it you can change it in your config either in game under the "Mod Options" button or in the instance folder \config\oreexcavation.cfg

**Comment by Avi-E-Koenig** [comment]
Incorrect.
All attempts to do so failed prior to submitting this ticket.

**Comment by aaronhowser1** [comment]
Disable the [Invert Block Blacklist](https://i.imgur.com/iBQOOdF.png) button, then [remove all the blocks from the blacklist](https://i.imgur.com/0WNfwEr.png). I just did this in a test world and it worked, using 1.0.1 of the pack.

You may also want to change the [mode option](https://i.imgur.com/mLvEgs5.png) so it doesn't do it every time you mine a block.

**Comment by 016Nojr** [comment]
Nobody can "disable" configs from being changed.

**Comment by Avi-E-Koenig** [comment]
I stand corrected,
@aaronhowser1 solution did the desired result.
