### ISSUE TITLE
Clear glass from Tinker contruct not craftable.

### ISSUE THREAD

**Issue by Dorfinger** [FTBTeam/FTB-Continuum#120]
Hello - everytime I click the faucet to pour the liquid glass in the casting basin - It stops instantly
If you spam click the liquid is ghosted and if you spam long enough it even fill the basin and start to dry but its just a Ghost block .
Every other liquid works just fine.
Its working in solo game  but not on Multiplayer.

Minecraft 1.12.2
FTB Continuum 1.10.1

Repeatable  yes - I rebuildtthe tinker foundry and even tryed an other one from someone else base. Same result.

* **Mod/s Affected**: Tinker>

**Comment by TNovalis** [comment]
I cannot repeat this on another server, this may be due to potential server lag, do you have any problem with any other blocks in the casting basin?

**Comment by Dorfinger** [comment]
No everything else is working just fine.

**Comment by tfox83** [comment]
I am able to make it fine using the casting basin.

**Comment by Dorfinger** [comment]
Are you on 1.10.1 ?
