### ISSUE TITLE
Server crashes when blocking damages from guardians using redstone arsenal shield

### ISSUE THREAD

**Issue by LaTrissTitude** [FTBTeam/FTB-Continuum#122]
* **Modpack Version**: 1.0.2

* **Issue**: Server crashes when taking guardian laser attack damage

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/4939775d

* **Is it Repeatable?**: yes, get hit by a guardian using the redstone arsenal shield

* **Mod/s Affected**: Redstone arsenal

**Comment by tfox83** [comment]
fixed in next update
