### ISSUE TITLE
Gluttony charm does not interact with the lunch box

### ISSUE THREAD

**Issue by Owis54** [FTBTeam/FTB-Continuum#123]
* **Modpack Version**: 1.1.0 

* **Issue**: Gluttony charm does not interact with the lunch box

* **Is it Repeatable?**: yes just put food in the lunch box, equip the gluttony charm and it will not insta-eat

**Comment by aaronhowser1** [comment]
I recommend posting this on the [Spice of Life}(https://github.com/squeek502/SpiceOfLife/issues) and [Dark Utilities](https://github.com/Darkhax-Minecraft/Dark-Utilities/issues) issue trackers as well

**Comment by tfox83** [comment]
Fix in 1.3.0
