### ISSUE TITLE
Modpack crashes loading mods

### ISSUE THREAD

**Issue by Sleepnaught** [FTBTeam/FTB-Continuum#124]
* **Modpack Version**: FTBContinuum-1.1.0
* **Issue**: Client Crashes while loading mods

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d3362c9e

* **Is it Repeatable?**: Every time I try to start the modpack

* **Mod/s Affected**: All. Won't start

**Comment by TNovalis** [comment]
If you haven't already, backup any saves, delete the modpack from the FTB directory, redownload and try installing again.

**Comment by Sleepnaught** [comment]
I've deleted everything, modpack, Minecraft, Java, Twitch, Forge. Same results.

**Comment by modmuss50** [comment]
Do you have the instance saved in virtual file system (I.E OneDrive or RamDisk), does the file path have any none standard characters in it? 

If not is the pack installed in the default location, or has it been moved?
