### ISSUE TITLE
Storage Tablet

### ISSUE THREAD

**Issue by cwilkinsvi** [FTBTeam/FTB-Continuum#125]
* **Modpack Version**: 
1.1.0
* **Issue**: 
RFTools Storage Tablet cannot be upgraded to use any module 
* **Link to Log or Crash File Paste**: 
No log.
* **Is it Repeatable?**: 
Yes
* **Mod/s Affected**: 
RFtools 
* **Known Fix**: 
Fix was posted in storage tablet bug report from 1.0.2

**Comment by tfox83** [comment]
Fixed in next update
