### ISSUE TITLE
How can I get obsidia? Been trying to get it for the past few hours...

### ISSUE THREAD

**Issue by BoomCheeseBurger** [FTBTeam/FTB-Continuum#126]
I really need help in finding a way to get obsidian. I can't continue my quests because I'm stuck trying to get obsidian. I have looked up many methods in getting it but they were outdated. Please respond! Thanks

**Comment by Kuktar** [comment]
The best way is to dig to y 6 and look for lava and dump water on it. Then
use a pickaxe to mine it. Wood>stone>iron>gold>diamond>obsidian

**Comment by BoomCheeseBurger** [comment]
But it seems that it won't produce obsidian when I put water over the lava. Could I have done something wrong? I'll check again. But thank you for your response :), I feel relieved that you had responded so I now know that I could've done a mistake.

**Comment by BoomCheeseBurger** [comment]
Right, I haven't played survival for a long time so I didn't realize I was pouring lava over water instead of water over lava and it confused me. So I went through a lot of methods on youtube through smeltery but it also didn't work and thats where I got stuck thinking for a few hours. Dumb me haha...
