### ISSUE TITLE
Fps Issues.

### ISSUE THREAD

**Issue by CaptianBoo** [FTBTeam/FTB-Continuum#127]
* **Modpack Version**: 1.1.0

* **Issue**: Heavy lag of 1 fps per chunk.

* **Image of F3**: https://s15.postimg.cc/k51mqwex7/fps.png

* **Is it Repeatable?**: Possible, I've uninstalled, but the issue persist.

* **Mod/s Affected**: Unsure

* **Known Fix**: Unshure

**Comment by modmuss50** [comment]
What graphics card do you have? (The graph is hiding quite a bit of useful info in the debug menu)

Make sure you have mipmap disabled in the video settings. 

Does it happen on a different world or a different pack?

Is there anything unusual in the logs.

**Comment by mynameispig123** [comment]
Try grabbing the log file of that game and post it here so we can see what is the issue
