### ISSUE TITLE
[Suggestion] All vanilla crafting table recipes working in EFAB

### ISSUE THREAD

**Issue by doritobob269** [FTBTeam/FTB-Continuum#128]
* **Modpack Version**: 1.0.2

* **Issue**: When crafting recipes such as wooden logs to planks, or planks to sticks, could these recipes and all other recipes like them work in the EFAB similar to how the chest recipe is with it's 0 second crafting time. This doesn't necessarily mean that they should be removed from being able to craft in a normal crafting table (as this would mess with the pre-EFAB mechanics). I just find myself crafting logs -> planks -> chest, but need to remember to use the EFAB, but if it's not a major problem, I'd like to see all crafting table recipes work in the EFAB to alleviate this confusion of remembering which table to use for what and just being able to use the EFAB for all EFAB and normal crafting related recipes.

* **Link to Log or Crash File Paste**: No Crash or log to report

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: EFAB (all versions?) and all other recipes of the pack

* **Known Fix**: Stated in the issue above

**Comment by doritobob269** [comment]
I don't know how to add a suggestion label

**Comment by 016Nojr** [comment]
Already a feature, but disabled in the pack. If you are playing in singleplayer you can turn this on if you want.

`# If enabled the EFab grid and crafter will also support vanilla recipes. If disabled they don't [default: true]
    B:vanillaCraftingAllowed=false`

**Comment by doritobob269** [comment]
Is there any reason this is disabled by default? Any reason to not default it to true?

**Comment by Kuktar** [comment]
I think because it will enable the basic recipes that come with minecraft
vanilla ie 4 planks per a log and that isn't how the pack is designed to
work.

**Comment by doritobob269** [comment]
Oh, that makes sense. I wonder if there is a way to change that option so EFAB doesn't steal recipes before minetweaker
