### ISSUE TITLE
Modded planks aren't craftable

### ISSUE THREAD

**Issue by Xavion3** [FTBTeam/FTB-Continuum#13]
* **Modpack Version**:
1.01

* **Issue**:
Modded planks aren't craftable.

* **Is it Repeatable?**:
Yes, just load the pack and check JEI.

* **Mod/s Affected**:
Natura, Traverse, Forestry, Binnie's

* **Known Fix**: 
Add recipes for them just like is already done for vanilla wood types

**Comment by tfox83** [comment]
It’s intended, the saw mill is used on non vanilla woods

**Comment by Xavion3** [comment]
Then JEI is displaying incorrectly or something has gone wrong, as none of them show up in the sawmill either. 9 different ways to get eucalyptus for instance, every one of them is recycling something made out of eucalyptus planks. That is the TE sawmill as it's the only one with even that, not the advanced rocketry, tech reborn, or binnie's methods of turning logs into planks either though.

**Comment by Kricked** [comment]
I tried to use the Saw Mill of Thermal Expension and it dosen't work. It only seems to work with vanilla wood. I can't place another type of wood in the Saw Mill.

**Comment by RealClassixX** [comment]
I wrote a script to re-add most of them. It's missing Quark coloured planks, and it doesn't works for all machines, but it's a start. You'll have to change it to a .zs file to use it.

[planks.txt](https://github.com/FTBTeam/FTB-Continuum/files/2009439/planks.txt)

**Comment by RealClassixX** [comment]
Oh, I didnt know it waas supposed to be saw mill only. You'd have to edit the script accordingly.

**Comment by tfox83** [comment]
yea this last large update we did about a week ago removed the non-vanilla logs from the sawmill with the "recipes.remove(<ore:plankWood>);" script which I use to allow the log/2 plank recipe.  It used to not affect the sawmill recipes but now we "think" CT is loading its recipes earlier and TE cant find the planks to auto gen its saw mill recipes.  Thats our best guess after talking to the TE dev.  I can force the modded logs all into the sawmill with Crafttweaker which is what I will end up doing for the looks and get that into the next hotfix.

**Comment by tfox83** [comment]
ok we got this sorted with some work arounds: all logs are craftable into 2 planks via crafting table/4 planks via TE sawmill/6 planks via TR sawmill, and unified the byproduct of sawdust while I was at it.
This will be released in 1.0.2 hopefully later today

**Comment by tfox83** [comment]
This has been released in v1.0.2
