### ISSUE TITLE
Some forestry trees wont drop their produce. 

### ISSUE THREAD

**Issue by TGSRagnarok** [FTBTeam/FTB-Continuum#130]
I did all the breeding to get the forestry coconut tree so I can use that for seed oil, but the trees will not drop their fruits, nor will the brazil nuts

* **Modpack Version**: 1.1
* **Issue**: Forestry coconut tree wont drop produce

* **Link to Log or Crash File Paste**: N/A
* **Is it Repeatable?**:  very

* **Mod/s Affected**: Forestry
* **Known Fix**: no clue

**Comment by tfox83** [comment]
you have to use a managed farm from forestry to obtain the drops

https://forestryforminecraft.info/farms:multi
