### ISSUE TITLE
Oak trees are growing above the sapling. Sapling remains

### ISSUE THREAD

**Issue by Pandragoon** [FTBTeam/FTB-Continuum#131]
* **Modpack Version**: 1.1.0

* **Issue**: I have a steves cart treefarm. My oak trees are growing hovering over the oak sapling, but the sapling isn't being replaced by a wood block, rendering the farm useless. The cart seems to know the tree is there as it slows down upon reaching one, but continues to move without cutting it down.
![2018-06-02_17 58 19](https://user-images.githubusercontent.com/36437649/40881759-25bee654-6695-11e8-9841-85db9884673c.png)

*EDIT* I just picked up all the cart stuff and planted a bunch of saplings, it's still happening. I planted an oak tree in another location, when it grew it just vanished.

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: Every sapling that gets place does it. Even if I pick up everything and put it all back down including the cart

* **Mod/s Affected**: n/a

* **Known Fix**: n/a

**Comment by tfox83** [comment]
I am not able to reproduce this, if you are playing on a server make sure they haven't modified the pack in any way.
