### ISSUE TITLE
Printing Press recipe not working

### ISSUE THREAD

**Issue by mtimyself** [FTBTeam/FTB-Continuum#132]
* **Modpack Version**: 1.1.0

**Comment by mynameispig123** [comment]
Could you please describe the issue in detail or post screenshot, your heading is very vague.
If you do not describe, then we might not be able to help you diagnose

**Comment by mtimyself** [comment]
Pretty straight forward really.
The custom recipe for the (bibiliocraft) printing press does not work.
http://prntscr.com/jqi17l
Also tried in a vanilla table.

**Comment by mynameispig123** [comment]
Did you try using the EFab? because the EFab is used in most recipes

**Comment by tfox83** [comment]
fixed in dev
