### ISSUE TITLE
How to obtain Inscriber Press

### ISSUE THREAD

**Issue by mtimyself** [FTBTeam/FTB-Continuum#133]
* **Modpack Version**: 1.1.0

* **Issue**: The quest has you craft an Inscriber to "craft the three Processors" but where to obtain the required Presses is not mentioned.

**Comment by liketechnik** [comment]
If I recall correctly (and it didn't change between 1.7.10 and 1.12), you obtain the Applied Energistics 2 presses from Meteorites found at random places in the overworld. I didn't progress to the quest myself, but maybe this should be indicated there?

**Comment by mtimyself** [comment]
Since I have found no meteors and the compass has been removed I assume that their spawning has been disabled (as is quite common in many expert packs).

**Comment by liketechnik** [comment]
Oh, I didn't knew that. Which version are you playing? Because I think I found a meteor in one of my worlds (generated with the natural (?) world generator) and I think I remember also a quest that is about said compass. (Talking about 1.1.0)

**Comment by alexsch01** [comment]
I think you have to craft them in the efab

**Comment by mtimyself** [comment]
It is possible to craft them all in the EFAB. However, there is the Quest that has you craft an Inscriber and specifically mentions that this is where you craft the three processors. The Advanced Inscriber of AE2 Stuff is also craftable.
Either there is a mistake with the Quest and the Inscribers need to be disabled or the Meteor Compass needs to be re-enabled or it needs to be mentioned in that Quest by what other means you are supposed to obtain the presses.

**Comment by Saereth** [comment]
you craft the printed circuits and printed silicon in the efab, you then take those + redstone and combine into an actual circuit in the inscriber. The presses are not needed/used at all.
