### ISSUE TITLE
Glass Fibre Cables eating power?

### ISSUE THREAD

**Issue by jels0002** [FTBTeam/FTB-Continuum#134]
* **Modpack Version**: FTB Continuum 1.1.0

* **Issue**: Glass fibre cables seemed to have eaten all my power from my Light Powercell. Initially I thought it was because I had them connecting to some Leadstone Fluxducts, but when I swapped them out it continued.

* **Link to Log or Crash File Paste**: N/a

* **Is it Repeatable?**: Yes, breaking and replacing all the cables changed nothing.

* **Mod/s Affected**: TechReborn, potentially RFTools?

* **Known Fix**: N/A

**Comment by modmuss50** [comment]
How many cables do you have? Is it possible to post a screenshot of what you have connected to them? If so I may be able to reproduce it.

**Comment by jels0002** [comment]
https://imgur.com/a/zUXtgdD
Heres an album of what the setup was, the power in the fibre cables is randomly jumping, doesn't seem like it's filling its buffer.

**Comment by LezChap** [comment]
https://github.com/TechReborn/TechReborn/blob/cc541bd55c178ed4cffdc44d72d2e68dde086af5/src/main/java/techreborn/tiles/cable/TileCable.java#L166-L181

I believe the cables are designed to be lossy...unless I'm misunderstanding the code.
