### ISSUE TITLE
E-Fab multiblock causing TPS lag

### ISSUE THREAD

**Issue by jels0002** [FTBTeam/FTB-Continuum#137]
* **Modpack Version**: FTB Continuum 1.1.0

* **Issue**: E-Fab multiblock structure seems to be causing massive lag

* **Link to Log or Crash File Paste**: No log, but here are images of it, as well as TickProfiler output: https://imgur.com/a/OSg5Gch , the RF Storages go 10 back, for around 40 of them, as well as a few boilers and bases, for around 70 blocks total.

* **Is it Repeatable?**: Yes, breaking and replacing the E-Fab and Crafter itself changes nothing

* **Mod/s Affected**: E-Fab, potentially TechReborn (using glass fibre cables)

* **Known Fix**: Breaking the E-Fab and Crafter itself stops the lag, but putting it back on the base resumes lag.

**Comment by HDR** [comment]
Does the multiblock have multiple grids? because this seems to cause lag.

see: https://github.com/McJtyMods/RFToolsPower/issues/7

**Comment by jels0002** [comment]
Initially it did, however we toned it down to one grid, unless the crafter also counts as a grid for these purposes, in which case there was a grid and a crafter.

**Comment by Kuktar** [comment]
Wtf I have a much more complex setup. Can you post you're fml log

**Comment by tfox83** [comment]
This will be much better in the next update which should come out soon
