### ISSUE TITLE
diesel generator wrong burningtime

### ISSUE THREAD

**Issue by jbs1** [FTBTeam/FTB-Continuum#138]
* **Modpack Version**:  
1.1.0
* **Issue**: 
The burntime for biodiesel is wrong.
1000 mb are supposed to burn for 6.25 sec (125 ticks)
I decompiled the ie modfile from the serverfiles and it says
`DieselHandler.registerFuel(fluidBiodiesel, 125);`.
yet for some reason ingame, 1000 mb burn for approx. 12.5 sec, so double.
I could not see any modifier in the cfg that you do that.
So is this a bug or on purpose?
Or did you reduce the tickrate to 10t/s or something?

* **Is it Repeatable?**: 
yes

* **Mod/s Affected**: 
ImmersiveEngineering-0.12-82

**Comment by tfox83** [comment]
This is due to the change in RF output.

**Comment by jbs1** [comment]
@tfox83 So how is the relationship? Is it linear?
So 4096 RF = 125 ticks, 1024 = 250 ticks, so 
fuelticks=(-125/3072) * rf output
