### ISSUE TITLE
tinkers forge

### ISSUE THREAD

**Issue by M3chi** [FTBTeam/FTB-Continuum#139]
modpact version: 1.12.2

i can't make the tool forge in tinker's construct and the normal iron tool forge recipe is showing ether

**Comment by Kuktar** [comment]
If I had the ability I would close this with no response.

You didnt follow the posting guidelines and that being said you gave only
10% of the problem details.

**Comment by tyler489** [comment]
yes... you have to make the ZINC tool forge
