### ISSUE TITLE
Translocators and fluid transport pipes

### ISSUE THREAD

**Issue by PooThee** [FTBTeam/FTB-Continuum#142]
Version: 1.1.0
I logged in and out on single player and my item trans locator disappeared, also I've found that the fluid pipes transporting plant oil/ethanol to the refinery have stopped working a couple times but they worked again once i broke them and replaced them again.

**Comment by aaronhowser1** [comment]
This seems to be a common problem with Translocators. It only happens in certain chunks in my experience though. I recommend posting this on the [Translocators](https://github.com/TheCBProject/Translocators/issues) issue tracker as well
