### ISSUE TITLE
Arc Furnace unnecessary but required by quest

### ISSUE THREAD

**Issue by Dawnflash** [FTBTeam/FTB-Continuum#143]
* **Modpack Version**: 1.1.0

* **Issue**: 
I noticed the "Mo Betta Alloys" quest (ID 64) has an AND requirement on the Arc Furnace quest (ID 116) and the quest says something about Arc Furnace being necessary to smelt "certain alloys".
However these certain alloys - lumium, enderium and signalum - can be melted in a magma crucible or smeltery and subsequently casted via TiCo.

* **Mod/s Affected**: Better Questing

* **Known Fix**: 
 I believe the Mo Betta Alloys quest should not depend on the Arc Furnace quest and the flavor text of the quest should be modified to mention the TiCo option.
Otherwise TiCo processing of these alloys should be forbidden but I don't think that's a good idea.

**Comment by GAJony** [comment]
It is used to smelt fluxed electrum, wich can't be smelted else!

**Comment by Dawnflash** [comment]
True, fluxed electrum is the only material for which Arc Furnace is required (and maybe ardite/cobalt doubling).
However, the immediate quests depending on Mo Betta Alloys don't require fluxed electrum as this is only used for Redstone Arsenal stuff, making the game's progression independent on its acquisition.

Maybe make the Arc Furnace quest a dependency for the Iron Man quest instead.

**Comment by aaronhowser1** [comment]
@tfox83 Is it intended to be able to use the Smeltery to smelt TE alloys?

**Comment by tfox83** [comment]
with the new changes in TE yes
