### ISSUE TITLE
EFab Advanced RF Storage doesn't contribute to RF/Tick

### ISSUE THREAD

**Issue by Ludi87** [FTBTeam/FTB-Continuum#144]
* **Modpack Version**: 1.2.0

* **Issue**: Wanted to  try the new Advanced RF Storage block, so replaced all of my standard ones with 3 of them. So with 4 RF Controls and 3 Advanced RF Storage blocks I should have 3200 RF/Tick available for the EFab. When I try to craft an Electronic Circuit I get the Error "Not enough power capacity! 1000 RF/Tick needed but only 200 possible". The blocks are connected, because when I replace them with the normal RF Storage blocks again, it shows a different value.

* **Is it Repeatable?**: Yes. replaced the blocks multiple times with normal rf storage blocks and they were recognized.

* **Mod/s Affected**: EFab 0.0.37

**Comment by Ludi87** [comment]
Something else that I just realized: With 4 Advanced RF Storage, 4 RF Control and 4 Gearboxes, the errormessage still shows 1000 RF/Tick for the recipe, with the normal storage blocks it correctly changes to 4000 RF/Tick. The blocks are definitely connected because I put the rf controls as the last connected blocks, and it recognized its rf/tick contribution

**Comment by yenbinhTV** [comment]
You should use 1 RF Control, I think it will work.

**Comment by covers1624** [comment]
I can also confirm this issue, it really is as simple as placing down Advanced RF Storage's.
![](https://cdn.discordapp.com/attachments/159971888485892096/459335398867599361/Screenshot_from_2018-06-21_22-03-34.png)
![](https://cdn.discordapp.com/attachments/159971888485892096/459335389702914051/Screenshot_from_2018-06-21_22-03-57.png)

**Comment by aaronhowser1** [comment]
This is fixed in the latest version of EFab. I'd tag the issue as such, but I'm away from my computer and my phone is not cooperating.

**Comment by noirsoldats** [comment]
This is still an issue in 1.3.1.  Is a fix forthcoming?

**Comment by aaronhowser1** [comment]
Tfox is going to be away for most of this week for 4th of July stuff, I'll poke him about an update when he gets back

**Comment by tfox83** [comment]
fixed in 1.4.0
