### ISSUE TITLE
Drawers Dupe/Bug

### ISSUE THREAD

**Issue by kristi71111** [FTBTeam/FTB-Continuum#145]
* **Modpack Version**: 1.3.1 and below

* **Issue**: 
   Duplication bug with Storage Drawers and backpacks. 
Confirmed that this works with other items besides backpacks as well.

   Explanation in text form: 

   Put two backpacks in drawer. Destroy the drawer from the side so that you do not take the backpacks out. You should then receive two stacked backpacks. Open the stacked backpacks in your inventory and put the items you want to dupe within. Unstack and bam you're rich.  

   Explanation in video form: 

   [Youtube video explaining it](https://youtu.be/7d2_bvv5Nps) 

* **Link to Log or Crash File Paste**: None needed. 

* **Is it Repeatable?**: Yes MP and SP

* **Mod/s Affected**: Storage Drawers 

* **Known Fix**: Edit the mod and compile your own fix.

**Comment by kristi71111** [comment]
@tfox83 Why was this closed when the issue remains in 1.2.1?

**Comment by Kuktar** [comment]
Lol tfox83 must be drunk I just tried and it works

**Comment by GWSheridan** [comment]
[243](https://github.com/FTBTeam/FTB-Continuum/issues/243)

**Comment by aaronhowser1** [comment]
This is a slightly different issue, though both are to do with backpacks. That was an incompatibility with Bibliocraft, this is with Drawers

**Comment by aaronhowser1** [comment]
Can you try manually updating Storage Drawers to the latest version and testing it again?

**Comment by tfox83** [comment]
Fixed in 1.4.0
