### ISSUE TITLE
Extrautils2 Mechanical Crafter Server Crash

### ISSUE THREAD

**Issue by KingDan27** [FTBTeam/FTB-Continuum#146]
* **Modpack Version**: 1.1.0

* **Issue: Server crashes when using the mechanical crafter from extrautils. Player shift clicked the recipe from jet and when that crashed he clicked the item into the grid manually also causing a crash

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/6c957134

* **Is it Repeatable?**: yes crashed it several times in a row

* **Mod/s Affected**: extrautils2 version 1.7.6

* **Known Fix**:

**Comment by tfox83** [comment]
the mechanical crafter inst made in the grid, its vanilla crafting
