### ISSUE TITLE
Void ore miner quest | upgrading from null modifier screwed me over real good

### ISSUE THREAD

**Issue by jottafan** [FTBTeam/FTB-Continuum#149]
* **Modpack Version**: 1.1.0

* **Issue**: "Metallum ex vacui IV" (maybe all void and resource miner quests) says i need 12 "null modifier" to complete. problem is i already upgraded my modifiers to speed and accuracy, and now i need to make 12 blank modifiers just to complete the quest (those cost 1 diamond block each).

* **Is it Repeatable?**: Yes
* **Mod/s Affected**: better questing?

* **Known Fix**: make quest look for any modifier (null/accuracy/speed modifier)

**Comment by jottafan** [comment]
or one could make the quest so it requires only 4x "null modifiers" and put in the quest description that u need a total of 12 modifiers

**Comment by aaronhowser1** [comment]
Removed all Null Modifier requirements after the second tier quests and added a line saying it needs X amount of ET Modifier blocks
