### ISSUE TITLE
OreDict changes in Thermal Foundation

### ISSUE THREAD

**Issue by 016Nojr** [FTBTeam/FTB-Continuum#15]
In a recent update to Thermal Foundation the oredictionary name for the 3 fluid ores were changed
This affect the products from the Void Ore Miner

oreFluidEnder -> oreClathrateEnder
oreFluidGlowstone -> oreClathrateGlowstone
oreFluidRedstone -> oreClathrateRedstone

**Comment by tfox83** [comment]
fixed in 1.0.2
