### ISSUE TITLE
Crash when alt tabbed i guess?

### ISSUE THREAD

**Issue by Amedinno** [FTBTeam/FTB-Continuum#150]
* **Modpack Version**: 1.10

* **Issue**: Crashes randomly, every time, there are no triggers. Mostly crashes when alt tabbed

https://paste.feed-the-beast.com/view/21ef714b

* **Is it Repeatable?**: It is

**Comment by tfox83** [comment]
note able to reproduce, please make sure you have at least 4GB of ram avail.  Things you are doing when tabbed out may by taking ram away
