### ISSUE TITLE
a bug about rftools.zs

### ISSUE THREAD

**Issue by KuroPeach** [FTBTeam/FTB-Continuum#151]
Modpack Version: 
1.1.0

at rftools.zs line 16

#storage tablet
recipes.removeShaped(<rftools:storage_module_tablet>);
recipes.addShaped(<rftools:storage_module_tablet>, [[<ore:ingotIron>, <extrautils2:terraformer:1>, <ore:ingotIron>], [<wrcbe:material:2>, <thermalexpansion:frame>, <wrcbe:material:2>], [<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>]]);

we should change to

#storage tablet
recipes.removeShaped(<rftools:storage_module_tablet>, [[<minecraft:gold_nugget>, <minecraft:emerald>, <minecraft:gold_nugget>], [<minecraft:redstone_block>, <minecraft:quartz_block>, <minecraft:redstone_block>], [<minecraft:gold_nugget>, <minecraft:redstone_block>, <minecraft:gold_nugget>]]);
recipes.addShaped(<rftools:storage_module_tablet>, [[<ore:ingotIron>, <extrautils2:terraformer:1>, <ore:ingotIron>], [<wrcbe:material:2>, <thermalexpansion:frame>, <wrcbe:material:2>], [<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>]]);

Now we can storage card into it

**Comment by tfox83** [comment]
fixed in next version
