### ISSUE TITLE
Making Tier 3 void miner is unintentionally hard

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Continuum#152]
* **Modpack Version**: 
1.2.0-1
* **Issue**: 
Removal of TE Factorizer made making Tier 3 void miner unintentionally hard.
To make tier 3 void miner you need roughly 3 stacks of Prismarine Shard. Since Prismarine Bricks gave 9 shards, all you had to do was just bring 22 bricks from the Ocean monument back to base then put in factorizer.  
Removing factorizer made this impossible and the difficulty of getting the tier 3 miner is unintentionally harder now.

Making Prismarine Bricks grindable could fix it I guess

**Comment by tfox83** [comment]
The Factorizer will be back in next update now that it has been fixed
