### ISSUE TITLE
Client Crash: EFab + Armor Stand

### ISSUE THREAD

**Issue by mtimyself** [FTBTeam/FTB-Continuum#154]
* **Modpack Version**: 1.2.0

* **Issue**: Crashed the client on initial load/render of my base.

* **Link to Log or Crash File Paste**: https://pastebin.com/7kQ8dK7u

* **Is it Repeatable?**: No, I am able to play just fine now.

* **Mod/s Affected**: Efab + Bibliocraft (?)

**Comment by tfox83** [comment]
fixed in 1.3.0
