### ISSUE TITLE
bloodwood fence conflict

### ISSUE THREAD

**Issue by TheGameGeek** [FTBTeam/FTB-Continuum#155]
* **Modpack Version**: 1.1.0

* **Issue**: i went to go make a bloodwood fence to find you need bloodwood sticks so i goto make those and it is conflicted with wooden pressure plate

* **Link to Log or Crash File Paste**: https://gyazo.com/32a1fab83e1dad5a681f175dd2f759b3

* **Is it Repeatable?**: yes

**Comment by Kuktar** [comment]
Bro. Put the planks vertically. Not horizontal lol. It's a shaped recipe
not shapeless.

**Comment by TheGameGeek** [comment]
https://gyazo.com/add8acaa7e9acdbb54dfbe522b1e7cdf

**Comment by TheGameGeek** [comment]
and up and down just makes a vinilla stick not a bloodwood

**Comment by Kuktar** [comment]
What did you do to resolve it. Craftweaker?

**Comment by TheGameGeek** [comment]
i havent resolved it

**Comment by TheGameGeek** [comment]
the gyazo is JEI

**Comment by Kuktar** [comment]
I thought that last pic showed the bloodwood sticks you needed.

**Comment by TheGameGeek** [comment]
No that last pic was JEI to show that the recipe is right the output is wrong

**Comment by Kuktar** [comment]
http://imgur.com/ygzD54V

According to nature it should produce the bloodwood sticks. Here is there github desk maybe its something in the continuum scripting or just nature itself. 

https://github.com/progwml6/Natura/issues

**Comment by tfox83** [comment]
Its intended due to the oreDict of custom recipes, the fences have been hidden in next update to avoid confusion

**Comment by spdkils** [comment]
Are you also going to remove all the Natura tools fro JEI? Because the blood wood pick is an 'iron' pick, etc. And can't be crafted, but I saw them and dug for them. :(

**Comment by Kuktar** [comment]
I'm not sure why natura is in the pack if you take all the cool looking
stuff out lol.

Is there any way not to disable them?

If its oredic issues only maybe someone can make a craftweaker script to
change them.
