### ISSUE TITLE
TE Sawmill: Pulped Biomass

### ISSUE THREAD

**Issue by mtimyself** [FTBTeam/FTB-Continuum#157]
* **Modpack Version**: 1.0.2

* **Issue**:
The TE sawmill can no longer cut up melon blocks into slices but rather produces pulped biomass.
This has implications for the production of Ethanol (used for Biodiesel).
Now only potatoes remain as a viable (garden cloche based) option.
This is a major nerf to Biodiesel, which was better than the far more complex and expensive (Crude Oil) Diesel.

Just wanted to point this out and ask if it was intentional.

**Comment by tfox83** [comment]
This was an intentional change done by the mod
