### ISSUE TITLE
Luck III + Autosmelt = triple (allmost, RNG) resources in early game, intended?

### ISSUE THREAD

**Issue by ByteTemplar** [FTBTeam/FTB-Continuum#159]
* **Modpack Version**: 1.2.0

* **Issue**: Title pretty much covers it. It is a game mechanic in Tinkers construct and pretty rarely used cause most modpacks provide better way to multiply resources early game. It also does have some other interesting effects with some resources.

* **Link to Log or Crash File Paste**: This has no logs

* **Is it Repeatable?**:  well, yeah

* **Mod/s Affected**: Tinkers construct, but its intended game mechanics in it

* **Known Fix**: disable Autosmelt?

This topic seems to be bit controversy among players, so just wanted to see what is the devs opinion on this matter.

**Comment by Kuktar** [comment]
#148
Duplicating seared bricks
Opened by Drak0necal about 21 hours ago

This is also a simaler problem. The luck and autosmelt features kind of ruin the pack... on my own server I disabled them but a lot of people like to and have gotten used to abusing the mechanic. 

My suggestion would be to make the modifiers much more expensive. Instead of lapis for luck modifier or should be like ender dragon eggs or even nether stars. Or outright disable it like I did :)

**Comment by zenoran** [comment]
Ore doubling is already disabled until tons of grind... Getting Luck 3 + smelt on a pickaxe isn't exactly a quick thing to begin with but it hardly "ruins the pack."  There is so much mining grind even after you get luck3+smelt!  Honestly, that's about one of the only rewarding experiences the pack offers at the moment.  Even the quartz grindstone is gated behind empowered diamonds and that's a MANUAL clicky thing.  If you really want to talk about something ruining the pack you should consider disabling career bees.  That's BEYOND unbalanced.  Mining is a repetitive chore until you get void ore miner ***5*** and autosmelt just makes it borderline tolerable.

**Comment by Kuktar** [comment]
Ask yourself this, why in the config do modpack makers have the ability to
set the option for luck(fortune) and autosmelt interaction?

The tinkers developer knows this can be overpowered.... and I thought
people wanted an expert pack lol.

At the end of the day FTB has never configured the interaction to be
disabled so abuse away.

Ps: here is how to get luckIII and lootingIII in a matter of an hour or so
using math.

reddit.com/r/feedthebeast/comments/21bkic/tinkers_construct_how_to_use_and_abuse_the_lapis/

**Comment by tfox83** [comment]
THis has been disabled in 1.2.1
