### ISSUE TITLE
Compartment crash

### ISSUE THREAD

**Issue by el1xlv** [FTBTeam/FTB-Continuum#160]
* **Modpack Version**: 1.1.0

* **Issue**: When try to open or set filters inside Compartment from mod Binnie Core, game going to crash, every time.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/52838bef

* **Is it Repeatable?**: Yes

* **Known Fix**: Remove recipes

**Comment by tfox83** [comment]
I am not able to reproduce this
