### ISSUE TITLE
Issues due to MineTogether when a player joins.

### ISSUE THREAD

**Issue by Zexceil** [FTBTeam/FTB-Continuum#161]
Modpack Version: 1.1.0

Server details:
Running sponge ver: 1.12.2-2705-7.1.0-BETA-3148
Plugins: Nucleus, LuckPerms, Nuvotifer, Serious vote, EconomyLite.
Hosted via: Pterodactyl panel

Issue: Issue causing users to time out/ take a long time joining server.

Link to Log or Crash File Paste:
https://pastebin.com/QVHasqY5

Is it Repeatable?:
Happens with every player including myself.

Mod/s Affected:
MineTogether

Known Fix:
I removed MineTogether and it didn't have this issue.

**Comment by Kuktar** [comment]
Do they have same modpack version? Recently forge fixed this in version
4.2705

**Comment by Zexceil** [comment]
Updated the thread with the proper info modpack ver: 1.1.0, which runs forge 2702.

**Comment by tfox83** [comment]
On a non-sponge server this works fine.  Sorry we do not support sponge
