### ISSUE TITLE
Heavy fps drop [EFAB]

### ISSUE THREAD

**Issue by Sergent78** [FTBTeam/FTB-Continuum#162]
* **Modpack Version**: 1.10

* **Issue**: Heavy fps drop from EFAB

* **Link to Log or Crash File Paste**: No log / crash

* **Is it Repeatable?**:  Yes, very easly, just put like 10 crafter from Efab, and see your FPS drop like space station entering in atmosphere... Impact all around player looking the Efab area. 120 Fps lock to 30/40fps.

* **Mod/s Affected**: EFAB only.

* **Known Fix**: No fix found, i try to use Optifinie but nothing change. Problem don't come from my pc, my friends got also this problem.

Sorry for my bad english, i try to explain has much i can. I'm french ^^"

**Comment by Kuktar** [comment]
Use the latest version of Efab released in continuum 1.2

This was released 2 days ago it fixed almost 20 bugs in the pack.

**Comment by Sergent78** [comment]
Ah, but its beta actually, didn't see it.. Thx ^^"
