### ISSUE TITLE
Crashes...

### ISSUE THREAD

**Issue by JTatb1** [FTBTeam/FTB-Continuum#164]
* **Modpack Version**: < 1.10 >

* **Issue**: < the game will sometimes say unable to save game ( something about java) then when i try to save and exit the game stops responding and doesn't save >

* **Link to Log or Crash File Paste**: < Minecraft wont show me the crash file >

* **Is it Repeatable?**: < most of the time >

* **Mod/s Affected**: < N/A>

* **Known Fix**: < N/A >

**Comment by tfox83** [comment]
No idea without a crash report

**Comment by JTatb1** [comment]
@tfox83 i just pulled these logs. 2 are from the 8th of June and it crashed but didn't put the log in the crash report folder and the other one is a crash from 2 days ago it was in the crash folder.

[crash files.zip](https://github.com/FTBTeam/FTB-Continuum/files/2085741/crash.files.zip)

**Comment by Kuktar** [comment]
Try this in your java arguments.

To prevent this crash, add "-Dcofh.rf.crashOnOldAPI=false" to your command
line arguments.



That came from your crash log on the 6th. It will prevent crashes on the
mod flux. There is a tile entity from that mod calling an old api that
causes a crash.
