### ISSUE TITLE
Loot Chest Rewards Suggestion

### ISSUE THREAD

**Issue by sbm019222** [FTBTeam/FTB-Continuum#165]
* **Modpack Version**: 1.1.0

* **Issue**: loot chests really unrewarding

* **Link to Log or Crash File Paste**: none

* **Is it Repeatable?**:N/A
* **Mod/s Affected**: N/A

* **Known Fix**: expand the items that can be obtained from loot chests from quest rewards. I've exclusively seen food items drop and the first thing many players do when playing with spice of life is focus on a farm and finding food so getting a little cooked meat or potatos from your quest reward is really unsatisfactory

**Comment by Kuktar** [comment]
Maybe they could add a larger loot table.

**Comment by sbm019222** [comment]
Atleast the chance for something useful, maybe materials or really good food or even tools would be helpful and rewarding without breaking the pack

**Comment by Kuktar** [comment]
I liked how the smeltery quest rewarded a can of lava.

They could add TNT and sponges.

My son just suggested the totem of undying.

Potions/splash potions.

They could add wood drops. Wood is always useful.

Things like that really have no progression reward but can be really
useful.

**Comment by eikotehmouse** [comment]
I would like to see things that help with future quest. Rewards to should help with progression. Not have you going ..."oh... wood...."

**Comment by sbm019222** [comment]
Giving it more thought an enchantment table, maybe just a few diamonds/emeralds, enchanted tools or tinker tools would all be welcome reward that i don't think would break the progression

**Comment by aaronhowser1** [comment]
There are several types of loot boxes. A bunch of early quests give you food (although it'd be neat if they gave Pam's food imo), later quests give you better loot boxes.

**Comment by sbm019222** [comment]
Perhaps those early quests would be better off giving materials then, like logs, clay, or string

**Comment by 016Nojr** [comment]
I'll see what I can do

**Comment by Kuktar** [comment]
Yay an FTB team member is gonna take a look. Nojr thanks!

**Comment by sbm019222** [comment]
Any idea as to what you have in mind Nojr?

**Comment by 016Nojr** [comment]
Cant promise anything. I am a bit busy these days, but I have monday off :)

**Comment by Kuktar** [comment]
We understand. I personally appreciate everything you have done for the
pack.

**Comment by zenoran** [comment]
I'm not sure if FTB staff has been monitoring content providers trying to play this pack but if you guys haven't; the general feedback from everyone is you never feel any sense of reward even after busting your butt grinding out some silly recipe. It's kind of a slap in the face when you spend so much time and effort on progression and get rewarded with something like food or a few ingots. 

If you guys were to spend some serious time planning rewards out, it would greatly change the general vibe players get from the pack. Some quests don't even give any rewards at all which is odd. I'm in the final frontier and I've seen quite a few which were empty. But generally speaking, I haven't gotten even *1* useful thing from quests rewards up to this point in the pack. 

Some general recommendations on no brainer rewards would be materials players are experiencing shortages of at that time. I.e. gold in early game and maybe iridium or tungsten/titanium mid+. Just an example.

**Comment by 016Nojr** [comment]
There will be some noticeable changes. Removing the "Decoration" set, replace vanilla food with Pam's. All sets of loot chests will be available at any time when opening a chest.

**Comment by spdkils** [comment]
Maybe throw in a purple slime ball, or maybe some glowstone... Something that may be useful but annoying to get.

**Comment by Kuktar** [comment]
Even something as mundane as an actually additions iron casing can feel
rewarding. These 8 less iron to grind out.

I understand it's an expert pack, I also fully understand FTB ie a non
profit so I'm not complaining :)

**Comment by 016Nojr** [comment]
There are a bunch of tech stuff you can get in some loot chests, but not all. After I am finished, you will see more of that

**Comment by 016Nojr** [comment]
I am waiting for a mod update to update loot chests. I can do some changes, but not all

**Comment by 016Nojr** [comment]
I am waiting for a mod update to add a few things to the loot chests. Check the changelog for the next update to see the changes.
