### ISSUE TITLE
AE2 eating items after stalling on Lapatron

### ISSUE THREAD

**Issue by zenoran** [FTBTeam/FTB-Continuum#166]
* **Modpack Version**: https://www.feed-the-beast.com/projects/ftb-continuum/files/2569414

* **Issue**: Trying to do Powercell recipes in AE2 crafting it errors out on Lapatron Crystal and eats all the items if you try and cancel it

* **Link to Log or Crash File Paste**: no logs

* **Is it Repeatable?**: yes 100%

* **Mod/s Affected**: AE2

* **Known Fix**: Manually build the Lapatron and AE2 recipes work for up to High Powercells

**Comment by tyler489** [comment]
You can do what i did and set it to a processing pattern and hook it to an rftools crafter and an interface. As a workaround
