### ISSUE TITLE
Magma Crucible uncraftable

### ISSUE THREAD

**Issue by Godelboard** [FTBTeam/FTB-Continuum#167]
* **Modpack Version**: Continuum 1.2.0

* **Issue**: Magma Crucible is unobtainable.

  - Recipe requires Hardened Glass.
  - Hardened Glass requires Signalum.
  - Signalum requires Destabilized Redstone.
  - Destabilized Redstone is only available from Magma Crucible.

You can see how this makes magma crucible uncraftable.

* **Is it Repeatable?**: Yes, through natural progress, attempt to craft magma crucible on version 1.2.0 of the modpack. It requires things that only it can make.

* **Mod/s Affected**: Latest Thermal Series mods included in pack (not sure specifically if it's ThermalExpansion-1.12.2-5.5.0.29-universal or ThermalFoundation-1.12.2-2.5.0.19-universal)

* **Known Fix**: Without altering the progression for obtaining hardened glass, fix would be to change magma crucible recipe to something obtainable.

* **Other thoughts**: COFH Patch notes for thermal series mentions "Tweaked various recipes and energy values." It might be a good idea to look through these to make sure progression isn't now blocked (or broken) by these changed recipes.

**Comment by tfox83** [comment]
fixed in 1.2.1
