### ISSUE TITLE
Enderium Jetpack not being able to hover/ Slow flight speed

### ISSUE THREAD

**Issue by Lyte2k** [FTBTeam/FTB-Continuum#168]
* **Modpack Version**: 1.2.1

* **Issue**: Enderium Jetpack hovering doesn't work, when trying to fly the player keeps going down at a very fast rate. You should be able to hover for quite a bit with the Enderium jetpack. Don't know if this change is intentional. (wasn't stated in patch notes)

* **Is it Repeatable?**: Yes you just need to fly with a Enderium Jetpack

* **Mod/s Affected**: Simply Jetpacks 2

* **Known Fix**: Perhaps it has to do with configs of the jetpacks?
Updated video: https://www.youtube.com/watch?v=raR_7ttqdPg&feature=youtu.be

**Comment by Kuktar** [comment]
In my own server I had this issue. The hover hotkey was L. It was linked to
3 other hotkeys. I made sure the hover key was the only hotkey using L and
it worked for me.

**Comment by Lyte2k** [comment]
I made sure that no other hotkey was bounded to the hover hotkey and it still didn't work, Single player world btw.

**Comment by Kuktar** [comment]
Dang I am unsure why this would happen. Did you install any additional mods
beyond the base pack? I'm just a friend trying to help I'm not with Team
FTB although sometimes I wish :)

**Comment by Lyte2k** [comment]
No I haven't changed any of the mods. :/

**Comment by Ludi87** [comment]
I believe in the questbook it says that only the higher tier hovermode works. So I guess its disabled, just wasn't disabled entirely in the older versions

**Comment by Kuktar** [comment]
What's higher than endierim lol. Maybe ftb need to take a look at this.

**Comment by Ludi87** [comment]
The fluxed electrum one? I haven't made it yet. Don't have my Blast Furnace upgraded that far

**Comment by aaronhowser1** [comment]
The JetPlate is the highest tier and has a working hover mode. I'm not sure about the lower tiers though.

**Comment by Lyte2k** [comment]
Ah, so it is intended. I'll just make the jetplate then.
