### ISSUE TITLE
Script errors in Efab.zs

### ISSUE THREAD

**Issue by eikotehmouse** [FTBTeam/FTB-Continuum#169]
* **Modpack Version**:1.2.0 & 1.2.1 

* **Issue**:CraftTweaker is broken a long with other errors 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: Don't know the full extent ,but efab and crafttweaker seem to be to the issue

* **Known Fix**: 
![2018-06-05_18 41 01](https://user-images.githubusercontent.com/39401341/41133677-53f12b04-6a96-11e8-9929-ad76dbce6613.png)
![2018-06-07_21 14 28](https://user-images.githubusercontent.com/39401341/41133962-f31968a8-6a97-11e8-93d0-5a40981140fd.png)

**Comment by aaronhowser1** [comment]
Have you tried reinstalling the pack from scratch? Make a backup of the instance, or just tell Twitch to install the pack again from the Continuum page

**Comment by eikotehmouse** [comment]
No, I haven't as just patching back to 1.1.0 fixed the errors.

**Comment by aaronhowser1** [comment]
It looks like there was an error updating or something. I updated to 1.2.1 and it works fine.

**Comment by eikotehmouse** [comment]
Iv been patching from cursed since I first downloaded it. Because when I first got it. the IE crafting table was disabled. No one informed when I was asking in streams that there was a "version tab"

**Comment by tfox83** [comment]
This works fine for me as well, please do a fresh install of client and server if playing on server
