### ISSUE TITLE
Sticky Sucrose quest task does not match description

### ISSUE THREAD

**Issue by Xavion3** [FTBTeam/FTB-Continuum#17]
* **Modpack Version**: 
1.01

* **Issue**:
Sticky Sucrose quest says it requires 131,072 buckets of honey in the description, but it actually requires 1,000,000 buckets of honey from the actual number on the task.

* **Is it Repeatable?**:
Yes.

* **Mod/s Affected**: 
Better Questing

* **Known Fix**:
Change the value in the description or task.

**Comment by aaronhowser1** [comment]
I'll get that fixed in the next update, I had all the hoarding quests need that much originally and changed all of them to 2 Gargantuan Drums. Apparently I missed this one :P

**Comment by tfox83** [comment]
got this change merged into 1.0.2
