### ISSUE TITLE
Quartz wont reconstruct into Prismarine Shards

### ISSUE THREAD

**Issue by tarjayylmao** [FTBTeam/FTB-Continuum#170]
* **Modpack Version**: 1.2.1

* **Issue**: Throwing quartz on the ground, and hitting it with the reconstructor beam wont give me prismarine shards! My generators are maxed on banked power and the atomic reconstructor has max power as well, it just wont conver it. Zombie turning into leather doesn't work either, multiple recipes aren't working.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**:  Yes

* **Mod/s Affected**: ActallyAdditions is the mod that isn't working properly.

* **Known Fix**: 

* **Example**: https://gyazo.com/6b0f8d3f90c6a7d046cfd4dd207261a8

**Comment by aaronhowser1** [comment]
Both of those recipes were removed, this is on purpose. You're supposed to go find an Ocean Monument for Prismarine.

**Comment by tarjayylmao** [comment]
Can it please be removed the Actually Additions Manual then?

**Comment by aaronhowser1** [comment]
I don't think we can actually do that, you'd have to ask the AA dev to let us disable those pages
