### ISSUE TITLE
Thermoelectric Generator?

### ISSUE THREAD

**Issue by BoomCheeseBurger** [FTBTeam/FTB-Continuum#171]
Hi, I'm wondering of where the instructions are to make/craft the thermoelectric generator. I can't seem to find the crafting recipe for it for some reason. Please help! Thanks

**Comment by mtimyself** [comment]
This pack has disabled a lot of things from the mods included.
If you can not find a crafting recipe in JEI you can assume that this particular block is disabled.

**Comment by Lyte2k** [comment]
The thermoelectric generator has been disabled, you have to find other ways of generating power. I used the dynamos at the start to generate enough power to progress. Hoped this helped :)

**Comment by BoomCheeseBurger** [comment]
@mtimyself I'm sorry I responded late, thank you for responding me. Ah, I see, no wonder I have been seeing some blocks and other stuff in the JEI not showing its recipes to me :I

**Comment by BoomCheeseBurger** [comment]
@Lyte2k Ooo, thanks for your advice! I'll try the dynamos that you mentioned and other power generators(hopefully they have the recipes) to help me continue the quests. This really helped me a lot because its my first time using a big modpack haha

**Comment by mtimyself** [comment]
Not to be too pushy about this but I can relate to this one a bit,
I am now at the point where the Extreme Reactor (let alone the Fusion Reactor) makes these issues irrelevant but I would like to come back to the issue of https://github.com/FTBTeam/FTB-Continuum/issues/61 .
The idea and/or demand has never been to change the power generation and balance but to document it a bit better.
The quest book is full of ways to spend Power but hardly any to make it.
The truth of the matter is that with the way this pack is balanced TE Dynamos are the absolute meat of early and/to mid gamer power gen.
Why not mention this in the quests?

**Comment by BoomCheeseBurger** [comment]
@mtimyself Right, I agree with you. They should've just added it in. Like why not? you know... Makes it easier for the early players out there.

**Comment by BoomCheeseBurger** [comment]
Do you have any suggestions for beginners like me to power the metal press?

**Comment by aaronhowser1** [comment]
I can see about making more RF gen quests. The biggest problem I'm having with adding more quests is that like 99% of them would go into "Industrial Rebirth" which is already the most cluttered chapter and I don't know where it'd be best to split it into multiple chapters. Any suggestions for that would be much appreciated though :D

**Comment by BoomCheeseBurger** [comment]
Thanks for your response! I'm already satisfied by the work you put into these modpacks too. Ah... I'll think about some ideas. In the meantime, I'm going to be using the clockwork engine, its as useful as other power gen.

**Comment by ByteTemplar** [comment]
LibVulpes coal generators are extremely cheap to make and provide good amount of power per coal, and are "smart" to not burn any resource if power is not needed. Highly recommend for early game.

Only problem I have with them is, when they start animation, my FPS drops down quite badly.

**Comment by BoomCheeseBurger** [comment]
Thanks for your suggestion! I think I've seen that somewhere in the quests. Hopefully, it will help me with my progress in the game :) @ByteTemplar
