### ISSUE TITLE
Extra Bees - Missing recipes

### ISSUE THREAD

**Issue by Zianno** [FTBTeam/FTB-Continuum#172]
* **Modpack Version**: 1.1.0

* **Issue**: Certain recipes do not seem to be available in JEI, for example Tarnished bees create tin grains which can then be crafted into pulverised tin. Corroded bees produce copper grains which appear to have no valid recipe in JEI. Glittering bees create gold grains which also appear to not have a valid JEI recipe for crafting them into gold dust. I do not know whether this is intentionally disabled in this pack, but these are the two I have come across so far. There may well be others.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Extra bees

**Comment by tfox83** [comment]
fixed in 1.4.0
