### ISSUE TITLE
Mutagen Not Obtainable

### ISSUE THREAD

**Issue by apdjz** [FTBTeam/FTB-Continuum#173]
Modpack Version: 1.1.0

Issue: A big part of GenDustry is to be able to mutate your bees. Unfortunately, you need mutagen to do so.  I could make the mutagen producer and the advanced mutatron. But with no recipe for mutagen,  I don't see the point of adding GenDustry in the modpack.

Is it Repeatable?: Yes

Mod/s Affected: GenDustry

**Comment by leojaxx** [comment]
put Glowstone or Redstone in the Mutagen producer. Works for me

**Comment by aaronhowser1** [comment]
@leojaxx is right, the recipe just doesn't show up in JEI. You could post this on the [Gendusty issue tracker](https://github.com/bdew/gendustry/issues), but it does works.
