### ISSUE TITLE
Server crash loop upon updating to version 1.2.1

### ISSUE THREAD

**Issue by TGSRagnarok** [FTBTeam/FTB-Continuum#174]
* **Modpack Version**: 1.2.1
* **Issue**: Server Crash loop upon updating to version 1.2.1
* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/2474a851
* **Is it Repeatable?**: every time trying to start server
* **Mod/s Affected**: no clue
* **Known Fix**:

**Comment by KuroPeach** [comment]
you should updata  forge to 14.23.4.*

**Comment by tfox83** [comment]
you are missing mods, please try a fresh download of the server
