### ISSUE TITLE
Tech Reborn: Import Stack Limit

### ISSUE THREAD

**Issue by mtimyself** [FTBTeam/FTB-Continuum#175]
* **Modpack Version**: 1.2.1

* **Issue**: The latest patch causes TR machines to ignore internal inventory space and import unlimited amounts of items when using the machines' own import function.

http://prntscr.com/jsnt42

The items are returned when breaking the block.

**Comment by Kuktar** [comment]
That's awesome. Imho but ya maybe limit to like 4 stack sizes lol

**Comment by modmuss50** [comment]
I am aware of this, I will fix ASAP (tomorrow)

**Comment by aaronhowser1** [comment]
Interestingly, the items are actually in the block still, and it works fine.

![image](https://user-images.githubusercontent.com/15698722/41195460-7d6c94ec-6bf3-11e8-82c4-db7297210af6.png)
![image](https://user-images.githubusercontent.com/15698722/41195462-82189608-6bf3-11e8-8653-17a49fb7b7a9.png)

**Comment by modmuss50** [comment]
Yeah, once the stack goes below 64 it should start working again, anyway its fixed in the next version.

**Comment by tfox83** [comment]
fixed in 1.3.0
