### ISSUE TITLE
AE2 autocrafting of vanilla crafting table fails

### ISSUE THREAD

**Issue by Prometheus0000** [FTBTeam/FTB-Continuum#176]
* **Modpack Version**:
1.2.1
* **Issue**:
When trying to autocraft a crafting table, when you click next, it's supposed to show you the needed materials, but it fails to do anything. Autocrafting a molecular assembler also fails in the same way, probably because of using the crafting table in its recipe. Allowing oredict substitutions doesn't help either. Removing the crafting table pattern allows the molecular assembler recipe to work correctly, if you make the crafting tables yourself.
* **Is it Repeatable?**:
Yes, also fails on my test world. Although it mysteriously started working properly right when I finished typing this, exiting and entering the test world caused it to not work again.
* **Mod/s Affected**:
AE2

**Comment by aaronhowser1** [comment]
I tested this by autocrafting 100 Molecular Assemblers and it worked fine. Are you sure you're trying to autocraft *vanilla* Crafting Tables, and not a Natura variant?

**Comment by Prometheus0000** [comment]
It's made with oak planks, so it should be the vanilla one. After loading the game up today I went into my test world and it worked, so I went into my SSP game and it didn't work, then I went back into the test world and it once again didn't work so I figured maybe it's something that persists across sessions? I completely exited the game and twitch, and then tried loading up my SSP game first. The crafting table recipe worked the first time but when I exited and reentered the world it would no longer load the recipe materials page once again. I did the same thing for my test world, and it failed the second time as well, so it's not just my SSP save.

**Comment by Prometheus0000** [comment]
I looked at the logs and found the relevant portion that relates to this. It repeats whenever I click the next button.
Https://pastebin.com/xcq2QMUm

**Comment by aaronhowser1** [comment]
Have you tried remaking the patterns? I was having some issues with Mixed Metal Ingots not being made that got fixed when I reset then remade the pattern for it.

**Comment by Prometheus0000** [comment]
Yes, I tried even using a different blank pattern to make it too.

**Comment by tfox83** [comment]
I am not able to reproduce this, as Aaron suggested try remaking the patterns, sometimes the oreDict can be a little dirty with AE2
