### ISSUE TITLE
Remove Slimesling's tooltip about Slime Boots

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Continuum#177]
* **Modpack Version**: 1.2.1

* **Issue**: The Slimesling's tooltip says to use Slime Boots, which are disabled. It'd be less confusing if it was removed. Keep the "Charge up, aim low" bit though!

* **Mod/s Affected**: Tinkers' Construct, maybe CraftTweaker

**Comment by tfox83** [comment]
I cant edit a mods tooltip, I can only add my own

**Comment by aaronhowser1** [comment]
Can't you remove the tooltip that's already there, then add in a new tooltip that has the part we want to keep?

**Comment by Morganamilo** [comment]
On a similar topic, I made this purely because the quest suggested it. After finding there are no slime boots it seems a little useless? Is there an alternative to negate fall damage?

**Comment by aaronhowser1** [comment]
The Hang Glider works pretty well with it. Use the Slime Sling to get high, then use the Hang Glider to fly away
