### ISSUE TITLE
Remove RFToolsPower Power Cores

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Continuum#178]
* **Modpack Version**: 1.2.1

* **Issue**: RFToolsPower added Power Cores for the different tiers, which are supposed to be used for crafting components. They have no use in this pack so they should be disabled I think.

* **Mod/s Affected**: RFToolsPower, CraftTweaker

**Comment by tfox83** [comment]
![image](https://user-images.githubusercontent.com/4246308/41367137-04a01658-6ef3-11e8-869e-bed6d65be93c.png)

This has been in since release:
```
#remove power cores (using own recipes)
mods.jei.JEI.removeAndHide(<rftoolspower:power_core1>);
mods.jei.JEI.removeAndHide(<rftoolspower:power_core2>);
mods.jei.JEI.removeAndHide(<rftoolspower:power_core3>);
```
