### ISSUE TITLE
Modded planks aren't craftable in any sawmill variant

### ISSUE THREAD

**Issue by Xavion3** [FTBTeam/FTB-Continuum#18]
Modpack Version:
1.01

Issue:
Modded planks aren't craftable in either of the saw mills, this is because the normal crafting recipes are removed so the mods don't pick it up as a valid log -> planks combo when automatically scanning for them so no sawmill recipes are added. Opening with more information due to closure of #13 which referenced vanilla crafting too.

Is it Repeatable?:
Yes, just load the pack and check JEI.

Mod/s Affected:
Natura, Traverse, Forestry, Binnie's

Known Fix:
Either allow them to be crafted via vanilla crafting, which gets recipes automatically created for Binnie's Lumber mill and both the tech reborn and thermal expansion sawmills, or manually add saw mill recipes for every single modded log.

Drawing from @RealClassixX 's script posted in #13, just adding a few missing logs I noticed [this will work to manually readd every recipe to vanilla crafting](https://hastebin.com/evedaxafig.css) if that fits the idea that people can actually use any of the trees and don't need to track down vanilla trees. The alternative is to add recipe similar to those for the sawmill, but there's multiple sawmills in the pack and I don't have time to make recipes for all of them right now. That script will add recipes for the lumber mill and both sawmills as mentioned however in addition to the normal crafting options.

**Comment by RealClassixX** [comment]
Oh, right, I forgot about Techreborn and Traverse.

**Comment by Xavion3** [comment]
Also there's two bloodwood logs for some reason.

**Comment by tfox83** [comment]
Ok I think its best to add in the 2 plank output for everything at this point so all the saw mills populate that recipe correctly.  Ill get this finished and pushed in the next hotfix

**Comment by RealClassixX** [comment]
I looked that up, and I only found the one where bark only covers part of the log crafting into planks, I assumed the other one was like bark.

**Comment by tfox83** [comment]
techreborn rubber wood isnt in the pack, but ill get the traverse fir log added to that list and test, thanks for the help

**Comment by tfox83** [comment]
ok so now all logs give two planks via crafting, 3 via TE sawmill and forestry lumbermill and 4 via TR sawmill
this will go into 1.0.2 which I should have out today.  Thanks again for all the help guys.

**Comment by Xavion3** [comment]
What do you mean rubber wood is not in the pack? I've got several saplings in a chest and a dozen trees grown, or is it that planks aren't meant to be craftable? If it's trees don't spawn then you missed something, tech reborn adds a village structure which is just a small farm with dozens of saplings and several rubber trees already grown, been in all three villages I've found so far.

**Comment by tfox83** [comment]
we decided to change the output of TE sawmill to 4 planks and TR sawmill to 6 planks.  instead of 2/3/4.  Just so it feels like its worth the upgrade more.

**Comment by tfox83** [comment]
This has been released in v1.0.2
