### ISSUE TITLE
ME Controller doesn't instantly craft with Power Optimizer

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Continuum#180]
* **Modpack Version**: 1.2.1

* **Issue**: It takes 3.75 minutes to craft with or without the Power Optimizer instead of crafting instantly. 
![image](https://user-images.githubusercontent.com/15698722/41195824-54da0b3e-6bfa-11e8-8818-1c53d3a2286b.png)

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: EFab

**Comment by mtimyself** [comment]
Is an instant craft the intended outcome?
When I did it last it still showed the full time but then a minute would pass in a few seconds.
So it worked in speeding it up it just was not representing it properly.

**Comment by aaronhowser1** [comment]
The Power Optimizer is supposed to make it so that RF crafts complete instantly, or at least it did in development. That sounds like another issue, looks like the Power Optimizer got a bit buggy in recent versions.

**Comment by tfox83** [comment]
Fixed in 1.4.0
