### ISSUE TITLE
Advanced RF Storage provides 0 RF/t to craft operations

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Continuum#181]
* **Modpack Version**: 1.2.1

* **Issue**: Advanced RF Storages provide no RF/t to the EFab. This multiblock should be providing 1050 RF/t , but it only provides 50.

![image](https://user-images.githubusercontent.com/15698722/41196362-ccb256b2-6c03-11e8-86ca-498e9e07f60a.png)

* **Mod/s Affected**: EFab

**Comment by Lyte2k** [comment]
Having the same issue.
![2018-06-10_16 28 54](https://user-images.githubusercontent.com/26687145/41203180-7cac005a-6ccb-11e8-9f47-05942c1f7915.png)

**Comment by Lyte2k** [comment]
It's actually not providing any RF, the RF controls are giving the Efab 50 RF/t each.

**Comment by aaronhowser1** [comment]
Duplicate of FTBTeam/FTB-Continuum/issues/144
