### ISSUE TITLE
Crash: java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Continuum#182]
* **Modpack Version**: 1.2.1

* **Issue**: Crash happened after putting Tri/Deuterium into a Fusion Controller filled with RF.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/ad49eca1

* **Mod/s Affected**: TechReborn

**Comment by tfox83** [comment]
fixed in 1.3.0
