### ISSUE TITLE
Gears are uncraftable

### ISSUE THREAD

**Issue by geogabe20** [FTBTeam/FTB-Continuum#184]
* **Modpack Version**: <1.1.0>

* **Issue**: <I cant craft gears. Gear crafting machines seem to be disabled and there are no recipes for gear crafting in TMI (or whichever version it happens to be). The gear recipes I know of without using TMI don't produce anything either. Making gears are needed for the clockwork engine and subsequent mission so I cant proceed without them.>

* **Is it Repeatable?**: <yes>

**Comment by alexsch01** [comment]
use smeltery with gear cast in the beginning and when you have steel and other things make the metal press from ie and gear mold 


Close this issue
