### ISSUE TITLE
Liquid DNA Planet is Gas Giant, cannot visit it

### ISSUE THREAD

**Issue by zeryl** [FTBTeam/FTB-Continuum#185]
* **Modpack Version**: 1.2.1

* **Issue**: When attempting to visit the Liquid DNA planet, you cannot.  After checking the planet definition, it's a gas giant, so you cannot visit it as the quest wants you to

* **Is it Repeatable?**: Yep, can't fly to it, nor can you use commands to get to it.

**Comment by aaronhowser1** [comment]
That's my fault, sorry. In development, it was a planet with an ocean made of the DNA from Gendustry when it was supposed to be the one from Binnie's Genetics, which doesn't have a valid liquid form. It was changed after I'd made the quest and I didn't realize it was changed. The quest will be changed to reflect that in the next update.
