### ISSUE TITLE
Quest description directly conflicts with the tooltips on the block

### ISSUE THREAD

**Issue by treechain** [FTBTeam/FTB-Continuum#186]
1.1.0
Quest description directly conflicts with the tooltips on the block. All the RFTools powercells have the same tooltip.
![2018-06-09_21 08 47](https://user-images.githubusercontent.com/30122899/41198143-08811000-6c38-11e8-96ca-374712c2ab02.png)

**Comment by aaronhowser1** [comment]
Update the modpack, this was fixed already
