### ISSUE TITLE
Bucket in vanilla Dungon

### ISSUE THREAD

**Issue by RedstoneMedia** [FTBTeam/FTB-Continuum#187]
* **Modpack Version**: FTB Continuum 1.12.2 (Beta)

* **Issue**: I got a bucket in a normal vanilla dungon . Wich made the game way easyer at the start .
Am I supposed to get a bucket at the start of the game ?

* **Is it Repeatable?**: Yes by finding a dungon .

* **Known Fix**: Edit the loot-tabels .

**Comment by Kuktar** [comment]
Buckets can be made in less than 1 hour after starting. Only need 3 iron
ore....

**Comment by RedstoneMedia** [comment]
Nevermind , sorry only saw the Galgadorion Metal recepie .

**Comment by Kuktar** [comment]
Oh lol. That makes like 64 buckets Haha

**Comment by aaronhowser1** [comment]
Yeah the Galgadorian bucket is a joke recipe, kind of poking fun at Infinity Expert Mode :P 
The real recipe is way easier, regular in the EFab with a Gear Box
