### ISSUE TITLE
Centrifugal Seperator - Wrong comb item extracted

### ISSUE THREAD

**Issue by Valerate** [FTBTeam/FTB-Continuum#188]
* **Modpack Version**: 1.1.0

* **Issue**: Some (I have not tested all combs tho) combs give the wrong items when used in Centrifugal Seperator(Thermal Expansion) vs Centrifuge (Forestry). For example: Platinum Comb is supposed to give Platinum Grains (4 -> 1 dust) but instead just straight up gives me 1 dust.
or Diamond comb which is supposed to give Diamond fragment instead gives a Diamond nugget (Its the same 9 -> 1 diamond tho so no biggie)
Another issue is that all the Centrifugal Seperator comb recipes are missing from JEI so I had to test it before I even knew it worked,

* **Is it Repeatable?**: yeah

* **Mod/s Affected**: Thermal Expansion, Extra Bees (Possibly Binnies Bees and Forestry aswell)

* **Known Fix**: I suppose check the recipe

**Comment by Valerate** [comment]
Id also like to add that the Centrifugal Seperator doesnt support lux comb from Extra bees, and that it is missing localization; https://i.imgur.com/BUv3I5E.png

**Comment by tfox83** [comment]
reported and should be fixed soon
