### ISSUE TITLE
RFTools Infuser will not infuse Builder

### ISSUE THREAD

**Issue by zeryl** [FTBTeam/FTB-Continuum#189]
* **Modpack Version**: 1.2.1

* **Issue**: RFTools Builder cannot be infused in current version

* **Link to Log or Crash File Paste**: No crash log

* **Is it Repeatable?**: Yep

* **Mod/s Affected**: RFTools

* **Known Fix**: Looks like McJTY fixed this: https://github.com/McJtyMods/RFTools/issues/1779

**Comment by tfox83** [comment]
fixed in 1.3.0
