### ISSUE TITLE
Server issues: Libraries not found

### ISSUE THREAD

**Issue by DerSoftwerker** [FTBTeam/FTB-Continuum#19]
* **Modpack Version**: 1.0.1 / 1.0.2

* **Issue**: Server won't start because it cannot find the Libraries. Uploaded to a gamehosting service and started the forge jar file as usual.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/ce70f91a

* **Is it Repeatable?**: Yes

I have contacted the support of the hosting company, they have not found any problems on their side so far.

**Comment by LatvianModder** [comment]
Does it work on your computer? Maybe its a permission issue or smth

**Comment by DerSoftwerker** [comment]
Possibly. Sadly I do not have the knowledge to properly test a server pack on my local machine. I am using a managed root server for that reason too.

**Comment by 016Nojr** [comment]
Can you try downloading it from Curse again and uploading it to your host? All the libraries are correct in the server files on Curse so it's not on our end.

**Comment by DerSoftwerker** [comment]
Thanks for the update. Already tried that without success. Will relay the info to the server hoster.
