### ISSUE TITLE
Mobs spawn on planets without oxygen and instantly die

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Continuum#190]
* **Modpack Version**: 1.2.1

* **Issue**: Especially at night, they just spawn and die and spawn and die, and tons of item entities stay on the ground.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Advanced Rocketry

**Comment by tfox83** [comment]
I dont see that as a huge deal, I have no way of controlling without a additional mod.  Entities time out after 5 minutes.
