### ISSUE TITLE
X-Net 1.7.0 

### ISSUE THREAD

**Issue by dragonpaw** [FTBTeam/FTB-Continuum#191]
Please update to X-Net 1.7.0

(I was unlucky enough to hit this: https://github.com/McJtyMods/XNet/issues/253 )

**Comment by jottafan** [comment]
1.2.0 UPDATE got xnet 1.7.0

**Comment by aaronhowser1** [comment]
Like @jottafan said, this is already in. Update your modpack.

**Comment by dragonpaw** [comment]
Ah, ok. Had it sent to latest released pack and didn't notice the newer betas.
