### ISSUE TITLE
Can't Claim quest rewards since Update

### ISSUE THREAD

**Issue by Zaphod776** [FTBTeam/FTB-Continuum#193]
* **Modpack Version**: 1.2.1

* **Issue**: Can't claim quest rewards, Quest shown as "unclaimed reward" but claim button is grayed out. 

* **Link to Log or Crash File Paste**: No Crash log

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Better Questing

**Comment by aaronhowser1** [comment]
have you tried closing and opening the GUI? Sometimes it gets stuck like that.

Also, which quest is it? Is it a quest with multiple rewards?

**Comment by Zaphod776** [comment]
yes It was multiple reward quests, I forgot to choose a reward, my fault. sorry
