### ISSUE TITLE
Natura trees wont grow at sea level 1.2.0 "possible work around"

### ISSUE THREAD

**Issue by FuzZzerJUnKey** [FTBTeam/FTB-Continuum#194]
_I think this may be a mod issue but may have found a work around_

Version: 1.2.0

Issue: The Natura trees will not grow from a sapling at sea level. I set the Y level. to 61 in the nature config file and that fixed the issue. that is 2 block below the actual water lvl at 63. 

No log file.

Yes this is repeatable.

Unknown. 

Set the the spawn of Natura trees in the Natura config file to 2 blocks below the sea level setting.

**Comment by tfox83** [comment]
fixed in 1.3.0
