### ISSUE TITLE
Not loosing XP on death.

### ISSUE THREAD

**Issue by Kuktar** [FTBTeam/FTB-Continuum#195]
* **Modpack Version**:1.2.0

* **Issue**: When i die i do not loose XP wether i am an OP or not>

* **Link to Log or Crash File Paste**: NA

* **Is it Repeatable?**: YES

* **Mod/s Affected**: the whole modpack?

* **Known Fix**: i know there has to be somthing to enable loss of xp on death or even other means. i am level 163 playing for 100 days now. i have died many times. it never occured to me that i have never lost XP other than using oreexcevate wich i have set to 10 lvls per orevein.

please help me by either letting me know an config option or somthing. i just think its overpowered to never loose xp

**Comment by aaronhowser1** [comment]
Do you have keepinventory set to true?

**Comment by Kuktar** [comment]
No it gets put into my grave. I will double check though.

**Comment by Kuktar** [comment]
Ok i figured it out. On my server I'm open. And with my grave mod corail
tombstone it has a config to keep % of xp. I didnt notice but I set non op
to 50%. And op was set to 100% lol

Thanks for the reply I'll close this.
