### ISSUE TITLE
Comb and Grain issues

### ISSUE THREAD

**Issue by Godelboard** [FTBTeam/FTB-Continuum#196]
* **Modpack Version**: 1.2.0

* **Issue**:

1. Several honeycomb grain piles are uncraftable into their dust variants. Gold, Silver, Copper, Nickle, and Zinc. The rest of the grain piles are craftable into dusts (iron, platinum, tin, lead, titanium, tungsten, coal, yellorium, cyanite, blutonium).
2. Several combs are giving 100% grain yield in centrifugal separator, but 25% in forestry centrifuge. This applies to yellorium, blutonium, and cyanite combs.
3. In centrifugal separator, blutonium combs yield cyanite grains, and cyanite combs yield blutonium grains.

* **Is it Repeatable?**: Yes; persistent.

* **Mod/s Affected**: Extra Bees/Forestry.

* **Known Fix**:
I don't know if disabling some of the grain -> dust recipes was intentional or not, but those recipes should be enabled/disabled to be consistent with whatever the original intention was. If disabled, maybe disable even obtaining the comb if possible?
If left enabled, centrifugal separator recipes should fix yields for yellorium, cyanite, and blutonium combs to be consistant (% wise and output wise)

**Comment by tfox83** [comment]
fixed in 1.4.0 (added drops to missing grains)
