### ISSUE TITLE
Fusionarium quest or planet is incorrect, no heliumplasma present

### ISSUE THREAD

**Issue by zeryl** [FTBTeam/FTB-Continuum#198]
* **Modpack Version**: 1.2.1

* **Issue**: Fusionarium quest says HeliumPlasma is on the planet, but only helium3, tritium and deuterium is.  Either the quest is wrong, or the planet is wrong.

**Comment by tfox83** [comment]
Ill have @aaronhowser1 update the quest

**Comment by zenoran** [comment]
I can't seem to rocket down to Fusionarium?  It says destination unreachable when orbiting the planet?

**Comment by aaronhowser1** [comment]
It's a gas giant, it can't be landed on.

**Comment by zenoran** [comment]
Ooh okay. I didn't realize that was a thing so I'll look into it.  Thanks!

**Comment by tfox83** [comment]
Fixed in 1.4.0
