### ISSUE TITLE
Items thrown out of inventory when left-clicking them

### ISSUE THREAD

**Issue by DevSnobo** [FTBTeam/FTB-Continuum#199]
* **Modpack Version**: 1.1.0

* **Issue**: Disclaimer: This happened to me in singleplayer without Optifine and also after I installed Optifine for fps reasons. If this renders this ticket useless for you, so be it, sad me.

Sometimes (I can't make out the cause for this), when just logged into my world/a multiplayer server, I try to put things into chest via Shift + Left-click, which throws stuff on the ground. When I pick the stuff up again and try to manually click it into the chest, upon clicking the items are thrown out of my inventory.

I was just complaining to other people on the server and after about 5 minutes, it returned to normal. Re-logging multiple times also seemed to resolve the issue.

* **Link to Log or Crash File Paste**: I don't think there's any log about this. If there is, please point me to the correct folder.

* **Is it Repeatable?**: Not deliberately.

* **Mod/s Affected**: I think I did things in the Immersive Engineering Workbench before this happened (upon next login). But don't quote me on that, could be anything, really.

* **Known Fix**: Waiting or re-logging lots.

If you need more information, please go ahead and ask for it. I'll try my best to provide it.

**Comment by aaronhowser1** [comment]
This is an InventoryTweaks issue I think. Basically just start spamming space, shift, and alt for a few seconds, then try again.

**Comment by DevSnobo** [comment]
Thanks for the instant response. I'll try that when it occurs the next time!
