### ISSUE TITLE
Is coop play possbile?

### ISSUE THREAD

**Issue by mtimyself** [FTBTeam/FTB-Continuum#2]
* **Modpack Version**: 1.0.0

* **Issue**: 
For people unfamiliar with Better Questing you could add instructions on how to form a group/party to share Quest progress in the BQ Introduction Quest.
I have only previously used Better Together and that is not present so we are currently not able to play.

**Comment by mtimyself** [comment]
I have found the Party button on the main page. Must try pretty hard to miss that... Maybe still worth adding a small line of text for people as stupid as me ;)

**Comment by aaronhowser1** [comment]
I'll see about adding a note about it in the Questing Tutorial quest :)

**Comment by tfox83** [comment]
going to close this, a note in the tutorial will work, thanks
