### ISSUE TITLE
Minor discrepancy in quest text about Efab Tank

### ISSUE THREAD

**Issue by Joe4evr** [FTBTeam/FTB-Continuum#20]
* **Modpack Version**: 1.0.1

The questbook claims an Efab Tank holds 10 buckets, but it's 16.
![2018-05-16_16 25 33](https://user-images.githubusercontent.com/1058562/40151253-09937d32-597f-11e8-9a31-972aad07a32b.png)

**Comment by aaronhowser1** [comment]
Will be fixed in next update
