### ISSUE TITLE
Electric Furnace deletes input buffer of items on log out if it holds more than 64 items.

### ISSUE THREAD

**Issue by MBlore** [FTBTeam/FTB-Continuum#200]
* **Modpack Version**: 1.2.1-1.12.2 (Beta)

* **Issue**: Placed 10 stacks of iron dust in a chest on the left side of an Electric Furnace. The furnace begun inputting the iron dust and outputting bars to a chest on the right side of the machine. I loggged out, logged back in, all 10 stacks of Iron dust had magically dissappeared. I've just confirmed again by filling the furnace with another batch of dust (this time Nickle), logged out, logged back in, all dusts dissappear out of the machine. It appears the machine is holding all the ore inside of the machine, as it shows 64 in the slot when I open the UI, but when I look at the tooltip of the machine, it shows all the dust beind held inside the machine somewhere. Logging out clears out the entire input buffer of the machine.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes, as explained in the issue above.

* **Mod/s Affected**: Tech Reborn 2.15.12.690

* **Known Fix**: It appears that if I do not put more than 64 items in the machine (it doesnt show more than this when you look at the machine), the input stack does not clear when I log out and back in. Fix by limitting the machine from taking more than 64 in total - somehow having it see how much it holds in that magical input buffer it has?

**Comment by aaronhowser1** [comment]
This is a known bug that's fixed in mod updates, will be included in next Continuum version

#175

**Comment by tfox83** [comment]
fixed in 1.3.0
