### ISSUE TITLE
"Empty cell" gets NBT tag in ME Fluid Terminal.

### ISSUE THREAD

**Issue by jottafan** [FTBTeam/FTB-Continuum#201]
* **Modpack Version**: 1.2.1
* **Issue**: emptying a fluid from a tech reborn cell into the fluid terminal gives the empty cell a NBT tag wich shows it holds no fluid. This makes the "empty cell" unusable in the "industrial electrolyzer". (possibly more issues with other machines/recipes.) The tagged and the untagged cell obviosly doesnt stack either. Still, both are just empty cells from the same mod.

* **Link to Log or Crash File Paste**: ![alt text](https://i.imgur.com/RuxOfF8.png "nbttag")
* **Is it Repeatable?**: yes, every cell that i empty into the ME gets the tag. 

* **Mod/s Affected**: Tech Reborn, Extra cells 2

* **Known Fix**: dont know, but the tag is gone if u fill the cell back up and empty it into any tank by rightclicking.

**Comment by tfox83** [comment]
Fixed in 1.4.0
