### ISSUE TITLE
Assassin Queen Disappeared (from crashing world)

### ISSUE THREAD

**Issue by alexsch01** [FTBTeam/FTB-Continuum#204]
Modpack Version: 1.1.0
Issue: When I right click the apiary with an Assassin Queen in there it crashes to desktop

Link to Log or Crash File Paste: https://paste.feed-the-beast.com/view/9239ba56

Is it Repeatable?: Yes

Mod/s Affected: Probably Forestry and Career Bees

**Comment by alpal01** [comment]
now i can't even go to my world without crashing to desktop i need help

**Comment by alpal01** [comment]
@tfox83 world is basically corrupt now

**Comment by alexsch01** [comment]
so the assassin queen disappeared but the world is no longer corrupt @tfox83

**Comment by alexsch01** [comment]
Update: What worked for me is I just put the Assassin Queen in my bee-bee gun instead of putting it in an apiary for the princess (still cost me an Assassin Queen that was voided) - This is still a bug (not intended)

**Comment by tfox83** [comment]
its a known bug at this time, as soon as a fix comes from career bees it will be added into the pack
