### ISSUE TITLE
Openblocks grave doesnt spawn on bedrock

### ISSUE THREAD

**Issue by SomeWeirdGuyWithAProblem** [FTBTeam/FTB-Continuum#205]
* **Modpack Version**: 1.1

* **Issue**: Graves from the mod Openblocks do not spawn on bedrock.

* **Link to Log or Crash File Paste**: I dont crash

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: OpenBlocks

* **Known Fix**: I dont know a fix.

**Comment by alexsch01** [comment]
A fix for the future might be disable OpenBlocks Graves and add Tomb Many Graves 2

**Comment by Kuktar** [comment]
Or corail tombstone! It's my favorite grave mod. 

Which dimension did this happen in. The overworld ?

**Comment by tfox83** [comment]
it spawns on the first block above it
