### ISSUE TITLE
Techreborn: Range Upgrade Uncraftable 

### ISSUE THREAD

**Issue by wyndman** [FTBTeam/FTB-Continuum#206]
* **Modpack Version**: 1.10

* **Issue**: Range upgrade from Techreborn Shows in JEI, but is not craftable

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: It sure is!

* **Mod/s Affected**: Tech Reborn

* **Known Fix**: Item is available via command, creative etc, appears that it should be blocked in JEI as a craftable recipe

**Comment by tfox83** [comment]
I did not remove this anywhere, ill have @modmuss50 take a look.  Thanks

**Comment by modmuss50** [comment]
I’d forgotten this was even a thing. I’m not sure it does anything. I’ll take a look, if it doesn’t do anything I’ll remove it.

**Comment by modmuss50** [comment]
Ok, it doesnt appear to do anything, so it will be removed in the next version of the mod.

**Comment by tfox83** [comment]
Fixed in 1.4.0
