### ISSUE TITLE
Blank quests interface.

### ISSUE THREAD

**Issue by Vudul** [FTBTeam/FTB-Continuum#208]
Modpack Version: 1.1.0

Issue: Better Questing interface is blank on my server.

I re-downloaded the pack but it didn't help.

**Comment by tfox83** [comment]
I cannot reproduce, I suggest a fresh install of both server/client

**Comment by Vudul** [comment]
Fresh install didn't work

**Comment by aaronhowser1** [comment]
Use the command "/bq_admin default load"
