### ISSUE TITLE
FTB Continuum 1.3.0: Updating the BQ book updates titles/description with useless ones :)

### ISSUE THREAD

**Issue by msegaud** [FTBTeam/FTB-Continuum#209]
* **Modpack Version**: 1.3.0

* **Issue**: After updating the quest book, nearly all descriptions and quests titles are missing

* **Is it Repeatable?**: yes

* **Known Fix**: Reedit the betterquesting/DefaultQuests.json file to fill the name/desc with real ones :)

**Comment by aaronhowser1** [comment]
I updated the quests to use localization, is there nothing in FTB Continuum\resources\continuum\lang? That might have been accidentally left out of the update :P I'll message @tfox83 and hopefully we can get a quick patch out that fixes it.

**Comment by aaronhowser1** [comment]
Fixed in 1.3.1
