### ISSUE TITLE
[Suggestion]The localization of the quests is needed

### ISSUE THREAD

**Issue by SihenZhang** [FTBTeam/FTB-Continuum#21]
In FTB Continuum, the names and descriptions of the quests is hardcoded which is hard to tranlsate to other languages.

Better Questing supports full localization of quest names and descriptions. 
https://github.com/Funwayguy/BetterQuesting/wiki/Localisation

So could you please use keys instead of plain text so that we can make localization for the modpack? I'll appreciate it if you can do this for a better localization.

**Comment by SihenZhang** [comment]
Hey! I just change all the hardcodes into keys. And here is the repository.

https://github.com/SihenZhang/FTB-Continuum-Guidebook-i18n

You can go and check it if you wanna use keys. 

Really appreciate it if you can use keys so that we can make localization more easily.

**Comment by tfox83** [comment]
going to have @aaronhowser1 look into this as he is handling most the quests in Continuum.  Thanks for your help.

**Comment by aaronhowser1** [comment]
Was this done with a script or other tool, or done manually?

Also, do you know if I can edit directly from the quest book if I change it to use localization like this?

**Comment by SihenZhang** [comment]
**Manually**...
I finished it for almost a week. And now it updated to 1.2.1

And, **NO** :( You should edit in the **lang file**. However,  I think it will become easier to edit quest without starting the game. 
The other things like quest requirement and the location of the quest logo should edit in game and will **NOT** have effect on the localization. 
The purpose of using key names is to make localization more easily. Just like what I do in the chinese-l10n branch.

**Comment by aaronhowser1** [comment]
Thank you so much for updating it to 1.2.1, I'll get the current dev changes applied to it too and then hopefully get it in the next version. Editing the text will be a bit simpler, but making new quests will be slightly more complicated. It's worth it for localization though!

Seriously, thanks for doing the bulk of the lang file, that would have taken me a really long time.

**Comment by juggarnost** [comment]
is there any way to get a list of the quests to their corresponding id #? i am working with a streamer on a semi private server and we have run into an issue with being able to travel to planets out of the "sol" solar system. i know we can force complete quests  with /bq_admin complete but it seems almost redundant to go through and complete them one by one until we find the right quests these people are on. Thanks!

**Comment by aaronhowser1** [comment]
@juggarnost That's the problem #253 had, still no idea why some people can see it and some can't.

**Comment by juggarnost** [comment]
i found a pseudo fix... have the player place down the holographic planet selector and select the planet they wish to travel to, then add the necessary "relics" to the warp controller. this will allow them to warp to planets in the Etech Conglomerate and the fluid planet systems, but it still does not allow them to travel to any planet within the consortium of resource. so those quests will ahve to be forceably achieved via /bq_admin complete 270 (playername) *eye of the storm* or so on for each quest. if i can find some kind of work around for the rest of the quests in that tree i will post it. I do most of my trouble shooting on modded minecraft whilst drunk and tend to find solutions in round-a-bout ways... hope this helps both server operators and the developers find some kind of solution!

**Comment by aaronhowser1** [comment]
If you just want to teleport to all the planets, you can do `/advancedRocketry goto [dimid]`. You can get the dimids using the command `/advancedRocketry planet list` also. You can find the rest of the AR commands [here](http://65.78.115.159:8000/AdvancedRocketry/Commands.php).

**Comment by juggarnost** [comment]
I will just do this then set beacons on the planets so they are discovered for all other players in the server! Thanks for the help!
