### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by as3ii** [FTBTeam/FTB-Continuum#210]
* **Modpack Version**: 1.3.0 and also 1.2.1

* **Issue**: _"The file ChickenASM-1.12-1.0.2.7.jar could not be identified; The file ImmersiveEngineering-core-0.12-82.jar could not be identified"_

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/e1a48895

* **Is it Repeatable?**: I've tried di reinstall the pack and the problem remains

* **Mod/s Affected**: Immersive Engineering

* **Known Fix**: noone

**Comment by Boomflex** [comment]
This is an error that is seen quite often using the Twitch launcher.

I would try closing down the Twitch App fully, waiting for around 10-15mins, then try again.

Sometimes the servers just don't pull the right things at the right time.
