### ISSUE TITLE
Crash when starting continuum *Update* fixed! 

### ISSUE THREAD

**Issue by xAceAngelx** [FTBTeam/FTB-Continuum#211]
Hello, originally I was receiving the following crash during launch. 
https://pastebin.com/rGpyQbfb

It took a while but I finally managed to fix the issue. here's how.
-uninstalled all versions of continuum from my system. 
-disabled onedrive (might be unnecessary)
-Twitch settings -> minecraft -> change download location to anything else **outside of onedrive**. 
-Used native launcher. 
-reinstalled to the new location, and DONE! 

I don't really know why things don't work within a onedrive folder, but hopefully this helps anyone else who might have been having a similar problem.

**Comment by aaronhowser1** [comment]
Try reinstalling Continuum from scratch using 1.3.1 on a new instance maybe

**Comment by xAceAngelx** [comment]
I still cannot figure out what is wrong. almost all the modpacks are giving me an error during launch. the only one that seems to be working is infinity lite.

**Comment by aaronhowser1** [comment]
Have you tried updating your graphics driver and Java?

**Comment by aaronhowser1** [comment]
Read the edited title, how was it fixed? If it's fixed, can you close the issue?

**Comment by xAceAngelx** [comment]
the fix was laid out in the original post. 

didn't realize I could close the issue, have a good one :]
