### ISSUE TITLE
Liquid Translocators Dissapearing?

### ISSUE THREAD

**Issue by tarjayylmao** [FTBTeam/FTB-Continuum#213]
* **Modpack Version**: 1.0.2

* **Issue**: I had liquid translocators setup on a sink, pumping water into a tank 24/7 and liquid translocators pumping latex from tree fluid extractors into a tank. These liquid translocators have seemed to just dissapear, I have no clue why. They are just gone

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**:  I dont know, I don't know what caused them to dissapear so no.

* **Mod/s Affected**: N/A

* **Known Fix**: N/A

**Comment by alexsch01** [comment]
try to middle click for inventory tweaks and update to latest release version

**Comment by gotnate** [comment]
I'm getting reports of the same issue on modpack version 1.1.0. Seems to be just liquid translocators, and not even all of them. Don't see anything standing out in my logs to indicate that this is happening.

**Comment by aaronhowser1** [comment]
I think it's chunk based. I have a chunk in my base that I had to replace all the Translocators with Ducts or Transfer Nodes, but the Translocator in the chunk directly next to it was fine.

**Comment by tfox83** [comment]
Fixed in 1.4.0
