### ISSUE TITLE
Multiblock caused Crash

### ISSUE THREAD

**Issue by FTBlover123** [FTBTeam/FTB-Continuum#214]
* **Modpack Version**: 1.1.0 (1.12.2 minecraft)

* **Issue**: When placing a redstone torch and a regular torch in the same block the multipart becomes invisible. Trying to break this multipart by removing the blocks supporting either of the torches crashes the game. Tested in Single Player.

* **Link to Log or Crash File Paste**: -

* **Is it Repeatable?**: Absolutely, first crash I experienced so far and did it again to check what actually happened.

* **Mod/s Affected**: Multiparts

* **Known Fix**: Not placing torches and redstone torches in the same block :P

**Comment by tfox83** [comment]
Crash report?
