### ISSUE TITLE
Industrial Foregoing Laser Lens missing for Dye Mixer

### ISSUE THREAD

**Issue by zenoran** [FTBTeam/FTB-Continuum#215]
* **Modpack Version**: https://www.feed-the-beast.com/projects/ftb-continuum/files/2572473

* **Issue**: The Dye Mixer is in the pack but there is no way to use it without the Laser Lense recipes.  I even tried using pink slime + stained glass pane to see if they were working but not showing up in JEI but that doesn't work either.

* **Is it Repeatable?**: YES

* **Mod/s Affected**: Industrial Foregoing

* **Known Fix**: NONE

**Comment by aaronhowser1** [comment]
Oh, does the Dye Mixer use Laser Lenses? I actually didn't know that, it was a bit of a niche block.

**Comment by zenoran** [comment]
Ya I've never used it either but saw it for dye recipes and was excited to try it out. Apparently there are separate laser lenses (not the environmental tech ones) for each color. I had to login to dw20 pack to verify myself. Not sure why they wouldn't show up on continuum but the block is 100% worthless without them.

**Comment by aaronhowser1** [comment]
I think the IF Laser Lenses were removed from Continuum because we assumed they were only used for the IF Laser Drill, which was also removed. Didn't know they were also used for the Dye Mixer, might add them back in so you can use those.

**Comment by mtimyself** [comment]
Since the Lens of Color is available I think the Dye Mixer should be allowed too.

**Comment by aaronhowser1** [comment]
It wasn't removed on purpose, it was an unintended consequence of removing the Laser Drill. We didn't know that the Dye Mixer used it at all.

**Comment by mtimyself** [comment]
I got confused by you saying you "might" re-add them.
The consideration is to introduce a custom recipe rather than to re-enable the Lens to not mislead people into thinking the Drill is a thing?

**Comment by aaronhowser1** [comment]
My understanding of the Dye Mixer is that you insert the color Laser Lens you want to get a dye of, the recipe for the Dye Mixer itself doesn't use any Lens at all. I'm not really in charge of item removals and additions, but I think that we should re add the Laser Lenses so that the Dye Mixer works, but keep the Laser Drill itself removed.

**Comment by mtimyself** [comment]
That sounds about right. I assumed you had jurisdiction over that.

**Comment by tfox83** [comment]
readded laser lens in 1.4.0
