### ISSUE TITLE
Runs fine for 5-10 minutes then has continuous lag spikes every 2-5 seconds

### ISSUE THREAD

**Issue by TheKiwiCub** [FTBTeam/FTB-Continuum#216]
Modpack Version: 1.1.0

Issue: Game runs fine for 5-10 minutes upon launch, then it will start to lag down to 1 fps every 2-5 seconds almost being unplayable

Image of F3: https://imgur.com/a/mbZ3FVg

Is it Repeatable?: Repeatable if you play for the 5-10 minutes beforehand

Mod/s Affected: Unsure

Known Fix: Restarting the game, need a permanent fix

*Note* Adding RAM does not affect the bug, my system has 16GB and putting everything from 3-8GB does nothing for this bug so I just put it back to default at 2.8GB

**Comment by mtimyself** [comment]
It does sound like a garbage collection issue to me so I would not count out RAM as the cause.
Are you playing on a server or SP? How do you launch the client?

**Comment by Kuktar** [comment]
Update modpack to 1.3 a lot of bugfixes related to efab and techreborn.



On Jun 15, 2018 11:18, "mtimyself" <notifications@github.com> wrote:

It does sound like a garbage collection issue to me so I would not count
out RAM as the cause.
Are you playing on a server or SP? How do you launch the client?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/FTBTeam/FTB-Continuum/issues/216#issuecomment-397703250>,
or mute the thread

**Comment by Kuktar** [comment]
Also 2.8GB of ram is not enough imo. Start with 4GB.

I believe it says 4 in curse overview as minimum recommended.

**Comment by TheKiwiCub** [comment]
I allocated 4 and then 6GB of ram and neither worked, also updating the pack to 1.3 has not solved the issue

**Comment by aaronhowser1** [comment]
Does it happen on every save/server? Have you tried completely reinstalling the pack? Does it happen with and without a resource pack?

**Comment by zenoran** [comment]
I spent TONS of time troubleshooting this too. There is some sort of memory leak or GC isn't happening. It fills up heap then GC spikes the CPU non-stop trying to clean up but never recovers. The heap graph just goes up and never comes down. I did notice some IF machines seem to make it worse, specifically the igneous extruder. When I had that thing on and pumping cobble into recycler it was 5 mins of playtime before 6gb RAM filled up. Turning that thing off lets me play longer so not sure if OP is using that too?

**Comment by TheKiwiCub** [comment]
This will occur whether I'm on a server, in single player, and it doesn't matter what is in the world like it can be a brand new world or one I've been on for hours. Any idea how to fix the GC?

**Comment by zeryl** [comment]
As noted in the other issue, it's the eden GC hitting it's peak, and clearing.  It starts out just fine, and then after some time, eden gc takes a good chunk of time.

**Comment by enrique556** [comment]
I have same issue, I've increased ram (maximum) to 5.5gb, which allows the java client process to get up to over 9gb ram usage before it starts doing the aggressive and slow gc which makes it unplayable. I can, depending on activity, play for 2 hours straight with this amount of ram allocated however. I'm running Continuum 1.3.1 on linux (mint) box w/ openjdk:
$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

**Comment by tfox83** [comment]
Must run with at least 4GB of ram, I suggest 5-6GB and even more if using a resource pack
