### ISSUE TITLE
Advanced Rocketry: Artifacts

### ISSUE THREAD

**Issue by mtimyself** [FTBTeam/FTB-Continuum#218]
* **Modpack Version**: 1.3.1

* **Issue**: I forgot about the need for artifacts to go to the (ET) planets.
Yet I could set warp target to Litherite and engage. While I am yet to find any Litherite the Quest book marks the goal to visit the planet as done (after taking a rocket down of course).

**Comment by aaronhowser1** [comment]
I don't suppose you could link to a pastebin of your save's advRocketry\planetDefs.xml? That's where all of the AR planet data should be saved. I think this bug was supposed to be fixed in a recent update, maybe it didn't work. Had you gone to this planet before the last couple updates?

**Comment by mtimyself** [comment]
I have just made it to this planet for the first time. Having seen this was an issue here on GitHub and Litherite being the next step for us I left it until 1.3 came out.
I only intended to report the artifacts not being required to warp to the destination but it would seem that I am also experiencing the issue of the ET "minerals"(?) not spawning, even with the DIM being generated in 3.0.1

This is the file you were asking for:
https://pastebin.com/A3GYfAiV

**Comment by aaronhowser1** [comment]
I just made a brand new world to test, and it seems to be working for me 
![image](https://user-images.githubusercontent.com/15698722/41487052-9c6695ce-70ac-11e8-8978-be561753c0cb.png)

This is the Litherite planet on the planetDefs you just linked:

```
        <planet name="Litherite" DIMID="30" customIcon="iceworld">
            <isKnown>false</isKnown>
            <fogColor>1.0,1.0,1.0</fogColor>
            <skyColor>0.533,0.509,1.0</skyColor>
            <gravitationalMultiplier>90</gravitationalMultiplier>
            <orbitalDistance>180</orbitalDistance>
            <orbitalPhi>270</orbitalPhi>
            <rotationalPeriod>54000</rotationalPeriod>
            <atmosphereDensity>50</atmosphereDensity>
            <biomeIds>advancedrocketry:crystalchasms</biomeIds>
            <oceanBlock>techreborn:techreborn_techreborn.potassium</oceanBlock>
            <fillerBlock>minecraft:snow</fillerBlock>
        </planet>
```

It seems to be completely missing the artifacts and ore gen for some reason. This is the one from the brand new world I just made using 1.3.1:

```
		<planet name="Litherite" DIMID="30" customIcon="iceworld">
			<isKnown>false</isKnown>
			<fogColor>1.0,1.0,1.0</fogColor>
			<skyColor>0.533,0.509,1.0</skyColor>
			<gravitationalMultiplier>90</gravitationalMultiplier>
			<orbitalDistance>180</orbitalDistance>
			<orbitalPhi>270</orbitalPhi>
			<rotationalPeriod>54000</rotationalPeriod>
			<atmosphereDensity>50</atmosphereDensity>
			<oreGen>
				<ore block="environmentaltech:litherite" minHeight="4" maxHeight="80" clumpSize="15" chancePerChunk="64" />
			</oreGen>
			<biomeIds>advancedrocketry:crystalchasms</biomeIds>
			<artifact>environmentaltech:structure_panel 0 64</artifact>
			<oceanBlock>techreborn:techreborn_techreborn.potassium</oceanBlock>
			<fillerBlock>minecraft:snow</fillerBlock>
		</planet>
```

It looks like maybe Advanced Rocketry isn't updating the save's planetDefs.xml whenever the config updates for some reason. Are those lines in the config\advRocketry\planetDefs.xml? It should start on line 229.

**Comment by aaronhowser1** [comment]
You might be able to fix it by replacing the planetDefs.xml in your save with the one in the config, if the config is using the updated planets. I'll have to talk with the AR dev about why it isn't updating for a more permanent fix though.

**Comment by mtimyself** [comment]
Seems like it.
This is 228 onwards:
https://pastebin.com/QZu0NJaN

e: Just as a hint for other having the same issue and me being able to fix it for my players real quick can I copy the planetDefs.xml from configs to the world folder and delete the DIM to fix the issue?
e2: I just saw you had me covered before I had to ask. Thx

**Comment by aaronhowser1** [comment]
Could you try downloading and installing the [latest unstable build of AR](https://minecraft.curseforge.com/projects/advanced-rocketry/files/2569792) and loading the world with that? Make a backup of it first. After you load the world, see if the world's planetDefs.xml was changed to match the config's.

**Comment by mtimyself** [comment]
As is advisable I made a backup of the original file before I copied over the new one.
I will clone the files later and throw it up on a different port to see if it behaves the way we would want it with the unstable build.
I can however not ask my players to manually patch stuff and/or take the main instance down on a friday night so it'll take a bit for me to get around to it.

**Comment by aaronhowser1** [comment]
Oh, didn't realize it was on a server. Not sure how to test it in that case. Maybe move the server's save and load it in a single player instance with the unstable build, just to see if it works?

**Comment by mtimyself** [comment]
It is a dedicated box. I will simply copy over the entire folder, revert back the file, patch the mod, change the port, forward it and boot it back up.

**Comment by aaronhowser1** [comment]
In the server's config\advRocketry\advancedRocketry.cfg, change `B:resetPlanetsFromXML=false` to true. This should fix it. I'll see about getting this into the next update, had on idea that that was even a config option.

**Comment by aaronhowser1** [comment]
Looks like that config is broken, never mind then. I guess wait for it to be fixed for now, maybe manually copy over the xml in the mean time.

**Comment by mtimyself** [comment]
Manually copying over the .xml file from the config/advRocketry folder into the world/advRocketry folder did do the trick.
For anyone coming across this while looking for a solution it is also worth noting that the advanced rocketry dimensions are saved in the advRocketry sub-folder rather than the world folder itself.
Delete the dimension there if you wish to regenerate the world rather than just generate new chunks once the config is in.

**Comment by zenoran** [comment]
Just got to this point and had the same problem.  Copying the xml and deleting the world folders to regen worked.

**Comment by tfox83** [comment]
known issue at this time, should be better in 1.4.0
