### ISSUE TITLE
Quest: Eye of the Storm

### ISSUE THREAD

**Issue by mtimyself** [FTBTeam/FTB-Continuum#219]
* **Modpack Version**: 1.3.1

* **Issue**: There are two mismatches between the Planet ID chip's description and the Quest Book's one when it comes to the artifacts required to travel to Eye of the Storm planet.

http://prntscr.com/jvhcun
http://prntscr.com/jvhdg2

**Comment by aaronhowser1** [comment]
Whoops, I'll fix it to use Charcoal. Thanks!
