### ISSUE TITLE
Can't launch game; error

### ISSUE THREAD

**Issue by shikiko** [FTBTeam/FTB-Continuum#22]
* **Modpack Version**: Continuum

* **Issue**: Can't launch game

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/f6c9997b

Tried to repair minecraft file using the twitch app but still have the same error

**Comment by Kuktar** [comment]
the easy fix is to clean wipe and re install. it seems the core install of the minecraft assets is corrupted. your problem is the asset appache its a programing language forge depends on to do some work. 

my advice is to re install and try again.

**Comment by 016Nojr** [comment]
As Kuktar suggested, try re-installing the pack.
