### ISSUE TITLE
Quick Notice

### ISSUE THREAD

**Issue by mtimyself** [FTBTeam/FTB-Continuum#220]
Could not find you on Discord so I guess I'll have to make a new one.

In https://github.com/FTBTeam/FTB-Continuum/issues/219 make sure to change both Coal to Charcoal and Firewood to Lavawood.

Did not know how else to get in touch...

**Comment by aaronhowser1** [comment]
You could've just replied on #219, I think I would've gotten an email about it, but no worries. Didn't notice the Firewood/Lavawood mixup, I'll fix that now too, thanks :D
