### ISSUE TITLE
[suggestion] Configure Adventure Backpack (Forestry)

### ISSUE THREAD

**Issue by spdkils** [FTBTeam/FTB-Continuum#221]
* **Modpack Version**: 1.31

* **Issue**: Add items to adventurers backpack. (Torches, rope ladder, ladder, doors, tiny torches, sleeping bag) So it can be used in game. Or remove it, because once crafted it can't be used without configuration changes.

* **Link to Log or Crash File Paste**: No Crash

* **Is it Repeatable?**: Yup

* **Mod/s Affected**: Forestry

* **Known Fix**: Add some 'adventure' items to the adventure backpack.

**Comment by tfox83** [comment]
added some items to it in 1.4.0
