### ISSUE TITLE
3D texture issue

### ISSUE THREAD

**Issue by Gottabepro** [FTBTeam/FTB-Continuum#223]
* **Modpack Version**: 1.3.1

* **Issue**: I don't exactly know whats happening, so here's a picture. The best I can explain it is that the game is trying to use 3D graphics (like a movie) on a 2D screen.
![2018-06-16_11 57 08](https://user-images.githubusercontent.com/40323455/41501630-10836b34-715d-11e8-8dcd-2c42d770e7f0.png)
* **Is it Repeatable?**: Yes, every world I create does this. I've also tried updating changing the version from 1.2 to 1.3 but it didn't work.

**Comment by aaronhowser1** [comment]
It looks like you've enabled the 3D Anaglyph setting, which is in the Video Settings.
