### ISSUE TITLE
Constant Lag Spikes after about 5 mins of running.

### ISSUE THREAD

**Issue by Species5681** [FTBTeam/FTB-Continuum#224]
Modpack Version, 1.2.1 and 1.3.1

After running world for about 10 minute after restart will run fine then.
Problems with lag spikes every 5 to 10 seconds, normal FPS is around 180 and will spike to around 1fps.
Currently running with 9GB of ram dedicated in an 16 GB system. Am not using any texture packs.
![2018-06-16_14 03 43](https://user-images.githubusercontent.com/13374729/41502102-c4058450-716f-11e8-9617-d08c8156a682.png)

Is it repeatable? Yes happens with both versions and different saves.

It is unknown to me if any specfic mod is causing the problem

Only known fix is to restart the game.

**Comment by Kuktar** [comment]
Post your fml log so we can see what mods you have. 

Also can we merge these 

https://github.com/FTBTeam/FTB-Continuum/issues/216

**Comment by Species5681** [comment]
[latest.log](https://github.com/FTBTeam/FTB-Continuum/files/2108517/latest.log)
as requested my latest log

**Comment by zeryl** [comment]
I ran visualvm against my instance of Minecraft when this was happening on my end.  The eden GC is getting cleared, a lot.  It was fine when you first start Minecraft, and eden gc was quick.  As time goes on, it gets longer and longer to clear.  I noticed logging out and back in (no close of Minecraft) helps a bit, but it comes back quickly.

**Comment by shhIMsneeking** [comment]
I have a similar issue. Unfortunately not as savy with the tech.  There was one day a week or so ago when continuum was down for 30 mins at a time and ever since I have barely been able to play it. I spent at least three hours in the lobby or reloading continuum today and only about an hour or two playing the game. 

I'm not sure what it is but I quit voting because of it.

**Comment by ghost** [comment]
I have this issue, I've had to lower my graphics settings and render distance but I still get small freezes every few seconds

**Comment by ghost** [comment]
@Species5681 try launching Continuum with these parameters: -XX:+UseParNewGC -XX:ParallelGCThreads=x, where 'x' is the amount of cores in your CPU plus one. Mine would be -XX:ParallelGCThreads=5.
Go to your FTB launcher and put these under Options > Advanced Options > Additional Java Parameters

**Comment by tfox83** [comment]
Closing as this is not an issue with the modpack
