### ISSUE TITLE
Can't set fluid of creative Drums

### ISSUE THREAD

**Issue by derNiklaas** [FTBTeam/FTB-Continuum#225]
* **Modpack Version**: 1.0.2

* **Issue**: You can't set the fluid of a creative drum in survival mode

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Extra Utils 2

* **Known Fix**: N/A

**Comment by aaronhowser1** [comment]
Can you try inserting a fluid using pipes to set it?

**Comment by derNiklaas** [comment]
I tried using the following things:
Transfer Node (Liquid)
Fluid translocator
hardened fluiducts
Phantom Liquidface

**Comment by aaronhowser1** [comment]
And I don't see anything in the extrautils2.cfg. That's a problem, huh. Trying to figure out how to spawn Creative Portable Tanks right now to see if those work.

**Comment by aaronhowser1** [comment]
Yeah, that can be set in Survival mode. @tfox83 I think we should replace all instances of the Creative Drum with the Creative Portable Tank. The Creative Conversion Kit is hidden but you can spawn it with `/give [name] thermalfoundation:upgrade 1 256`

**Comment by zeryl** [comment]
Ran into this as well.  Need to be in creative to use the creative drum, from what I can see.

**Comment by tfox83** [comment]
I will have to think of something, the creative conversion kit inst an option as it can be applied to storage and get inf items for free.  I look into this before next update.  Maybe I can grab the NBT data of a tank with the creative upgrade installed and replace the drum with that.

**Comment by aaronhowser1** [comment]
Can't you make it so that the recipe instead crafts a Creative Portable Tank instead of the Creative Conversion Kit? I couldn't figure out how to spawn the Tank so I had to use the Kit to get it. I don't know how the NBT and all that works though.

**Comment by tfox83** [comment]
Ok so the creative tank doesnt exist in JEI so making a recipe for it is hard for the players to find so what I did was make the TE creative tank craftable from a creative drum and vice versa.
![image](https://user-images.githubusercontent.com/4246308/42466190-0ddcd060-8363-11e8-99d7-bf827ba45027.png)
![image](https://user-images.githubusercontent.com/4246308/42466210-189d23ec-8363-11e8-979b-0fc345dd73a7.png)

**Comment by aaronhowser1** [comment]
@tfox83 If you have a working recipe for Creative Drum -> Creative Portable Tank, couldn't you just replace the input to the Drum recipe?

**Comment by aaronhowser1** [comment]
```
recipes.addShaped(<thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 1 as byte, Level: 4 as byte}), [[<thermalcultivation:watering_can:32000>, <projecte:condenser_mk2>, <thermalcultivation:watering_can:32000>], [<projecte:condenser_mk2>, <extrautils2:creativeenergy>, <projecte:condenser_mk2>], [<thermalcultivation:watering_can:32000>, <projecte:condenser_mk2>, <thermalcultivation:watering_can:32000>]]);
```
![image](https://user-images.githubusercontent.com/15698722/42549077-f31c4e58-848f-11e8-9f52-a6fe1b88784a.png)
I got that working, but it isn't in JEI.... which is what you meant. Welp, that was a waste of 10 minutes.

**Comment by aaronhowser1** [comment]
I enabled this config option in \cofh\thermalexpansion\client.cfg and they show up in JEI now

```
        # If TRUE, Creative version of Blocks will show in the Creative Tab. [default: false]
        B:ShowCreativeBlocks=true
```
![image](https://user-images.githubusercontent.com/15698722/42549330-32cf9fd6-8491-11e8-9f55-88cdb5be98b2.png)
