### ISSUE TITLE
Server Crash due to Codechicken.lib Particles and Mob Spawns

### ISSUE THREAD

**Issue by mtimyself** [FTBTeam/FTB-Continuum#227]
* **Modpack Version**: 1.3.1

* **Issue**: Auto spawning massive amounts of Magma Cubes for Galgadorian Metal and ProjectE progression is essential.
There is a server crash that happens quite regularly (world loads fine afterwards).

https://pastebin.com/SvS1dVYp

E: Blazes are also affected: https://pastebin.com/JE8SWCn1
E2: I am beginning to think that it has something to do with proximity of multiple mobs more so than specific mobs themselves.

**Comment by covers1624** [comment]
The actual issue here was a bug in EnderStorage that i have since fixed in version 2.4.4.+ (pending on curse.)

**Comment by tfox83** [comment]
Fixed in 1.4.0
