### ISSUE TITLE
Game client is crashing while using the engineers workshop together with storage scanner

### ISSUE THREAD

**Issue by BadBoyfromHell** [FTBTeam/FTB-Continuum#228]
* **Modpack Version**: 1.31

* **Issue**: I am playing FTB Continuum. After building the storage scanner the client crashes after trying to manage my storage with the storage scanner. Unfortunately I am not able to start my game again, because it is now crashing on every start. After contacting McJty it seems to be a problem with the Engineers Workshop. So I also post the crash report to the Engineers Workshop Reloaded board and here hoping for a solution.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/edc68f69

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Interplay between RFTools and Engineers Workshop Reloaded

* **Known Fix**:

**Comment by Boomflex** [comment]
I would recommend quite heavily that you update your current java version.

I can see that you are running on Java Version: 1.8.0_25, the latest version is Java Version: 1.8.0_171, so you are quite a few versions behind.

I recommend you follow this guide: https://gist.github.com/darkhax/2d82494a88327327cec6d5172b1db239

I would 99% say that this will sort the issue for you.

**Comment by Kuktar** [comment]
Regardless of how they fix it. You have what is called a erroring title
entity. You have a couple solutions to get your world working again.


In the config file for forge mod loader there is an option for it to
automatically removing erroring entity's on world start. That will simply
remove either the errored scanner or storage or workshop.

The other option is to use NBTexplorer and load your minecraft world save
into it and track the entity down and fix or remove the entity yourself.

Probably the best option is to revert to a backup. By default ftb utilities
mod backs your world up like every hour depending on if you changed the
default config. These backups are timestamped. You simply unzip the world
backup before you had the crash and use those files to restore your world
from earlier.

Let me know if you have any questions.

**Comment by BadBoyfromHell** [comment]
Thanks you two for your effort. I will try my old backup to see if your solutions solves the problem. 
Meanwhile I have deleted the storage scanner by using Mcedit which prevents my client to crash.

**Comment by Kuktar** [comment]
Good work! Have fun:p
