### ISSUE TITLE
"The game crashed whilst tesselating block model"

### ISSUE THREAD

**Issue by Chaftalie** [FTBTeam/FTB-Continuum#229]
* **Modpack Version**: 1.3.1
* **Issue**: Game crashes when joining one specific map with the short Code "The game crashed whilst   tesselating block model"
**EDIT:** It looks like it is not just an joining Problem, if I am flying to the base the game crashes too. 

* **Link to Log or Crash File Paste**: 
Log:https://paste.feed-the-beast.com/view/e59bc242
Crash Report:https://paste.feed-the-beast.com/view/88383050
* **Is it Repeatable?**: ~~Yes, whenever sombody joins my map (including me) the Client crashes~~ 
No, I tried it an different maps also in the fixed affected world the problem did not occur again. 
* **Mod/s Affected**: ~~My gues would be EFAB because the game loads chunks and if it gets to the chunk with the EFAB Stuff it crashes. but thats only a gues from seeing the first few secounds of chunkloading before crashing! (also there is a lot of other stuff, ist the middle of the base)~~ Translocators (liquid) translocators
* **Known Fix**: ~~Turn down ALL graphic Settings and pray for the best ( I do not know if this is a fix because I needed 2 or 3 attempts with it. What seems to realy help: teleporting the Player who joins somewhere else before his chunks begin loading.
**EDIT:** The best working fix is to get out of the base before closing the game so you do not spawn near the base on joining.
**EDIT:** These fixes worked yesterday, now I cannot get the world working. 
A misserable fix is o downgrade to 1.1.0 (I did not test any other Version)but than some things like servos would need to be replaced and the performance takes a noticeable hit.)
**EDIT:** Replaceing nearly all EFAB Blocks Liquid translocators and some irondrums ontop of the EFAB Stuff fixed my world.~~
**EDIT:** I found the real cause of the problem. In my case a liquid translocator (non upgraded) sucking out molten lumium from an empty reinforced tank from thermal expansion into an EFAB tank (normal or advanced i do not know) was the problem. removing it with MCedit fixed it.

**Comment by ghost** [comment]
Are you using a resource pack? I'm pretty sure I got this error when I was using one

**Comment by Chaftalie** [comment]
Sadly i am.not using a resourca pack.

**Comment by Chaftalie** [comment]
No, I am not using a resourcepack.
*Updated the main post.

**Comment by Chaftalie** [comment]
*Updated Main Post with following Infos and fix:

I replaced most of my EFAB stuff (and iron Drums with sludge and Lumium and empty ones &&  also some liquid translocator without any upgrades got replaced)with stone in MCedit 2 which fixed the problem.

**Comment by Chaftalie** [comment]
The liquid traslocater definitely causes this crash. I yoused the magain and the game crashed until I removed the liquid translocater again.

**Comment by tfox83** [comment]
fixed in 1.4.0
