### ISSUE TITLE
gravestone.cfg?

### ISSUE THREAD

**Issue by Kuktar** [FTBTeam/FTB-Continuum#23]
* **Modpack Version**: 
1.0.1

* **Issue**: 
There is an Gravestone.cfg file in the server configs folder.

* **Link to Log or Crash File Paste**: 
N/A

* **Is it Repeatable?**: 
yes i looked in the ZIP file just to make sure it wasnt me accidently doing some weird thing and its in the zip for both 1.0.0 and 1.0.1

* **Mod/s Affected**: 
NONE

* **Known Fix**: 
Probably remove the config file because it is not needed, from what i can tell openblocks is the actualy gravestone mod. I am nott 100% if the config file is from maybe having gravestone installed earlier pack version. i dont see it being used at all. thanks.

**Comment by Kuktar** [comment]
also found malisescore and maliesesdoors or however its spelled. the mod does not seem to be installed in the pack so these are also not needed.

**Comment by tfox83** [comment]
We use a lot of common configs between FTB modpacks, these small text files have no impact on performance if the mod isn't present.
