### ISSUE TITLE
Fusion Reactor makes infinite Heliumplasma

### ISSUE THREAD

**Issue by Chaftalie** [FTBTeam/FTB-Continuum#230]
* **Modpack Version**: 1.3.1
* **Issue**: If you put Helium-3 and Deuterium Cells into the Fusion Control Computer it makes Helium Plasma, but does not use up the Helium-3 and Deuterium.
* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: On this world, yes. I have to try it in an other world.
* **Mod/s Affected**: Tech Reborn
* **Known Fix**: N/A

**Comment by electromatter** [comment]
Upstream issue:
https://github.com/TechReborn/TechReborn/issues/1551

**Comment by electromatter** [comment]
Fixed upstream by https://github.com/TechReborn/TechReborn/pull/1556

**Comment by tfox83** [comment]
Fixed in 1.4.0
