### ISSUE TITLE
Industrial Electrolyzer and Extractor getting stuck at 100 and 0%

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Continuum#231]
* **Modpack Version**:  1.3.1

* **Issue**:  Industrial Electrolyzer and Extractor getting stuck at both 0% and 100% when doing bauxite recipe and extracting compressed air cans respectively. Also tried extracting poppies which got stuck at 0%. Saving and reloading world temporarily solves problem, both machines get stuck once again after a couple processes. 

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/a4c6a53b

* **Is it Repeatable?**: Yes, see above.

* **Mod/s Affected**: tech reborn v 2.15.15.712

* **Known Fix**: Reloading world **temporarily** fixes

**Comment by aaronhowser1** [comment]
Does TheOneProbe show anything weird about them? Does breaking and replacing the machine fix it?

**Comment by ghost** [comment]
Did some more testing and found that breaking also works to resume the process. Did some more testing and was able to recreate in creative testing. 99% sure it's caused by auto exporting to a cache from thermal expansion as the machines were both running fine until I set them to do so.

**Comment by ghost** [comment]
Item barrels from YABBA and drawers work fine however for a quick fix.

**Comment by modmuss50** [comment]
Can confirm, I’ll investiage it a bit more later.

**Comment by modmuss50** [comment]
Fixed in next version

**Comment by tfox83** [comment]
Fixed in 1.4.0
