### ISSUE TITLE
Industrial Electrolyzer

### ISSUE THREAD

**Issue by Frazzer951** [FTBTeam/FTB-Continuum#232]
* **Modpack Version**: 1.2.1

* **Issue**: When using the auto input feature on the Industrial Electrolyzer, once it starts pulling one empty cell from the chest, it pulls all of them and leaves what looks like only one stack in the electrolyzer, but the tool tip from "The One Probe" shows multiple stacks https://imgur.com/a/8CJ38mG In the picture you can see there is one stack of each in the machine, but in the tool tip is shows more

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes, it happens on my server and a test world

* **Mod/s Affected**: Tech Reborn

* **Known Fix**: N/A

**Comment by aaronhowser1** [comment]
This is a known issue. Try using 1.3.1, I think the issue was fixed by then.
