### ISSUE TITLE
Shipping Bin needs nerfed somehow

### ISSUE THREAD

**Issue by Kuktar** [FTBTeam/FTB-Continuum#235]
* **Modpack Version**: 1.3.2

* **Issue**: the pams harvestcraft bin is uber strong. Basically with some of the much easier to gather farms/drops you can get loads and loads of emeralds! End game this isnt that big of a deal but in the questline it takes a measly 4 diamonds to make the shipping bin. that is an EPIC tradeoff.

i am including screenshots of the 4 most op trades. 

![2018-06-17_20 05 57](https://user-images.githubusercontent.com/24352734/41516647-cf9b86e2-726a-11e8-87f4-8fb6f84452b4.png)
![2018-06-17_20 05 47](https://user-images.githubusercontent.com/24352734/41516648-cfad5bec-726a-11e8-9d79-60462423c536.png)
![2018-06-17_20 05 41](https://user-images.githubusercontent.com/24352734/41516649-cfbd994e-726a-11e8-965d-988651ff7974.png)
![2018-06-17_20 05 35](https://user-images.githubusercontent.com/24352734/41516650-cfce7dd6-726a-11e8-817d-4a28abf43b36.png)

**Comment by aaronhowser1** [comment]
I think this is pretty much as nerfed as it can possibly be, Harvestcraft isn't really the most well-coded mod in existence. Also, in my several hundred hours of playing Continuum, I have legitimately never seen a naturally spawning Emerald Ore, so this is pretty much the only way I could get Emeralds before the T6 Void Ore Miner.

**Comment by robertjbeaver** [comment]
I'd argue that the pack is balanced around the shipping bin. Recipes can requires a couple hundred emeralds once you get to the digital upgrade.

**Comment by Kuktar** [comment]
So doing quick math I could trade a stack of 64 apples worth just about 1k
emc value and get back an emerald work 12k emc value.

Best part is you can do this very early game. Steve's tree farm equals
plenty of apples. By the time I get to the digital age I will be swimming
in emeralds.

**Comment by robertjbeaver** [comment]
Correct, and you will need those emeralds. That's the balancing. The nerf would be requiring even more emeralds later in the game, or by removing it completely and opening themselves up to rebalancing the pack around its absence. And with a project-e overhaul incoming, I'm interested to see what they do with them. Likely just an adjustment to the emeralds value.

**Comment by Kuktar** [comment]
I see you on that. If emeralds become needed in vast amounts then it's
fine. Just this morning I set up the farmer on my carrot crops.


Just wow. Emeralds from tree farm apples and carrots galor.

Now I have to find a way to automate the shipping bin. If mouse tweaks
actual worked on it and shift clicking a stack of apples went into the bin
It would be bearable. But here i am i can't even keep up with the crops lol

**Comment by aaronhowser1** [comment]
I don't think you can automate it short of using AutoHotKey or something, again Pams is weird like that

**Comment by alexsch01** [comment]
best thing to do is put item translocators on chest and shipping bin and add glowstone on chest side to just auto click emeralds

**Comment by Kuktar** [comment]
Does glowstone modifier ensure only full stacks get moved?

I thought you had to use the arrows to find the correct item to sell. Can
you or someone else explain how this would work a little. Thanks.
