### ISSUE TITLE
No way to create Titanium

### ISSUE THREAD

**Issue by stupidanon** [FTBTeam/FTB-Continuum#236]
* **Modpack Version**: 
FTB Continuum Version 1.2.1

* **Issue**: 
There is no way to make Titanium as there is no Rutile Ore in the game. 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
Obviously.

* **Mod/s Affected**: 
Vulpes Library.

* **Known Fix**: 
Enable Rutile Ore to spawn in the overworld.

**Comment by gripbozo** [comment]
Im also having this issue, i dont know where to find Rutile Ore and i dont think its even in the game

**Comment by aaronhowser1** [comment]
You can get Small Piles of Titanium by putting (I think, can't launch it right now so can't check) Bauxite Dust in the Industrial Electrolyzer.

**Comment by tfox83** [comment]
Bauxite dust provides it.
