### ISSUE TITLE
Refined Storage's Interface can still be crafted using the RS Solderer

### ISSUE THREAD

**Issue by KuroPeach** [FTBTeam/FTB-Continuum#237]
RS interface can craft , RS interface with RFTOOL's storage scanner have bug [rftool](https://github.com/McJtyMods/RFTools/issues/1708) [RS](https://github.com/raoulvdberge/refinedstorage/issues/1744) They didn't solve the bug . 
so at my server change refinedstorage.cfg , 
line 73     # The energy used by Interfaces [range: 0 ~ 2147483647, default: 3]
                I:interface=100000000 .

at jei interface is hide but we can find it at solderer . Forgive me for my poor English.

**Comment by tfox83** [comment]
fixed in 1.4.0
