### ISSUE TITLE
Hydrator's range is too small

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Continuum#238]
Although this machine's range is supposed to be 5x5, it only has 0 range. Even if I insert tier 10 range addon, it won't go wider than 5x5.
Sorry if it's intended

**Comment by aaronhowser1** [comment]
As of a recent update of IF, all machines start with a range of 1 block. I don't know why you can't go above 5x5 though.

**Comment by GWSheridan** [comment]
Hydrator only accepts tier 1 range addon
