### ISSUE TITLE
FTB Continuum 1.0.2 Unable to craft

### ISSUE THREAD

**Issue by kerfufflator** [FTBTeam/FTB-Continuum#24]
* **Modpack Version**: FTB Continuum versions 1.0.1 and 1.0.2, multiplayer server

* **Issue**: Unable to craft in inventory 2x2 or 3x3 vanilla crafting table grid

* **Link to Log or Crash File Paste**: No crash or console error.

* **Is it Repeatable?**: Only happens on multiplayer server.

* **Mod/s Affected**: I'm not sure. Happens with vanilla and modded recipes. The only recipes I know works are sticks, the EFab itself and crafting vanilla wood into two vanilla planks.

**Comment by 016Nojr** [comment]
Can you try restarting the server? We havent had this issue while beta testing.

**Comment by kerfufflator** [comment]
I've restarted the server, restarted the machine, deleted the server files, redownloaded the server files, reinstalled java and have had no change in behavior.

**Comment by VexaBoops** [comment]
this pack changes nearly every recipe make a fabricator and follow your quest book

**Comment by kerfufflator** [comment]
I understand that. I assume you are referring to the EFab? With the issue I'm having, it's impossible to make one unless I happen to find a village with a crafting table generated in since it's impossible to craft one. Even if I get a naturally occurring crafting table, I'm still stuck at the step where I need to craft an Armory Upgrade since vanilla tools are unable to be crafted in either a crafting table or the EFab, which leaves the AIOT out of the question.

**Comment by gotnate** [comment]
I ran into a similar issue where my 1.0.1. Server was using vanilla recipes - (I couldn't craft an efab, and I could craft vanilla tools using the standard recipes. My server mates even made crafting stations not realizing that they're black listed). I fixed it by re-installing the pack on the server. And then 1.0.2 shipped.

**Comment by kerfufflator** [comment]
Something I mistakenly forgot to disclose - I've been running the server using CubeCoders application management panel, AMP. I've since discovered that the issue I'm having only seems to be present when using their software and not when I run the server from the ServerStart.bat included with the server's files. From here on out I'll update in case anyone else finds themselves in a similar situation, but I'm considering this issue closed since it's not the FTB team's bug. Thanks.
