### ISSUE TITLE
Pulverized silver from small pile of silver dust recipe missing

### ISSUE THREAD

**Issue by yanny7** [FTBTeam/FTB-Continuum#240]
* **Modpack Version**: 1.3.1

* **Issue**: Unable to create pulverized silver from small pile of silver dust - missing recipe. Oposite direction is working -> creating small pile of silver dust from pulverized silver

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by tfox83** [comment]
fixed in 1.4.0
