### ISSUE TITLE
Unbreakable tools breaking

### ISSUE THREAD

**Issue by OrbitStudios** [FTBTeam/FTB-Continuum#241]
* **Modpack Version**: 1.3.1
* **Issue**: Unbreakable tools are breaking after use, after some mining with the hammer, it broke. I applied the 5 reinforced plates to make it unbreakable.

![broken](https://user-images.githubusercontent.com/7864809/41603316-561be562-73a2-11e8-8526-18e8f3643d5d.png)

**Comment by robertjbeaver** [comment]
Magically brittle bypasses the unbreakable modifier. They will still break from time to time.

**Comment by Kuktar** [comment]
It even says in the magically brittle tooltip that can't be unbreakable
lol.

In my modpack I have botania all balanced out and I just use livingwood
instead of magical wood. It's the same thing but living wood gives an extra
trait and the boost from wood ecological.
