### ISSUE TITLE
BiblioCraft Dupe/Bug

### ISSUE THREAD

**Issue by kristi71111** [FTBTeam/FTB-Continuum#243]
* **Modpack Version**: 1.3.1 and below

* **Issue**: Duplication bug with BiblioCraft and backpacks.
Confirmed that this works with other items besides backpacks as well.

Explanation in video form:

  [Youtube video explaining it](https://youtu.be/idaG7AO7byY)

* **Link to Log or Crash File Paste**: None needed 

* **Is it Repeatable?**: Yes SP and MP

* **Mod/s Affected**: BiblioCraft

* **Known Fix**: Edit the mod and compile your own fix.

**Comment by aaronhowser1** [comment]
Does this work in version 1.3.1? If so, I recommend also submitting this to the [Bibliocraft Issue Tracker](https://github.com/Nuchaz/BiblioCraft/issues)

**Comment by kristi71111** [comment]
@aaronhowser1 I'll refrain from doing that due to past experiences with dealing with mod developers however the dupe still works on version 1.3.1 of the modpack.
