### ISSUE TITLE
Cruse shows every version as beta

### ISSUE THREAD

**Issue by Morganamilo** [FTBTeam/FTB-Continuum#244]
* **Modpack Version**: All

* **Issue**: Cruse now shows every version of the pack as beta. https://www.feed-the-beast.com/projects/ftb-continuum/files. I've noticed what you normally do when you have a new release version and to move to old release back to beta. That's kind of strange, release versions shouldn't go back to beta but anyway that's besides the point.
1.2.1 was the latest release. I'm assuming what you meant to do what make 1.3.1 the release version and move 1.2.1 back to beta. It appears as though something went wrong.

**Comment by aaronhowser1** [comment]
This is being fixed right now. The reason old versions are put back to beta is that the FTB legacy launcher needs to have only one version set to recommended for it to work.

**Comment by Morganamilo** [comment]
That makes sense, plus I prefer the legacy launcher so nice it's still supported.

Seems like it just got fixed so I'll close... and you just closed it. Oh well thanks anyway.
