### ISSUE TITLE
Platinum Grains cant be made into platinum dust.

### ISSUE THREAD

**Issue by Valerate** [FTBTeam/FTB-Continuum#245]
* **Modpack Version**: 1.3.1

* **Issue**: Platinum grains has no recipe

* **Is it Repeatable?**: Yes

* **Known Fix**: Fix the recipe, I have no idea what you guys did to remove it

Suspects its the same issue as  https://github.com/FTBTeam/FTB-Continuum/issues/240

**Comment by Tandorius** [comment]
It's not Platinum Dust, it is Pulverized Platinum ... I can craft it. https://imgur.com/a/ND6jOOg

**Comment by robertjbeaver** [comment]
Most recent update (1.3.1) seems to have broken this recipe

**Comment by alexsch01** [comment]
You should make the bee that is bred from the platinum bee that makes platinum dust from another mod, pretty awesome and OP

**Comment by tfox83** [comment]
fixed all grains in 1.4.0
