### ISSUE TITLE
There are two different Cotton -> String recipes

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Continuum#248]
![](https://i.redd.it/pcufufkfm2511.png)

The shaped one should be removed I think

**Comment by Kuktar** [comment]
This is expert mode keep the shaped. 2 string is to much!

**Comment by aaronhowser1** [comment]
I don't know why anyone would really even bother growing Cotton when we have Flax, which drops like 5 string each haha

**Comment by tfox83** [comment]
fixed in 1.4.0
