### ISSUE TITLE
Connection to sever timed out.

### ISSUE THREAD

**Issue by PasarMalam** [FTBTeam/FTB-Continuum#249]
Modpack Version: 1.3.1

Issue: Cant connect to sever, GREENHOUSE TAKING xxxx ms LONGER THAN NORMAL

Link to Log or Crash File Paste: https://paste.feed-the-beast.com/view/1ddd5ed8 

Is it Repeatable: Yes

Mod/s Affected: Have no idea

**Comment by Boomflex** [comment]
I would try running the server with more than 2GB RAM.

Can you try 3GB and let me know how you get on?
