### ISSUE TITLE
Animation folder is wasted space in server files

### ISSUE THREAD

**Issue by gotnate** [FTBTeam/FTB-Continuum#25]
Both the curse version of the pack and the server version of the pack come with an Animation folder showing a nifty FTB splash screen. Thing is, the server has no graphical capabilities to show this animation, so it's wasted space to distribute these files in the server package.

**Comment by tfox83** [comment]
Its only 1MB but sure Ill have the guys that manage the server install scripts blacklist that folder when they can.

**Comment by Watchful1** [comment]
This should be done with the next update.

**Comment by Kuktar** [comment]
Personally this included I have found over 20 files or folders not even used. According to FTB team they sometimes use files from other packs to make configuring new packs simpler and a faster. FTB doesn't seem interested in removing these to save space (I don't blame them as they don't really take up more than a couple MBs)
