### ISSUE TITLE
Infinite Engineer's Hammers

### ISSUE THREAD

**Issue by stupidanon** [FTBTeam/FTB-Continuum#250]
* **Modpack Version**: 
1.3.1

* **Issue**: 
Get two slightly or medium damaged Engineer's Hammers and craft them in the 2x2 crafting slot on your player in this [formation](https://i.imgur.com/yGoBtmr.png)

There you go infinite engineers hammers if you hold shift and click.
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 
Yes i have ten chests of hammers now

* **Mod/s Affected**: 
Immersive Engineering

* **Known Fix**:

**Comment by Kuktar** [comment]
You should put this issue on IE issue tracker. Doesn't seem like ftb team
can do much. I would just disable the recipe. Make you craft a new hammer
each time

**Comment by malte0811** [comment]
This is known and fixed for the next release of IE.
