### ISSUE TITLE
Assassin Bee Tries to Kill All Tile Entities, Crashing Server

### ISSUE THREAD

**Issue by hk21702** [FTBTeam/FTB-Continuum#251]
* **Modpack Version**: 1.3.1

* **Issue**: Assassin bee tries to kill all tile entities including non queens around it, and causes a server crash. As soon as it detects a tile entity it crashes the server. 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/ef351e01

* **Is it Repeatable?**: Yes, tested in an industrial apiary. Have not tested in other types of apiaries.

* **Mod/s Affected**: Career Bees, Maybe gendustry but most likely just career bees.

**Comment by alexsch01** [comment]
You are prob. going to go through many crashes until a point in time where the server doesn't crash anymore but you will loose the assassin queen, FYI for the future just put the Assassin Queen in a bee-bee gun

**Comment by alexsch01** [comment]
Also happened in every version

**Comment by tfox83** [comment]
Known bug with career bees, awaiting a fix from the moddev, will get in next update
