### ISSUE TITLE
Shaders Conflict

### ISSUE THREAD

**Issue by ryder2341** [FTBTeam/FTB-Continuum#252]
* **Modpack Version**: 
1.3.1 with Optifine added
* **Issue**: 
I added Optifine to the game to increase performance, and everything went smoothly until i tried to use a shaders mod, which caused the sky to become messed up in a load of different ways. Which mod would I need to delete in order to fix the stability of the game, as I am unsure of what would conflict with the shaderpack in this way.

* **Link to Log or Crash File Paste**:

* **Is it Repeatable?**: 
Yes, any shaderpack i try has different effects
* **Mod/s Affected**:
Optifine
* **Known Fix**: 
Delete a conflicting mod

**Comment by aaronhowser1** [comment]
This gets fixed by disabling Advanced Rocketry's skyboxes in the config, but generally we don't support OptiFine because it breaks a lot of stuff like this.
