### ISSUE TITLE
I can't see quest info!

### ISSUE THREAD

**Issue by ibrayim54** [FTBTeam/FTB-Continuum#253]
*Modpack Version*: 1.3.1 and all other version.

*Issue*: I can't see the quest number and quest info. I try all the key but nothing work.

*Link to Log or Crash File Paste*: Didn't crash just a basic issues (I guess).

*Is it Repeatable?*: Try older versions, start new game (repeatedly), and manual delete and install for BetterQuest mod but any of them is not work.

*Mod/s Affected*: BetterQuest I guess.

*Known Fix*: I don't know any fix about this.

**Comment by aaronhowser1** [comment]
Try the command `/bq_admin default load`

**Comment by ibrayim54** [comment]
Unfortunately it isn't work :( Can I ask your Java versions please? Because I guess issue is about my java versions :(

**Comment by aaronhowser1** [comment]
Version 8 Update 171 is the latest version and it works. Try reinstalling Continuum 1.3.1 onto a new instance and make a new save. On the old instance, is BQ even installed? Check the mods folder for that, and check the config folder for the betterquesting folder, and if it has a DefaultQuests.json that's around 614KB.

**Comment by ibrayim54** [comment]
I reinstall everything. I'm using the Twitch Launcher for modpack. I delete profile and reinstall it from zero. BQ installed it mods folder and 614kb DefaultQuests.json file in config/betterquesting folder too. And I'm make a new random world in survival mod (by default settings). But even so still I can't see quest info and title number :(

**Comment by aaronhowser1** [comment]
Wait, you mean like the quest ID at the end of titles? I thought you meant you couldn't see any of the quests at all. Can you show a screenshot?

**Comment by ibrayim54** [comment]
![minecraft 1 12 2 21 06 2018 07_02_12](https://user-images.githubusercontent.com/40445369/41697386-319d0a9c-7521-11e8-9964-6da63fa92cb6.png)
![nether ve empowerer _ ftb continuum _ bolum 5 - youtube - google chrome 21 06 2018 07_01_04](https://user-images.githubusercontent.com/40445369/41697387-31bf7078-7521-11e8-82f2-8798f205564c.png)
upper was mine screenshot

**Comment by ibrayim54** [comment]
In other modpacks I can see the quest's detailed info by press shift but in this modpack I can't

**Comment by aaronhowser1** [comment]
![image](https://user-images.githubusercontent.com/15698722/41697697-86d8a38c-74df-11e8-9f0f-191672836f5b.png)

I don't know why you don't have that, I have it on this world I just made. Have you changed any settings or added/removed any mods? Have you tried opening the quest GUI from the book and the keybind?

**Comment by ibrayim54** [comment]
I don't change anything as ı know. And also I looked in game settings and mod settings but only one keybind in there (Quest book opening button). I'm sad af right now :( . I try delete all Minecraft, Java, Twitch and Curse files now and load back. Maybe it works. Thanks for help :)

**Comment by Kuktar** [comment]
I know your issue. Try getting rid of the mod named custommainmenu

For me custom main menu broke better questing and the developer is working
on a fix.

**Comment by aaronhowser1** [comment]
Is there any specific reason you want all this debug information? Can you not see like what quests are required to unlock that one?

**Comment by Kuktar** [comment]
Some people like that info. It killed me not to have it. Again I put my money on custom main menu

**Comment by ibrayim54** [comment]
For me quest title number important more than quest info. I like doing in order. 
Try this and still can't see any differance :(

**Comment by ibrayim54** [comment]
What java versions you use friend? 64 or 32 bit ?

**Comment by KingDan27** [comment]
I dont know if this has been said yet but turning on advanced tool tips with F3+h allowed me to see the quest ids in the title

**Comment by ibrayim54** [comment]
oh my god thank you sso much mate it is solve the problem thank you so much :)

**Comment by aaronhowser1** [comment]
Oh wow, I legitimately never would have never guessed that is what the problem was. Thanks!

**Comment by rkarlzzon** [comment]
Hi i dont know if this is relevant but i can´t see any quest in my questbook? anyoneelse? sorry for bad writning?

**Comment by aaronhowser1** [comment]
@rkarlzzon This is the wrong thread, but use the command `/bq_admin default load`. That should fix it.

**Comment by LORDDOOKY** [comment]
hey i was wondering if anyone knows why my ftb quest wont show up i try /bq_admin default load but my game just tells me to do /help i am on 1.12.2 for mc eternal mod pack and when i click the quest book it is just a blank screen

**Comment by aaronhowser1** [comment]
@LORDDOOKY why would a command for Better Questing work for FTB Quests.

Wait what the hell why are you asking for help with MC Eternal on the Continuum issue tracker???

**Comment by aaronhowser1** [comment]
This issue is from 2018 how did you even find this
