### ISSUE TITLE
industrial grinder - platinum ore / uranium ore

### ISSUE THREAD

**Issue by statphantom** [FTBTeam/FTB-Continuum#254]
* **Modpack Version**: 1.2.1

* **Issue**: platinum ore to 2 platinum dust and uranium ore to 2 uranium dust missing from industrial grinder, however it is present on the regular grinder which is why I think it is missing

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Tech Reborn

* **Known Fix**: I assume its just adding this recipe to the industrial grinder.

**Comment by aaronhowser1** [comment]
Does this still happen in 1.3.1?

**Comment by statphantom** [comment]
Sorry my twitch never told me there was a new version, updates and yes issue is still there in 1.3.1

**Comment by xdorito** [comment]
A small consideration: The grinder outputs an ingot directly. Some automation chains may only be equipped to handle dusts as output from the industrial grinder Would we be able to get a uranium dust added as an output for both the grinder and industrial grinder? It fits with the other ore processing in the game.

**Comment by tfox83** [comment]
fixed in 1.4.0
