### ISSUE TITLE
caught exception from minecraft forge

### ISSUE THREAD

**Issue by blacktailnomore** [FTBTeam/FTB-Continuum#256]
* **Modpack Version**:1.3.1

* **Issue**: unable to connect to the server，no crash at server or client side，just got an error:
```
Internal Exception: com.google.common.util.concurrent.UncheckedExecutionException:
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge(forge)
```
* **Link to Log or Crash File Paste**: 
server-side:https://drive.google.com/open?id=1KvvlbhfDYmTn4Sz1qRNZnG-sUsTNuw0s
client-side:https://drive.google.com/open?id=15jvfWPqFkTR4RhmBZCS3GjKQ-eaVL80Y

* **Is it Repeatable?**: true

* **Mod/s Affected**: Don't know what triggers this

* **Known Fix**: I have no ideal

**Comment by aaronhowser1** [comment]
In the server-latest.log, there's a bunch of lines by OptiFine. Why is that installed on a server?

There's a line on there that says `[16:03:39] [Session-Validator/INFO]: Session validation failed: Invalid token`, maybe you just need quit the game and log back in from the start to reset your client's token.

**Comment by aaronhowser1** [comment]
Just read the client-latest.log, that looks like a server's log. Are you sure those are the right files? It looks like they might've been swapped on accident.

**Comment by blacktailnomore** [comment]
Sorry,i reversed the links,please read the correct file.
The server-files is downloaded from the ftb website,I didn't change any files of them.
@aaronhowser1  thanks for your help

**Comment by aaronhowser1** [comment]
Did relogging fix it?

**Comment by blacktailnomore** [comment]
No,it doesn't work...

**Comment by aaronhowser1** [comment]
There's a line in the server log, `[16:05:01] [Netty Server IO #2/INFO] [FML]: Attempting connection with missing mods [bedpatch] at CLIENT`. Looks like you're missing a mod on your client, or the server still has a mod that was removed. Try reinstalling the modpack on the server and client just to make sure, 1.3.1 on both.

The client log also has this line twice: `[16:06:17] [Netty Client IO #4/INFO]: Attempting connection with missing mods [controlling, ctgui, ctm, custommainmenu, defaultoptions, jehc, jeiintegration, moreoverlays, mousetweaks, resourceloader, tipthescales, reauth] at SERVER`. That's a lot of missing mods, definitely reinstall the server and client.

**Comment by blacktailnomore** [comment]
The client has this file,but server still reports that.
I download the client-files by MultiMC,is that would be a problem?
The file-name is FTBContinuum-1.3.1-1.12.2.zip

**Comment by aaronhowser1** [comment]
I've never used the MultiMC Curse import feature, so I wouldn't know. I still think reinstalling the server and client could be worth a shot, I don't know why it's saying those mods are missing if they're actually present. Sorry I couldn't help more.

**Comment by blacktailnomore** [comment]
Ok,i'll try it.

**Comment by cnideria70** [comment]
I have the same problem with Bedpatche

**Comment by blacktailnomore** [comment]
@cnideria70 can you connect to the server without problems?

**Comment by cnideria70** [comment]
No I could not connect to my server @blacktailnomore

**Comment by ghost** [comment]
@aaronhowser1 @cnideria70 The [bedpatch] mod was introduced in Continuum 1.3.1, I think, as a serverside patch, it's in the server distribution files for 1.3.1 but not the client ones.
You can connect just fine with it installed.

**Comment by blacktailnomore** [comment]
So you got a same issuse as me? @cnideria70

**Comment by cnideria70** [comment]
I'm beginning to start all over again.

**Comment by blacktailnomore** [comment]
Good luck!

**Comment by cnideria70** [comment]
Thanks but it's all just unbearable to restart 3 foit in a beautiful day because of Bedpatch

**Comment by blacktailnomore** [comment]
@major-profundis How could I know if it installed well? 
I've tried the version 1.3.0,still got a same problem Neither connect from Lan nor Internet.

**Comment by blacktailnomore** [comment]
@cnideria70 Yes, absolutely

**Comment by ghost** [comment]
Just for some further insight, here are some lines from the client of @blacktailnomore in which something failed:

```
[16:06:22] [Netty Client IO #6/INFO]: Attempting connection with missing mods [controlling, ctgui, ctm, custommainmenu, defaultoptions, jehc, jeiintegration, moreoverlays, mousetweaks, resourceloader, tipthescales, reauth] at SERVER
[16:06:24] [main/INFO]: Injecting existing registry data into this client instance
[16:06:27] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Forge (forge)
```

And here are those same lines from a working server, a properly installed Continuum 1.3.1 server with 1.3.1 client:

```
[19:05:22] [Netty Epoll Client IO #0/INFO] [FML]: Attempting connection with missing mods [controlling, ctgui, ctm, custommainmenu, defaultoptions, jehc, jeiintegration, moreoverlays, mousetweaks, resourceloader, tipthescales, reauth] at SERVER
[19:05:24] [main/INFO] [FML]: Injecting existing registry data into this client instance
[19:05:29] [main/INFO] [foamfix]: JEI search tree manager injection complete!
```
(Just so you know, this JEI line on the end probably has nothing to do with this error.)

**Comment by blacktailnomore** [comment]
@major-profundis Thanks,I'll check it

**Comment by cnideria70** [comment]
The problem is going to happen at some point

**Comment by ghost** [comment]
Make sure you have a clean install of Continuum server 1.3.1 and Continuum pack 1.3.1 and try it, then try it again with your Optifine to see if that's the problem.
There's also a chance that you haven't updated the pack from an earlier version properly.
Backing up the mods/, scripts/ and config/ folders and the server.properties, deleting them all from the main server directory, getting the new ones from the modpack server release zip and re-editing my configs and server.properties worked just fine for me (server edition).
For client updates, they are handled properly by the launcher anyway.

**Comment by blacktailnomore** [comment]
@major-profundis What is your java version?

**Comment by cnideria70** [comment]
Ok I'll looked thanks

**Comment by ghost** [comment]
My server:
```
[root@vps189773 5f3aa2f9-0f92-487a-b1c2-65e1c5b50b45]# java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
```
My client:
```
[insert_username_here@localhost Downloads]$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
```

**Comment by blacktailnomore** [comment]
@cnideria70 Have you solved your problems?

**Comment by blacktailnomore** [comment]
Finally,I solved this problem...

**Comment by ghost** [comment]
@blacktailnomore How did you fix it? What was wrong?

**Comment by aaronhowser1** [comment]
![wisdom_of_the_ancients](https://user-images.githubusercontent.com/15698722/43693869-19fb15de-98f6-11e8-9602-59b122a1f25c.png)

**Comment by manic-machiavelli** [comment]
Had the same issue. My forge installation was corrupted. Try running the forge installer again.
