### ISSUE TITLE
Bibliocraft Framed Fancy Sign crash

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Continuum#257]
* **Modpack Version**: 1.3.1

* **Issue**: When you place a framed fancy sign anywhere and shift+right click it, the cursor to write on it doesn't come up. Then, when you try to exit the GUI the game crashes. https://github.com/Nuchaz/BiblioCraft/issues/579

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/480d3c4a

* **Is it Repeatable?**: Yes, I have tried it 4 times with different fancy signs.

* **Mod/s Affected**: Bibliocraft

* **Known Fix**: https://github.com/Nuchaz/BiblioCraft/issues/579
Upgrade the pack to BiblioCraft v2.4.5.

**Comment by Boomflex** [comment]
Thank you for the report.

This has been updated in the next version of the pack.
