### ISSUE TITLE
Should be Alternative Way to make Chrome

### ISSUE THREAD

**Issue by alexsch01** [FTBTeam/FTB-Continuum#259]
So I wanted to make Resonant Jetpack with Armor but it requires the TechReborn Blast Furnace with 3500 Heat. It freakin requires 32 advanced machine casings that cost 32 data control circuits which requires 6 stacks of emeralds and 2 stacks of reinforced circuits!

2 Solutions: Change the required heat of the Armored Resonant Jetpack to 2812 heat (34 reinforced casings + 2 lava sources) or change the advance machine casing recipe from TechReborn

Thanks for reading this

**Comment by alexsch01** [comment]
Should be an alternate way to make chrome dust because currently you need 96 chrome plates to get the heat up to 3500 (like a chrome bee)

**Comment by zenoran** [comment]
I don't remember this being that big of a deal?  I mean, considering all the other silly things you have to craft in this pack this isn't exactly hard.  Ruby comes from Tier 3 miner which is pretty easy to get.

**Comment by alexsch01** [comment]
Which requires tungstensteel which requires 3000 heat which the max reinforced casings from TR gives up to 2812 heat
