### ISSUE TITLE
Question about Gear Box

### ISSUE THREAD

**Issue by SihenZhang** [FTBTeam/FTB-Continuum#26]
* **Modpack Version**: 1.0.2

* **Issue**: 
In the quest, it is said that the time can be lowered by adding more Gear Boxes (maximum of 4, which lowers crafting speed to 25 percent of original).
I don't understand. Why decrease the time will decrease the speed? What's the meaning of it? The more Gear Boxes, the less time used? Or the more Gear Boxes, the more time used? If adding 4 Gear Boxes, the time will be 75% or 25% or 125%?

**Comment by aaronhowser1** [comment]
If a recipe that uses 1 Gear Box takes 4 minutes to craft, using 4 Gear Boxes will take 1 minute to craft. More Gear Boxes = less time. I'll edit it to say "maximum of 4, which lowers crafting **time** to 25 percent of original" to be more clear
