### ISSUE TITLE
AdvancedRocketry crashes world immediately

### ISSUE THREAD

**Issue by Bobert-Ross** [FTBTeam/FTB-Continuum#260]
Version 1.3.1

Game crashes when loading a world. 

link:
https://paste.feed-the-beast.com/view/4e29e773

The crash is repeatable, but only for this world.

The issue seems to be with advancedrocketry and an xml file.
Note that I haven't used advancedrocketry yet.

**Comment by tfox83** [comment]
This is a known issue for some worlds that we do not have a fix for at this time, sorry.
