### ISSUE TITLE
crash due to Tech Reborn GUI

### ISSUE THREAD

**Issue by AmalProg** [FTBTeam/FTB-Continuum#261]
* **Modpack Version**: 1.3.1

* **Issue**: it seems the game crashes when you hover the energy bar in a Tech Reborn machine

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d9308859

* **Is it Repeatable?**: well, at least in my world, didn't test in an other one

* **Mod/s Affected**: Tech Reborn

* **Known Fix**: well seems to be an OutOfBoundException, so there is an access to a not existing key in an array i guess ^^

**Comment by modmuss50** [comment]
Have you changed or unbound your sneak key?

`Minecraft.getMinecraft().gameSettings.keyBindSneak.getKeyCode()` is the keycode we are checking against there.

**Comment by AmalProg** [comment]
Yes i did change the binding

**Comment by modmuss50** [comment]
What did you change it to? As even when I change it it seems to work ok. Even unbinding it doesnt crash

**Comment by AmalProg** [comment]
Ok, i binded it to Left shift back and no crash. 
I binded it to one of my mouse button

**Comment by AmalProg** [comment]
Some kind of custom button ...
Thanks a lot

**Comment by tfox83** [comment]
Fixed in 1.4.0
