### ISSUE TITLE
Jet Packs Up and Down speeds are off

### ISSUE THREAD

**Issue by FeedTheChunk** [FTBTeam/FTB-Continuum#262]
* **Modpack Version**: 1.3.1

* **Issue**: While using a jetpack, going up is very fast w/o hover enabled.  When hover is enabled, the up speed is more in line with what I expected  However, with hover enabled, the sink speed is incredibly fast.  Almost like the up and down speeds are reversed.  Both the Reinforced and Resonant versions exhibited the same behavior.  Other tiers of the jetpack was not tested.  This behavior was not in earlier versions of the mod pack.  The speeds didn't change until after upgrading to v1.3.1

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: Simply Jetpacks

**Comment by tfox83** [comment]
Known issue without a fix at this time
