### ISSUE TITLE
How many Elytra's is to many Elytra's?

### ISSUE THREAD

**Issue by NassiC** [FTBTeam/FTB-Continuum#264]
* **Modpack Version**: 1.3.1

* **Issue**: Crafting one of each of the creative items + one extra Energy Condenser will cost you 62 Energy Condenser. To craft one will cost you 8 Elytra. So crafting only one of each Creative item + one extra Energy Condenser, will cost you 496 Elytras.

Elytras have no recipe. So you must fly around the end and find 496 Elytras, as that is the only way of getting them. If that is even is possible in a reasonable amount of time, and HDD space. I think its safe to assume that it will not be on our server with 7 players on. That is 3472 Elytras we have to find.

* **Known Fix**: You need to add a recipe to craft an Elytra, or remove it from the Energy Condenser recipe.

**Comment by aaronhowser1** [comment]
You can duplicate Elytras by crafting them with Dragon Scales, which drop from every Dragon after the first.
