### ISSUE TITLE
Help I can't play FTB Continuum!

### ISSUE THREAD

**Issue by ThedestroycraftMC** [FTBTeam/FTB-Continuum#265]
Modpack Version : 1.12.2

Help I can't play FTB Continuum, every time I click play it won't let me it says "this app can't run on your PC," then it says "to find a version for your PC, check with the software publisher".
Here is a picture of it :

Yes, the issue is repeatable.

I don't think any mods are affecting the issue it might just be an app or software that I need to download.

I might need to download an app or a software, but I'm still not sure if that will work, because I already have Java.
![screenshot_1](https://user-images.githubusercontent.com/40508881/41805348-49a0ea26-76db-11e8-8449-2bd0395db32b.png)

**Comment by Kuktar** [comment]
Are you using twitch?

**Comment by ThedestroycraftMC** [comment]
Yes, I am using Twitch.

**Comment by aaronhowser1** [comment]
Wow I've never seen this issue before. Update Windows and Java then try again. Can you play other modpacks?

**Comment by Morganamilo** [comment]
Any chance you're on a non x86 device?

**Comment by Kuktar** [comment]
Try launching vanilla minecraft.
