### ISSUE TITLE
How to Progress with Crank Engine

### ISSUE THREAD

**Issue by ryder2341** [FTBTeam/FTB-Continuum#266]
* **Modpack Version**: 
1.3.1
* **Issue**: 
In the quest book it tells me to build a crank-driven engine out of gold in order to create RF energy, however the only way to get a gold gear is to put it through a metal press or some other contraption that requires an RF signal to work. The engine is the only way I have of producing RF signal so how do I get the materials to gain access to it? My only other assumption is that you need to find an engineer's house but for every village I visited he was nowhere to be found, so I seem to be stuck.
* **Is it Repeatable?**: 
So far I don't seem to have found a workaround

**Comment by aaronhowser1** [comment]
The Gear Cast can be made by pouring Aluminum Brass or Gold onto a Wooden Gear in the Smeltery, which lets you get all the Gears.

**Comment by ryder2341** [comment]
I just now noticed this, thank you

**Comment by aaronhowser1** [comment]
No problem, I made a note in the Crank Engine quest about how to get Gears so hopefully other people don't get confused about this in the future.
