### ISSUE TITLE
1.2.1 World not loading, "Ticking block entity" -> "ConcurrentModificationException"

### ISSUE THREAD

**Issue by rad4day** [FTBTeam/FTB-Continuum#267]
* **Modpack Version**: In 1.2.1 as well as 1.3.1

* **Issue**: The server crashes while loading the world. `java.util.ConcurrentModificationException`

* **Link to Log or Crash File Paste**: [Crash 1](https://paste.feed-the-beast.com/view/b5f85cc4), [Crash 2](https://paste.feed-the-beast.com/view/10e7a5fc)

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Obviously a mod as it's some scala code which is throwing the error. Not sure which one though.

* **Known Fix**:

**Comment by NeosGhost** [comment]
Getting a similar one although mine is a ticking player


[crash-2018-06-22_04.47.24-server.txt](https://github.com/FTBTeam/FTB-Continuum/files/2130062/crash-2018-06-22_04.47.24-server.txt)
[crash-2018-06-22_19.43.39-server.txt](https://github.com/FTBTeam/FTB-Continuum/files/2130063/crash-2018-06-22_19.43.39-server.txt)
[crash-2018-06-22_15.56.22-server.txt](https://github.com/FTBTeam/FTB-Continuum/files/2130064/crash-2018-06-22_15.56.22-server.txt)

**Comment by rad4day** [comment]
After I deleted the unknown block with MCEdit at the stated location it crashed two more times on startup but then ran again. I still don't know what caused it and what was the actual fix tbh.
@NeosGhost  I'd guess you gotta remove that player from the players.dat (don't know if they have seperate files by now)
