### ISSUE TITLE
Auto Anvil is not craftable

### ISSUE THREAD

**Issue by FeedTheChunk** [FTBTeam/FTB-Continuum#269]
* **Modpack Version**: 1.3.1

* **Issue**: Auto Anvil is uncraftable.  The craftweaker script is calling for 'blockMetal' in the upper 3 slots.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Yes

* **Mod/s Affected**:  Openblocks

* **Known Fix**:

**Comment by tfox83** [comment]
fixed in 1.4.0
