### ISSUE TITLE
Using chest transporters duplicates barrels

### ISSUE THREAD

**Issue by bendober** [FTBTeam/FTB-Continuum#271]
* **Modpack Version**: 1.3.1

* **Issue**: If you use an obsidian dolly on a barrel you get 2 barrels in return

* **Link to Log or Crash File Paste**: /

* **Is it Repeatable?**: Yes, I tried it in offline test world and it works, but only if there is ITEMDUCT from thermal dynamics connected to it and it must not be empty. 

* **Mod/s Affected**: JABBA

**Comment by tfox83** [comment]
fixed in 1.4.0
