### ISSUE TITLE
Suggestion/Edit: Quest description for Certified Crafting

### ISSUE THREAD

**Issue by sharkbite3105** [FTBTeam/FTB-Continuum#273]
* **Modpack Version**: 1.3.1

* **Issue**: Quest Certified Crafting in first and second tab have exactly the same quest description,

* **Known Fix**:  the first tab should have the quest description for the workshop table.

**Comment by aaronhowser1** [comment]
Different tasks can't have different descriptions, there's just one text field per quest.

**Comment by aaronhowser1** [comment]
Whoops, that was an accident with localization. Apparently both got assigned the same localization name, I'll get that fixed.

**Comment by tfox83** [comment]
Fixed in 1.4.0
