### ISSUE TITLE
Items voiding from multiple items

### ISSUE THREAD

**Issue by Anakardian** [FTBTeam/FTB-Continuum#274]
* **Modpack Version**: 1.2.1

* **Issue**: 
Items appear to be voided from multiple items.
First noticed the problem with a blaze hopper when trying to extract from a chest and insert into the back of a storage drawer. The hopper removed all items from the chest and did not insert any items in the drawer. No items remained in the hopper and none were left on the ground.

Later the same issue appeared with item laser relays voiding all items it was sending to a regular hopper.

Lastly the tech reborn grinder started voiding items.
Noticed it could suck more than one stack of items from a chest when it had auto-input enabled.
When logging off and returning, the entire content of items was voided and it started sucking new items.
No items were ejected from the grinder to account for the missing items.

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Have repeated the first and second scenario. third scenario has happened a few times but have not tried to repeat it.

**Comment by aaronhowser1** [comment]
Do all those still happen in 1.3.1?

**Comment by Anakardian** [comment]
i am not sure, the server is still on 1.2.1.
once it is updated i will test it again

**Comment by GWSheridan** [comment]
Need more info on latest version of the pack. If this is still an issue

**Comment by Anakardian** [comment]
finally back from travelling and had time to test

the issue seems to have disappeared with the update of the pack
