### ISSUE TITLE
Cant Interact with using Shift and right-click

### ISSUE THREAD

**Issue by Valerate** [FTBTeam/FTB-Continuum#275]
* **Modpack Version**: 1.3.1

* **Issue**:  I cant access Fancy sign from Bibliocraft with Shift + rightclick, nor can I access Vacuumulator from TE with Shift + rightclick

* **Is it Repeatable?**: Yes and annoying

* **Mod/s Affected**: Probably any mod with shift + rightclick interaction

* **Known Fix**: I dont know sadly

**Comment by aaronhowser1** [comment]
Is the sneak key conflicting with anything else?

**Comment by Valerate** [comment]
I doubt it, in earlier versions of Continuum it worked fine, and I havn't Changed any keybinds since 1.1.0

**Comment by tfox83** [comment]
Fixed in 1.4.0
