### ISSUE TITLE
Certus Quartz ore is not recognized as an ore (?) [Mining bees & Ore processor]

### ISSUE THREAD

**Issue by Valerate** [FTBTeam/FTB-Continuum#279]
* **Modpack Version**: 1.3.1 (But I've had the same issue since I started in 1.1.0

* **Issue**:  Certus Quartz ore from Applied Energistic 2 isnt being mined with Mining or Silky mining bees, and you cant put it inside a Ore processor from Industrial Foregoing for automatic mining

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: AE2, Careerbees, Industrial Foregoing, not sure which end it lies in

* **Known Fix**:  I added
`val Certus = <ore:oreCertusQuartz>;
Certus.add(<appliedenergistics2:quartz_ore>);`
At the end of appliedEnegistics.zs and now it works.

**Comment by tfox83** [comment]
Fixed in next udpate
