### ISSUE TITLE
Advanced Rocketry: Astrobody data processor

### ISSUE THREAD

**Issue by Rebelofroses** [FTBTeam/FTB-Continuum#280]
Playing on a minecraft server, I have begone  to explore in to the advanced rocketry mod. When i reached to the Astrobody data processor, i was looking to make a luna id chip. However according to videos I have researched, I am missing the section to enter the blank planet id chip to be processed with the data found. 
![2018-06-27_10 22 06](https://user-images.githubusercontent.com/40640443/41989401-0bd50fd0-79f4-11e8-9055-90214a502d9f.png)
when it should be 
![image](https://user-images.githubusercontent.com/40640443/41989449-34c16b5a-79f4-11e8-895a-d078acbaf7f3.png)
appoligize if print screen works hope it does. 
if anyone has any idea how to fix, or what i can do to get around the issue of programming planet data chips, it would be much appreciated. 

Sincerely,
RebelOfRoses

**Comment by aaronhowser1** [comment]
That video is over 3 years old, [this one](https://www.youtube.com/watch?v=Bb2jC1RP4mY) is much more recent and up to date

**Comment by Rebelofroses** [comment]
still doesnt help the issue. he skips right over it. but thanks i guess.

**Comment by aaronhowser1** [comment]
It's a series of videos, the relevant part is [here](https://youtu.be/2VU1uOmn1ZU?t=679). Basically just put a Guidance Computer on the rocket. When it's an entity, sneak right click on the rocket, open the Guidance Computer and insert an unprogrammed Planet ID Chip, then click "Select Destination" on the main rocket menu, then click on the moon. This is all explained in the quest as well.
