### ISSUE TITLE
Bug: Advanced Rocketry satellite terminal?

### ISSUE THREAD

**Issue by Rebelofroses** [FTBTeam/FTB-Continuum#281]
Continuing Advanced rocketry sent satellite in to space, upon opening terminal  my inventory goes from...
![2018-06-27_10 50 36](https://user-images.githubusercontent.com/40640443/41990818-65c9fe5c-79f8-11e8-97e8-420b1eed281e.png)
 to looking bugged out with id chips for satellite 
like this ...
![2018-06-27_10 50 28](https://user-images.githubusercontent.com/40640443/41990843-7592529e-79f8-11e8-8042-8f72aaffa37c.png)

**Comment by aaronhowser1** [comment]
Yeah, this is a known issue with Advanced Rocketry.

zmaster587/AdvancedRocketry/issues/1298
zmaster587/AdvancedRocketry/issues/1280

**Comment by tfox83** [comment]
Known issue will get into pack as soon as fixed by mod dev.

**Comment by BloodyMikey** [comment]
Sorry for doing this but has this not been fixed yet?

**Comment by SergeantTibbs** [comment]
> Sorry for doing this but has this not been fixed yet?

No.
