### ISSUE TITLE
Cannot craft Void Ore Miner Controller tier 1

### ISSUE THREAD

**Issue by pfmoore** [FTBTeam/FTB-Continuum#282]
* **Modpack Version**: 1.3.1

* **Issue**: I have all of the components for a Void Ore Miner controller (tier 1), but if I place them in a crafting grid, the controller is not visible in the output slot and I can't craft it. I've tried with the AA crafting table on a stick, the Tinker's crafting station and the vanilla crafting table, and none work. I've tried shift-clicking from JEI or placing the components manually. I've tried with the drill and lapotron crystal uncharged and having some charge in. I've logged off and on again. No improvement from any of these.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: 100%

* **Mod/s Affected**: N/A

* **Known Fix**: I'm unaware of any fix.

**Comment by Morganamilo** [comment]
Have you tried crafting it through JEI? click on the item and there's a little + where it will move the items into the table for you. It does a good job of pointing out items you don't have.

**Comment by Kuktar** [comment]
Try it in a singleplayer creative world. Does the issue still occur?

**Comment by pfmoore** [comment]
> Have you tried crafting it through JEI?

Yes. Same result.

> Try it in a singleplayer creative world

Works in a creative world :-( But still fails in my world. Even if I switch my world to creative mode.

**Comment by aaronhowser1** [comment]
Do other modified-expert-mode-ish recipes work? Is this on a server?

**Comment by pfmoore** [comment]
This is on a singleplayer world. All of the other recipes have worked so far. This just looks like I've got the wrong recipe - but I haven't (I've checked).

I guess there could be some weird metadata that doesn't match (it wants a red drill rather than the normal uncoloured one, or it needs a fully/partially/un-charged drill or lapotron, or whatever). I haven't tried all possible combinations here. What I have tried is:

1. Uncharged drill and lapotron
2. Partially charged drill and lapotron

I could fully charge either or both. It'd be a PITA to drain the charge from either or both - I had a battery that gave them both a chunk of charge before I could stop it, and I don't have anything with enough of a power need that I can drain the lapotron into it.

**Comment by aaronhowser1** [comment]
I'm 90% sure that, if the metadata matters, they should be freshly crafted and default everything (no RF and default color).

**Comment by pfmoore** [comment]
Yeah, and that combination definitely didn't work.

**Comment by Degenerecy** [comment]
Tried it myself, previous version of the pack worked but not the latest 1.3.1.

**Comment by pfmoore** [comment]
@GWSheridan Good to know, thanks. For now, I cheated one in.

PS Just adding the label doesn't notify me that the issue has been updated. Maybe you could add a mention in situations like this in future?

**Comment by tfox83** [comment]
Fixed in 1.4.0
