### ISSUE TITLE
UU-Matter 

### ISSUE THREAD

**Issue by RickERMc** [FTBTeam/FTB-Continuum#283]
* **Modpack Version**: FTB Continuum

* **Issue**: UU-Matter Platinum recipe gives Tungsten Dust

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
You didn't actually say which version of Continuum the issue is on

**Comment by Ravalli03** [comment]
Having the same issue, using version 1.3.1

**Comment by RickERMc** [comment]
It's on v1.3.1 sorry

**Comment by tfox83** [comment]
Changed the recipe slightly in 1.4.0 to produce platinum dust
