### ISSUE TITLE
My friend an I are playing the FTB Continuum on LAN  and we came across an issue?

### ISSUE THREAD

**Issue by Tony266x** [FTBTeam/FTB-Continuum#285]
-->

* **Modpack Version**: FTB Continuum 1.3.1

* **Issue**: <My friend and i are playing LAN of FTB continumm we enjoyed the modpack so far. We were excited on getting the ore excavation unlocked. I put 3 of the upgrades onto my pick axe which gave me the excavation modifier. Yet when i tried to use it. an error message appeared in red such "Shape mining has been disabled". I gave him the pick axe and he had no trouble using it. So I think this is a bug/issue. Is there any known ways i can fix this

**Comment by aaronhowser1** [comment]
Were you using a keybind? You shouldn't have to, it should just mine ore veins automatically. If you can, check the server and client's oreexcavation.cfg for this:

```
    # Allow players to use shape mining [default: true]
    B:"Allow Shapes"=false
```
It should be set to false on both.

Also, I recommend more than 3 upgrades, it doesn't do much with that little on it.

**Comment by Tony266x** [comment]
Thank you for helping, I truly appreciate it and will try this nest time my friend comes over.
