### ISSUE TITLE
Having some trouble in multiplayer connection

### ISSUE THREAD

**Issue by papadave66** [FTBTeam/FTB-Continuum#286]
* **Modpack Version**: 
v1.3.1

* **Issue**: 
I am trying to use a custom launcher, and using the latest forge and this cool mod package. It is ok to play in single mode . but when I try to connect server , it will give a notice something like this
![tim 20180628121457](https://user-images.githubusercontent.com/14260128/42013206-cd87b788-7ace-11e8-845e-b8b668fc667d.png)
so what should I do . thanks.  I am running offline mode by the way.
* **Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/c880097d
* **Is it Repeatable?**: 
Yes
* **Mod/s Affected**: 
I dont know
* **Known Fix**: 
unknown

**Comment by ghost** [comment]
@papadave66 you are using the wrong version of Forge. You are running 14.23.4.2703 while this modpack runs 14.23.4.2705, the version recommended by MinecraftForge for 1.12.2.
Retry the modpack with the correct version of Forge enabled.
Most of those errors in your log basically stated that "these mods won't work because Forge has errored".

**Comment by papadave66** [comment]
@major-profundis Thanks for your advice . I tried to change the forge version to .2705 , but the issue still there 
![tim 20180629093021](https://user-images.githubusercontent.com/14260128/42068790-a67fd44c-7b80-11e8-8600-1b6a4f9f7e89.png)
https://paste.feed-the-beast.com/view/f0acf015
the new game log is here . and the bottom of the log is when I clicked the multiplayer and it reported.

**Comment by tfox83** [comment]
You will need to test in Online mode, this is a known issue with mods in offline mode due to cracked versions of Minecraft
