### ISSUE TITLE
Java crash

### ISSUE THREAD

**Issue by ThinkPotato** [FTBTeam/FTB-Continuum#287]
* **Modpack Version**: 
1.3.1
* **Issue**: 
Everytime I play, it always said:
[Immersive Engineering] Warning: Your java version is 1.8.0_25. This version causes crashes with engineer’s manual. There crashes are close to impossible to fix for us. You can prevent the crashes by installing up-to-date java (make sure to use java 8 not java 9) and forcing your launcher to use it.
I just forget it and keep play, but after 30 minutes the game just freeze and not responding. If I keep waiting it's gonna work normal after 3-5 minute and keep repeat like that, but if I try to close it, the game gonna crash.
I try to uninstall the old java version and install the newest version (which is java 8 update 171) but it seem not work. Maybe I haven't set the launcher run at new java version but I don't know how to do that.
Please help me.
![img_20180628_175845](https://user-images.githubusercontent.com/40668197/42044243-ad91695c-7b22-11e8-9ba4-047fa939a2fd.jpg)

* **Link to Log or Crash File Paste**: 
Sorry, but I don't know how to get log or crash file.
* **Is it Repeatable?**: 
Just play game and forget the warning, after 30-45 minutes, it happen
* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
The Twitch launcher is a little weird with Java versions. You can use [this guide](https://www.reddit.com/r/feedthebeast/comments/8awxf4/having_problems_with_java_180_25_not_anymore/) to make the Twitch launcher use the latest Java, or use MultiMC instead.

**Comment by ThinkPotato** [comment]
Okay thanks I'll try it late. It's been 11 pm at my country now.

**Comment by ghost** [comment]
You could just use the FTB Launcher, which you can get from the Feed The Beast homepage.

**Comment by aaronhowser1** [comment]
The FTB Launcher is outdated and unsupported though, so I personally wouldn't recommend it

**Comment by ghost** [comment]
It works just fine on Linux though.
