### ISSUE TITLE
RS Crafter Manager should have its recipe removed and be hidden

### ISSUE THREAD

**Issue by Morganamilo** [FTBTeam/FTB-Continuum#289]
* **Modpack Version**: 1.3.1

* **Issue**: I have set up a refined storage system after following the extremely short quest tree. The crafter does not appear to have a recipe nor does it appear in jei. This leads me to think it is disabled but the crafter manager has a recipe that requires a crafter. Maybe this is an oversight and should be disabled too?
The quest also says "Autocrafting comes later". I'm not sure if this is supposed to mean it comes later in refined storage or if It's intended to eventually move over to an ME system and get auto crafting there.

**Comment by aaronhowser1** [comment]
Yes, RS has no autocrafting, only AE2. I'll change the quest to explain it better though.

**Comment by Morganamilo** [comment]
Alright thanks. Make sure to also disable the crafter manager recipe.

**Comment by aaronhowser1** [comment]
Oh, I think that should already be disabled. I'll reopen this and tag it in that case.

**Comment by tfox83** [comment]
fixed in 1.4.0
