### ISSUE TITLE
Can't craft Magma Crucible

### ISSUE THREAD

**Issue by EscolarProgramming** [FTBTeam/FTB-Continuum#290]
* **Modpack Version**: 1.3.1

* **Issue**: It is not possible to craft the Magma Crucible of the mod Thermal Expansion. In JEI there is the crafting recipe and you can put it with the plus symbol in the craftig field, but there's no item in the output field.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/c0394f79

* **Is it Repeatable?**: Yes, 5 people tried to craft it. Some versions ago all worked well.

* **Mod/s Affected**: Thermal Expansion

* **Known Fix**: ----

**Comment by tfox83** [comment]
Fixed in 1.4.0
