### ISSUE TITLE
Metallum Ex Vacui II: Lists 1 laser core when 3 are needed

### ISSUE THREAD

**Issue by Morganamilo** [FTBTeam/FTB-Continuum#291]
* **Modpack Version**: 1.3.1

* **Issue**: The quest `Metallum Ex Vacui II` Requires 1 laser core when the tier II void miner needs 3 laser cores to complete. The similar quest `Saxa Ex Vacui II` is listed correctly.

* **Known Fix**: Change the laser core requirement to three.

**Comment by tfox83** [comment]
changed to 3 in next update
