### ISSUE TITLE
Diamond Compartment Crash

### ISSUE THREAD

**Issue by Ofruit** [FTBTeam/FTB-Continuum#293]
**Modpack Version:** 1.3.1

**Issue:** Most of the time i try to interact with my Diamond Compartment, the game crash.

**Crash File:** 
[crash-2018-06-30_15.55.08-server.txt](https://github.com/FTBTeam/FTB-Continuum/files/2151768/crash-2018-06-30_15.55.08-server.txt)

[crash-2018-06-30_15.49.57-server.txt](https://github.com/FTBTeam/FTB-Continuum/files/2151769/crash-2018-06-30_15.49.57-server.txt)

[crash-2018-06-30_15.46.25-server.txt](https://github.com/FTBTeam/FTB-Continuum/files/2151770/crash-2018-06-30_15.46.25-server.txt)

**Is it Repeatable?:** I tried to find what cause this, but it happens 90% of the time and still have no clue.

**Mod/s Affected:**  From Binnie Mods

**Comment by tfox83** [comment]
Fixed in 1.4.0
