### ISSUE TITLE
Alarm and Incandescent Lamp need uninsulated Copper Cable, which isn't craftable

### ISSUE THREAD

**Issue by Jacy4321** [FTBTeam/FTB-Continuum#294]
* **Modpack Version**: 1.3.1

* **Issue**:  Not able to make copper cable.  Used in two recipes, Alarm and Incandescent Lamp. The method for creating copper cable is to use the wrench to break insulated copper cable but when done deletes the cable and doesn't give un-insulated cable. I am trying to craft the alarm.
* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Tech Reborn
* **Known Fix**: Spawning in the items, rather than crafting them.

**Comment by aaronhowser1** [comment]
Isn't it made by putting 2 Copper Wire into an EFab with Latex?

EDIT: Nope, nevermind. I'll label this as a recipe issue then.

**Comment by tfox83** [comment]
Fixed in 1.4.0
