### ISSUE TITLE
Lazer animation absent when crafting Electronic circuit

### ISSUE THREAD

**Issue by Jacy4321** [FTBTeam/FTB-Continuum#295]
* **Modpack Version**: 1.3.1

* **Issue**: When crafting Electronic Circuits from TechReborn using the Empowerer method the animation is see through.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: TechReborn/ActuallyAdditions
* **Known Fix**: none so far

**Comment by aaronhowser1** [comment]
With regular AA recipes, the beams are the color of the material being infused (Palis is blue, Restonia is red, etc). I think it might be because there's no way (that I know of) to specify the color of the beam for custom recipes.

**Comment by tfox83** [comment]
Correct, I could go through and set a bunch of custom colors up for it, but it really came down to having the lack of time for such a small cosmetic feature
