### ISSUE TITLE
When i use the hang glider in ftb continuum it sounds like a theremin playing

### ISSUE THREAD

**Issue by pablodrake** [FTBTeam/FTB-Continuum#296]
* **Ftb Continuum/Minecraft version 1.12.2**: 
* **When i use the hang glider in the ftb continuum modpack it sounds like if i were playing a theremin and it is very anoying**: 
* **Whenever i use the hang glider it sounds**:

**Comment by Chalmes** [comment]
That's the Variometer.  Default key is V (might be conflicted)

**Comment by GWSheridan** [comment]
This is a sound the glider makes when using a keybind

**Comment by pablodrake** [comment]
ok thank you guys, i resolved the problem
