### ISSUE TITLE
yabba infinite capacity

### ISSUE THREAD

**Issue by zenoran** [FTBTeam/FTB-Continuum#298]
* **Modpack Version**: https://www.feed-the-beast.com/projects/ftb-continuum/files/2572473

* **Issue**: I can't find a way to apply the infinite capacity upgrade to yabba barrel.  I was looking through the code and it seemed you must be in creative mode to actually apply it unless I'm missing something.  Right clicking on the barrel with the upgrade does not seem to work unless in creative mode.

Trying to make the octuple compressed cobblestone for the creative modifiers and this appears to be the only way to effectively store that much cobblestone.  If I'm doing it wrong or there is some other way to accomplish that much cobble please let me know.  I guess I'll try AE2 storage disks for now.

* **Link to Log or Crash File Paste**: no crash

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: Yabba

* **Known Fix**: gamemode 1 ??? if that's a "fix"

**Comment by aaronhowser1** [comment]
You have to go up the tiers, not just straight to Infinite. Install Iron, then Gold, then Diamond, then Infinite.

**Comment by zenoran** [comment]
Thanks! Couldn't find anything even googling.
