### ISSUE TITLE
Unable to make bronze gear with the metal press

### ISSUE THREAD

**Issue by S0llux** [FTBTeam/FTB-Continuum#299]
* **Modpack Version**: 1.3.1

* **Issue**: Bronze gears are uncraftable with the metal press from IE. Using blaze hoppers to feed the bronze into it.

* **Link to Log or Crash File Paste**: No crash
* **Is it Repeatable?**: Affirmative.

* **Mod/s Affected**: Immersive Engineering

* **Known Fix**: You can still make the bronze gear with the smeltery and gear cast.

**Comment by aaronhowser1** [comment]
Can you throw the Bronze manually onto the Metal Press? Hoppers are a bit weird with them.

**Comment by Kratzwurst** [comment]
Gears needs 4 Ingots to Craft on the Metall Press. Hoppers drops only 1 Ingot (ideal for Wires or Plates).
