### ISSUE TITLE
Clockwork Engine has a broken recipe

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Continuum#3]
* **Modpack Version**
1.0.0
* **Issue**
![image](https://user-images.githubusercontent.com/15698722/40085127-1d17a408-585f-11e8-88ab-64c48570b329.png)

* **Link to Log or Crash File Paste**:
N/A
* **Is it Repeatable?**
N/A
* **Mod/s Affected**
N/A
* **Known Fix**
N/A

**Comment by tfox83** [comment]
Fixed in Hotfix 1.0.1, releasing asap

**Comment by tfox83** [comment]
Fixed in 1.0.1 which is released.
