### ISSUE TITLE
Some grains not producible to pulverized Version

### ISSUE THREAD

**Issue by Greendrgon** [FTBTeam/FTB-Continuum#300]
* **Modpack Version**: FTBContinuum-1.3.1

* **Issue**: The following grains do not have a recipe to produce the Pulverized version:
Gold grains # 4694/7
Platinum grains # 4694/9
Tin grains # 4694/11
Nickel grains # 4694/12
Lead grains # 4694/13
Zinc grains # 4694/14

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: Binnie´s Extra Bees

* **Known Fix**:

**Comment by Kuktar** [comment]
I think they combine I to tint piles.

**Comment by Greendrgon** [comment]
There are no recipes for the grains

**Comment by tfox83** [comment]
Fixed in 1.4.0

**Comment by Greendrgon** [comment]
Thx 👍
