### ISSUE TITLE
Can't launch rocket

### ISSUE THREAD

**Issue by EscolarProgramming** [FTBTeam/FTB-Continuum#302]
* **Modpack Version**: 1.3.1

* **Issue**: In al ot of times, it's impossible to reach the moon. The rocket is big enough and we've already reached the moon with that rocket once.
We can start and the rocket launches up to y=998, but than the velocity goes to 0, the fuel gets empty and you fall back to earth.

Edit: It's also impossible for us to shoot a station in the orbit

![java_2018-07-04_20-42-37](https://user-images.githubusercontent.com/6965961/42291254-e1d05302-7fca-11e8-96d4-92804d594587.png)

![java_2018-07-04_20-43-34](https://user-images.githubusercontent.com/6965961/42291268-ee9f5150-7fca-11e8-848c-8af143954985.png)

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/e4eda409 
That error is everytime in the console

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Advanced Rocketry

* **Known Fix**: Unfortunately no

**Comment by aaronhowser1** [comment]
Can any rockets at all launch? Can you try remaking that rocket in SP?

**Comment by EscolarProgramming** [comment]
Rockets can launch, we chan shoot them in the air, but they fell down after the sprit is empty. 
In SP there's the same problem, in the first try all worked well, all the other tries (with the same and other rockets) don't reached the moon and flew only to high y=998. But in SP there's another error: https://paste.feed-the-beast.com/view/81a0a362

**Comment by aaronhowser1** [comment]
You can try adding more fuel things to the rocket, I don't really know what else you could do.

**Comment by EscolarProgramming** [comment]
I've added a lot (36) of Liquid Fuel Tanks, but there's the same issue. In SP it works more often than in MP.
Here's a video of the issue: https://www.youtube.com/watch?v=m9F8RNTbvo0

**Comment by tfox83** [comment]
will get into pack as soon as fixed by moddev
