### ISSUE TITLE
Better Questing bug: quests get renamed to "new quest" and lose their descriptions and requirements

### ISSUE THREAD

**Issue by Mafferr** [FTBTeam/FTB-Continuum#303]
Modpack Version: 1.3.1

Issue: so far 2 of my quests have been auto-completed and lost their names and descriptions and have had their icons changed to a nether star. I noticed that it has happened both times when opening my world. This is single player btw. I lost the quest for the vacuum freezer, which is what I'm making now in order to get tungtensteel, and I lost a quest in the rocketry tab which will be very annoying because I dont even know what the quest was originally.

Link to Log or Crash File Paste: Not applicable

Is it Repeatable?: Not on purpose, but it has repeated twice

Mod/s Affected: Better Questing

*Edit*
Known Fix: (from aaronhowser1) this is the purpose of the "update quests" quest. 
For some reason, I can now claim the formerly broken quests, even though I still havent completed them. But I'll just finish them before I claim them now that i have the descriptions and requirements back. So I'll call this solved
![2018-07-04_17 18 31](https://user-images.githubusercontent.com/40840502/42294379-55061df6-7fae-11e8-89a9-b4508185675b.png)

**Comment by Mafferr** [comment]
I definitely havent started on anything in this page of the quest book

![2018-07-04_17 20 57](https://user-images.githubusercontent.com/40840502/42294417-a35a0bc0-7fae-11e8-8429-6a35e93b6bca.png)

**Comment by aaronhowser1** [comment]
Was this world made in 1.3.1? If not, definitely go to the first tab of the quests and do the Reload Quests quest (or just use the command `/bq_admin default load`). It looks like your quests are outdated, you have to reload them whenever they change.

**Comment by Mafferr** [comment]
ahhh, thank you. that's what i needed!
