### ISSUE TITLE
resturbed ghast spawner not spawning

### ISSUE THREAD

**Issue by statphantom** [FTBTeam/FTB-Continuum#305]
* **Modpack Version**: 1.3.1

* **Issue**: the resturbed ghast spawner isn't spawning ghasts at all. Have made sure it has way then enough power, tried in both nether and overworld, made sure it has way more then enough space (64 x 64 x 32 room), made sure it's set to always on, also tried redstone on. also tried speeding it up with no spawning.

* **Link to Log or Crash File Paste**: NA

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Extra Utilities 2

* **Known Fix**:

**Comment by aaronhowser1** [comment]
Try making a creative flat SP world and put the spawner way up in the air. I had a ton of problems with my Ghast spawner, it turned out to be a problem with room. Although I used the IF spawner not the ExU2 one.

**Comment by statphantom** [comment]
I'll try the IF spawner, if I can make it.
