### ISSUE TITLE
Crashes before i can do anything

### ISSUE THREAD

**Issue by iamanewbieboob** [FTBTeam/FTB-Continuum#306]
I am using the FTB Continuum Pack and am unable to play anymore. I have not changed the mudpack in any way. Help would be appreciated

* **Modpack Version**: 1.3.1

* **Issue**:Crashes without fail on boot
* **Link to Log or Crash File Paste**: 

2018-07-05 17:48:43,020 Client Shutdown Thread WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream 2018-07-05 17:48:43,026 Client Shutdown Thread WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream 2018-07-05 17:48:43,028 Client Shutdown Thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger   <log4j:Event logger="journeymap" timestamp="1530830923044" level="ERROR" thread="Client Shutdown Thread">     <log4j:Message><![CDATA[Error handling WorldEvent.Unload]]></log4j:Message>     <log4j:Throwable><![CDATA[java.lang.NullPointerException 	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1570_WorldEventHandler_onUnload_Unload.invoke(.dynamic) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:452) 	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:372) 	at net.minecraft.client.Minecraft.func_71363_D(Minecraft.java:2968) 	at net.minecraft.client.main.Main$2.run(SourceFile:116) ]]></log4j:Throwable>   </log4j:Event>
--
12:48:43 | monitor | expected <
17:48:43 | journeymap | ExecutionException in getPlayer: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) 	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) 	at journeymap.client.data.DataCache.getPlayer(DataCache.java:303) 	at journeymap.client.data.DataCache.getPlayer(DataCache.java:190) 	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1570_WorldEventHandler_onUnload_Unload.invoke(.dynamic) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:452) 	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:372) 	at net.minecraft.client.Minecraft.func_71363_D(Minecraft.java:2968) 	at net.minecraft.client.main.Main$2.run(SourceFile:116) Caused by: java.lang.NullPointerException 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) 	at com.google.common.cache.LocalCache.get(LocalCache.java:4153) 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) 	at journeymap.client.data.DataCache.getEntityDTO(DataCache.java:441) 	at journeymap.client.data.PlayerData.load(PlayerData.java:86) 	at journeymap.client.data.PlayerData.load(PlayerData.java:30) 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) 	... 13 more
17:48:43 | journeymap | Error handling WorldEvent.Unload java.lang.NullPointerException 	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1570_WorldEventHandler_onUnload_Unload.invoke(.dynamic) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:452) 	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:372) 	at net.minecraft.client.Minecraft.func_71363_D(Minecraft.java:2968) 	at net.minecraft.client.main.Main$2.run(SourceFile:116)
17:48:43 | journeymap | ExecutionException in getPlayer: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) 	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) 	at journeymap.client.data.DataCache.getPlayer(DataCache.java:303) 	at journeymap.client.data.DataCache.getPlayer(DataCache.java:190) 	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1570_WorldEventHandler_onUnload_Unload.invoke(.dynamic) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:452) 	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:372) 	at net.minecraft.client.Minecraft.func_71363_D(Minecraft.java:2968) 	at net.minecraft.client.main.Main$2.run(SourceFile:116) Caused by: java.lang.NullPointerException 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) 	at com.google.common.cache.LocalCache.get(LocalCache.java:4153) 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) 	at journeymap.client.data.DataCache.getEntityDTO(DataCache.java:441) 	at journeymap.client.data.PlayerData.load(PlayerData.java:86) 	at journeymap.client.data.PlayerData.load(PlayerData.java:30) 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) 	... 13 more
17:48:43 | journeymap | Error handling WorldEvent.Unload java.lang.NullPointerException 	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1570_WorldEventHandler_onUnload_Unload.invoke(.dynamic) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:452) 	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:372) 	at net.minecraft.client.Minecraft.func_71363_D(Minecraft.java:2968) 	at net.minecraft.client.main.Main$2.run(SourceFile:116)
17:48:43 | journeymap | ExecutionException in getPlayer: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) 	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) 	at journeymap.client.data.DataCache.getPlayer(DataCache.java:303) 	at journeymap.client.data.DataCache.getPlayer(DataCache.java:190) 	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1570_WorldEventHandler_onUnload_Unload.invoke(.dynamic) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:452) 	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:372) 	at net.minecraft.client.Minecraft.func_71363_D(Minecraft.java:2968) 	at net.minecraft.client.main.Main$2.run(SourceFile:116) Caused by: java.lang.NullPointerException 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) 	at com.google.common.cache.LocalCache.get(LocalCache.java:4153) 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) 	at journeymap.client.data.DataCache.getEntityDTO(DataCache.java:441) 	at journeymap.client.data.PlayerData.load(PlayerData.java:86) 	at journeymap.client.data.PlayerData.load(PlayerData.java:30) 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) 	... 13 more
17:48:43 | journeymap | Error handling WorldEvent.Unload java.lang.NullPointerException 	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1570_WorldEventHandler_onUnload_Unload.invoke(.dynamic) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:452) 	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:372) 	at net.minecraft.client.Minecraft.func_71363_D(Minecraft.java:2968) 	at net.minecraft.client.main.Main$2.run(SourceFile:116)
17:48:43 | journeymap | ExecutionException in getPlayer: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) 	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) 	at journeymap.client.data.DataCache.getPlayer(DataCache.java:303) 	at journeymap.client.data.DataCache.getPlayer(DataCache.java:190) 	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1570_WorldEventHandler_onUnload_Unload.invoke(.dynamic) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:452) 	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:372) 	at net.minecraft.client.Minecraft.func_71363_D(Minecraft.java:2968) 	at net.minecraft.client.main.Main$2.run(SourceFile:116) Caused by: java.lang.NullPointerException 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) 	at com.google.common.cache.LocalCache.get(LocalCache.java:4153) 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) 	at journeymap.client.data.DataCache.getEntityDTO(DataCache.java:441) 	at journeymap.client.data.PlayerData.load(PlayerData.java:86) 	at journeymap.client.data.PlayerData.load(PlayerData.java:30) 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) 	... 13 more
17:48:43 | journeymap | Error handling WorldEvent.Unload java.lang.NullPointerException 	at journeymap.client.forge.event.WorldEventHandler.onUnload(WorldEventHandler.java:33) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1570_WorldEventHandler_onUnload_Unload.invoke(.dynamic) 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) 	at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:452) 	at net.minecraft.server.integrated.IntegratedServer.func_71260_j(IntegratedServer.java:372) 	at net.minecraft.client.Minecraft.func_71363_D(Minecraft.java:2968) 	at net.minecraft.client.main.Main$2.run(SourceFile:116)

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: 

* **Known Fix**: 

ps I am sorry about the horrible formatting

**Comment by aaronhowser1** [comment]
Have you tried reinstalling onto a new instance Have you changed any configs or anything? Is this crash before you get to the main menu? It looks like it's JourneyMap doing it, you could try uninstalling it and seeing if that works I suppose.

**Comment by iamanewbieboob** [comment]
ok thanks ill try

**Comment by tfox83** [comment]
Please follow instructions when posting logs/crash reports.
