### ISSUE TITLE
Arc Furnace Electrode Blueprint

### ISSUE THREAD

**Issue by Zero9o1o** [FTBTeam/FTB-Continuum#307]
* **Modpack Version**: 1.3.1

* **Issue**: The Blueprint from Immersive Engineering for Arc Furnace Electrodes can only be acquired from the quest book once. So if you lose it for what ever reason you cannot get it back. There is no crafting recipe for it, it is not part of any villager trade table, nor is it in a loot table.

* **Known Fix**: Add a crafting recipe, Add it to a villagers trades table, or put a repeatable quest to reacquire it again

**Comment by ZeekDaGeek** [comment]
This is major issue considering if you break the Workbench from the child block with a silk touch you lose everything in the table. I'm just without a way to make good electrodes now.

**Comment by Zero9o1o** [comment]
You don't need silk touch for that Workbench bug

**Comment by tfox83** [comment]
fixed in 1.4.0
