### ISSUE TITLE
Chrasherino riperino

### ISSUE THREAD

**Issue by Printeris** [FTBTeam/FTB-Continuum#309]
Modpack Version: 1.3.1

Issue: I play the game for about 30 mins then i crash. Happens pretty regularly. I play on a high end laptop and have allocated about 8 gigs of ram to minecraft. Tried messing with the settings and nothing really changed although i noticed that when i put my chunk loading to the minimum and while i was playing underground i barely crashed at all but when i went to the neather i crashed every 5 mins. But then i could also go 40 mins without crashing on "max" settings and sometimes could crash after less than a minute on "min" settings. I also play on a multiplayer server with a friend who plays on a damn toaster of a pc that can barely get 30fps on "min" settings and he has not crashed once in the time we have been playing together (about a week).

Link (WITHOUT the "info" & "debug") : https://paste.ubuntu.com/p/VcqhsmFRj3/
Link (WITH the "info" & "debug") : https://paste.ubuntu.com/p/v9fBR2ywsp/
Link (WITH the "info" & WITHOUT "debug") : https://paste.ubuntu.com/p/78TP3pc4Dr/

Dont know whats important and whats not in those so just have them all :p

Is it Repeatable? : Im not sure but i think it happens during some world gen (if i understand how that works correctly :D)

**Comment by tfox83** [comment]
More than likely happening during world gen, I am not able to reproduce this
