### ISSUE TITLE
Loading up my world gets stuck on 0%

### ISSUE THREAD

**Issue by H20verdrive** [FTBTeam/FTB-Continuum#31]
* **Modpack Version**: 1.0.2

* **Issue**: loading world gets to 0% on the screen and stops.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: All of them?

No matter what version i change to, its the same world that never works. i made another world which loaded fine, but i dont want to have to restart. Im gonna try to duplicate the world.

**Comment by aaronhowser1** [comment]
What's near your base? Did you do anything right before this started happening? Can you post your client log when it happens?

**Comment by Kuktar** [comment]
Did you check for failed ticking entities or title entities. There should be a crash log and or stall log. Without those logs FTB hands are tied. If you can paste the logs it would be super helpful

**Comment by Kuktar** [comment]
Also unless you changed the backup options in FTB utilities then you have backups of your world. These are in zip format and allow you to go back and copy a previous version of your world.

**Comment by modmuss50** [comment]
When you load that world is there anything of use in the log? If so can you post it here please.
