### ISSUE TITLE
Can’t autocraft crafting tables with AE

### ISSUE THREAD

**Issue by chancock1991** [FTBTeam/FTB-Continuum#310]
* **Modpack Version**: 1.3.1-1.12.2

* **Issue**: cannot craft vanilla crafting table with ae system using autocrafting via interfaces. Programmed correctly using actual 4 oak planks which outputs crafting table instead of JEI. When attempting to request craft, the select cpu doesn’t pop up which prevents crafting the table. Also unable to autocraft anything with ae that uses a crafting table as part of its recipie dispite having crafting tables in the system

* **Not a crash

* **Is it Repeatable?**: <!-- yes. Tested on test world with only the crafting table recepie and 4 planks in system

* **Mod/s Affected**: <!-- AE

* **Known Fix**: <!-- ex. Molecular interphase is able to be crafted when crafting table recepie is removed and provided a crafting table that I made

**Comment by tfox83** [comment]
Fixed in 1.4.0
