### ISSUE TITLE
Cannot craft Normal Dense / Vacuum Item and Fluid ducts

### ISSUE THREAD

**Issue by Zero9o1o** [FTBTeam/FTB-Continuum#311]
* **Modpack Version**: 1.3.1

* **Issue**:  Cannot craft dense or vacuum versions of normal item or fluid ducts

* **Mod/s Affected**: Thermal Dynamics

* **Known Fix**: Re-add the recipe for them. Recipes for them got removed on line 7,8,13, and 14 of thermalDynamics.zs which caught the dense and vacuum versions of the ducts cause thermal dynamics uses NBT for which version of the duct it is.

**Comment by tfox83** [comment]
Fixed in 1.4.0
