### ISSUE TITLE
Openblocks tank bucket (lava) not working

### ISSUE THREAD

**Issue by RealTrueDeviL** [FTBTeam/FTB-Continuum#312]
* **Modpack Version**: 1.3.1

* **Issue**: Can't fill buckets from Openblock tanks (Lava)

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/9e094ee0

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Openblocks

* **Known Fix**: No idea :P

**Comment by Morganamilo** [comment]
Shift right click, make sure the individual tank has at least 1B worth of liquid.

**Comment by RealTrueDeviL** [comment]
Ohhh.. ok When did they change that?..

Ok, nevermind then, thanks..
