### ISSUE TITLE
Quests gone

### ISSUE THREAD

**Issue by CHATALOT1** [FTBTeam/FTB-Continuum#313]
![2018-07-09_15 17 07](https://user-images.githubusercontent.com/41011078/42456734-880fc7b4-838d-11e8-9fbe-cfb6a02d739c.png)
![2018-07-09_15 17 11](https://user-images.githubusercontent.com/41011078/42456735-882e66e2-838d-11e8-90b7-4c7fe29b84a9.png)

* **Modpack Version**: 1.3.1

* **Issue**: i just logged into my world today and the quest interface had all the quests missing and some extra buttons

* **Is it Repeatable?**: I don't know

**Comment by tfox83** [comment]
Try reinstalling your instance, seems something may of curopted on download/install.  I am not able to reproduce this issue.

**Comment by CHATALOT1** [comment]
that didn't fix it

**Comment by aaronhowser1** [comment]
Use the command `/bq_admin default load`
