### ISSUE TITLE
Steel Ingots cannot be melted in a magma crucible

### ISSUE THREAD

**Issue by ZeekDaGeek** [FTBTeam/FTB-Continuum#315]
* **Modpack Version**: 1.4.0

* **Issue**: You're unable to melt Steel Ingots in magma crucible. Small over sight but you can melt Steel blocks, plates and nuggets, so it seems unintended.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Thermal Expansion.

* **Known Fix**: Recipe change.

**Comment by tfox83** [comment]
Added in 1.4.1
![image](https://user-images.githubusercontent.com/4246308/42649412-833146b8-85be-11e8-9dbd-925321f77b66.png)
