### ISSUE TITLE
Creative drum does not work as the modpack intends.

### ISSUE THREAD

**Issue by SpentBarn** [FTBTeam/FTB-Continuum#317]
* **Modpack Version**: 1.3.1

* **Issue**: "The Creative Drum stores an unlimited amount of any fluid of you choosing. Right click the Creative Drum with the fluid you want to set it to that fluid. You can reset it by crafting it by itself.

Okay, so i'm on a server. I have worked really hard on the pack and gotten to the point where i now mostly lack for nothing. So i got the chance to create creative things. Yay! unlimited GP, unlimited energy and unlimited fluids.

However, my joy was short lived when it came to the drum. I've tried right clicking it with buckets, cans from Forestry, Cells from TechReborn, to no avail. 
"No worries", thought I! "for I have fluiducts!"
Fluiducts is a no go. Even the super laminar ones, opaque and non-opaque. 

Transfer nodes should do the trick, being the same mod and all, but nay. That too was bust. 

I tested in a single player world and it works perfectly IF i'm in creative. Otherwise, no. Halp?

* **Link to Log or Crash File Paste**:

* **Is it Repeatable?**: Well, yes. It doesn't work every time.

* **Mod/s Affected**: 

* **Known Fix**: <!-- optional;

**Comment by tfox83** [comment]
Ok so the Drum recipe has been replaced fully by the TE creative Tank which can be found in JEI.  We added tooltips to the creative blocks that they cannot be removed once placed by a non-op player on a server.  This will be in 1.4.1
