### ISSUE TITLE
Creative blocks are placeable, but can't be picked up

### ISSUE THREAD

**Issue by SpentBarn** [FTBTeam/FTB-Continuum#318]
* **Modpack Version**: 1.4.0

* **Issue**: The new fix with creative drum being craftable into creative tank is all well and good, but there's no way for anyone in survival mode to pick the darn tanks up. Thus, no way to clear them. In other words i have to spend ages crafting one for each type of liquid.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
Can you wrench it to pick it up? I think you can just use another fluid to change what it has too.

**Comment by zenoran** [comment]
Same deal for creative energy source?  Is it just assumed you can't pick these items up after you put them down or is there some tool I'm missing?

**Comment by aaronhowser1** [comment]
Have you tried sneak right clicking it with a wrench?

**Comment by SpentBarn** [comment]
I found that you indeed can change the contents by right clicking it with another fluid. Wrench does not work. I’ve also tried drill, pickaxe, tinkers pick and hammer, builder with quarry card(clearing and regular).

**Comment by aaronhowser1** [comment]
Did you sneak right-click or regular right-click with the wrench? I think sneak right-clicking does it.

**Comment by SpentBarn** [comment]
Wrench does not work

**Comment by aaronhowser1** [comment]
I just went into a singleplayer world, and a Wrench did the trick on the Creative Portable Tank. Don't use the Smart Wrench, it doesn't work on Thermal Suite blocks for some reason (#278). Sneak right click with a Wrench from AE2 or Redstone Arsenal (it has to have RF for the RA ones to work). Try again with one of those Wrenches.

**Comment by zenoran** [comment]
I think he was saying there is no way for people to pickup the Extra Utilities tank so they can craft the portable one from it.

There doesn't appear to be anything in the pack that allows survival to break these blocks so I assume you would need OP to do it.

**Comment by zenoran** [comment]
@aaronhowser1 I tested wrench and it doesn't work either unless you are OP on the server.  I think the only way you could test this is with a server because even if you /gamemode 0 on a server it won't work unless you have OP when you're in gamemode 0.  Once you deop it won't work anymore.

**Comment by aaronhowser1** [comment]
Oh, I was only trying in SP, which I suppose automatically OPs you. I don't see a config option for that either. Maybe we'll just have to ask the mod devs to add a config option?

**Comment by SpentBarn** [comment]
I'm saying you can't pick up the Thermal Expansion creative tank. In other words, the supposed fix for the creative drums brought with it other problems. I have also tested in SP, and it works as long as one is OP, but i'm playing on a server, so that's kind of a problem

**Comment by zenoran** [comment]
Ya ideally there should probably be some tool to break the blocks. I think this was the Vajra in previous versions but not available in 1.12. But ya if u can get Temma to add config options that's even better.

Worst case, it might not hurt to warn the user in the quest notes they need to use caution when placing the blocks since they can't be broken.

**Comment by tfox83** [comment]
Ok so the Drum recipe has been replaced fully by the TE creative Tank which can be found in JEI.  We added tooltips to the creative blocks that they cannot be removed once placed by a non-op player on a server.  This will be in 1.4.1
