### ISSUE TITLE
FTB Continuum Crash 1.0.2 - Deep dark

### ISSUE THREAD

**Issue by CephalonCosmic** [FTBTeam/FTB-Continuum#32]
* **Modpack Version**: 1.0.2

* **Issue**: Crashed while going to the deep dark in creative on a single player world

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/ddfba5d4

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Unknown

* **Known Fix**: Not that I know of.

**Comment by aaronhowser1** [comment]
The Deep Dark Portal isn't craftable so it really isn't an issue for Continuum. You may want to post this to the [Extra Utilities 2 issue tracker](https://github.com/rwtema/Extra-Utilities-2-Source/issues) though

**Comment by tfox83** [comment]
The deep dark is disabled in Continuum.  As @aaronhowser1 said you may still want to post to ExU in case something is wrong on his end.  But I do have it disabled in the configs for the mod, so likely its crashing for that reason (although it shouldnt)
