### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by Honobe** [FTBTeam/FTB-Continuum#320]
* **Modpack Version**: 1.3.1

* **Issue**: Whenever I use a chest transporter on a YABBA barrel connected with an itemduct from thermal dynamics it will create an extra barrel (without the items of the original).

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: YABBA 1.1.2.9 and Thermal Dynamics 2.5.1.14

* **Known Fix**: Unknown

**Comment by Honobe** [comment]
BTW this doesn't seem to affect any other containers when I tried to recreate it with something else i.e. chests, drawers. It might work with something else that I am not familiar with.

**Comment by tfox83** [comment]
Fixed in 1.5.0
