### ISSUE TITLE
No recipe for Iron Band, so new ProjectE rings are uncraftable

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Continuum#322]
* **Modpack Version**: 1.4.0

* **Issue**: You can't craft Iron Bands, which the new ProjectE rings need. 
![image](https://user-images.githubusercontent.com/15698722/42549688-1e1fa7f0-8493-11e8-9cc1-645553227bf6.png)

Personally I think that the Archangel's Smite should be pretty expensive, it's pretty powerful. The Black Hole Band should also be pretty cheap or removed, as there are already item magnets that are a lot cheaper.

Covalance Dusts also have no recipe, so Divining Rods are uncraftable too.

**Comment by tfox83** [comment]
fixed in 1.4.1, also removed Divining Rods as they are useless in late game.
