### ISSUE TITLE
Coke dust cannot be made

### ISSUE THREAD

**Issue by s0hv** [FTBTeam/FTB-Continuum#323]
* **Modpack Version**: 1.4.0

* **Issue**: Coke dust cannot be made which makes crafting HOP graphite ingots impossible to make

* **Link to Log or Crash File Paste**: None
* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Coke dust is from Immersive engineering

* **Known Fix**: Worked in the previous version (1.3.1)

**Comment by sinfulkidd** [comment]
This seems to be linked to https://github.com/FTBTeam/FTB-Continuum/issues/314

**Comment by tfox83** [comment]
This is fixed in 1.4.1 hotfix
