### ISSUE TITLE
World loading screen stuck at 0%

### ISSUE THREAD

**Issue by Reeign** [FTBTeam/FTB-Continuum#326]
* **Modpack Version**: 1.3.1

* **Issue**: World loading scren stuck at 0%

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/1bf99334

* **Is it Repeatable?**: Occurs every time I try load the world. 

* **Mod/s Affected**: Whole pack?

* **Known Fix**: ?

**Comment by aaronhowser1** [comment]
Can you try updating to 1.4.0? Does this work on brand new worlds? Have you changed the pack at all (added/removed mods, changed configs, etc)?

**Comment by WilxGaming** [comment]
Modpack Version: 1.4.0

Issue: World loading screen stuck at 0%

Is it Repeatable?: 
It occurs after playing and pressing [Save and Quit to Title], when I try to restart with [Play Selected World]. It gets stuck at 0%. I must force the window closed with the [X] in the top right corner. Then reload the pack from Twitch and it works. But I must go all the way out to Twitch and reload the pack each time. The problem only started with 1.4.0

I have not changed the pack at all. I used a clean install and copied over my save game directory contents, options.txt and the Journeymap directory. I do use faithful32 as a resource pack.

**Comment by aaronhowser1** [comment]
Does it happen on brand new worlds? How much memory are you giving it?

**Comment by aaronhowser1** [comment]
Does it happen on brand new worlds? How much RAM are you giving the modpack?

**Comment by WilxGaming** [comment]
Created a brand new world. Same problem. 
I've allocated a little over 6GB Ram. Would more be better?

**Comment by aaronhowser1** [comment]
Install a new instance and see if it happens there too maybe. I can launch worlds in 1,4 no problem, maybe there was an issue installing it?

**Comment by WilxGaming** [comment]
Installed a new instance again. It came as 1.3.1 so I upgraded it to 1.4.0
I didn't change anything. No resource pack etc.
Created a new world with default settings.
After saving and trying to play it again, it got stuck at 0%.

**Comment by Reeign** [comment]
Wasn't a brand new world, haven't touched the modpack at all.
But with other worlds it works. For me I can't access the world at all, going to try 1.4.0

**Comment by Reeign** [comment]
Still didn't work

**Comment by aaronhowser1** [comment]
@Reeign Your world may have been corrupted. You could try looking for a backup of your world and using that (I don't have any backups in my instance so I don't know where they're stored, sorry)

**Comment by tfox83** [comment]
Tested this multiple times on two different systems and cannot reproduce, as aaron pointed out you may have a corrupt world, its rare but does happen with modded minecraft.
