### ISSUE TITLE
Item Translocators dissapear or make world unloadable

### ISSUE THREAD

**Issue by Aceslayer** [FTBTeam/FTB-Continuum#328]
version 1.4.0

I am trying to transfer my items with item translocators from an Enderchest into a YABBA item barrel controller which is connected to a bunch of item barrels (Main storage system). when i reload the world the item translocators are gone after a longer load than usual, i have recreated this situation about 5 times to be sure what was happening. After the 5th recreation the game would just crash on start up and say that it was having trouble tessellating blocks, I had to load up a backup version of the game to get back into my world.

Hopefully someone can find a solution untill then ill just use a different form of item transfer.
Thanks in advance.

**Comment by aaronhowser1** [comment]
Yeah, Translocators is unfortunately super buggy right now. I've had an issue where Translocators in certain chunks kept disappearing, but not the ones in other chunks. I ended up just changing to Transfer Nodes with speed upgrades, or high tier Ducts and Relays.

**Comment by tfox83** [comment]
This maybe fixed in 1.5.0 with latest version.  If not I will get this in as soon as the dev can fix it.
