### ISSUE TITLE
Void ore miner tier 2 using too much RF?

### ISSUE THREAD

**Issue by PooThee** [FTBTeam/FTB-Continuum#329]
Modpack Version**: <1.3.1 >

Issue: < I've set up 2 biodiesel gens, and when i connect a tier 2 void ore miner my power get instantly drained. ive tried to have it only connect to the void miner and the machines required for biodiesel generation (squeezer fermenter, refinery, 1 of each), and the power still get drained rapid. I'm aware they only make 1024rf/t but surely the tier 2 miner doesnt use that much rf/t?>

Is it Repeatable?: < Yes >

**Comment by Morganamilo** [comment]
A tier 2 ore miner used around 3.7k rf/t last time I checked.

**Comment by aaronhowser1** [comment]
Right click on Void Miners to see the amount of RF/t they drain.

**Comment by tfox83** [comment]
Two diesel gens would not be enough since their output is reduced in this pack.  You would need 4 or other power gen sources
