### ISSUE TITLE
Huge fps chops

### ISSUE THREAD

**Issue by Zumyumy** [FTBTeam/FTB-Continuum#33]
* **Modpack Version**:1.0.2

* **Issue**:Huge fps chops from 120-140 fps to 15-20 fps(about 80% chops) if i lower the fps limit to 60 i get drops to 5 and it only happens to the ftb packs(had same issue with revelation) playing exoria for example with constant 100 fps and no issues.
Using native launcher method on twitch
Tried to add more ram(4 gb ram/6gb ram same issue) 
specs:gtx 1050 intel i5 7th gen
Also tried disabling the minimap no change to issue.

* **Link to Log or Crash File Paste**: have a ss of the f3 screen with the spikes https://imgur.com/a/n60yHst

* **Is it Repeatable?**: yes

* **Mod/s Affected**: /
* **Known Fix**:Update to the latest java version and switch from native launcher to jar launcher in the twitch launcher.

**Comment by Sir-Will** [comment]
If you don't have the issue with Exoria you could compare the mods and remove the mods which are not in Exoria from Continuum to find which mod is causing it.

Did you add optifine? Optifine did reduce it for me in the Revelation pack.

**Comment by Zumyumy** [comment]
I didn't add optfine, I udapted java to the latest version in switched from native launcher method to the jar one and it fixed the problem.
Removing the mods will make you unable to play on some servers i guess :)
Ill udapte the known fix, and close the issue thanks :)
