### ISSUE TITLE
Advance RF Storage EFab still not contributing

### ISSUE THREAD

**Issue by statphantom** [FTBTeam/FTB-Continuum#330]
* **Modpack Version**: 1.4.0

* **Issue**: 

* **Link to Log or Crash File Paste**: NA

* **Is it Repeatable?**: yes

* **Mod/s Affected**: EFab

* **Known Fix**: NA

My EFab grid is still not getting RF/tick from advance RF storage. I am trying to make the ME controller which requires 8,000 RF/t and I have 8 Advance RF Storage and 10 regular RF Storages and it isn't letting me start crafting it.

I have tried replacing the RF storages, the power upgrade and the crafter itself, still not working.

**Comment by droidix** [comment]
This is currently a bug in the EFab mod: McJtyMods/EFab#15

**Comment by tfox83** [comment]
Disabled the block and added tooltip in JEI until this is fixed.

**Comment by tfox83** [comment]
Should be fixed in 1.5.0 (reenabled the block)
