### ISSUE TITLE
Oil Generator "Empty" Recipe not Obtainable

### ISSUE THREAD

**Issue by Amezylst** [FTBTeam/FTB-Continuum#333]
* **Modpack Version**: 1.3.1

* **Issue**: Placing AA Oil Generator in a crafting table [should empty the generator](https://github.com/Ellpeck/ActuallyAdditions/blob/21f179aab47ef9aa7f186b2c46b373538c59570a/src/main/java/de/ellpeck/actuallyadditions/mod/crafting/BlockCrafting.java#L120), but it does not

* **Is it Repeatable?**: Place an oil generator with fluid inside it in a crafting table

* **Mod/s Affected**: Actually Additions r135

* **Known Fix**: Insert the following line in powerGeneration.zs. Oil generator recipes are at line 29
`recipes.addShapeless(<actuallyadditions:block_oil_generator>, [<actuallyadditions:block_oil_generator>]);`

Tested this script change and it works

This is because the original oil gen recipes were removed, but the emptying recipe not reimplemented.

The same can be done for blockFluidPlacer and blockFluidCollector, but as far as I know this isn't necessary since their original recipes are used

**Comment by tfox83** [comment]
Fixed in 1.5.0, thanks
