### ISSUE TITLE
Team not getting credit for completed quests.

### ISSUE THREAD

**Issue by phrantick99** [FTBTeam/FTB-Continuum#335]
* **Modpack Version**: 1.14.1

* **Issue**: I have a multi-player server since the modpack came out. Until the recent release (not beta), everyone on the quest team has been getting credit for quests as they are completed. Now, no one on the team has been getting credit for completed quests.  Updated to the beta release that was done today for both server and client, still don't have the quests showing as completed in my book. 

There's also no way to admin complete them as I've done in other modpacks because there aren't quest numbers.

* **Is it Repeatable?**: reopen quest book--still sad.

* **Mod/s Affected**: Better Questing

* **Known Fix**: unknown

**Comment by Kuktar** [comment]
There are two commands on the left hand side of first quest tree. Called
it's like a whole new game. They are better questing commands. One is
called admin reload. Try those commands and see if they help.

**Comment by phrantick99** [comment]
I've tried both of those in the server like I'm playing and in the command prompt on our server computer--doesn't work. Also had the person that completed the quest do the same commands in the game and still doesn't update the quests to completed. 
Also tried the /bq_user refresh from the BetterQuesting Github and still doesn't update the quests. 
Boyfriend's quest book
![chrome_2018-07-12_22-41-17](https://user-images.githubusercontent.com/39253223/42669696-e2e74308-8624-11e8-884f-c4c07198105e.png)
My quest book:
![javaw_2018-07-12_22-41-34](https://user-images.githubusercontent.com/39253223/42669700-ea646ee4-8624-11e8-89be-5075a5bcc054.png)

**Comment by phrantick99** [comment]
So, we were thinking and came up with the idea of disbanding the team and reforming the team. When we did this, it worked and I now have the quest progress like my boyfriend does.
