### ISSUE TITLE
Cant play Continuum at all. Need help

### ISSUE THREAD

**Issue by jamesbauckman** [FTBTeam/FTB-Continuum#336]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
Is your Java up to date?

**Comment by tfox83** [comment]
Closing due to no response
