### ISSUE TITLE
v1.4.1 - Quest book categories are wrong

### ISSUE THREAD

**Issue by tjsd** [FTBTeam/FTB-Continuum#337]
* **Modpack Version**: 1.4.1

* **Issue**: Questbook categories have lost their "friendly name"

* **Is it Repeatable?**: reloaded default quest database but it still shows wrong, so yes it is repeatable.

![image](https://user-images.githubusercontent.com/7138125/42682510-148918da-868b-11e8-98ab-97bac0f5f96c.png)

**Comment by aaronhowser1** [comment]
Do you have the file \FTB Continuum\resources\continuum\lang\en_us.lang? All the quest names and description and title chapters are localized, and those right there are the unlocalized names for them. If you don't have that lang file, maybe try reinstalling onto a new instance.

Or you could download the base pack zip from [here](https://www.feed-the-beast.com/projects/ftb-continuum/files/2582097) and then take the lang file from \overrides\resources\continuum\lang\ and put it into the instance's folder.

**Comment by tjsd** [comment]
there is no such file on server install. Client side issue then?

**Comment by aaronhowser1** [comment]
I'm not sure if it needs to be on the server and the client. Does the client have that file on it? Do those work on new SP worlds? if it works on SP but not that server, try putting the lang onto the server and restarting it.

**Comment by tjsd** [comment]
seems the file were missing on local client, redownload of the pack in multimc fixed it.
