### ISSUE TITLE
AE2 Auto-Crafting Confusion

### ISSUE THREAD

**Issue by statphantom** [FTBTeam/FTB-Continuum#338]
* **Modpack Version**: 1.4.0

* **Issue**: not really an issue but there was no indication about the crafting multi-block in AE2 needed for the molecular assembler auto crafting etc. This really confused me and look me a while googling to understand it. I think on the page where you make the molecular assembler it would be much less confusing if you also put the crafting CPU multi-block on that quest on a next page and explain about it there. 

* **Link to Log or Crash File Paste**:

* **Is it Repeatable?** :yes

* **Mod/s Affected**: AE2

* **Known Fix**: explain a bit more :P

**Comment by aaronhowser1** [comment]
Oh wow, I actually completely forgot about that! I feel really silly, I'll make another quest to explain how they work, thanks!

**Comment by zenoran** [comment]
Wait, what? There is something that integrates with AE2 molecular assemblers? Any link or something that elaborates on this? I was just putting feedback on efab project about how lack of integration is what really makes this mod cumbersome from an automation perspective.

**Comment by aaronhowser1** [comment]
@zenoran What do you mean? You can use Interfaces with Molecular Assemblers to do regular crafting recipes, but nobody mentioned EFabs. You can use the Interface to automate the EFab though by putting the Interface onto an EFab's Item Storage block while it has a Crafter set to a recipe. I made a huge multiblock full of Crafters set to the TR Wires, then had an ME Interface connect to a bunch of Item Storages so I could craft them faster, for instance.

**Comment by zenoran** [comment]
Okay I was clearly confused he meant just AE2 since I figured that setup was common knowledge. My bad!  My whining about efab on curseforge remains valid. Lol
