### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by kuniak9977** [FTBTeam/FTB-Continuum#339]
Hello.  I was receiving the following crash during launch.

* **Modpack Version**: On each version newer than 1.2.1

* **Issue**: I try to launch the modpack when crash appear.

* **Link to Log or Crash File Paste**: https://pastebin.com/5X1wAfp2

* **Is it Repeatable?**: On each launch

* **Mod/s Affected**: Probably CodeChicken lib

* **Known Fix**:  N/A

**Comment by aaronhowser1** [comment]
Are you using the Twitch launcher? Can you try reinstalling Continuum 1.4.1 onto a new instance?

**Comment by kuniak9977** [comment]
Yes I use Twitch app. I reinstall modpack several times and still didn`t work.

**Comment by kuniak9977** [comment]
Every time when I launch modpack and progression bar of initialization will load to CodrChicken LiB then crash occur.

**Comment by kuniak9977** [comment]
Just update codechicken lib to the 3.2.1 version and works. LOL
