### ISSUE TITLE
Typo in the EFab-ulous Quest

### ISSUE THREAD

**Issue by mynameispig123** [FTBTeam/FTB-Continuum#34]
* **Modpack Version**: 1.0.2 

* **Issue**: There is a typo in the text: "...to the multiblock instead **of of** upgrade put into the machine GUI"

![2018-05-18_16 04 33](https://user-images.githubusercontent.com/32813480/40223475-c01185ae-5ab5-11e8-97e0-d64038f5c53d.png)

**Comment by aaronhowser1** [comment]
Fixed for next update
