### ISSUE TITLE
Re-enable Autosmelt/luck for TiCon tools

### ISSUE THREAD

**Issue by rdb101** [FTBTeam/FTB-Continuum#340]
* **Modpack Version**: 1.3.1

* **Issue**: Need help reenabling autosmelt/luck for TiCon tools which was disabled in an earlier update

* **Link to Log or Crash File Paste**: None
* **Is it Repeatable?**: N/A

* **Mod/s Affected**: Tinker's Construct

* **Known Fix**: Unknown to myself, could not find any info.

**Comment by aaronhowser1** [comment]
in tconstruct.cfg, the option `B:AutosmeltFortuneInteraction=false` needs to be changed to true for it to work.
