### ISSUE TITLE
Single player world stuck in loading screen at 0%

### ISSUE THREAD

**Issue by Obtrusive** [FTBTeam/FTB-Continuum#341]
* **Modpack Version**: 1.3.1

* **Issue**: When I log into a single player world that I previously worked on it gets stuck in the loading screen at 0% and wont progress any more. Creating a new world and reloading that in singleplayer still works, its just this one world that cant be loaded.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**:  Yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by ghost** [comment]
Had the same issue. Badly i didnt saved the log file. But i can remember some content. Immersive Engineering had cause the error as far as i remember. This caused a server stop and the loading screen stucked at 0%.
My World creation options were: Creativ; Superflat; Structures off.

**Comment by Prometheus0000** [comment]
I have a similar problem in 1.4.1. When loading a world the first time it works properly, but exiting and trying to load that world or another causes it to get stuck at the loading screen at 0%.

World loading properly [latestA.log](https://github.com/FTBTeam/FTB-Continuum/files/2195674/latestA.log)
World fails to load [latestB.log](https://github.com/FTBTeam/FTB-Continuum/files/2195675/latestB.log)

It seems it's either IE as mentioned, or maybe Journeymap

**Comment by Prometheus0000** [comment]
After reading #356, I tried using the updated IE, and it loaded the worlds properly, even after entering and exiting multiple times.

**Comment by MegaRad24** [comment]
This is happening to me and I am not sure how to fix it any help?

**Comment by tfox83** [comment]
Fixed in  1.5.0 Beta
