### ISSUE TITLE
Wireless charging issue 

### ISSUE THREAD

**Issue by Ravalli03** [FTBTeam/FTB-Continuum#342]
* **Modpack Version**: v1.4.1 

* **Issue**: using the Flux mod for power, the wireless charging no longer works for the AE2 wireless CRAFTING terminal using 1.4.1. It work fine using v1.3.1

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Wireless crafting terminal and Flux networks

* **Known Fix**: unknown

**Comment by aaronhowser1** [comment]
Does it only happen when it's in your baubles slot? I don't think that Flux Networks charges those slots.

**Comment by Ravalli03** [comment]
It does charge baubles slot, but in my case I use the terminal in my hot bar. You can turn on/off any area of your inventory to what you want charged in the flux network controller block interface. I have done more testing and it actually doesn't charge any item in any slot anymore using v. 1.4.1

**Comment by Ravalli03** [comment]
It looks like an issue with Flux network mod. 

https://github.com/SonarSonic/Flux-Networks/issues/247

**Comment by Dragon87tamer** [comment]
The issue is fixed from sonar..which means the modpack needs updating to fix the issue arising in the modpack

**Comment by tfox83** [comment]
Fixed in 1.5.0
