### ISSUE TITLE
Bug (Dupe) with Steve Carts Assamber with Modifier Upgrade

### ISSUE THREAD

**Issue by freytastiQ** [FTBTeam/FTB-Continuum#343]
Modpack Version: 1.3.1

Issue: I m using the Cart Assembler with the Upgrade: Cart Modifier to modify the Cart. If i put the cart in the modifier slot and break the Assambler i get the cart back plus all installed things (drill, engine, addon, attachments)

Link to Log or Crash File Paste:

Is it Repeatable?: yes working on multiplayer server and single player

Mod/s Affected: Steve Carts 2

Known Fix: Don´t break the Assembler

**Comment by tfox83** [comment]
Ill have @modmuss50 take a look at this when he has time, thanks for the report

**Comment by modmuss50** [comment]
Fixed, I will push a new version now

**Comment by tfox83** [comment]
Fixed in  1.5.0 Beta
