### ISSUE TITLE
RF Tools Inventory checker crash

### ISSUE THREAD

**Issue by V8gaming** [FTBTeam/FTB-Continuum#346]
* **Modpack Version**: 
1.3.1
* **Issue**: 
Game crashed after opening RFTools Inventory Checker's GUI.
* **Link to Log or Crash File Paste**:
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen
* **Is it Repeatable?**: 
Yes.
* **Mod/s Affected**: 
RFTools.
* **Known Fix**:

**Comment by tfox83** [comment]
Fixed in 1.5.0
