### ISSUE TITLE
Thermal Dynamics servo not working

### ISSUE THREAD

**Issue by V8gaming** [FTBTeam/FTB-Continuum#347]
* **Modpack Version**: 
1.3.1
* **Issue**: 
Thermal Dynamics servo still works even though it has redstone functions on the garden cloche

* **Is it Repeatable?**: 
Yes.
* **Mod/s Affected**: 
Thermal Dynamics
Immersive Engineering

**Comment by tfox83** [comment]
Could not repeat.  Try 1.5.0 when released.
