### ISSUE TITLE
Natura Planks give too many sticks.

### ISSUE THREAD

**Issue by triggerfinger12** [FTBTeam/FTB-Continuum#35]
* **Modpack Version**: 1.0.2

* **Issue**: When crafting sticks with Natura planks, the output is 4 sticks instead of the intended 2.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Natura  v4.3.2.49

* **Known Fix**: Change Recipe

**Comment by EthanlifeGaming** [comment]
![desktop screenshot 2018 05 18 - 14 50 42 39](https://user-images.githubusercontent.com/37051567/40259449-ffe955f4-5aaa-11e8-853b-07320afe1e3f.png)

soooo erm are you positive?

**Comment by EthanlifeGaming** [comment]
Nvm

**Comment by tfox83** [comment]
fixed in next update
