### ISSUE TITLE
Crash when using Move Items for Antenna

### ISSUE THREAD

**Issue by Degenerecy** [FTBTeam/FTB-Continuum#350]
- Modpack Version: 1.4.1

- Issue: Game crashes when using move items(the +) in recipe mode.

- Link to Log or Crash File Paste: 
https://paste.feed-the-beast.com/view/d6ccca6f

- Is it Repeatable?: Yes, happens every time I click the + icon when attempting to craft the Antenna.

- Mod/s Affected: Extra Utilities 2, JEI(I think, or w/e handles crafting recipe)

- Known Fix:  Manual Crafting of the item is only work around.

**Comment by tfox83** [comment]
Known issue, if this is fixed ill get the update in ASAP, thanks
