### ISSUE TITLE
Extra Utilities 2 speed upgrade bug

### ISSUE THREAD

**Issue by statphantom** [FTBTeam/FTB-Continuum#351]
* **Modpack Version**: 1.4.0

* **Issue**: when adding speed upgrade to an extra utilities block such as item transfer node it doesn't update the new amount, you have to remove all the upgrades and re-add them back. This seems like an extra utilities 2 bug but unsure.

* **Link to Log or Crash File Paste**: NA

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Extra Utilities 2

**Comment by tfox83** [comment]
Known issue, if ever fixed will get into modpack ASAP
