### ISSUE TITLE
Server Problems

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Continuum#352]
* **Modpack Version**: 1.4.1
* **Issue**: Friends cannot connect to hamachi server

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/efa99476

* **Is it Repeatable?**: Yes it happens always

* **Extra added mods**: DankNull, Aroma1997Core, Aroma1997s-Dimensional-World.

* **Mod/s Affected**: I don't really know

* **Known Fix**: Maybe it is problem with hosting or something

**Comment by Morganamilo** [comment]
Have you considered just plain port forwarding? It's less of a headache to set up.

**Comment by ghost** [comment]
mmm... sorry what plain port forwarding is?

**Comment by aaronhowser1** [comment]
Port forwarding basically lets your computer be accessed over the internet, so you don't need to use Hamachi or anything.

**Comment by ghost** [comment]
yeah it's OP thing

**Comment by ghost** [comment]
but less secure

**Comment by ghost** [comment]
by the way how can i do that port forwarding?

**Comment by tfox83** [comment]
closing this issue as its not modpack related.  Have a look on the Minecraft forums or post your question there about port forwarding.
