### ISSUE TITLE
Compartment block bug

### ISSUE THREAD

**Issue by CG-Matt** [FTBTeam/FTB-Continuum#353]
When you place a compartment beside a crafting table from Tinkers Construct it replaces the items in your hot bar with the items from the first tab. or if you place a tool workstation from Tinkers Construct beside the compartment block it glitches out your inventory.

**Comment by aaronhowser1** [comment]
Yeah the Compartments are notoriously buggy.

**Comment by tfox83** [comment]
No know fix at this time.
