### ISSUE TITLE
AE2 staffs drops

### ISSUE THREAD

**Issue by BeckLouis1999** [FTBTeam/FTB-Continuum#354]
* **Modpack Version**: 1.3.1

* **Issue**: AE2 advanced inscriber drops after a while and i dont know why

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
Yeah AE2 Stuff is notorious for blocks dropping when they're part of a system with a Security Terminal and the chunk loads. Basically, keep those on their own system, don't have them connected to your main one. 

bdew/ae2stuff/issues/190

**Comment by tfox83** [comment]
If this is ever fixed I will get it in the next update, thanks
