### ISSUE TITLE
Continuum crashes when loading world

### ISSUE THREAD

**Issue by Razvcrist** [FTBTeam/FTB-Continuum#356]
* **Modpack Version**: 

* **Issue**: 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Razvcrist** [comment]
After downloading the new version of the Feed The Beast Continuum I opened the launcher. When I wanted to open my world the game kept crashing .What should I do??

**Comment by t0suj4** [comment]
Replace Immersive Engineering 0.12 - 83 with [0.12 - 84](https://minecraft.curseforge.com/projects/immersive-engineering/files/2583282)

**Comment by Razvcrist** [comment]
Thank you

mie., 18 iul. 2018, 11:32 t0suj4 <notifications@github.com> a scris:

**Comment by tfox83** [comment]
Fixed in  1.5.0 Beta
