### ISSUE TITLE
Cannot Craft Essence of the Scornful Oblivion

### ISSUE THREAD

**Issue by superdbk** [FTBTeam/FTB-Continuum#359]
* **Modpack Version**: 1.4.0
* **Issue**: Cannot Craft Essence of the Scornful Oblivion. JEI shows craftable item, however no matter what table I use the output is blank.

* **Link to Log or Crash File Paste**: No Crash

* **Is it Repeatable?**: Everytime

* **Mod/s Affected**: MagicBees

* **Known Fix**: Noticed on another forum that it has been fixed in the latest version of Magic Bees.
(https://forum.feed-the-beast.com/threads/cannot-craft-essence-of-scornful-oblivion.264641)

**Comment by tfox83** [comment]
Fixed in  1.5.0 Beta
