### ISSUE TITLE
Railgun "randomly" loses mods

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Continuum#360]
* **Modpack Version**: 1.4.1

* **Issue**: Immersive Engineering - The railgun is able to have 2 modifications to it. However they seem to not save properly, after a while (I don't know the reason why) the mods are just gone if I check again

![capture](https://user-images.githubusercontent.com/30607152/42921549-c13b5346-8b1c-11e8-9187-33f88e79b9df.PNG)

* **Is it Repeatable?**: Not directly but it happened very often so probably yes.

* **Mod/s Affected**: Immersive engineering

* **Known Fix**: The shader is unaffected. Look at the code differences of those 2 properties maybe (?)

**Comment by tfox83** [comment]
Fixed in 1.5.0
