### ISSUE TITLE
space station not producing items once built

### ISSUE THREAD

**Issue by statphantom** [FTBTeam/FTB-Continuum#361]
* **Modpack Version**: 1.4.0

* **Issue**: according to guides once you scan then build a space station which then produces a programmed ID chip and a space station container however when I press build, it builds but when finished the satellite bay and the chip completely disappear. the scan does not show any errors, says ready to build.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Advance Rocketry

* **Known Fix**:

**Comment by tfox83** [comment]
Known issue with Adv Rocketry, if this is fixed ill get the update in ASAP, thanks
