### ISSUE TITLE
advanced rocketry rolling machine bugged

### ISSUE THREAD

**Issue by kamrantekkit** [FTBTeam/FTB-Continuum#363]
modpack version: FTB continuum 1.4.1

Issue: Everytime i put advanced alloy ingots in the rolling machine to make advanced alloy plates they dissapeared

repeatable: maybe remaking the multiblock structure fixes it

**Comment by statphantom** [comment]
There are two inputs and two outputs, but the inputs don't really correlate to the outputs, try checking the different output blocks, also if using lower tier coils it might be slow so check if the rolling mechanism in the center is rolling and you see a sheet moving.

**Comment by kamrantekkit** [comment]
i use the iridium coils and the elite motor but i checked the output hatches  and nothing is there. i also made sure the machine is working
