### ISSUE TITLE
lanching satellite crashed game now wont open

### ISSUE THREAD

**Issue by statphantom** [FTBTeam/FTB-Continuum#367]
* **Modpack Version**: 1.4.1

* **Issue**: after launching a manned rocket with a satellite the game crashed and now wont open. I have heard that this is a known bug in advanced rocketry with manned rockets with satellite but any way I can get the game loading again?

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/07abaf70

* **Is it Repeatable?**: yes

* **Mod/s Affected**: advance rocketry

**Comment by Ravalli03** [comment]
Same bug issue as #348

**Comment by tfox83** [comment]
Known issue with Adv Rocketry, if this is fixed ill get the update in ASAP, thanks
