### ISSUE TITLE
returning to earth on rocket ship bug

### ISSUE THREAD

**Issue by statphantom** [FTBTeam/FTB-Continuum#368]
* **Modpack Version**: 1.4.1

* **Issue**: when going from the moon to earth the spaceship spawns at 0 and when you descend you just fall through the world for ages then spawn at 0 inside rocks and the ship disapears, this also bugs the rocket assembly machine and you need to break and replace it.

* **Link to Log or Crash File Paste**:

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Advance rocketry

* **Known Fix**: NA

**Comment by DerSoftwerker** [comment]
In my case I also spawned in bedrock and fell through the world after destroying the blocks above me.

**Comment by Bizuex** [comment]
Had the same issue. Managed to /home but lost rocket.

**Comment by Jadoz** [comment]
Same problem here.  Problem occurs after dimension switch back to Earth: as soon as descent begins, either by pressing space or timeout, the ship displays disappear and I end up at loc 0,0,5.  From there I either die or /home with loss of ship.  Keen to see a solution so I can continue this modpack, which I am thoroughly enjoying.

**Comment by tfox83** [comment]
Known issue.  If its ever fixed I will get the udpate in ASAP, thanks
