### ISSUE TITLE
Fluid Duplication

### ISSUE THREAD

**Issue by pred1990** [FTBTeam/FTB-Continuum#369]
Modpack Version: 1.4.1

Issue: Fluid Duplication,

The Semi fluid Generator takes any capsule or can(thats not from Tech Reborn) and wont use them up. 
Instead it will duplicate the fluid.

Is it Repeatable?:  yes, possible with any fluid

Known Fix: no known fix

**Comment by Brend-Smits** [comment]
I can confirm this is still an issue in the latest version of Continuum

**Comment by tfox83** [comment]
will tag @modmuss50 is this
THanks

**Comment by modmuss50** [comment]
ok, ill take a look when I get a chance. Thanks
