### ISSUE TITLE
Include TexFix

### ISSUE THREAD

**Issue by midorlo** [FTBTeam/FTB-Continuum#37]
TexFix by Speiger: https://minecraft.curseforge.com/projects/texfix

>Reduce the memory footprint of your textures

Named mod had a tremendously beneficial impact on the memory requirements of every modpack I yet created or used. The author, who also made Fastcraft is reputable. I yet added the mod to my local instance of FTB-Continuum and faced no issues yet. 

-> Please consider evaluating said mod for this modpack. Succesfully reducing the average memory requirements for the modpack instance - which undoubtly rose drastically with >=1.8 - will widen the potencial audience and improve the user experience on just capable systems.

**Comment by mezz** [comment]
Speiger made TexFix, Player made Fastcraft.

TexFix is only helpful if you have large-size textures  (32x or 64x). For normal 16x it is not really beneficial.

**Comment by tfox83** [comment]
Feel free to add this yourself, but at this time I will not add it to the pack. Thanks for the suggestion.
