### ISSUE TITLE
Purple slime ?

### ISSUE THREAD

**Issue by Thyriel** [FTBTeam/FTB-Continuum#370]
* **Modpack Version**: 1.4.1

* **Issue**:
Did you change how to obtain purple slime or reduced the droprate extremely ?
I destroyed leaves from like ~30 grown purple slime trees and not a single purple slime droped yet. As knightslime ingot is needed for the slimesling quest and i don't see any other way of making knightslime i would guess there should be a way to obtain them.

**Comment by aaronhowser1** [comment]
I've gotten Purple Slime before, so I don't think it was changed. Maybe you just got really unlucky?

**Comment by Thyriel** [comment]
Installed JEI blockdrops and that doesn't show them being droped from purple slimy leaves, only sapling being droped.

**Comment by aaronhowser1** [comment]
The purple sapling makes a purple slime tree right? That purple slime tree has purple slime blocks, while the naturally spawning trees have green slime blocks I think.

**Comment by Thyriel** [comment]
No, both have green slime blocks as tribe. The leaves should drop the slime balls.

**Comment by Hazmatik** [comment]
some of the slime islands have purple slime blocks, usually the same island you find the purple trees on

**Comment by tfox83** [comment]
You have to find a purple slime island.
