### ISSUE TITLE
Infinite copper and other materials

### ISSUE THREAD

**Issue by Neophos** [FTBTeam/FTB-Continuum#371]
* **Modpack Version**: FTB Continuum 1.3.1

* **Issue**: Using a single Copper Ingot, you can create two copper casings in the Metal Press. Each copper casing becomes one Copper Ingot in the Tinker's Construct Smeltery. Thus you can create infinite copper, and using the Industrial Centrifuge, you can turn these into infinite gold, iron, nickel and possibly other materials as well. This feels like an oversight and not an intentional design.

* **Known Fix**: Make each copper casing become 4 nuggets of copper in the smeltery.

**Comment by tfox83** [comment]
removed casing from smeltry in 1.5.0
