### ISSUE TITLE
world disappearing 

### ISSUE THREAD

**Issue by harpo545** [FTBTeam/FTB-Continuum#372]
* **Modpack Version** 1.4.1

* **Issue**: my world isint showing up anymore, ive taken it out of the save files and put it back in multiple times, other worlds can be taken out and put back in just fine but the world i play on isint showing up anymore

* **Is it Repeatable?**: yes very

**Comment by aaronhowser1** [comment]
Make a new world and compare the two folders. Is there something missing in the old one? Maybe something got deleted and now the game doesn't recognize it as a world anymore.
