### ISSUE TITLE
advanced rocketry unmanned vehicle timer 

### ISSUE THREAD

**Issue by kamrantekkit** [FTBTeam/FTB-Continuum#373]
version: FTB Continuum 1.4.1

Issue:every time i launch a unmanned vehicle. i check the rocket monitoring station the time is in negative numbers and keeps going down

* **Is it Repeatable?**: yes it is repeatable

**Comment by tfox83** [comment]
Known issue with Adv Rock, will update as soon as a fix is released, thanks
