### ISSUE TITLE
Natura berries are in the wrong food group

### ISSUE THREAD

**Issue by SpectacularNumbers** [FTBTeam/FTB-Continuum#375]
* **Modpack Version**: 1.4.1

* **Issue**: When hovering over the Natura berries (Raspberry, Blueberry, Maloberry, Blackberry), the tool tip says the berries are part of the fruit group as well as the _Raw Meat_ food group.

* **Is it Repeatable?**: Yes. Opening a new world creates the same issue.

* **Mod/s Affected**: Natura, Spice of Life

* **Known Fix**: Remove the Natura berries from the Raw Meat food group.

**Comment by asphaltbuffet** [comment]
This also prevents using those berries to create Fruit Bait for traps.

**Comment by asphaltbuffet** [comment]
Looking through the spice of life config (`/config/spiceoflife/raw_meat.json`), the trouble is here:

`      "natura:edibles",`

Replacing that line with:

`"natura:edibles:0",`

Will single out the Raw Imphide and group things appropriately.

**Comment by tfox83** [comment]
fixed in 1.5.0, thanks for the report
