### ISSUE TITLE
Stall / Crash of server, not sure how to reproduce it, possibly on player death

### ISSUE THREAD

**Issue by Alckor** [FTBTeam/FTB-Continuum#38]
* Version **1.0.2**: 

* **Issue**: Server Crash / Stall

* **Link to Log or Crash File Paste**: 

I went to sleep at midnight, with 1 player still left online, 20 minutes later he reported getting dc'd.

Got back from work today with a few stalls warning in the console. I pressed enter to have this appear : 

[17:53:34] [Server Watchdog/FATAL] [net.minecraft.server.dedicated.ServerHangWatchdog]: Considering it to be crashed, server will forcibly shutdown.

Crash Report mentions null pointer in codechicken wireless redstone but my world does not have anything made of redstone yet.

might we worth saying that other player tried connecting a few times during the day without success. so the server has been either stalled or crashed since that time. ~midnight 

Server Log  of when crash happened: https://pastebin.com/YkkQquQ4

Stall Report : https://pastebin.com/LkJ44vuT

Crash Log : https://pastebin.com/wktB1QSG

* **Is it Repeatable?**: Server is working fine after starting it again, will report back if it happens again

* **Mod/s Affected**: No idea

* **Known Fix**: None Sorry :( other than rebooting the server

**Comment by jc2xs** [comment]
So the crash report says you are running the server with only 2GB of RAM.  You may want to try and boost that up a little and see if that also fixes the issue.  Not sure if that is the issue or not.  But I've never run any 1.12 packs at 2GB.  I've always used more than 4GB for my servers.

**Comment by Alckor** [comment]
You're making a good point! This machine has 32GB so I can definitely bump that up.

I left the default configs that come with the server download. If that's the issue then perhaps it is a good idea to bump the default values up for everyone else who will download it in the future

**Comment by 016Nojr** [comment]
@Alckor I'll close it for now, but if it happens again with more RAM dedicated, ping me and I'll reopen the issue.

**Comment by Alckor** [comment]
@016Nojr Happened again during the night after bumping it up to 8GB. This time nobody was playing.

I also updated java from 1.8.171 to 1.8.172 to make sure it was not that.

Crash Log : https://pastebin.com/xFzkCivU

Stall Report : https://pastebin.com/EnimSebJ

**Comment by Alckor** [comment]
I just made a few additionnal check ups on my setup. Checked Windows 10 Power Options to make sure it was not some stuff turning off when I go off my computer. 

All sleep / drive sleep options were already turned off.

**Comment by jc2xs** [comment]
Another little tidbit since this is the server watchdog error. Edit the server.properties file and change max-tick-time to -1 instead of 6000.  Might want to make sure you are restarting the server at least once a day as well.
