### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by faustorfs** [FTBTeam/FTB-Continuum#380]
* **Modpack version**: <12.2>

* **Issue**: <Can't login. I'm sure i have the right information. It sugests that i check if i'm online (where?) and if minecraft is blocked (blocked where? i play minecraft normally on my computer)>

**Comment by aaronhowser1** [comment]
Can you log in to other modpacks? This probably isn't a modpack issue.

**Comment by faustorfs** [comment]
No.
This is what it says when i can't log in:
![captura de ecra 2018-07-26 as 09 16 03](https://user-images.githubusercontent.com/41701666/43250286-e8691d7a-90b4-11e8-8bf2-08c35eb1b074.png)

**Comment by aaronhowser1** [comment]
Try logging in to vanilla Minecraft. If that works, try the modpack again. Otherwise. it's a problem with either your internet or the Minecraft servers, neither of which we can really help with.

**Comment by faustorfs** [comment]
yes i can play vanilla and multiplayer normally. I tryed that and it still doesn't work...

**Comment by aaronhowser1** [comment]
Are you using the Twitch Launcher, MultiMC, or the legacy launcher?

**Comment by faustorfs** [comment]
i'm using the twitch one

**Comment by Tandorius** [comment]
Sometimes i have the same issue. Then i login at the minecraft website and the i can login to the launcher. Dunno why.

**Comment by tfox83** [comment]
This is not a FTB issue.
