### ISSUE TITLE
distillation tower not taking in oil

### ISSUE THREAD

**Issue by aspryin** [FTBTeam/FTB-Continuum#381]
Modpack Version 1.4.1    :   14.23.4.2730

I can not get oil into the distillation tower to create any of the products.(diesel, gasoline, lubricant). I have tried fluid ducts w/ servos. liquid pipes. tanks with levers... power or no power ( I believe you need power to process it but not to input the raw oil) I have tried with a configured IE pump powered. in all cases I can put a fluid tank or drumb and collect liquid through the pipes right up to the input hatch on the distillation tower. but the raw oil will not go into the tower.

* **Link to Log or Crash File Paste**: no crash file.

![2018-07-26_21 33 37](https://user-images.githubusercontent.com/28640795/43297082-282f752c-911d-11e8-9607-5254764b661e.png)

Repeatable: yes I can not get the oil in.

* **Known Fix**:    none

**Comment by aaronhowser1** [comment]
Is it Immersive Petroleum's Crude Oil or is it Thermal Foundation's?

**Comment by aspryin** [comment]
did not realize there was a difference standby... I got it from the black gold planet. ill check soon

**Comment by aaronhowser1** [comment]
The Black Gold planet uses TF's oil I think, which unfortunately means it can't be processed. We've tried making it so that you can convert between the two with IF, but the IP oil isn't very easy to work with as far as scripting goes.

**Comment by aspryin** [comment]
It is for sure the Termal Foundations oil on the liquid gold planet. your saying I need IP then... ok! thanks for the fast response.

**Comment by tfox83** [comment]
This is a known bug that doesnt have a fix atm.  IF there is a fix I will get it in ASAP
