### ISSUE TITLE
Chisel client crash - Tesselating block model

### ISSUE THREAD

**Issue by Tandorius** [FTBTeam/FTB-Continuum#382]
* **Modpack Version**: 1.4.1

* **Issue**: Since the last update to Continuum 1.4.1 the client crashed very often. Seems to be an issue with chisel. Its not only the Block: chisel:laboratory[variation=2], also others like Andesite or GRanite which processed with Chisel.

* **Link to Log or Crash File Paste**: 
https://pastebin.com/7Wsj817Y

* **Is it Repeatable?**: It happens while i dont do anything specific

* **Mod/s Affected**: Chisel

* **Known Fix**: Don't use Chisel

**Comment by tfox83** [comment]
This has been fixed in latest update, 1.5.0
