### ISSUE TITLE
No generation of RF with Kinetic Dynamo

### ISSUE THREAD

**Issue by alchimyste** [FTBTeam/FTB-Continuum#384]
Hello,

Beug no generation of RF with Kinetic Dynamo, both with water whell and with the windmill.

Modpack Version: 1.4.1 via the Twitch launcher locally without adding a mod

Issue: No RF

* **Link to Log or Crash File Paste**: No Crash No Log :)

Is it Repeatable?: Yes

* **Mod/s Affected**:  Immersive Engineering Version 0.12-83

Sorry for my english, i'm french ^^

**Comment by aaronhowser1** [comment]
Can you show some screenshots of them? The Kinetic Dynamo might be facing the wrong direction, or the RF could be piping out the wrong face.

**Comment by alchimyste** [comment]
Hi, I post the screenshots ask with the different possible positions for the demonstration. I want to point out that I'm not at my first modpack with Immersive Engineering

![2018-07-29_06 29 56](https://user-images.githubusercontent.com/41839782/43362986-dd872730-92f8-11e8-84cd-213a08ef2847.png)

![2018-07-29_06 10 12](https://user-images.githubusercontent.com/41839782/43362989-fbcabd4c-92f8-11e8-9d65-fd5a9c984974.png)

![2018-07-29_06 12 30](https://user-images.githubusercontent.com/41839782/43362955-0612c354-92f8-11e8-9cbd-d652eed16c7a.png)

**Comment by lglare** [comment]
Did you place Kinetic Dynamo first?
If Water Wheel first, its not working.

**Comment by alchimyste** [comment]
résolu

I started a new game and the miracle everything works :)
I suppose a corruption of my part when I had a crash loading the map.

Thanks all the same for the help, good luck !!
