### ISSUE TITLE
Immersive Petroleum Can't Install Mods to Motoboat While Playing on Server

### ISSUE THREAD

**Issue by beldroy** [FTBTeam/FTB-Continuum#385]
* **Modpack Version**: 1.4.1

* **Issue**: Can't install mods to Motorboat from "Immersive Petroleum"while playing on server but there is no problem with this while playing in singleplayer.

* **Is it Repeatable?**: It is repetable while on server.

**Comment by tfox83** [comment]
This has been reported, as soon as a fix is out I will get it in the pack ASAP
