### ISSUE TITLE
AE Quantum Rings unusable without AE2 Cells

### ISSUE THREAD

**Issue by ZeekDaGeek** [FTBTeam/FTB-Continuum#386]
**Modpack Version**: FTB Continuum 1.4.1

**Issue**: It's impossible to use Applied Energistic's Quantum rings without the Energy cells, I'm not to sure why they're even disabled, they don't allow you to import power from any other mods other than the ME Controllers and Energy Acceptors.

Quantum rings take over 400 RF/t to power and Acceptors will only accept as much as there's storage in the network, so they can never be turned on.

This is a major issue considering the fact that the larger your AE network the laggier it ends up being, using quantum rings means less wire calculations have to happen and Applied Energistics really doesn't like running into chunks that are unloaded, especially with P2P networks, they will spam the console and cause massive TPS issues.

![Power Usage](http://zeekdageek.tv/ss/w3Vhp.png)

Also how the hell am I supposed to Spatial I/O without any way to store the power required to activate a Spatial I/O Port.

**Mod/s Affected**: Applied Energistics / Craft Tweaker

**Known Fix**: Put the recipe back.

**Comment by aaronhowser1** [comment]
I used a Controller on the other side with the Quartz Fibre things (the ones that transmit power, not channels). Although, I also think that AE2 Energy Cells should be reenabled.

**Comment by tfox83** [comment]
The intended work around is using a controller for the power.  The AE2 energy cells are disabled by default.
