### ISSUE TITLE
Land of the red Blood Recipe wrong

### ISSUE THREAD

**Issue by meriweather2** [FTBTeam/FTB-Continuum#387]
* **Modpack Version**: 1.4.1

* **Issue**: Land of the red Blood Recipe wrong
States to use 2 Destabilised Redstone Ore 
should be Destabilised Redstone Ore, Redstone Plate, Resonating Redstone Crystal, Redstone and one normal Redstone Ore 

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: 

* **Mod/s Affected**: Advanced Rocketry 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
Is this a quest issue? Or is the recipe from scanning planets?

**Comment by meriweather2** [comment]
Both 
in the quest book it states to use 2 x Destabilised Redstone Ore, Redstone Plate, Resonating Redstone Crystal and Redstone as artefacts to scan for the planet and warp to it.

it Should be
Destabilised Redstone Ore, Redstone Plate, Resonating Redstone Crystal, Redstone and one normal Redstone Ore
