### ISSUE TITLE
Smeltery and Redstone Torches crashes the server/game

### ISSUE THREAD

**Issue by Neophos** [FTBTeam/FTB-Continuum#388]
* **Modpack Version**: 1.3.1

* **Issue**: When paired together with certain blocks such as the Redstone Clock in close proximities, the Smeltery Controller will "eat" any Redstone Torches placed on it. These torches will not be active or visible, and you will regain them when you destroy the Redstone Clock. However, attempting to place a torch on a faucet or destroying a block from the smeltery will crash the server with an error about the placement of a multiblock. Image example: https://i.imgur.com/mHkhZ3r.png If I place a Redstone Torch on the Controller here, it would disappear, and the game would crash if I broke a Seared Brick.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: Easily repeatable.

* **Mod/s Affected**: Tinker's Construct.

**Comment by tfox83** [comment]
This has been reported before to the dev.  If a fix is released I will get it in the modpack ASAP.
