### ISSUE TITLE
Immersive Engineering's Wires recipe Slow

### ISSUE THREAD

**Issue by W1nt3rR** [FTBTeam/FTB-Continuum#389]
* **Modpack Version**: 1.4.1

* **Issue**: Immersive Engineering's Metal Press is too slow for making Copper Wires (and other Wires) needed for Electronic Circuits (from Tech Reborn).

I wanted to make a large number of Electronic Circuits and then realized that Metal Press is the bottleneck. Why would anyone use the EFab recipe, which takes roughly 10 seconds and uses more Copper, if Empowerer recipe is much faster, about 4 seconds, and doesn't use Copper?

Someone would maybe say: "Make more Metal Presses", well, why not make more Empowerers?

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: Immersive Engineering

* **Known Fix**:  Make a faster way to make Immersive Engineering Wires.

**Comment by tfox83** [comment]
Intended
