### ISSUE TITLE
Server Crash - net.minecraft.item.ItemAir cannot be cast to squeek.spiceoflife.items.ItemFoodContainer

### ISSUE THREAD

**Issue by ThorVonAwesome** [FTBTeam/FTB-Continuum#39]
* **Modpack Version**: FTB Continuum 1.0.2

* **Issue**: An unknown set of criteria is leading the server to think that a player is trying to insert a block of air into an food container from Spice of Life and crashes when the type cast fails. This has happened twice in the span of ~1.5 hours. Server was operating above 17TPS at the time, and there were 8 players on the server. All players present before the crash came back on line so I asked everyone to do exactly what they were doing before the crash and no crash occurred. If there are any additional questions please let me know. 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/d9572a20

* **Is it Repeatable?**: Yes and No. It has happened twice today on my server, however when the players do what they were doing before the crash the server did not crash. So it's repeatable in that it has happened more than once, however the criteria leading to the event are still under investigation. 

* **Mod/s Affected**: According to the crash log it seems to be an issue when a block of Minecraft.Air is entered into an ItemFoodContainer from Spiceoflife.

* **Known Fix**: Unknown at this time.

**Comment by KingDan27** [comment]
had this issue also +1
Pastbin file: https://pastebin.com/bttFih5q

**Comment by modmuss50** [comment]
Issue on mod tracker found here: https://github.com/squeek502/SpiceOfLife/issues/146

**Comment by tfox83** [comment]
fixed in 1.3.0
