### ISSUE TITLE
Save now crashes

### ISSUE THREAD

**Issue by MrJoshua68** [FTBTeam/FTB-Continuum#390]
* **Modpack Version**: FTB Continuum (Forge-12.23.4.2705) 

* **Issue**:  Today I was just running around my base rearranging things, when the game crashed.  Now every time I try and load my save, it crashes.  I had been breaking a number of drawers and moving them and their contents to another location.

The major thing that I built that may have introduced something new was the Immersive Engineering distillation tower, but it had already run a full cycle and filled its internal storage, so it was inactive at the time of the crash.

Everything happening in the background:
-  cooking some Titanium in a blast furnace.  
- Diesel generator
- A number of IE Cloches
-IE squeezer
-IE Refinery
-IE Fermenter.
* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/697bddf3

* **Is it Repeatable?**: yes.  It crashes to the desktop every time the save loads.

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by tfox83** [comment]
Fixed in 1.5.0 with update to IE
