### ISSUE TITLE
Applied Energistics 2 - auto crafting of signalum capacitor is not working

### ISSUE THREAD

**Issue by RareDevil** [FTBTeam/FTB-Continuum#391]
* **Modpack Version**: 1.4.1

* **Issue**: Applied Energistics 2 - auto crafting of signalum capacitor is not working, it just stalls the craft. 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/2da2dc13

* **Is it Repeatable?**: I have not tested in single player but everytime i tried on the server i play on it was just stuck on crafting

* **Mod/s Affected**: Applied Energistics 2 and Thermal Expansion

* **Known Fix**: None

**Comment by aaronhowser1** [comment]
You might not have room in your ME system for one of the ingredients.

**Comment by RareDevil** [comment]
@aaronhowser1 I tried on a total separate system because I thought it was my system that was the problem. That system add all it needed and plenty space.

EDIT: 
I just tried in single player for just to make sure that it was not the server that was the problem.
Here are some screenshot of the setup:
![setup 1](https://user-images.githubusercontent.com/9973318/43387243-3b9e36e0-93e6-11e8-94ad-1a7f3509f5f9.png)
![setup 2](https://user-images.githubusercontent.com/9973318/43387244-3bc01314-93e6-11e8-8b2a-60bbc67a102b.png)
![setup 3](https://user-images.githubusercontent.com/9973318/43387245-3be08edc-93e6-11e8-8e5d-1a3c215f54a4.png)
![setup 4](https://user-images.githubusercontent.com/9973318/43387246-3bffad26-93e6-11e8-8cb8-f516b08154c6.png)

Also just like to point out that i did try allow substitutions on the pattern and that just made it not work at all.
![no working pattern](https://user-images.githubusercontent.com/9973318/43387419-ac782c40-93e6-11e8-8707-9263dc3f0a26.png)

The pattern below is the only one that i can get to work:
![working pattern](https://user-images.githubusercontent.com/9973318/43387447-bc6b9862-93e6-11e8-9613-7ef2de311cb5.png)

**Comment by tfox83** [comment]
I was able to craft this in my test world fine.

**Comment by bryaqui** [comment]
I am playing on the All The Mods 3 Expert modpack and having the same exact issue as described here and in the screenshots above. No matter how I make the recipe the following screenshot is the only thing that happens when I try to autocraft the Flux Capacitor (Signalum)
![image](https://user-images.githubusercontent.com/88563590/128578741-8f0b991c-c9db-4955-baf5-99ea31cff7c6.png)
If anyone here was able to resolve this issue could you go into a bit more detail about how you resolved it.

**Comment by aaronhowser1** [comment]
Why are you asking here instead of the ATM issue tracker?

**Comment by bryaqui** [comment]
Because this issue was the exact same as mine and it was stated that they got it to work so if I could just get a resolution that would be easiest.
