### ISSUE TITLE
FTB Continuum Server error.

### ISSUE THREAD

**Issue by grealyve** [FTBTeam/FTB-Continuum#392]
* **Modpack Version**: <1.4.1>

* **Issue**: <When I starting the server, it gives an error like the images.The images links are in Paste.>

* **Link to Log or Crash File Paste**: <https://paste.feed-the-beast.com/view/fa3b6f14>

* **Is it Repeatable?**: <I don't know.>

* **Mod/s Affected**: <I don't know.>

* **Known Fix**: <Not found.>

**Comment by russjr08** [comment]
Your screenshots are just giving an authorization error. You may need to put them somewhere else.
