### ISSUE TITLE
"Search nearbly items" broken by bookcase

### ISSUE THREAD

**Issue by Proha5** [FTBTeam/FTB-Continuum#394]
1.4.1 singleplayer
(bad english)
Some quest give me reward bookcase. (from bibliocraft)
if place the bookcase - then search (T key) is no working. If break bookcase - then work fine.

**Comment by aaronhowser1** [comment]
I had a similar issue, I never made the connection that it was the bookcase. I wonder why that would break it, weird. I suggest forwarding this to the Bibliocraft and Extra Utils issue trackers too.

**Comment by Proha5** [comment]
The bug in ExUt2:
https://github.com/rwtema/Extra-Utilities-2-Source/issues/93

**Comment by tfox83** [comment]
Will get in as soon as the fix is avail.
