### ISSUE TITLE
remove useless tabs

### ISSUE THREAD

**Issue by Proha5** [FTBTeam/FTB-Continuum#395]
1.4.1 singleplayer
(bad english)
how remove useless tabs and "thermal dynamics covers" tabs?

![image](https://user-images.githubusercontent.com/29812448/43495688-c29d7024-957c-11e8-889b-e2ca098d740f.png)

**Comment by aaronhowser1** [comment]
I don't know if it's possible to hide those tabs. The blocks are disabled in the cofh configs, I don't knbw what else we can do.

**Comment by NielsPilgaard** [comment]
I believe you can hide the tabs by removing all the machine processing recipes.

**Comment by tfox83** [comment]
I am not able to remove those tabs at this time in a reliable way.
