### ISSUE TITLE
Infinite Essence of Knowledge

### ISSUE THREAD

**Issue by Richetoku** [FTBTeam/FTB-Continuum#397]
* **Modpack Version**: 1.4.1

* **Issue**: If you place essence of knowledge from thermal expansion into a open blocks tank, you can put the tank in a forestry bottler and pump it out and the tank never depletes.

* **Link to Log or Crash File Paste**:

* **Is it Repeatable?**: Yes. Happens in single player and on server.

**Comment by temp1011** [comment]
this is fixed here in forestry: https://github.com/ForestryMC/ForestryMC/pull/2128. So an update would solve this. Also same as https://github.com/FTBTeam/FTB-Continuum/issues/345?

**Comment by tfox83** [comment]
Fixed in 1.5.0
