### ISSUE TITLE
Server crashes when heading to Luna on a rocket with a satellite inside.

### ISSUE THREAD

**Issue by loudcricketts** [FTBTeam/FTB-Continuum#398]
* **Modpack Version**: 1.4.1

* **Issue**: I placed a satellite in my rocket that I planned to put into orbit, took off, and the server crashed once I was about to enter the space menu to head to Luna. Now it crashes whenever I join the server.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/58c3a150 

* **Is it Repeatable?**: Yes, the same server crash occurs each time I join

* **Mod/s Affected**: Looking at the crash report, it appears that Advanced Rocketry itself is the culprit.

* **Known Fix**: None

**Comment by tfox83** [comment]
Fixed in  1.5.0 Beta
