### ISSUE TITLE
Impossible sawmill quest

### ISSUE THREAD

**Issue by Proha5** [FTBTeam/FTB-Continuum#399]
1.4.1 singleplayer
Quest "Really for wood" is impossible to complete, because "TE sawmill" is disabled.

**Comment by aaronhowser1** [comment]
Is it? IIRC you should be able to make it, it gives you 4 planks while the TR one gives 6. This looks more like a recipe issue I think.

**Comment by Proha5** [comment]
(i bad english.)
i not understand you.
Quest "Really for wood" requere "thermal dynamic sawmill". But all thermal dynamic machines disabled.( exclude blue TE machines).

**Comment by aaronhowser1** [comment]
The Thermal Expansion Sawmill has a recipe, I don't know what you mean. Some Thermal Expansion blocks are disabled, but a lot of them aren't and are actually required for progression. This is the recipe for the Sawmill:

![image](https://user-images.githubusercontent.com/15698722/43681349-67cad348-9816-11e8-8603-81ead2fab9dc.png)

Why did you think that there wasn't a recipe or that it was disabled? If you just looked up the recipe and it didn't work, remember that this is an expert mode modpack that uses altered recipes. Use JEI to find items and their recipes.

**Comment by Proha5** [comment]
The problem solved. I changed launcher from "FTB launcher" to Twitch. Now i have sawmill recipe.
