### ISSUE TITLE
Recipe in JEI not craft-able in a crafting bench

### ISSUE THREAD

**Issue by redawgts** [FTBTeam/FTB-Continuum#40]
* **Modpack Version**: 1.0.2

* **Issue**: According to JEI you can use Pressed Wax from HarvestCraft to make Wax Capsules from Forestry but they don't show up as craft-able in a crafting bench.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Pam's HarvestCraft and Forestry. Maybe others if there were recipe changes.

* **Known Fix**: No idea.

**Comment by tfox83** [comment]
forced the recipe to fix it in next update
