### ISSUE TITLE
No way to create enderium

### ISSUE THREAD

**Issue by Proha5** [FTBTeam/FTB-Continuum#400]
1.4.1
(bad english)
How create enderium ingot? No any link between ender pearl and enderium (or ender liquid)

**Comment by pfmoore** [comment]
4 enderium blend is 1 bucket of resonant ender, 3 lead dust, 1 platinum dust. Use an arc furnace (or Tinker's smeltery and ingot cast) to make the blend into enderium ingots.

**Comment by Proha5** [comment]
**pfmoore**, How create "resonant ender"? Its no have source.

**Comment by aaronhowser1** [comment]
Resonant Ender is made by melting Ender Pearls in the Magma Crucible. In JEI, click on the bucket to see how it's made, and then click on the fluid to see how the fluid is made.

**Comment by Proha5** [comment]
But there no recipe. Magma cruicible disabled. I use 1.4.1. Why i not have Thermal expansion machines? its bug?
![image](https://user-images.githubusercontent.com/29812448/43681405-2242bd38-9896-11e8-9050-fbcb3b532f62.png)

**Comment by aaronhowser1** [comment]
Sorry for closing this. On my brand new 1.4.1 instance I don't have this issue. Maybe try installing a new instance from scratch?

**Comment by Proha5** [comment]
FTB launcher no have "reinstall modpack" function.
TE machines available at early game? may be its will opens in future?

**Comment by aaronhowser1** [comment]
I suggest using the Twitch launcher instead of the old FTB launcher, that one isn't supported any more. You could also try using MultiMC if you're on Linux or just don't like the Twitch launcher. You could make a backup of the modpack and then delete the original version and redownload it though.

The Sawmill is the only TE machine available early game, that is on purpose and will likely never change in this modpack. This modpack is supposed to be hard, so the more useful machines are locked behind late game stuff.

**Comment by Proha5** [comment]
I installed Twitch. Problem solved!
TE Sawmill available. Magma cruicible available! Probably unlocked many other items.
Why "FTB Launcher" locking this machines?
If other users have same problem, then may be write note that the modpack not compatible with ftb launcher?

**Comment by aaronhowser1** [comment]
I have no idea why the version you downloaded from the legacy launcher is broken, maybe it was an issue with updating or installing the modpack. I'm sure it wasn't meant to be incompatible with the legacy launcher, but I don't think anyone on the staff uses it so nobody found it during testing. I don't know how it would be fixed either, as the legacy launcher isn't going to be getting any more updates. Glad that we got the issue sorted out though!
