### ISSUE TITLE
Questline gated by error?

### ISSUE THREAD

**Issue by mattie078** [FTBTeam/FTB-Continuum#401]
* **Modpack Version**: 1.4.1
* **Issue**: For the Metallum Ex Vacui quest I need to finish Pierce the Heaven first. But there is no Pierce the Heaven quest, only PierCING the Heaven. And for that quest you need to finish the prerequisite quests which one of them is Metallum Ex Vacui. Am I missing something or is this a bug in the pack?

* **Link to Log or Crash File Paste**:  -

* **Is it Repeatable?**: -

* **Mod/s Affected**: None

* **Known Fix**: Removing the need to have Pierce the Heavens for the quest.

**Comment by aaronhowser1** [comment]
Quests are linked to IDs, not to names. Can you show me some screenshots of the drill quest and the ex vacui quest that says it needs it? Is there a line connecting the two?

**Comment by aaronhowser1** [comment]
I just made a new world and force completed Pierce the Heavens and Compressum, and that unlocked Metallum Ex Vacui. 

![image](https://user-images.githubusercontent.com/15698722/43681333-d5ce5ba4-9815-11e8-8c56-1e52e62dfd02.png)
![image](https://user-images.githubusercontent.com/15698722/43681334-da15c74c-9815-11e8-9bf5-994ce14d587a.png)

I think you should try reloading your quests with the "Update Quests" quest in the first chapter or the command `/bq_admin default load`.

**Comment by mattie078** [comment]
Doing the reload resolved the issue. Weird but it worked. Thanks!
