### ISSUE TITLE
Reopen: enderium

### ISSUE THREAD

**Issue by Proha5** [FTBTeam/FTB-Continuum#402]
**aaronhowser1**, you closed previus topic. But there bug.
My answer:
There no resonant fluid recipe. Magma cruicible disabled. I use 1.4.1. Why thermal expansion machines disabled? its bug?
![image](https://user-images.githubusercontent.com/29812448/43681439-433b8f00-9897-11e8-807f-5821d1e44478.png)

**Comment by aaronhowser1** [comment]
Oh, sorry. I'll close this one and reopen the last one.
