### ISSUE TITLE
efab sound

### ISSUE THREAD

**Issue by Proha5** [FTBTeam/FTB-Continuum#403]
1.4.1
When i craft using efab+steam, then my sound like as noise. Client-log spaming messages:
[Thread-9/ERROR] [minecraft/SoundManager]: Error in class 'SourceLWJGL OpenAL'
[Thread-9/ERROR] [minecraft/SoundManager]: Channel null in method 'stop'
[Thread-9/ERROR] [minecraft/SoundManager]: Error in class 'SourceLWJGL OpenAL'
[Thread-9/ERROR] [minecraft/SoundManager]: Channel null in method 'stop'

**Comment by louis71barker** [comment]
Ive got this issue too, so annoying, not so much just with the efab but randomly kills my game

**Comment by Proha5** [comment]
i edited efab config, and disable all sound effects.

**Comment by tfox83** [comment]
This should be fixed in 1.5.0 with latest eFab
