### ISSUE TITLE
Lens of Disruption is active in default config

### ISSUE THREAD

**Issue by DerSoftwerker** [FTBTeam/FTB-Continuum#404]
* **Modpack Version**: 1.4.1
* **Issue**: 
Greetings,

one of the players on my server informed me today that an easterEgg by Ellepack in Actually additions was active, the Lens of Disruption. (https://ftb.gamepedia.com/Atomic_Reconstructor#Lens_of_Disruption 1)

This should be off on default as not everyone is aware of this feature and it could really destroy the intended progress.

Regards
Softwerker

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Actually Additions

* **Known Fix**: AA config set "What is 11=0"

**Comment by chriswa** [comment]
This completely breaks the pack. Unobtainable, impossibly powerful items (such as a Creative ME Storage Cell) can be obtained. I've patched my configs now that I'm aware of the problem, and the offending player doesn't seem to have done too much damage to the server's economy, but for the benefit of everyone else, please fix the config!

**Comment by tfox83** [comment]
Hmm this must of reverted at some time during an update.  THis has been patched in 1.5.0 beta.  Thanks
