### ISSUE TITLE
recipe minecraft:wheat produces unregistered item minecraft:wheat

### ISSUE THREAD

**Issue by zmwwxa** [FTBTeam/FTB-Continuum#406]
when i join in my server,the client give me this :recipe minecraft:wheat produces unregistered item minecraft:wheat.....
[](url)

any ideal

**Comment by aaronhowser1** [comment]
can you post a screenshot of the recipe?

EDIT: Or do you mean in chat? If it's in chat, there's likely a script problem. Can you show a screenshot of the chat if that's the problem?

**Comment by zmwwxa** [comment]
![image](http://wx4.sinaimg.cn/mw690/0060lm7Tly1ftzrelhkchj30o60efwg5.jpg)

**Comment by zmwwxa** [comment]
i can start the game in sigalplayer ,but when i join my server,error

**Comment by zmwwxa** [comment]
Modpack Version: 1.4.1

**Comment by aaronhowser1** [comment]
That's very strange. Can other players join the server? Are you using Twitch, MultiMC, or the legacy FTB launcher? You might want to try reinstalling the modpack if other players can join the server but you can't.

**Comment by zmwwxa** [comment]
i am using MultiMC,and others cant join the server.when i login in the server the third time,i got this error....ill reinstall the server and the client.and thx for ur help

**Comment by tfox83** [comment]
I suggest a fresh install of server/client.  We are not able to repeat.
