### ISSUE TITLE
AE2 + Black Hole Unit/Controller + Tech Reborn Cells turns all cells in a Slot into the last inserted cell

### ISSUE THREAD

**Issue by nafftan** [FTBTeam/FTB-Continuum#407]
* **Modpack Version**: 1.4.1

* **Issue**: The combination of AE2 + Black Hole Unit/Controller + Tech Reborn Cells turns all cells in a Black Hole Unit into the last inserted cell and adds the ammount. 
Explanation: I exportet all my Compressed Air Cells to a Black Hole Unit inside an Controller and locked the inventory of that. Now every new added cell changes the content of the slot in the Black Hole Unit to the last filled cell inserted. (if i need 500k heliumplasma ... just add one cell ... if I need water or compressed air .. just add one cell of these ....) 

* **Link to Log or Crash File Paste**: no crash

* **Is it Repeatable?**: yes. the content of the Black Hole Unit changes every time a filled cell is pushed into the network. it does not matter if it comes over an import Bus or the ME Interface or an storage bus.

Edit: you can "dublicate" any fluid in Tech Reborn Cells with the black hole unit. Just insert one cell with the fluid to dublicate. Then insert as many empty cells as you want and remove them filled with the fluid of the first cell. Using that in combination with AE2 the last cell entered to the system changes the type of fluid. With a single unit the first cell defines what to dublicate.

* **Mod/s Affected**: (AE2) + TechReborn + Industrial Foregoing

* **Known Fix**(Idea): The icon which indicates the type when the inventory of the BlackHole Unit is locked looks like an empty cell. So perhaps the Unit or the controller is unable to specify the correct item type and adds all what looks like a cell and changes the item type.

**Comment by tfox83** [comment]
Should be fixed via latest TR udpate
