### ISSUE TITLE
Flux Network disconecting from channel

### ISSUE THREAD

**Issue by TheFrostSeraph** [FTBTeam/FTB-Continuum#408]
Modpack Version: 1.4.1

Issue: When having a Flux Network, from the mod @Flux Networks, the various plugs and points (even if theres only one of each) will keep disconnecting in an apparently random way from the selected network. So i have some energy going  from a plug to a point and everything is fine, but, from time to time, it just disconnects and i have to manually connect them again. There doesnt seem to be a patron. I thought it might be cause unloaded chunks but it isnt.

Is it Repeatable? Yes, although it happens randomly.+

Mod/s Affected: Flux Network

**Comment by tfox83** [comment]
This should be fixed in 1.5.0 via Flux Networks udpate
