### ISSUE TITLE
Unbalanced energy cost to creating biodiesel (and diesel too).

### ISSUE THREAD

**Issue by Proha5** [FTBTeam/FTB-Continuum#409]
1.4.1
(bad english)

To make 2048rf from biodiesel you should spend 1400rf! Effeciency = 32%

I maked tests for energy consumption:
Refinery 80rf/t.
Fermenter 720rf/t. (!!)
Squezer 720rf/t (!!)

Refinery consume 8mb+8mb source fluids per tick. And full support for 2 diesel generators.

Fermenter make 8mb ethanol per tick. (refinery proportion = 1.0 )
Squezer(hemp) make 12mb oil per tick. (refinery proportion = 8/12 = 0.66)
720rf x 1.0 + 720rf x 0.66 + 80rf = 1275 rf / t total consumtion.
Plus energy for 16 garden cloche. 16 x 8rf = 128rf.
Then i should spend 1400rf to make 645 rf !! (2x1024 - 1400 = 645rf)

I should spend big amount resources to build 5 big structures to make only 645rf/t.  And should build 16 cloch for grow hemp and melons. Better way to get 645rf - create 7 water wheels.
Water wheels - is best choise. Biodiesel and diesel is very bad choise.

The modpack nerf diesel generator from 4K to 1K. May be reduce Refinery Squezeer Refinery consumtion 4 times? (and pumpjack and destill tower)

**Comment by tfox83** [comment]
We have already balanced this in earlier testing and will keep current configs, thanks for the report.
