### ISSUE TITLE
Potion Of Love + Potion Of Relapse

### ISSUE THREAD

**Issue by Bennjy** [FTBTeam/FTB-Continuum#410]
* **Modpack Version** 1.4.1

* **Issue**: So here I am trying to get my animals to breed super easily, so I see the potion of love, I go 
                   to craft it and it makes potions of relapse. Turns out they have the same exact recipe, is this 
                  on purpose or is this a bug?

* **Link to Log or Crash File Paste**: http://prntscr.com/kh68ks < recipe for potion love
                                                           http://prntscr.com/kh68v7 < recipe for potion of relapse
* **Is it Repeatable?**: Yes ( just try to make a potion of love )

* **Mod/s Affected**: ExtraUtilities2 

* **Known Fix**: ?? ( not sure if there is one, If you change one of the potions and make it use the red dye instead of the flower, that would fix it )

**Comment by tfox83** [comment]
At this time I am not able to change the brewing mechanics without breaking alot of things.. I suggest possibly reporting to the ExU dev.  Sorry
