### ISSUE TITLE
Some items not displaying in quest book

### ISSUE THREAD

**Issue by lukegehring99** [FTBTeam/FTB-Continuum#411]
* **Modpack Version**: 1.4.1

* **Issue**:  The icons for some of the items required in some quests aren't displaying.

* **Link to Log or Crash File Paste**: Images of an example quest. https://imgur.com/a/WILqSoO

* **Is it Repeatable?**: Yes I have this problem on both a server and my client. Same quests. 

* **Mod/s Affected**: Better Questing

* **Known Fix**: None

**Comment by aaronhowser1** [comment]
Hit the right arrow next to the submit button in the quest
