### ISSUE TITLE
Lightning Hit Close to House. Had AFK session going. Computer shut down, but now I can't edit world

### ISSUE THREAD

**Issue by N8Blueberry** [FTBTeam/FTB-Continuum#413]
* **Modpack Version**: 1.12.2

* **Issue**: FTB shuts down when I try to open this world that I was afk'ing in after my computer shut down because of lightning in the area.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/ee900ce9
IDK if this is what is meant with the crash log. I found this in the output log in the settings of the Minecraft Launcher, which I launch from Twitch

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: --

* **Known Fix**: 

It's only my one world. All other worlds I have are able to be opened. It is probably because this one was opened while I was AFKing, and since my computer got shut down during a lightning storm, the world I had opened was the only one affected.

**Comment by rune-san** [comment]
Have you tried creating a new FTB Instance and copying your world folder into that one? Sounds like you have some corruption.

**Comment by N8Blueberry** [comment]
@rune-san Do you have a video I can watch to make sure I do it right? Haven't done this before...

**Comment by tfox83** [comment]
I suggest a fresh install.
