### ISSUE TITLE
Infinity cresosote oil

### ISSUE THREAD

**Issue by vicente-higino** [FTBTeam/FTB-Continuum#414]
* **Modpack Version**: 1.4.1

* **Issue**: When i put the  creosote oil can on the semi fluid generator i get infinity resource and the oil can is never consumed.

* **Is it Repeatable?**: yes

**Comment by copysaurus** [comment]
Actually we just noticed this too. And it's not only creosote oil but any liquid in a forestry can. Infinite everything.

**Comment by tfox83** [comment]
Known issue, if there is ever a fix ill get it in ASAP
