### ISSUE TITLE
Wrong recipe (aluminium+copper alloy).

### ISSUE THREAD

**Issue by Proha5** [FTBTeam/FTB-Continuum#415]
1.4.1
(bad english)
Tech reborn alloy smelter: 1+1=1 (wrong)
![image](https://user-images.githubusercontent.com/29812448/44067923-15786ef0-9fbb-11e8-9da5-7a5235fade71.png)

Should be:  (3+1=4)
![image](https://user-images.githubusercontent.com/29812448/44067953-349ee944-9fbb-11e8-9eb9-fb645a877f83.png)
Also, need adding dust variants.

**Comment by Proha5** [comment]
how i may fix this? 
i can't wait for new version.

**Comment by aaronhowser1** [comment]
You could report this to the Tech Reborn issue tracker, or you could use a different method to get Bronze than the TR Allot Smelter.

**Comment by drcrazy** [comment]
This issue is not with TR. Change to TR recipe is in scripts\techReborn.zs.
Existing one is:
```
#add alum brass to alloy smelter
mods.techreborn.alloySmelter.addRecipe(<tconstruct:ingots:5>, <ore:ingotAluminum>, <ore:ingotCopper>, 300, 20);
```

**Comment by tfox83** [comment]
I have no idea what the issue really is here.  It works as its intended.  As aaron said if that isnt the way you want to make tit then use another method to get Alum Brass.
