### ISSUE TITLE
oreExcavation

### ISSUE THREAD

**Issue by xXboomXx91** [FTBTeam/FTB-Continuum#416]
* **Modpack Version**: 1.4.1

* **Issue**: oreExcavation wont work, I press and hold the key bind and break a block with the correct tool and nothing happens when I finish breaking the block

* **Is it Repeatable?**: iv tried several times

* **Mod/s Affected**: oreExcavation v1.4.119

**Comment by aaronhowser1** [comment]
It only works on ores, and you don't need to hold any button. See the quest for more details.
