### ISSUE TITLE
Extra Utilities 2 Mechanical Crafter can't craft some small piles of dust

### ISSUE THREAD

**Issue by Rodg88** [FTBTeam/FTB-Continuum#417]
* **Modpack Version**: 1.4.1

* **Issue**: Can't craft small piles of iron, copper, silver, or lead dust into full dusts in the Extra Utilities 2 Mechanical Crafter. Other small piles work properly in the Mechanical Crafter, and the small piles of iron/copper/lead/silver are craftable in other rafting tables

* **Is it Repeatable?**: Place down a Mechanical Crafter, and use the [+] button in JEI to put the recipes for small piles -> regular dusts into the Mechanical Crafter, the recipes for iron/copper/lead/silver dust will have no crafting result.

**Comment by tfox83** [comment]
Known issue, if there is ever a fix ill get it in ASAP
