### ISSUE TITLE
[Suggestion]XNet is SO CHEAP that no one will choose other ducts to transfer items, fluid or energy

### ISSUE THREAD

**Issue by SihenZhang** [FTBTeam/FTB-Continuum#42]
* **Modpack Version**: 1.0.2

* **Issue**: 
XNet is a useful mod that can transfer items, fluid and energy. Besides it will not decrease TPS. 
But XNet is so cheap. It only needs Advanced Machine Frame in TechReborn while other ducts need some items or machine that need a lot of time such as chipsets in Forestry or silicon. 
I'm confused why omnipotent XNet can be so cheap that everyone of us who are in the server will give up other pipes or ducts or conveyors immediately.
So please make XNet expensive 'cause it is valuable.

**Comment by tfox83** [comment]
The are a bit cheaper because they impact performance the least, and its a newer mod and encourages players to sway off their standard route using TD or other means of common transfer.  I feel the cost is fine atm.  Thanks for the input
