### ISSUE TITLE
No recipe for Reactor Casing

### ISSUE THREAD

**Issue by MrJoshua68** [FTBTeam/FTB-Continuum#421]
* **Modpack Version**: 1.3.1

* **Issue**: Im on the Extreme Energy quest.  All of the components for the quest show up in JEI (Controller, Access Port, etc...) except for the Reactor Casing.  I have searched on casing, reactor and @extreme.  Its just not there.

Not sure if its related, but I have had quite a bit of glitching. Recipes that dont remove all the ingredients from my inventory after crafting.  Lumium from the smeltery turning to water when I pump it into a tank, etc...
 
* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**:Yes.  Shut down and restarted.  Still happening.

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by aaronhowser1** [comment]
Do you mean 1.4.1? If not, update to that version and try again. If you *are* on 1.4.1, try installing a new instance and seeing if the recipe is on that one.

**Comment by Proha5** [comment]
MrJoshua68, i had  same problem. I used "FTB Launcher". When i use "Twitch" - the problem disapear.

**Comment by MrJoshua68** [comment]
This was fixed when I installed the new instance as suggested by @aaronhowser1 
Thanks!

Any idea when an update will go out?  Is there discussion of that I am missing somewhere?

**Comment by tfox83** [comment]
1.5.0 will be in beta today.  1.4.1 is current release
