### ISSUE TITLE
NBT Tag too big Clientcrash (Fluxpoint - BUG) --Please Close--

### ISSUE THREAD

**Issue by theralmccoy1234** [FTBTeam/FTB-Continuum#422]
* **Modpack Version**: 
FTBContinuum-1.4.1

* **Issue**: 
Client crashes: Internal Exception: io.netty.handler.codec.DecoderException: java.lang:RuntimeException: Tried to read NBT tag that was too big: tried to allocate: 2097170bytes wher max allowed: 2097152
see Error Message on: http://pix.toile-libre.org/upload/original/1534497053.png

* **Link to Log or Crash File Paste**: 
Client-Log: https://paste.ee/p/qGNdr
Server-Log: https://paste.ee/p/oVLy8

* **Is it Repeatable?**: 
Yes happens every time when i try to log in

* **Mod/s Affected**: 
unknown

* **Known Fix**: 
no known fix

**Comment by theralmccoy1234** [comment]
While further investigating I found in Clientlog:
[19:17:20] [Netty Epoll Client IO #0/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/1 (SPacketSpawnExperienceOrb) was larger than I expected, found 333196 bytes extra whilst reading packet 1

**Comment by theralmccoy1234** [comment]
After searching through a regionfile with nbt-explorer I found a Fluxplug wit almost 26000 NBT-Entries
see: 
![grafik](https://user-images.githubusercontent.com/38962374/44369077-5bcdbf80-a4d5-11e8-9142-e66bda214b98.png)
after deleting the fluxplug from the chunk everything was fine again :)

**Comment by aaronhowser1** [comment]
You should forward this to the Fluxplugs dev too, if it hasnt been already
