### ISSUE TITLE
Journeymap Crash 

### ISSUE THREAD

**Issue by AftDawn** [FTBTeam/FTB-Continuum#423]
* **Modpack Version**: 1.4.1

* **Issue**: journeymap Error handling WorldEvent.Unload problem

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/736c65f2

* **Is it Repeatable?**: yes, it happens every time i try to go to my world

* **Mod/s Affected**: unknown

* **Known Fix**: no known fix

**Comment by splitraid** [comment]
Same problem here, was doing fine yesterday, but now I can't open my world that I created months ago.

**Comment by tfox83** [comment]
Fixed in  1.5.0 Beta
