### ISSUE TITLE
Auto inserting electrodes into Arc furnace not working.

### ISSUE THREAD

**Issue by Proha5** [FTBTeam/FTB-Continuum#425]
1.4.1
Quest "Arc furnace" says, thtat electodes can be inserted into the top center block.
But its wrong info. No way to insert electrodes into furnace.
I found, that Its not bug. Developers deleted automation from furnace :((
https://www.reddit.com/r/feedthebeast/comments/5r9b8p/immersive_engineering_question_arc_furnace/

**Comment by BluSunrize** [comment]
*clap clap clap clap*
