### ISSUE TITLE
Tech Reborn Auto Crafting Table broken

### ISSUE THREAD

**Issue by Neomania** [FTBTeam/FTB-Continuum#426]
* **Modpack Version**: 1.4.1

* **Issue**: The Tech Reborn auto crafting table appears broken; the UI is generally unresponsive and looks bugged, with a search bar overflowing into the inventory section. Was this recipe meant to be disabled, given how it would remove the need for the Factorizer?

* **Is it Repeatable?**: Yes, tested on multiplayer and singleplayer with vanilla redstone block recipe.

* **Mod/s Affected**: Tech Reborn

**Comment by tfox83** [comment]
Fixed in  1.5.0 Beta
