### ISSUE TITLE
Efab autocrafting sometime stucked with planks

### ISSUE THREAD

**Issue by Proha5** [FTBTeam/FTB-Continuum#427]
1.4.1
Any recipes with planks sometime stucked.
Example: ae2 interface place 32 planks into "item storage". Efab consume some time 6 or 10 planks intstead 8. And stucked. Not starting anymore. I should break and place again any efab block.
its bug is rare.

I tired from bugs in beta mods. Please, dont include beta mods in modpack. Tech reborn, efab e.t.c.
this mods is very bugged.

**Comment by Proha5** [comment]
Probably, its same bug:
https://github.com/McJtyMods/EFab/issues/19

**Comment by Proha5** [comment]
Not. Its other bug. Not only planks. Any recipes.
Sometime(at start game) efab not autocrafting. Why?

![image](https://user-images.githubusercontent.com/29812448/44324455-155a6f80-a499-11e8-9192-1a97532a8b99.png)

![image](https://user-images.githubusercontent.com/29812448/44324476-1f7c6e00-a499-11e8-81a6-39f7450624cd.png)

![image](https://user-images.githubusercontent.com/29812448/44324875-4f784100-a49a-11e8-805e-1b116b78e785.png)

**Comment by tfox83** [comment]
Fixed in 1.5.0
