### ISSUE TITLE
Steve's Carts 2 Chunk Loader Module. Cannot activate. Unsure if it's intentional or a issue with the mod.

### ISSUE THREAD

**Issue by MrEssex** [FTBTeam/FTB-Continuum#430]
Hi, unsure if this is intended (I feel it is) but I'm unable to active the chunk loader module attached to a Steve's carts 2. I can hover over the button, but no amount of clicking will change it to active. (returning to minecraft from a long hiatus) I remember reading that FTB disabled all chunk loading to use the FTB Utilities chunk loading only, but I'm unsure if that's the case here and/or how to change it (Which is why I thought to post here first). Any help or advice would be much appreciated. 

* **Modpack Version**: 1.4.1

**Comment by tfox83** [comment]
Disabled due to FTBU chunkloading present in the mod pack
