### ISSUE TITLE
Industrial Foregoing Plant Interactor will not accept fluid containers. 

### ISSUE THREAD

**Issue by Jadoz** [FTBTeam/FTB-Continuum#432]
* **Modpack Version**: 1.4.1

* **Issue**: I am using Plant Interactor from Industrial Foregoing to harvest Pam’s tree crops. All works well except that it will not accept any fluid containers to fill with sludge. I have tried buckets, cells and wax capsules.  Cannot manually insert any of them. Plant Gatherer from Industrial Foregoing also produces sludge and will accept containers. Pumping sludge out does work, so very minor issue. 

* **Link to Log or Crash File Paste**: No crash.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Industrial Foregoing. 

* **Known Fix**: Workaround by pumping out. Fix by comparing with Plant Gatherer.

**Comment by tfox83** [comment]
I believe pumping out is the intended method at least in my testing.
