### ISSUE TITLE
Ore miner ignore accuracy modifier

### ISSUE THREAD

**Issue by Proha5** [FTBTeam/FTB-Continuum#433]
1.4.1
I maked test:

Ore miner tier 5.
15 accuracy + 1 speed modifier
Accuracy multiplier = 1.18^accuracy = x12
( formula: https://ftb.gamepedia.com/Void_Ore_Miner_Controller )
![image](https://user-images.githubusercontent.com/29812448/44509401-eb9d8480-a6f4-11e8-85db-dad0e65b2629.png)

Chanses of gray laser lens:
16% for tin ore.
13% for nickel ore.
![image](https://user-images.githubusercontent.com/29812448/44509537-577fed00-a6f5-11e8-9056-a71066ac246e.png)

Worked some time.
Result:
(right bottom ores is tin and nickel)
![image](https://user-images.githubusercontent.com/29812448/44509609-87c78b80-a6f5-11e8-977e-1e352fc45fe3.png)

Total digs = 260+49 tin+34 nickel  = 343
1% is 343 / 100 = 3.43
49 tin is 49 / 3.43 = 14%
34 nickel is 34 / 3.43 = 10%

What?!
14% and 10% ?
Multiplier of Accuracy modifier <1 ! (should be 12)
Accuracy modifier not affected.
Bug?

**Comment by Proha5** [comment]
I did some more tests.
0 Accuracy: ~12-15%
8 accuracy: ~12-15%
No difference. But each Accuracy modifier increase power consumption.
it is bug. How fix?
Can i update Envirompent tech in twitch? update not will broke modpack config?

**Comment by tfox83** [comment]
Should be fixed in 1.5.0 with ET update
