### ISSUE TITLE
Bug: "Extra Cells 2" fluid terminal add tag to empty cells.

### ISSUE THREAD

**Issue by Proha5** [FTBTeam/FTB-Continuum#434]
1.4.1
I electrolize cinnabar to mercury.
And process stoped.
![image](https://user-images.githubusercontent.com/29812448/44518267-2ca19300-a70d-11e8-9f0b-b6547ce18bc7.png)

I tryed replace machine - problem still.
I tryed restart client (and PC) - problem still!!
How fix electolyzer??
I can't continue play.
And other bug appear: I can't manualy place empty cells in left slot. Only autoinput works. But process still stoped.

**Comment by Proha5** [comment]
I found cause.
"Fluid terminal"(extra cells 2) converted cells to other empty cells (added tag to cell)
I poured out mercury cells using "fluid terminal". And this empty cells not accepted by machines.
How fix "extra cells 2" fluid terminal?
![image](https://user-images.githubusercontent.com/29812448/44520275-c881cd80-a712-11e8-8c3e-be9f729fd11d.png)

**Comment by drcrazy** [comment]
Duplicate for https://github.com/FTBTeam/FTB-Continuum/issues/201

**Comment by tfox83** [comment]
closed as dupilcate
