### ISSUE TITLE
Advanced RF Storage has no crafting (1.4.1)

### ISSUE THREAD

**Issue by TrademarkTM** [FTBTeam/FTB-Continuum#435]
Basically, the title.
Advanced RF Storage seems to have been fixed in 1.4.0, but it's still uncraftable in 1.4.1. That's quite bad, as ME Controller, for example, requires 8000 RF/t, 32 RF Storage, which requires tons of lapotrons.

Hope this can be fixed soon.
Thanks.

**Comment by MrJoshua68** [comment]
Any word on this?  Its starting to be a problem.

**Comment by MrJoshua68** [comment]
Pretty please?  
Im also at the ME controller stage now and I really need the Advanced version.

**Comment by aaronhowser1** [comment]
I just made a bunch of the normal version. Until an update comes out I recommend doing that.

**Comment by tfox83** [comment]
Reeabled in 1.5.0 beta as it should be working better now
