### ISSUE TITLE
Items going missing as they are crafting in the Efab or Metal Press

### ISSUE THREAD

**Issue by Solverbolt** [FTBTeam/FTB-Continuum#436]
* **Modpack Version**: 
Continuum 1.4.1
* **Issue**: 
I start the crafting process for Wires, Plates, or Gears with the metal press, or more advanced rf powered crafting with the Efab, and it crafts it, then the item disappears. 
* **Link to Log or Crash File Paste**: 
there is no crash report, as it does not crash the game
* **Is it Repeatable?**: 
easily. if I drop ingots on the metal press, they craft then disappear
* **Mod/s Affected**: 

* **Known Fix**:

**Comment by tfox83** [comment]
I am not able to reproduce.  Will need logs to look into this further
