### ISSUE TITLE
JEI not showing fusion reactor power generation

### ISSUE THREAD

**Issue by Proha5** [FTBTeam/FTB-Continuum#437]
1.4.1
![image](https://user-images.githubusercontent.com/29812448/44572820-65eb0900-a7c8-11e8-85b5-2610e6c33a50.png)
i tryed search in config and wiki - not found any info about amount generation.

**Comment by drcrazy** [comment]
Issue with ru_RU lang file

**Comment by drcrazy** [comment]
There are two PRs pending changes for ru_RU translation. No feedback from PR authors for a week (
