### ISSUE TITLE
Satellite Terminal messing with Inventory. 

### ISSUE THREAD

**Issue by Jadoz** [FTBTeam/FTB-Continuum#438]
* **Modpack Version**: 1.4.1

* **Issue**: Right Click on Satellite Terminal, which is essential to use it.  This shifts personal inventory right by 3 slots. It fills the first three slots with duplicates of the satellite id chip in the terminal. The last 3 slots are pushed out of the inventory. Error persists after leaving terminal until an item is selected from the inventory, at which point it corrects itself. The system is still usable, but very disconcerting. 

* **Link to Log or Crash File Paste**: No crash.

* **Is it Repeatable?**: Yes 100% of the time. 

* **Mod/s Affected**: Advanced Rocketry

* **Known Fix**: No fix, but not permanent.

**Comment by tfox83** [comment]
Known issue with Adv Rock, if there is ever a fix I will get it in ASAP
