### ISSUE TITLE
Space Station Package Disappears.

### ISSUE THREAD

**Issue by Jadoz** [FTBTeam/FTB-Continuum#439]
* **Modpack Version**: 1.4.1

* **Issue**: After packaging my Space Station, when I load it into the Satellite Bay of my ship, it disappears.  This happens as soon as it is placed in the rocket’s satellite bay. If I then travel to the station, it is not there.  As soon as I arrive my ship disappears and I am left floating in space. I am unable to progress in ftb continuum as it seems to me that the space station is the gate into the remainder of the package.

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Yes and with different rockets

* **Mod/s Affected**: Advanced Rocketry

* **Known Fix**: None

I did try to circumvent this problem by building a space station directly in space. I went up on a space station launch mission and when the rocket disappeared and left me in space, I used an angel block to construct a platform and a matter transmitter and receiver. I then used this to build a station which seemed to function. I then installed a warp core which built and seemed functional, but the warp controller would not work at all. I was unable to open its GUI and it is just an expensive decoration. My space station will not become a starship.  But, after closing down and reloading ftb continuum warp controller is active! Woohoo!

**Comment by tfox83** [comment]
Known issue with Adv Rock.  If there is ever a fix I will get it in asap.
