### ISSUE TITLE
Black Quartz Acquiring should be made clearer

### ISSUE THREAD

**Issue by MLellmann** [FTBTeam/FTB-Continuum#44]
* **Modpack Version**: 1.0.2

* **Issue**: Acquiring Black Quartz is done via a recipe with the Efab, which is fine, but there are no hints given that this is the way it should be acquired - and no hints are there that searching for Black Quartz Ore (which cannot spawn) is the wrong way to do it.

* **Known Fix**: Add either a tool tip to Black Quartz Ore that it cannot spawn and the way to acquire it, or add a section to the quest there it is needed first.

**Comment by tfox83** [comment]
Added black quartz ore back to JEI and added a tool tip on how to acquire black quartz
