### ISSUE TITLE
Chute and Low Fence recipes conflict

### ISSUE THREAD

**Issue by retep998** [FTBTeam/FTB-Continuum#441]
* **Modpack Version**: 1.4.1

* **Issue**: The recipe for the Chute is the same as the recipe for the Low Fence, rendering the Low Fence uncraftable.

![](https://i.imgur.com/uIqMjgL.png)
![](https://i.imgur.com/OAZm7BB.png)

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Quark and Binnie's Extra Trees

* **Known Fix**: The Low Fence recipes are handled in a special manner to avoid clogging JEI, so the fix is to change the recipe for the Chute to something else.

**Comment by tfox83** [comment]
Fixed in 1.5.0
