### ISSUE TITLE
Lapotron Crystal when charged can't be used for crafting RF Storage for EFab

### ISSUE THREAD

**Issue by woodshop2300** [FTBTeam/FTB-Continuum#442]
* **Modpack Version**: 1.4.1

* **Issue**: We have wireless RF charging setup (yay!), however, as we found last night, when you craft a Lapotron Crystal the wireless system will charge it. Once it is charged, its no longer valid to use for crafting the EFab RF Storage blocks, the crafting grid won't accept them as a valid Lapotron Crystal.

* **Link to Log or Crash File Paste**: None

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Not sure

* **Known Fix**: We turned off wireless charging long enough to make a few things.

**Comment by tfox83** [comment]
I am not able to edit the NBT data in efab recipes at this time.  It this fix is ever added I can look into it.  You may have to just craft those with wireless charging off for now.
