### ISSUE TITLE
Launch with Compass

### ISSUE THREAD

**Issue by cassoe** [FTBTeam/FTB-Continuum#444]
* **Modpack Version**: 1.4.1

* **Issue**: To change Laser Relays, it must be clicked with Compass. Click with compass will launch you through walls etc.

* **Link to Log or Crash File Paste**: Non

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Actually Additions

* **Known Fix**: No

**Comment by aaronhowser1** [comment]
I don't understand the issue. Right clicking a compass launches you into the air?

**Comment by Proha5** [comment]
i no have this problem.

**Comment by cassoe** [comment]
Well not into the air, it has to pass through something like a wall.

So when I try to click Laser, it just launches me to the other side

**Comment by aaronhowser1** [comment]
I've honestly never heard of this problem. Are you playing on a server that has plugins or something?

**Comment by cassoe** [comment]
After a lot of searching, I found the my son have installed WorldEdit. It is a feature from this mod.
Needless to say, he is grounded the rest of the year :-D :-D
