### ISSUE TITLE
Tree node crash 

### ISSUE THREAD

**Issue by Nickiel12** [FTBTeam/FTB-Continuum#447]
* **Modpack Version**: 1.4.1

* **Issue**: My Game Randomly crashes, this error has happened three times so far.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/22797e13
And here is the full report https://paste.feed-the-beast.com/view/a06abd94

* **Is it Repeatable?**: As said above, it has happened two to three times now

**Comment by tfox83** [comment]
This should be fixed in 1.5.0
