### ISSUE TITLE
crash about 30min on game

### ISSUE THREAD

**Issue by miouwarp** [FTBTeam/FTB-Continuum#448]
Hello

I'm currently playing on the 1.4.1 version of cotinuum solo with 10G ram

the first problem is, when I play, after about 30 min my my game crashes
either it marks "Java platform SE binary" does not answer and imposible to return in the game. Or he disconnects me from the server (I play solo) and can not restart the map after

in both cases I have to relaunch the lanche

thank you

**Comment by modmuss50** [comment]
we need the crash log to understand what is going on.

Thanks.

**Comment by miouwarp** [comment]
where can i find this file?

**Comment by aaronhowser1** [comment]
Right click on the modpack in the Twitch Launcher and then click "Open Folder." There should be a folder in there called "crash-logs" or something similar.

**Comment by miouwarp** [comment]
![sans titre](https://user-images.githubusercontent.com/38194568/44944751-ac4df280-addc-11e8-8395-cef44b7892eb.png)


I do not see any "crash logs" or something similar
here are the files I have in the folder

**Comment by miouwarp** [comment]
no crash-log on folder logs

**Comment by Nickiel12** [comment]
play the game, and when it crashes and you have to kill it, (with task manager?) the minecraft launcher will say, "The Game crashed Sorry, "  Click the "View Crash Report." then click "show More Details." and copy the notepad file to https://paste.feed-the-beast.com/ and copy the url after it is posted, and put it in this thread

**Comment by miouwarp** [comment]
ok I will try this

**Comment by miouwarp** [comment]
I do not have a button to see the crash report
here i have that when i crash java when it crash

![sans titre 2](https://user-images.githubusercontent.com/38194568/44954950-42e8e500-aeab-11e8-9b1c-7f475d886605.png)

**Comment by Nickiel12** [comment]
Did you allocate more RAM? if not read [this thread](https://www.reddit.com/r/feedthebeast/comments/7195n0/how_to_allocate_more_ram_to_sky_factory_3_through/) if you only have 8 GB, put the slider about 4-5ish, if you have 16 like me, i put mine around 7 GB

**Comment by miouwarp** [comment]
Yes
when I do f3 , do not exceed 5G RAM and i allocate 10G RAM

**Comment by Nickiel12** [comment]
I'm sorry, but I don't have any other ideas, and the FTB team seem to be a little slow on the customer service side. Mine crashes on startup, and I was halfway through. I started playing egnimatica 2 expert mode, I am enjoying it, it is similar to continuum, but different in that it focuses on late game automation, not early game grind.

**Comment by Proha5** [comment]
Try use parameters: (in twitch options. not in MC launcher)
-XX:+UseG1GC -Xmx5G -Xms4G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
I used this string for many modpack - its reduce lags and reduce frequency of crash. I have 8Gb RAM - no problem.

**Comment by miouwarp** [comment]
ok but when i go into twitch - mod - ftb continuum - profile option.
I did not enter the options "-XX: + UseG1GC -Xmx5G-Xms4G -Dsun.rmi.dgc.server.gcInterval = 2147483646 -XX: + UnlockExperimentalVMOptions -XX: G1NewSizePercent = 20 -XX: G1ReservePercent = 20 -XX: MaxGCPauseMillis = 50 -XX: G1HeapRegionSize = 32M
"

**Comment by Proha5** [comment]
Here:
![image](https://user-images.githubusercontent.com/29812448/44983797-df031100-afbd-11e8-810c-7271eea35c17.png)

**Comment by miouwarp** [comment]
ok I found, I test and I look if it works

**Comment by miouwarp** [comment]
does not work

**Comment by drcrazy** [comment]
Can you, please, do the following:
1) remove everything from logs folder
2) start game and play till crush
3) Upload latest log file to https://paste.feed-the-beast.com/

**Comment by miouwarp** [comment]
I deleted all log and then I play until the game crashes
here is the notepad in the log after the crash

[latest.log](https://github.com/FTBTeam/FTB-Continuum/files/2361195/latest.log)

upload on paste.feed-the-best:
https://paste.feed-the-beast.com/view/5d086c78

**Comment by miouwarp** [comment]
an idea ?

**Comment by Nickiel12** [comment]
https://paste.feed-the-beast.com/view/e1404d11
Here are some of the errors. Textures are missing. Are you using a texture pack? now this shouldn't be a game breaking crash, but it could be. Have you tried to reinstall the whole pack?

**Comment by miouwarp** [comment]
do not use texture pack and yes I uninstall and reinstall minecraft, twitch and modpack

**Comment by Nickiel12** [comment]
I have another computer that does something very similar, but on a different modpack. What are your computer specs?

**Comment by miouwarp** [comment]
processor: i5-2400 3.10GHZ
RAM: 16 GB
graphics card: Nvidia geforce GTX 1060 G1 gaming 6G
windows 10 64bits

**Comment by tfox83** [comment]
Am not able to reproduce
