### ISSUE TITLE
Quest about Liquid DNA & Gelid Cryotheum

### ISSUE THREAD

**Issue by SihenZhang** [FTBTeam/FTB-Continuum#45]
* **Modpack Version**: 
1.0.2
* **Issue**: 
1. The description of the planet where Liquid DNA is here is wrong. But the Dimension ID is right.
![](https://i.imgur.com/8YIWivW.png)
2. The description of the planet where Gelid Cryotheum is here is wrong. Also the Dimension ID is wrong.
![](https://i.imgur.com/zNYKy1R.png)
![](https://i.imgur.com/lTUV8Ib.png)

**Comment by aaronhowser1** [comment]
Whoops, I started with the honey quest and just copied it over and changed the details. I'll get the names and dimension IDs fixed in the next update
