### ISSUE TITLE
Badly compressed packet (too large) because of Alvearies and Frame Holders

### ISSUE THREAD

**Issue by Unfussable** [FTBTeam/FTB-Continuum#451]
* **Modpack Version**: FTB Continuum 1.4.1

* **Issue**: Hello everyone!

I'm playing the 1.4.1 version of FTB continuum and my server always kicks me when I return to an Alveary with variable bees inside with several (happened with 11 and 17) Careerbees Frame Holders in the Alveary block. Apparently the chunk holds too much information at that point for whatever reason and kicks me because the packet size when trying to load the chunk surpasses the protocol maximum of 2097152 bytes. The chunks in question are usually between 4 and 5 million bytes, so roughly 2x to 2.5x larger than the maximum.

How do I increase this protocol maximum to allow larger chunks to be a thing? Minimizing the bee production is not particularly desirable, so I would like to change the server / client setup. So far I tried changing the network compression threshold in the server properties, but that doesn't seem to be related as it used to be 1024 (doesn't quite fit the 2 million bytes definition) and now is 5120 without any changes to the issue.

The Alveary was filled with different bees, the Frame Holders contained Magic Frames.

EDIT: I went about asking a few people on a few forums and in a few chats about the matter and apparently you'd be needing mods to tap into the source / API of both server and client to increase the value. Is there any available mod I can add to the modpack? And is there a way for you to split the Alveary information into multiple packets, so it doesn't surpass the 2097152 byte maximum? Extremely unsatisfied to be forced to downgrade back to Industrial Apiaries.

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Forestry / Binnie's Extra Bees / Careerbees / MagicBees / XNet

**Comment by tfox83** [comment]
I am not able to fix this pack wide, I am sorry.

**Comment by Philosyang** [comment]
https://minecraft.curseforge.com/projects/bigger-packets-please
Might help for future references.
