### ISSUE TITLE
Efab Crafter not working (Just IDLE)

### ISSUE THREAD

**Issue by Ciberbago** [FTBTeam/FTB-Continuum#452]
* **Modpack Version**: 1.4.1 (With Immersive engineering updated to 0.12-84 to fix the problem of not being able to re-enter a world without restarting the game)

* **Issue**: The Efab crafters are not crafting. I have a setup with AE2, so I provide the storage with materials, but sometimes (a lot of the time) crafting does not work, even though the materials are in the correct item storage and the crafter is provided with redstone signal, I don't know why this happens. When the crafter is working properly I know it because there is a message saying: "Ingredients missing" waiting for the materials, but in this case every crafter does not have any message in it. It just stays idle forever.
(Happens with any crafter btw)
Related images: https://imgur.com/a/E83pwtR

* **Is it Repeatable?**: I tested it in a flat creative world and it happens too, is weird.

* **Mod/s Affected**: Efab

If you know of a fix please let me know! Thanks

**Comment by aaronhowser1** [comment]
Is there an EFab block on there? The block called EFab that you use to manually craft things.

**Comment by Ciberbago** [comment]
Yes, there are 3 of them on top, I'm going to take full screenshot of the structure: https://imgur.com/a/O8edYtw

And now, after a while removing and putting materials, restarting the world, suddendly started working. Is super weird.

**Comment by Proha5** [comment]
I have same bug. Happening at start game.
Temporary fix: at start game you should open and close GUI "efab workbench".

**Comment by MrJoshua68** [comment]
Yeah.  I have been seeing this too.  Then it will just kick in and start working. I havent been able to figure out the trigger, but it hasnt had anything to do with changing any of the blocks in the structure.
It might have to do with opening the eFAB workbench as Proha5 suggested, but its not an immediate thing if so.

**Comment by tfox83** [comment]
Should be fixed in 1.5.0
