### ISSUE TITLE
Running at 1fps

### ISSUE THREAD

**Issue by ItsCaten** [FTBTeam/FTB-Continuum#453]
Modpack Version: 1.4.1

Issue: At first everything was fine, the game was running at around 70fps, I played the modpack for 3 weeks (I've always been using version 1.4.1) then one day I opened the game and it was running at 1fps. I tried adding allocating more ram, I tried reinstalling my modpack, I even reinstalled my windows to see if that would help but nothing worked. 

I really don't know what to do anymore, maybe anyone can help me.

**Comment by Scratchman** [comment]
try lag goggles.. it can do an fps profile for you, it might be something you built lately or another change in the world, ask the admin to install it on the server and run a world scan for you.

https://minecraft.curseforge.com/projects/laggoggles

**Comment by ItsCaten** [comment]
> try lag goggles.. it can do an fps profile for you, it might be something you built lately or another change in the world, ask the admin to install it on the server and run a world scan for you.
> 
> https://minecraft.curseforge.com/projects/laggoggles

Well it isn't just multiplayer, it's singleplayer as well. I can make a completely new world and still get 1fps

**Comment by Scratchman** [comment]
You can also use the mod in a single player game.

**Comment by tfox83** [comment]
I am not able to reproduce without a log.  You can try the suggestion above.
