### ISSUE TITLE
World wont load

### ISSUE THREAD

**Issue by MrJoshua68** [FTBTeam/FTB-Continuum#454]
* **Modpack Version**: 1.4.1
* **Issue**: I have a backup save file that I can load, but any further saves will fail to load.  Even if all I do is load the world and immediately save it the new save will fail to load.  The load screen gets stuck on "0%".
I have downloaded a fresh instance of Continuum and  moved the working backup save file over with no change of behavior.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/91e57c62

* **Is it Repeatable?**: Sadly yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Icebarker** [comment]
try updating Immersive Engineering manually from 0.12 - 83 to 0.12 - 84 like it says in issue #356 . it works for some people so it might work for you, but for me it did not

**Comment by MrJoshua68** [comment]
@Icebarker That worked!  thanks for your help!!  Im sorry it didnt work for you though. This is a tough modpack to loose a world on :(
