### ISSUE TITLE
Suggestion: do nerf Fusion Reactor

### ISSUE THREAD

**Issue by Proha5** [FTBTeam/FTB-Continuum#455]
TechReborn Fusion reactor kill gameplay balance.
Power multiplier is very high.
Base generation is 64Krf. (burn deuterium + lithium, maked from water)
I have 40 coil block. Multiplier is 16.6 x 64Krf =  1.000.000 Rf / t !
Creation coil block is easy at middle-end game. I maked 40 coils during 30 minutes. For comparison:  i create one Red Matter block during 1.5 hours.
64 coils will generate 2Mrf.
Maximum coils will generate - 30Mrf/t.

Helium3+deiterium have more base generation = 128Krf.

May be reduce base generation 64 times less?
For deuterium: from 64Krf to 1Krf
For helium3: from 128Krf to 2Krf.

Then 16 coils will generate 1.74Krf (3.5Krf for Helium3)
64 coils will generate 32Krf (64Krf).
Maximum generating: 500Krf (1Mrf).

**Comment by tfox83** [comment]
It is end game and intended to be powerful.
