### ISSUE TITLE
Bug: Can't select target fluid.

### ISSUE THREAD

**Issue by Proha5** [FTBTeam/FTB-Continuum#456]
1.4.1
I click arrows for select fluid - nothing happening. Label "Select destination" not changing.
Planet Fusionarium.
![image](https://user-images.githubusercontent.com/29812448/45474212-79144780-b77c-11e8-9a76-98421f97468d.png)

**Comment by Proha5** [comment]
I found reason. Localization.
I changed lanquage to english and fluid selector appear.
![image](https://user-images.githubusercontent.com/29812448/45476777-386bfc80-b783-11e8-8163-9e4ec5515a3a.png)

**Comment by tfox83** [comment]
This will need to be fixed by adv rocketry dev.  When the fix is out ill get it in the modpack.  Thanks
