### ISSUE TITLE
Advanced Rocketry broke save file?

### ISSUE THREAD

**Issue by Proha5** [FTBTeam/FTB-Continuum#457]
Singleplayer.
I leaved game (located at Fusionarium orbit).
Now, i return to game. Loading show error.
I have backup. I restore old backup. All files saved at orbit show this error.
Only saved at earth loaded fine.
![image](https://user-images.githubusercontent.com/29812448/45482276-ecc04f80-b790-11e8-8917-b0bccc2e93d1.png)
Please, don't include Advanced Rocketry and EFAB in future modpack. This mods is mega-bugged. Very early beta. Advanced Rocketry have 403 issues.

**Comment by tfox83** [comment]
Known issue, closing as I have no fixes.  Sorry.  Its been reported to dev multiple times.
