### ISSUE TITLE
World killed by satellite

### ISSUE THREAD

**Issue by Berserker66** [FTBTeam/FTB-Continuum#458]
* **Modpack Version**:  1.4.1

* **Issue**: Player sent a satellite up on server, it killed the entire server and now have to restore from backup

* **Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/93b6dac4
https://paste.feed-the-beast.com/view/079bd708

* **Is it Repeatable?**: 
Yes

* **Mod/s Affected**: 
Advanced Rocketry

* **Known Fix**: Nope

**Comment by tfox83** [comment]
Known issue that has been reported to dev. If there is ever a fix I will be sure to get it in
