### ISSUE TITLE
Crash Starting Server

### ISSUE THREAD

**Issue by LynicTaken** [FTBTeam/FTB-Continuum#459]
* **Modpack Version**: 1.4.1

* **Issue**: I try create a server but have a error.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/400a2975

* **Is it Repeatable?**: I try it 4-5 times but..

* **Mod/s Affected**: Forestry? (Its Iroko sapling?)

* **Known Fix**: I can't :(

**Comment by tfox83** [comment]
Not able to repeat, maybe try with a fresh install or wait for 1.5.0 beta to release soon and try.
