### ISSUE TITLE
FTB Continuum crah opening world

### ISSUE THREAD

**Issue by Balda93** [FTBTeam/FTB-Continuum#46]
* **Modpack Version**: FTB Continuum 1.0.2

* **Issue**: When i try to join in to the world the game crashes and show this report. How could i fix it??

* **Link to Log or Crash File Paste** https://paste.feed-the-beast.com/view/4e601a95

**Comment by modmuss50** [comment]
Your advancements may have become corrupted, one thing to try is delete or rename the folder called `advancements` in the world directory.

**Comment by tfox83** [comment]
Try @modmuss50 suggestion, closing this as it cannot be reproduced
