### ISSUE TITLE
Tech reborn ores outside of the intended

### ISSUE THREAD

**Issue by DeeDoubleYous** [FTBTeam/FTB-Continuum#461]
Modpack version: 1.5.0

Tech reborn ores, such as copper, silver, galena and tin are spawning in the world alongside the thermal expansion ores.

Crash log: N/A

it is repeatable

Known Fix: disabling the ores in the cofig files I guess

**Comment by tfox83** [comment]
Hmm all the TR overworld ores are set to false.  
I can confirm this as well with a fresh test world.  I will have @modmuss50 take a look.

![image](https://user-images.githubusercontent.com/4246308/45762644-ab420100-bbe3-11e8-81b5-35aaa6ae11c5.png)


![image](https://user-images.githubusercontent.com/4246308/45762599-949baa00-bbe3-11e8-8c6a-55ec42fdc32b.png)

**Comment by tfox83** [comment]
fixed with 1.5.1 hotfix
