### ISSUE TITLE
Empowerer electronic circuit recipe is not working

### ISSUE THREAD

**Issue by drcrazy** [FTBTeam/FTB-Continuum#462]
Empowerer is not able to craft basic electronic circuit from TechReborn due to AE2 silicon being disabled and there is no recipe to use silicon from refined storage. 

* **Modpack Version**: 1.5.1

* **Is it Repeatable?**:  Yes

* **Known Fix**: Update CT script for TR

![image](https://user-images.githubusercontent.com/1382352/45778727-129e9600-bc62-11e8-80f6-55c7d32ecfb4.png)

**Comment by MrJoshua68** [comment]
@drcrazy Dont suppose you could provide the replacement line in the TR script?  I found in the script the line that needs to be updated, but Im not sure how to track down which elements need to be replaced with what.

**Comment by tfox83** [comment]
fixed in 1.5.2 hotfix
