### ISSUE TITLE
Planet Selector Empty

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Continuum#464]
* **Modpack Version**: 1.5.1

* **Issue**: The Advanced Rocketry Warp Controller will not display any planets if even they are discovered.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes. You can discover a planet manually by editing the files and it will still not show.

* **Mod/s Affected**: Advanced Rocketry

* **Known Fix**: TBD

**Comment by ghost** [comment]
Workaround is to set <isKnown> in the XML for the file in your world list to false. And then manually discover the planets.

**Comment by tfox83** [comment]
known issue with AR, if fix is ever done I will have the latest version in the pack right away.

**Comment by HeberonYT** [comment]
> Workaround is to set in the XML for the file in your world list to false. And then manually discover the planets.

@Communicator17 Hi, could you explain in detail how to solve the problem?
Thank you
