### ISSUE TITLE
Silicon Disabled

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Continuum#465]
* **Modpack Version**: 1.5.1

* **Issue**: There is no crafting recipe for silicon.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: Applied Energistics

* **Known Fix**: Not a fix, but a workaround: I know from version 1.4.1 that silicon was made in the EFAB with sand (and I believe water in a tank), so I tried to create silicon with sand. Instead, it creates an item that has the name 'This item has been disabled'. The 'This item has been disabled' can then be crafted into silicon within a crafting table.

(wanted to help the guy who submitted #463 and provide additional info)

**Comment by tfox83** [comment]
fixed in 1.5.2 hotfix
