### ISSUE TITLE
Environmental tech on multiplayer server not generating ores

### ISSUE THREAD

**Issue by bigsexyjoe** [FTBTeam/FTB-Continuum#468]
* **Modpack Version**: original save file from 1.3.1 issued persists after upgrading to 1.5.1

* **Issue**: ETech Planets are not generating their specific ores. This previous issue details it perfectly: https://github.com/zmaster587/AdvancedRocketry/issues/1325

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Advanced Rocketry

* **Known Fix**: https://github.com/zmaster587/AdvancedRocketry/issues/1325 but it is not working for me
here is my planetDefs.xml file
[planetDefs.zip](https://github.com/FTBTeam/FTB-Continuum/files/2407593/planetDefs.zip)

**Comment by tfox83** [comment]
Known issue, as soon as fix is released, if ever, I will get it in.
