### ISSUE TITLE
Prismarine shortage

### ISSUE THREAD

**Issue by MrJoshua68** [FTBTeam/FTB-Continuum#469]
* **Modpack Version**: 1.5.1

* **Issue**: I need significant amounts of prismarine for the Tier3 Structure Frame, but as far as I can tell the only way to get prismarine is with the Scrap-box-inator which seems WAY to slow to be the way you expect me to do this.
There is supposed to be a recipie to convert nether quartz to prismarine using the Atomic Reconstructor, but it doesnt work.

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: yes

* **Mod/s Affected**: 

* **Known Fix**: none

**Comment by Ludi87** [comment]
Guardians in a Mobspawner should help you out.

**Comment by tfox83** [comment]
during testing we used guardians and had no issues.
