### ISSUE TITLE
FTB Contiuum - Simply Jetpacks 2 Toggle Jetpack keybind broken

### ISSUE THREAD

**Issue by soymac** [FTBTeam/FTB-Continuum#470]
* **Modpack Version**: 1.5.2

* **Issue**:  Simply Jetpack wont turn on. I had it off cause i toggle it on and off during excavations.  I changed the keybinds to different keys and it didnt work. It was working in the previous version. When i updated to the most recent patch it stopped working. 

* **Is it Repeatable?**: Yes. I spawned in a fresh jetpack on and i wasn't able to turn it off. 

* **Mod/s Affected**: Simply jetpacks 2

**Comment by tfox83** [comment]
Try a fresh install or updating to 1.6.0 beta
