### ISSUE TITLE
FTB Contiuum-empowered void crystal

### ISSUE THREAD

**Issue by Papydede** [FTBTeam/FTB-Continuum#471]
. Modpack Version: 1.5.2

Issue : we can not craft empowered void crystal I test the different craft is nothing works

![2018-09-25_06 42 33](https://user-images.githubusercontent.com/10856215/45993764-9c01fe00-c090-11e8-9741-3949cfdc2717.png)

![2018-09-25_06 44 05](https://user-images.githubusercontent.com/10856215/45993765-9c01fe00-c090-11e8-9881-876ad85cadc6.png)

![2018-09-25_06 44 21](https://user-images.githubusercontent.com/10856215/45993767-9c01fe00-c090-11e8-8351-2d43f2d72008.png)

![2018-09-25_06 44 30](https://user-images.githubusercontent.com/10856215/45993768-9c9a9480-c090-11e8-8205-0cdffa0b546c.png)

Is it Repeatable?:yes 

Mod/s Affected: actually additions

**Comment by Kratzwurst** [comment]
Same Issue with Empowered Palis Crystal and Enori. After crafting was deleted the Block/Item. 

Normal Crafting without  AE2 works fine.

Edit: Issue importing in AE2 System, Interface, Import Bus doesn't work for Actually Additions

V 1.5.2 Server

**Comment by tfox83** [comment]
Using a hopper as a work around seems to work.  This issue maybe resolved in latest beta of pack 1.6.0 as it worked for me in testing today.  That should be out later today.
