### ISSUE TITLE
Immersive engineering Assembler won't assemble small piles of dusts

### ISSUE THREAD

**Issue by randknu** [FTBTeam/FTB-Continuum#474]
Version 1.4.1

* **Issue**: Immersive engineering Assembler won't assemble small piles of dusts from an industrial grinder. It will however combine small piles of emerald and peridot dusts. It seems to only affect the dusts that is smeltable afterwards

* **Link to Log or Crash File Paste**: There is no error or crash to find in the logs

* **Is it Repeatable?**: Yes tried many times, works on anything else but not the small piles of dust from zinc, tin, nickel, iron, copper, platinum or gold.

* **Mod/s Affected**: Immersive engineering, but could be a result of tweaking recipes too.

**Comment by randknu** [comment]
Correction, it Does work with small pile of nickel for some reason. Just not the other types.

**Comment by tfox83** [comment]
Fixed in latest beta
