### ISSUE TITLE
Game crashes when i open inventory

### ISSUE THREAD

**Issue by Darkestlink** [FTBTeam/FTB-Continuum#475]
When i open the inventory, it crashes

**Comment by modmuss50** [comment]
Have you got the log file?

**Comment by Darkestlink** [comment]
[2018-09-26-5.log.gz](https://github.com/FTBTeam/FTB-Continuum/files/2444397/2018-09-26-5.log.gz)

**Comment by tfox83** [comment]
Please try to update to 1.6.0 beta.  I am not able to reproduce this issue.
