### ISSUE TITLE
Unable to make silicon with Efab 

### ISSUE THREAD

**Issue by Fenris05** [FTBTeam/FTB-Continuum#477]
* **Modpack Version**: 1.5.2 

* **Issue**: when using the Efab to craft silicon it still produces silicon with the ore dictionary of the AE version which is disabled now. 

* **Link to Log or Crash File Paste**: No crash.

* **Is it Repeatable?**: yes.

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Kratzwurst** [comment]
Change the Recipes Silicon to Silicon Ingots from Vulpes... or from Refined Storage. AE2 Silicon was disabled

**Comment by tfox83** [comment]
There has always been an alt recipe for RS silicon in the eFab, but I have removed the AE2 one now to avoid confusion.
