### ISSUE TITLE
Refined Storage's Solderer still in Better Questing

### ISSUE THREAD

**Issue by johnkernke** [FTBTeam/FTB-Continuum#478]
* **Modpack Version**: 1.5.2

* **Issue**: Refined Storage's Solderer still in Better Questing, causing it not to be progress-able

* **Link to Log or Crash File Paste**: NA

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Better Questing / Continuum

* **Known Fix**: Remove the required item from the quest file

**Comment by tfox83** [comment]
Fixed in 1.6.0 beta

**Comment by MateuszKaput** [comment]
No it isn't
https://github.com/FTBTeam/FTB-Continuum/issues/532
