### ISSUE TITLE
No tiny zinc dust recipe

### ISSUE THREAD

**Issue by MrJoshua68** [FTBTeam/FTB-Continuum#479]
* **Modpack Version**:1.5.1

* **Issue**: There is no recipe to combine 4 tiny zinc dust into zinc dust.

* **Link to Log or Crash File Paste**: None

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by Foxbond** [comment]
Bump.

The only way to create zinc from tiny piles is to throw them into Tinker's Smeltery

**Comment by tfox83** [comment]
![image](https://user-images.githubusercontent.com/4246308/50937532-fbf69780-1428-11e9-83e3-2958c71dfde0.png)
This works fine for me in latest 1.6.0 beta
