### ISSUE TITLE
Quark Auto Jump Key Disabled via Config.

### ISSUE THREAD

**Issue by StoneLegion** [FTBTeam/FTB-Continuum#48]
I like to suggest it be added again:
B:"Auto jump hotkey"=false

When you do this instead of it setting to none it disables the key perm till you enabled it via the client again.

There is still tons of conflicts anyways since you are not fixing those i don't see what one more would hurt.

Thanks.

**Comment by tfox83** [comment]
that is only set up for first install, once you have the pack installed and set keybinds up yourself it will keep those settings.  I want to give people the option of using that since its a MC feature now, but I just ship it not binded so people can customize their keys to the way they like once.
