### ISSUE TITLE
rocket spawning at bedrock when i return to earth causing death

### ISSUE THREAD

**Issue by cowmoomoo406** [FTBTeam/FTB-Continuum#481]
-->

* **Modpack Version**: 1.4.1 server that was created around 2 weeks ago.
* **Issue**: when returning to earth on a rocket, it spawns you at bedrock causing you to die and the rocket is lost forever. kind of annoying.

* **Link to Log or Crash File Paste**: none

* **Is it Repeatable?**: yes, every time.

* **Mod/s Affected**:advanced rocketry
* **Known Fix**: < if you know of a fix please let me know! Thanks -->

**Comment by tfox83** [comment]
fixed in 1.6.0
