### ISSUE TITLE
crashes when I try to play the modpack

### ISSUE THREAD

**Issue by McMoaldSaysHI** [FTBTeam/FTB-Continuum#483]
* **Modpack Version**: Version 1.5.2. I just downloaded it today.

* **Issue**: Inside the Minecraft Launcher, when I press play, it will crash right after.

* **Link to Log or Crash File Paste**: 

23:04:32 | launcher | main | info | Minecraft client forge-14.23.4.2759 is ready to start.
-- | -- | -- | -- | --
23:04:32 | launcher | main | info | Starting!
23:04:32 | launcher | main | info | Using default game log configuration client-1.12.xml (outputs XML)
23:04:33 | LaunchWrapper | main | info | Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
23:04:33 | LaunchWrapper | main | info | Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
23:04:33 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
23:04:33 | FML | main | info | Forge Mod Loader version 14.23.4.2759 for Minecraft 1.12.2 loading
23:04:33 | FML | main | info | Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at E:\Marcos\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_51
23:04:33 | FML | main | warn | The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
23:04:33 | FML | main | warn | The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
23:04:33 | FML | main | info | Searching E:\Marcos\Documents\Curse\Minecraft\Instances\FTB Continuum\mods for mods
23:04:33 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.1.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
23:04:33 | FML | main | warn | The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
23:04:33 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.1.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
23:04:33 | FML | main | warn | The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
23:04:33 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in bedpatch-2.2-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
23:04:33 | FML | main | info | Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
23:04:33 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-0.3.1.16.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
23:04:33 | FML | main | warn | The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
23:04:33 | FML | main | warn | The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
23:04:33 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12.2-0.3.2.18.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
23:04:33 | FML | main | warn | The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
23:04:33 | FML | main | warn | The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
23:04:33 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in elulib-0.1.12.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
23:04:33 | FML | main | warn | The coremod FMLPlugin (elucent.elulib.asm.FMLPlugin) is not signed!
23:04:33 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.1-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
23:04:33 | FML | main | warn | The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
23:04:33 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in foamfix-0.9.9.1-1.12.2-anarchy.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
23:04:33 | FML | main | warn | The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
23:04:33 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in Forgelin-1.7.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
23:04:33 | FML | main | warn | The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
23:04:33 | FML | main | warn | The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
23:04:33 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
23:04:33 | FML | main | warn | The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
23:04:33 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in OpenModsLib-1.12.2-0.11.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
23:04:33 | FML | main | warn | The coremod openmods.core.OpenModsCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
23:04:33 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in Quark-r1.4-125.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
23:04:33 | FML | main | warn | The coremod vazkii.quark.base.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
23:04:33 | FML | main | warn | The coremod LoadingPlugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
23:04:33 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in Quark-r1.5-129.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
23:04:33 | FML | main | warn | The coremod vazkii.quark.base.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
23:04:33 | FML | main | warn | The coremod LoadingPlugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
23:04:34 | FML | main | warn | Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
23:04:34 | FML | main | warn | The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
23:04:34 | FML | main | warn | The coremod pl.asie.splashanimation.core.SplashAnimationCoremod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
23:04:34 | FML | main | warn | The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
23:04:34 | LaunchWrapper | main | info | Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
23:04:34 | LaunchWrapper | main | info | Loading tweak class name codechicken.asm.internal.Tweaker
23:04:34 | LaunchWrapper | main | info | Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
23:04:34 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
23:04:34 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
23:04:34 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
23:04:35 | FML | main | info | Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
23:04:35 | FML | main | error | FML appears to be missing any signature data. This is not a good thing
23:04:35 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
23:04:35 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
23:04:35 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
23:04:35 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
23:04:35 | LaunchWrapper | main | info | Calling tweak class codechicken.asm.internal.Tweaker
23:04:35 | STDOUT | main | info | [codechicken.asm.internal.Tweaker:injectIntoClassLoader:30]: false
23:04:35 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
23:04:35 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
23:04:36 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
23:04:36 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
23:04:36 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
23:04:36 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
23:04:36 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
23:04:36 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
23:04:36 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
23:04:36 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
23:04:36 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
23:04:36 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
23:04:36 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
23:04:36 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
23:04:36 | LaunchWrapper | main | info | Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
23:04:36 | LaunchWrapper | main | info | Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
23:04:36 | LaunchWrapper | main | info | Launching wrapped minecraft {net.minecraft.client.main.Main}
23:04:36 | STDOUT | main | info | [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:110]: pl/asie/foamfix/coremod/patches/IFoamFixWorldRemovable
23:04:36 | STDOUT | main | info | [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:113]: Added INTERFACE: pl/asie/foamfix/coremod/patches/IFoamFixWorldRemovable
23:04:36 | STDOUT | main | info | [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:150]: Added METHOD: net.minecraft.world.World.foamfix_removeUnloadedEntities
23:04:36 | STDOUT | main | info | [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:110]: pl/asie/foamfix/coremod/patches/IFoamFixWorldRemovable
23:04:36 | STDOUT | main | info | [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:113]: Added INTERFACE: pl/asie/foamfix/coremod/patches/IFoamFixWorldRemovable
23:04:36 | STDOUT | main | info | [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:126]: Spliced in METHOD: net.minecraft.world.World.foamfix_removeUnloadedEntities
23:04:36 | STDOUT | main | info | [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:110]: pl/asie/foamfix/coremod/patches/IFoamFixWorldRemovable
23:04:36 | STDOUT | main | info | [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:113]: Added INTERFACE: pl/asie/foamfix/coremod/patches/IFoamFixWorldRemovable
23:04:36 | STDOUT | main | info | [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:126]: Spliced in METHOD: net.minecraft.world.World.foamfix_removeUnloadedEntities
23:04:36 | STDOUT | main | info | [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:110]: pl/asie/foamfix/coremod/patches/IFoamFixWorldRemovable
23:04:36 | STDOUT | main | info | [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:113]: Added INTERFACE: pl/asie/foamfix/coremod/patches/IFoamFixWorldRemovable
23:04:36 | STDOUT | main | info | [pl.asie.foamfix.coremod.FoamFixTransformer:spliceClasses:126]: Spliced 
in METHOD: net.minecraft.world.World.foamfix_removeUnloadedEntities
23:04:36 | LaunchWrapper | main | error | Unable to launch java.lang.reflect.InvocationTargetException 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:497) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/World 	at net.minecraft.client.main.Main.main(SourceFile:38) 	... 6 more Caused by: java.lang.ClassNotFoundException: net.minecraft.world.World 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	... 7 more Caused by: java.lang.ClassFormatError: Duplicate interface name in class file net/minecraft/world/World 	at java.lang.ClassLoader.defineClass1(Native Method) 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) 	... 9 more
16:04:36 | game |   | error | Exception in thread "main"   <log4j:Event logger="STDERR" timestamp="1539497076352" level="INFO" thread="main">     <log4j:Message><![CDATA[[java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException]]></log4j:Message>   </log4j:Event>
16:04:36 | monitor | Process Monitor | error | expected <
23:04:36 | STDERR | main | info | [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
23:04:36 | STDERR | main | info | [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
23:04:36 | STDERR | main | info | [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
23:04:36 | STDERR | main | info | [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
23:04:36 | STDERR | main | info | [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
23:04:36 | STDERR | main | info | [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
23:04:36 | launcher | main | info | Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
16:04:36 | monitor | Process Monitor | fatal | Process crashed with exit code 1

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: No clue.

* **Known Fix**: If you know of a fix please let me know! Thanks

**Comment by tfox83** [comment]
Please use pastebin when posting reports.

Try a fresh install of the pack.
