### ISSUE TITLE
Bad compatibility between Immersive Eng. and Thermal Exp.

### ISSUE THREAD

**Issue by DonKastrolCZ** [FTBTeam/FTB-Continuum#484]
* **Modpack Version**:1.5.2
* **Issue**: Not working transmiting energy from IE connectors to TE energyducts

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: it repeats everytime I load the world

* **Mod/s Affected**: Immersive Engineering, Thermal Expansion
* **Known Fix**: When I replace the IE connector it's ok, but when it is somewhere far with bad access...

**Comment by aaronhowser1** [comment]
Can you post a screenshot?

**Comment by DonKastrolCZ** [comment]
You can see there. I just saved and loaded again to that world.
![2018-10-10_21 09 03](https://user-images.githubusercontent.com/44030333/46760057-3b4e0480-ccd1-11e8-8b80-8d3ce840a0d1.png)
![2018-10-10_21 09 45](https://user-images.githubusercontent.com/44030333/46760058-3b4e0480-ccd1-11e8-849c-b4ab1eebe039.png)

**Comment by MrJoshua68** [comment]
Im doing this with MV and HV connectors  and its working just fine.  I havent tried it with LV though....

**Comment by DonKastrolCZ** [comment]
Maybe I'll try to reinstall modpack. Thanks

**Comment by Foxbond** [comment]
Bump, issue still persists.

Every time you reload world (restart server/SP game) they stop working and must be replaced.

**Comment by tfox83** [comment]
Its safest to use a storage buffer between the connectors.  Its a hit and miss issue.
