### ISSUE TITLE
Thermal Dynamics covers appear completely black

### ISSUE THREAD

**Issue by natacreata** [FTBTeam/FTB-Continuum#485]
1.5.2

Thermal Dynamics covers - in placement preview and once placed down in the world, textures are completely black, regardless of the initial block used to set the texture.

This appears to be specific to Thermal Dynamics cover textures/blocks
![2018-10-11_17 28 13](https://user-images.githubusercontent.com/20807922/46835877-6a21b480-cd7d-11e8-9baf-3a9e52afdda7.png)

**Comment by tfox83** [comment]
Fixed in 1.6.0 beta
