### ISSUE TITLE
ftb continuum crashes while the mods are loading 

### ISSUE THREAD

**Issue by crossredgamer** [FTBTeam/FTB-Continuum#487]
* **Modpack Version**: 1.5.2

* **Issue**: when I start to load up the modpack in 4/7 it crash

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/b55e7bae 

* **Is it Repeatable?**: 

* **Mod/s Affected**: thermal expansion ( I think )

* **Known Fix**:  if you know of a fix please let me know! Thanks -->

**Comment by tfox83** [comment]
Please try a fresh install, we are not able to reproduce
