### ISSUE TITLE
Lab stand doubles item when broken

### ISSUE THREAD

**Issue by a-khmilevskiy** [FTBTeam/FTB-Continuum#488]
**1.5.2**: 

* **Lab stand doubles item when broken

WTR:
1. place lab stand in the world
2. give it an item
3. break lab stand with an pickaxe

What do we see:
Lab stand drops 2 items

**Comment by jd-ihm** [comment]
This is still occurring today :(

**Comment by Jadeon** [comment]
Still happening today :(.

**Comment by tfox83** [comment]
Fixed in 1.6.0 beta
