### ISSUE TITLE
Disappearing crystal growth accelerator

### ISSUE THREAD

**Issue by MrJoshua68** [FTBTeam/FTB-Continuum#489]
* **Modpack Version**: 1.5.2

* **Issue**: No patterns that I can see.  Its connected to my ME system, it works just fine.  I can be there for many hours of play, then suddenly its just gone.  Its connected to an ME Interface with a transfer node pulling items out and back to the ME interface and those remain in place when it disappears.  The next time it happens, I will try switching to itemducts just to change something up.
Its happened 4 times in the last month or so.

Nothing else is randomly disappearing or showing odd behavior.

* **Link to Log or Crash File Paste**: none

* **Is it Repeatable?**: yes

* **Mod/s Affected**: 

* **Known Fix**: cheat it back.

**Comment by tfox83** [comment]
This is hopefully fixed in 1.6.0.  It has been a known issue forever.  I cant get it to repeat with newest beta of the pack
