### ISSUE TITLE
[Edit: Slightly]Completely broken game, possibly mod id mix-up

### ISSUE THREAD

**Issue by PROMETHIA-27** [FTBTeam/FTB-Continuum#490]
Modpack Version: 1.5.2

Issue: Many issues seemingly related to id mismatches. There are bushes made of stained glass and mahogany door bottoms, trees made of some complicated machinery for the trunk and a different type of door bottom for leaves, stone axes can't be crafted, wooden tools of any kind have 2 durability. Couldn't get past here to find more bugs since it would take forever to progress even a little, and might be impossible without stone tools. Also, this bug(s) occurred to my friend who downloaded using the launcher at the same time as me.

Link to Log or Crash File Paste: https://paste.feed-the-beast.com/view/53dee469

Is it repeatable: Yes

Mod/s Affected: N/A

Known Fix: N/A

**Comment by aaronhowser1** [comment]
Wooden tool durability is intended, and Stone tools are made in the EFab. The other things are definitely bugs though. Is this on a new world or an old one?

**Comment by PROMETHIA-27** [comment]
This occurs on a new world. Both me and my friend downloaded just a day or two ago, and on either of us making a world, it creates trees and such like that, but only rarely. Actually, I don't think I've seen those trees in a while, as we spawned right next to a broken tree and bush in the first world we loaded and then in subsequent worlds I made, I found little or none of them. Will fly around in creative and try to find more later.

**Comment by aaronhowser1** [comment]
If you keep finding them, you could try reinstalling the instance from scratch.

**Comment by PROMETHIA-27** [comment]
I made a new world, and I couldn't find any more weird trees. Assuming that 2 wood planks per log and 2 sticks per wood plank is also intended, this issue is solved. I'd say it was either reinstalling or clicking "repair minecraft" fixed it.
