### ISSUE TITLE
Having Issues Crafting Multiple Items

### ISSUE THREAD

**Issue by toneyam** [FTBTeam/FTB-Continuum#491]
FTB Continuum Minecraft 1.12.2

I have been having issues crafting several items from the quest book since we started playing. The first one was the EFab Crafting Grid. I put all of the correct ingredients into the boxes, but there was nothing in the product box to the right. We couldn't figure it out so the admin just spawned a few so we could move on. Now, I am trying to craft the Clockwork Engine, and I'm having the same issue. I know I have all the right ingredients, so why is it not working? Please see images for details.
![image](https://user-images.githubusercontent.com/20804295/47604499-5eaacc00-d9c0-11e8-982e-4793a34ada70.png)

![image](https://user-images.githubusercontent.com/20804295/47604506-6b2f2480-d9c0-11e8-917d-013568280219.png)

**Comment by aaronhowser1** [comment]
Is that the right recipe? Continuum uses changed recipes, so check JEI to see if those are the right items. Are you using the latest version of Continuum?

**Comment by tfox83** [comment]
Also make sure if playing on a server they have the script files installed.  If not you can try to update to 1.6.0 beta that is coming out later today
