### ISSUE TITLE
Cooking for Blockhead item spawning

### ISSUE THREAD

**Issue by PeppeJ** [FTBTeam/FTB-Continuum#492]
* **Modpack Version**: 1.5.2 

* **Issue**: Trying to cook anything that needs the furnace causes items to be spawned. I have 25 raw mutton, upon spamming "cook mutton" i keep getting stacks of 64 of raw mutton.

* **Link to Log or Crash File Paste**: -

* **Is it Repeatable?**:  Yes

* **Mod/s Affected**: Cooking for Blockheads

* **Known Fix**: -

**Comment by PeppeJ** [comment]
Was a bug in Cooking for Blockheads, fixed in 6.4.65

https://minecraft.curseforge.com/projects/cooking-for-blockheads/files/2620498

Known Fix: Update to 6.4.65

> Fixed smelting recipes either resulting in item loss or free food

**Comment by tfox83** [comment]
Fixed in 1.6.0
