### ISSUE TITLE
no chunkloader recipe

### ISSUE THREAD

**Issue by SpongebobFan123** [FTBTeam/FTB-Continuum#494]
* **Modpack Version**: <1.5.2>

* **Issue**: <no chunkloader recipe>

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: <yes>

* **Mod/s Affected**: 

* **Known Fix**: <can we add a recipe to the tech reborn chunkloader?>

**Comment by aaronhowser1** [comment]
Use the FTBUtilities chunkloader. In the inventory click the map on the side, then click on a chunk to claim it to yourself. Hold control while clicking a chunk you've claimed to chunkload it while you're online.
