### ISSUE TITLE
infinite crude oil

### ISSUE THREAD

**Issue by IrishPankake** [FTBTeam/FTB-Continuum#495]
in version 1.5.2, when a crude oil can, from forestry, (got it from a quest) is put into the distillation tower from immersive engineering the can never runs out. haven't tested it with other IE machines but i  assume that it does the same thing

**Comment by ComradeAnthony** [comment]
I second this, I'm running a server on version 1.5.2 and the crude oil can from forestry is giving my distillation tower infinite crude oil.

**Comment by fmohican** [comment]
I can confirm, infinite crude oil 💯 
[https://i.imgur.com/p8sCBvX.png](https://i.imgur.com/p8sCBvX.png)

**Comment by tfox83** [comment]
Fixed in 1.6.0
