### ISSUE TITLE
Broken recipe

### ISSUE THREAD

**Issue by Eifekk** [FTBTeam/FTB-Continuum#497]
* **Modpack Version**: FTBContinuum-1.5.2-1.12.2

* **Issue**: broken/missing recipe for "Kitchen Cabinet" from cooking for blockheads. shows in jei but no recipe for it.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes, persistent in Modpack

* **Mod/s Affected**:  CookingForBlockheads_1.12.2-6.4.61

* **Known Fix**: This was an issue with that particular release of the mod, this is fixed in later version. Fix by updating to newest version.

**Comment by tfox83** [comment]
Fixed in 1.6.0
