### ISSUE TITLE
Cannot click on grindstone quest "Arm's Length"

### ISSUE THREAD

**Issue by jaredbeck** [FTBTeam/FTB-Continuum#498]
* **Modpack Version**: 1.5.2

* **Issue**: Cannot click on grindstone quest "Arm's Length"

* **Link to Log or Crash File Paste**: necessary for this bug?

* **Is it Repeatable?**: yes 100% of the time, even after quitting FTB and restarting

* **Mod/s Affected**: ae2, i guess? or, is Better Questing a mod?

* **Known Fix**: spam clicks on the bottom border of what should be its hitbox. seems to be a 1-pixel wide margin that works, below (outside) the icon

**Comment by tfox83** [comment]
Maybe adjust you GUI size and see.  I am not able to reproduce this in 1.6.0 beta

**Comment by jaredbeck** [comment]
Thx, I no longer play Continuum (too grindy for me, no pun intended, switched to Revelation) but if I ever go back to Continuum I'll try that. Thx for making packs!
