### ISSUE TITLE
Metal Press Gear Mold

### ISSUE THREAD

**Issue by mtimyself** [FTBTeam/FTB-Continuum#50]
* **Modpack Version**:  1.0.2

* **Issue**: 
The Metal Press does not accept ingots when a Gear Mold is active.
JEI shows the recipes.
It does work with Plates.

**Comment by Xavion3** [comment]
This likely isn't a bug. The gear recipes require 4 ingots at once, so the metal press only accepts 4 at once. If you try to feed it with a hopper or similar that only inputs 1 ingot at a time that'll never work as 1 ingot isn't a valid recipe input for a gear.

Use a different method of transporting items or just throw the items onto the conveyor. A hopper feeding into a conveyor belt which feeds into the metal press can work, as IE conveyors work just fine with metal presses.

**Comment by 016Nojr** [comment]
Please try what @Xavion3 is suggesting, @mtimyself

**Comment by mtimyself** [comment]
I remember that in 1.7.10 it would "stack up" the ingots in front of the press until it had 4.
If I feed ingots onto a conveyor they "pop off" the belt when reaching the press.
Only because an item stack of 4 ingots accumulates as entities in the world does it then work.
It does seem like something is not working as intended here.

**Comment by tfox83** [comment]
I am not able to reproduce this issue, as @Xavion3 suggested its not a bug.
