### ISSUE TITLE
World loading stuck at 0%

### ISSUE THREAD

**Issue by Demonhorde** [FTBTeam/FTB-Continuum#500]
* **Modpack Version**: 1.5.2

* **Issue**: World loading will get stuck at 0% and not work, creating a new world will fix it shortly but eventually come back, preventing me from ever getting past the early stages before having to restart

* **Link to Log or Crash File Paste**: N/A game dosen't crash

* **Is it Repeatable?**: Yes, it should appear on any world the 4th or 5th time you try to load it

* **Mod/s Affected**: N/A

* **Known Fix**: N/A

**Comment by tfox83** [comment]
Try a reinstall of the pack, also you can try the latest 1.6.0 beta coming out later today
