### ISSUE TITLE
Duplication Bug (any item that is stackable)

### ISSUE THREAD

**Issue by EastArctica** [FTBTeam/FTB-Continuum#501]
* **Modpack Version**: 1.5.2
* **Issue**: Any item that is stack able can be duplicated
* **Link to Log or Crash File Paste**: N/A
* **Is it Repeatable?**: Yes. 
1) Take a un-powered Crafting grid from Refined Storage
2) Take the item you want to duplicate with and put it in the first slot 
3) Hold Shift and click the item repeatedly (You will have to move your mouse)
4) Done! Each click will duplicate the item by 2x
* **Mod/s Affected**: Refined Storage V1.6.5

* **Known Fix**: Update Refined Storage to the latest or anything above 1.6.5

**Comment by tfox83** [comment]
Fixed in 1.6.0 of the pack
