### ISSUE TITLE
Stoneblock server

### ISSUE THREAD

**Issue by PinkEyeGuy** [FTBTeam/FTB-Continuum#502]
I had 2 small storage crates go missing as well as the things in them i was helped by solclaim as much as he/she could but i was unable to have my loot chests from the quests restored to me IGN: Pink_Eye_Guy

**Comment by aaronhowser1** [comment]
This is the issue tracker for the mod pack Continuum, not the Stoneblock server you play on. Try messaging the ops or admins of the server and see if they can help you.
