### ISSUE TITLE
unable to connect to server;no reason specified

### ISSUE THREAD

**Issue by slav-kun** [FTBTeam/FTB-Continuum#503]
Version : 1.5.2

I am unable to join servers, and cannot find any reason as to why 

https://pastebin.com/VyyRZNsf

Repeatable

**Comment by slav-kun** [comment]
![capture](https://user-images.githubusercontent.com/45678012/49626137-13f87880-f99e-11e8-80cf-91ad04a66fca.PNG)

**Comment by tfox83** [comment]
Try a fresh install of client/server.  1.6.0 beta will be out later
