### ISSUE TITLE
I.F. Potion Brewer not Brewing

### ISSUE THREAD

**Issue by Larlanen** [FTBTeam/FTB-Continuum#504]
* **Modpack Version**: 1.5.2

* **Issue**: Industrial Foregoing Potion Brewer not moving past the first step of filling jars with water.  I'm trying to brew Potion of Swiftnedd Speed II.  The machine has power, water, and the ingredients.  It fills 3 bottles with water and shifts them over to the first 'potions items outputs' slot. It then switches to indicate it is adding the nether wart but nothing happens.  If I right click the water bottles and remove two of them the brewer will turn the remaining one into an awkward potion and then continue operation until making one swiftness potion.  I believe what is happening is that when the machine fills the three bottles, they are supposed to be spread among the three 'potions items output' slot.  Instead they are stacking in the first slot for whatever reason and that's causing the machine to cease functioning.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/4cd913ee

* **Is it Repeatable?**: Yes.  I've rebooted my game and the server with no success.  

* **Mod/s Affected**: Industrial Foregoing

* **Known Fix**: I've been searching google and forums for relevant information but haven't found anyone reporting the same issue.

**Comment by tfox83** [comment]
Fixed in 1.6.0
