### ISSUE TITLE
Tank for Efab not craftable

### ISSUE THREAD

**Issue by MrScrewIt** [FTBTeam/FTB-Continuum#505]
Version 1.5.2

Efab tank not craftable, therefore cannot progress in pack

No Crash

Repeatable

Efab and the Quest book

I spent a long time trying to figure out how to make the casing, only to find out the tank isn't craftable. I've used the JEI shortcut to put the parts in the table, did it manually, and even tried different tables. However, nothing seemed to work.

Here are 3 different images of different crafting benches (Tconstruct, forestry, and AA)

![2018-12-12_21 11 44](https://user-images.githubusercontent.com/45838924/49915388-9677b100-fe52-11e8-8a02-0c24591fa268.png)

![2018-12-12_21 12 49](https://user-images.githubusercontent.com/45838924/49915420-bb6c2400-fe52-11e8-9659-2bb870a6eb55.png)

![2018-12-12_21 13 06](https://user-images.githubusercontent.com/45838924/49915421-bdce7e00-fe52-11e8-9c8e-a5e179392812.png)

**Comment by tfox83** [comment]
![image](https://user-images.githubusercontent.com/4246308/50936884-5d693700-1426-11e9-8abb-e706ccc15f3f.png)
Works fine for me.  Maybe try with latest 1.6.0 beta when it comes out
