### ISSUE TITLE
Server CPU usage sits at 100%, tps below 12

### ISSUE THREAD

**Issue by Foxbond** [FTBTeam/FTB-Continuum#506]
* **Modpack Version**: 1.5.2 (Latest)

* **Issue**: Server CPU usage sits at 100%, tps around 10-15. I tried removing all loaded chunks, killing all mobs (both neutral and hostile) disabling all machines. There is no messages in log other than "Can't keep up! Did the system time change, or is the server overloaded". 90% of CPU time is consumed by levels\world\tick\entities\regular\tick and half of it being "travel" or "unspecified".

Profiler was running for around 5 min, I can't run it for longer because hosting provider kills my server every time. Also it is not possible for me to download server and run it locally due to small mobile data plan (server size is aroud 5 GB)

* **Link to Log or Crash File Paste**: Profiler log: https://pastebin.com/UZNHpjZy

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: n/a

* **Known Fix**: n/a

**Comment by tfox83** [comment]
More than likely complex builds.  Maybe try with a new world, or thin out some builds on your server.  Also depending on your server specs it may be a lower end CPU
