### ISSUE TITLE
Rocket Crashes the server when you build or launch it/

### ISSUE THREAD

**Issue by VicCamoCraft** [FTBTeam/FTB-Continuum#507]
* **1.5.2**: 

* **Everytime someone builds or tries to launch a rocket the server crashes. I'm currently playing on ToastyNetworks. This really ruins the progression of the quests since we can't get Charcoal logs and other blocks that are required for ProjectRed/**: 

* **Yes, every time a player launches/builds the rocket**:

**Comment by tfox83** [comment]
Fixed in 1.6.0
