### ISSUE TITLE
Fusion Reactor Does NOT Output Power

### ISSUE THREAD

**Issue by bunnyman14** [FTBTeam/FTB-Continuum#508]
* **Modpack Version**: 1.5.2-1.12.2

* **Issue**: No method I try of extracting power out of a fusion reactor (Out of the top or bottom of the Control Block) works. I have tried HV power connectors from IE, and Cryostabilized ducts from TE.

* **Link to Log or Crash File Paste**: No crash.

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Tech Reborn

* **Known Fix**: ???

**Comment by tfox83** [comment]
Please try again in latest beta 1.6.0.  I was not able to reproduce this

**Comment by bunnyman14** [comment]
Still does not work. These resonant ducts don't take it either. Here's a screenshot.
![2019-01-19_22 24 13](https://user-images.githubusercontent.com/7276888/51434884-012dc080-1c39-11e9-830b-d8bb3b714c28.png)
Neither Resonant fluxduct has power. What did you use to extract power?
