### ISSUE TITLE
Quest Not Letting Me Redeem Reward

### ISSUE THREAD

**Issue by freetechtip** [FTBTeam/FTB-Continuum#510]
* **Modpack Version**: 1.5.2

* **Issue**: The Baking Bad (#6) quest will be marked as complete but I can't redeem the reward. 

* **Link to Log or Crash File Paste**: Heres a youtube video of the issue: https://youtu.be/iWa8r0X7RIs

* **Is it Repeatable?**: Yes. I tried /bq_admin reset 6, which reset the quest, and the issue persisted.

**Comment by aaronhowser1** [comment]
This is a choice reward. Click on the reward you want, either the Coal Coke or the Creosote, then you can claim it.
