### ISSUE TITLE
Binnie's Genetics Easy Polymerization

### ISSUE THREAD

**Issue by bunnyman14** [FTBTeam/FTB-Continuum#511]
* **Modpack Version**: 1.5.2-1.12.2

* **Issue**:  Polumerization of DNA Sequences can easily be cheated by putting unpolymerized sequences in an Item Repairer block from Actually Additions.

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Easily

* **Mod/s Affected**: Binnie's Genetics, Actually Additions

* **Known Fix**: Blacklist DNA Sequences

**Comment by tfox83** [comment]
Unfourtanally there is only a whitelist available for the repairer, no way for me to disable an item.  Ill shoot a message over to the dev and see what can happen
