### ISSUE TITLE
CustomPort [suggestion]

### ISSUE THREAD

**Issue by fmohican** [FTBTeam/FTB-Continuum#512]
Just a simple suggestion, can CustomPort (or other mod like) be included in modpack? It's just simple mod to start world in land with specific port instead of random port

[CustonPort](https://minecraft.curseforge.com/projects/customport)
[Server Properties for LAN](https://minecraft.curseforge.com/projects/server-properties-for-lan)

Thanks you.

**Comment by bunnyman14** [comment]
Took me a minute to figure out what this is supposed to say.

You can add mods yourself to the pack. The mod you described would affect a very select few players.

**Comment by fmohican** [comment]
I added already xD
Well thanks for reply.
