### ISSUE TITLE
Easy fluid duplication with Extra Cells 2

### ISSUE THREAD

**Issue by bunnyman14** [FTBTeam/FTB-Continuum#513]
I'm finding LOTS of bugs aren't I?

https://user-images.githubusercontent.com/7276888/50745004-c87ff700-11f5-11e9-8b2b-0f031b132408.png

* **Modpack Version**: 1.5.2

* **Issue**: Placing a CELL from Tech Reborn that contains a fluid into a ME Fluid Terminal, with valid storage of course (mine was partitioned for Destabilized Redstone and Resonant Ender), will cause 1000mb of that fluid to enter the ME system, but not empty the Cell (it just puts it in the output slot, still filled). If UU Matter were still a fluid, Soaryn would be very pleased.
![2019-01-06_20 57 54]

* **Link to Log or Crash File Paste**: No crashlog

* **Is it Repeatable?**: As stated, it's repeatable with Resonant Ender and Destabilized Redstone

* **Mod/s Affected**: Tech Reborn, AE2, Extra Cells, every mod that adds fluids.

* **Known Fix**: It's possible that the Mod creator has to fix this.

**Comment by bunnyman14** [comment]
Addemdum: It should be noted that this seems to ONLY work with Cells, NOT buckets.

**Comment by tfox83** [comment]
This has been a known issue for a long time, unfortunately without a fix, disabling the fluid terminal isn't really fair, so we have to live with this one for a while.  Hopefully a fix will come in soon
