### ISSUE TITLE
JEI does not show changed recipes

### ISSUE THREAD

**Issue by VlexDemic** [FTBTeam/FTB-Continuum#514]
-->Hello, I have a problem on my server FTB - Continuum, namely in the fashion JEI (Just Enough Items) does not display new recipes. As was translated from the Russian language through an online translator below Russian text.
-------------------------------------------------------------
Привет, у меня возникла проблема на моем сервере  FTB - Continuum, а именно в моде JEI (Just Enough Items) не отображаются новые рецепты.

 -->
FTB -Continuum

 -->
On the server, when viewing recipes through JEI, old, not edited recipes are displayed, but requires new ones that were made through CraftTweaker.
------------------------------------------------------------------
На сервере при просмотре рецептов через JEI отображаются старые, не отредактированные рецепты, но требует при этом новые, которые были сделаны через CraftTweaker.

* **Link to Log or Crash File Paste**: 

no, the server is stable

* **Mod/s Affected**: 
JEI - 1.12.2_4.14.3.239

**Comment by tfox83** [comment]
Please make sure you have the scripts installed on the server.

**Comment by VlexDemic** [comment]
Scripts are on the server. The server sees them, requires recipes from scripts, but JEI does not display the modified recipe.
