### ISSUE TITLE
Hardened Thruster from Simply Jetpacks2 is not craftable

### ISSUE THREAD

**Issue by blizzard4591** [FTBTeam/FTB-Continuum#515]
* **Modpack Version**: 1.6.0

* **Issue**: The recipe for the Hardened Thruster contains "Fluxed Armor Plating", three times: Once from Redstone Arsenal (craftable) and twice from Simply Jetpacks 2, which is uncraftable (no recipe).

* **Link to Log or Crash File Paste**: Does not apply

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: ?

* **Known Fix**: Replace the Fluxed Armor Plating with 3x the one from Redstone Arsenal

**Comment by WarGearLord** [comment]
Replacing the Fluxed Armour Platings doesn´t work

**Comment by gewoonnico** [comment]
I have provided a temporary fix for this in #531. Just in case you guys want to progress on :)

**Comment by 016Nojr** [comment]
This has been fixed in a pack update coming in a few days
