### ISSUE TITLE
Crash with Tree Fluid Extractor and Cells

### ISSUE THREAD

**Issue by gexwing** [FTBTeam/FTB-Continuum#52]
* **Modpack Version**: 1.0.2

* **Issue**: Placing a TechReborn Empty Cell inside a Tree Fluid Extractor crashes the game. Issue arrised on a server and was verified in singleplayer (see crash-log). As the cell remains in the ticking tile entity cannot rejoin the game without crashing the server again.

* **Link to Log or Crash File Paste**: [https://paste.feed-the-beast.com/view/fbc5d0fa](https://paste.feed-the-beast.com/view/fbc5d0fa)

* **Is it Repeatable?**: yes

* **Mod/s Affected**: TechReborn, IndustrialForegoing

**Comment by modmuss50** [comment]
This was an joint issue, that could be fixed on either our end, or on Industrial Foregoing's end. I spoke to buzz and we are both going to push a fix for this.

**Comment by Konngitas** [comment]
That does indeed fix the issue, but in doing so the empty cell is now filled with all the fluid in the tree fluid extractor, resulting in the excess being wasted

**Comment by modmuss50** [comment]
The cell should only allow 1000mb (1 bucket) of fluid into it. Sounds like something I will need to have  a closer look at.

**Comment by narken** [comment]
Have same problem on our server, now it crashes on every startup. Anyway to fix this without having recover old backup ?

**Comment by modmuss50** [comment]
@narken Forge has a config to remove erroring tile entities, try enabling that on the server, or wait for an update.

**Comment by gexwing** [comment]
@narken We fixed it by only restoring the backup for the chunk/region-file effected to minimize the impact for other players. The crash-log shows the corresponding chunk in the error message.

**Comment by narken** [comment]
Oki thanks, will give the the chunk restore a try

**Comment by modmuss50** [comment]
@Konngitas I can confirm the issue, and its on IF's end. I have let the devs know.

**Comment by modmuss50** [comment]
That has now been fixed on IF's end.

**Comment by tfox83** [comment]
in next update
