### ISSUE TITLE
Advanced Rocketry Space Station Multiplayer Issues

### ISSUE THREAD

**Issue by ZidSieze** [FTBTeam/FTB-Continuum#521]
* **Modpack Version**: 1.6.0

* **Issue**: Once you make a Space Station and you fly to it the rocket disappears to the void and you are left stranded in space just to fall and try to find your space station 1000 blocks behind you, if you land you can destroy stuff but it doesn't give you the tile entity to place it back again so it basically gets lost in space too.

* **Link to Log or Crash File Paste**: No crash yet.

* **Is it Repeatable?**: Yes.

* **Mod/s Affected**: Advanced Rocketry
* **Known Fix**: I don't know a fix yet but hopefully someone does know a fix for this or the modpack gets patched for it.

**Comment by 016Nojr** [comment]
If the bug isnt fixed in the pack version coming in a few days I cant fix it since the mod isnt getting updates for 1.12 anymore.
