### ISSUE TITLE
Advanced Rocketry Data Duplication

### ISSUE THREAD

**Issue by fmohican** [FTBTeam/FTB-Continuum#522]
* **Modpack Version**:  1.6.0 / 1.5.2

* **Issue**: The Data Storage Unit stack to 16 at one, if you insert a stack of 16 and press "Store to Chip", all 16 stick get same data 1000/1000 but use only 1000 data, so at 16 stick you use 1k data to get 16k mean 15k data profit check the video

https://youtu.be/HhXTcbx8lRY

* **Link to Log or Crash File Paste**: -

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Advanced Rocketry

* **Known Fix**: Limit Data Storage Unit to 1 instead of 16

**Comment by fmohican** [comment]
Fixed by Advanced Rocketry dev in https://github.com/zmaster587/AdvancedRocketry/commit/111814dba353ce0

atm just update the mod.

**Comment by 016Nojr** [comment]
Pack update coming in a few days
