### ISSUE TITLE
Cant open the world and broken backup system

### ISSUE THREAD

**Issue by kaancl3344** [FTBTeam/FTB-Continuum#523]
* **1.60**: 

* **Ftbutileies stoped backuping and now my game broke and i cant save it**: 

* **https://paste.feed-the-beast.com/view/844f1b8e**: 

* **Is it Repeatable?**: 

* **proebebly bees related and i was dealing with bee mods for 12 hour in a row and now i cant lose my everyhting

**: 

* **Known Fix**:

**Comment by kaancl3344** [comment]
i am uploading the save file for any case

**Comment by rune-san** [comment]
Why don't your backups work? That might have been your first sign of trouble.

It looks like there's something conflicting between an eFAB gearbox and an Apiary. The location of that apiary block is here in the Block Location data.

```
Name: gendustry:industrial_apiary // net.bdew.gendustry.machines.apiary.TileApiary
        Block type: ID #1238 (tile.gendustry.industrial_apiary // net.bdew.gendustry.machines.apiary.BlockApiary$ // gendustry:industrial_apiary)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (-59,64,-50), Chunk: (at 5,4,14 in -4,-4; contains blocks -64,0,-64 to -49,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
        Actual block type: ID #1238 (tile.gendustry.industrial_apiary // net.bdew.gendustry.machines.apiary.BlockApiary$ // gendustry:industrial_apiary)
        Actual block data value: 0 / 0x0 / 0b0000
```

It sounds on the surface to me like an integration issue between whatever's going on with the Bees in that apiary and the gearboxes. If you don't have a working save, and you can't start the server, you'll need to open up the World in a World Editor and destroy (I don't know if moving is possible) either that Apiary or the Gearbox (Crafter?) trying to interact with it and see if it can start then.

**Comment by kaancl3344** [comment]
> Why don't your backups work? That might have been your first sign of trouble.
> 
> It looks like there's something conflicting between an eFAB gearbox and an Apiary. The location of that apiary block is here in the Block Location data.
> 
> ```
> Name: gendustry:industrial_apiary // net.bdew.gendustry.machines.apiary.TileApiary
>         Block type: ID #1238 (tile.gendustry.industrial_apiary // net.bdew.gendustry.machines.apiary.BlockApiary$ // gendustry:industrial_apiary)
>         Block data value: 0 / 0x0 / 0b0000
>         Block location: World: (-59,64,-50), Chunk: (at 5,4,14 in -4,-4; contains blocks -64,0,-64 to -49,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
>         Actual block type: ID #1238 (tile.gendustry.industrial_apiary // net.bdew.gendustry.machines.apiary.BlockApiary$ // gendustry:industrial_apiary)
>         Actual block data value: 0 / 0x0 / 0b0000
> ```
> It sounds on the surface to me like an integration issue between whatever's going on with the Bees in that apiary and the gearboxes. If you don't have a working save, and you can't start the server, you'll need to open up the World in a World Editor and destroy (I don't know if moving is possible) either that Apiary or the Gearbox (Crafter?) trying to interact with it and see if it can start then.

I solved the problem with way on the link, thanks for your reply https://www.reddit.com/r/FeedTheBeastCrashes/comments/aim5kj/ftbutils_stoped_saving_backups_for_no_reaseon_and/
