### ISSUE TITLE
OSS missing all options

### ISSUE THREAD

**Issue by BlackNovaYZFR1** [FTBTeam/FTB-Continuum#526]
* **Modpack Version**: 1.6.0

* **Issue**: Object Submission Station (OSS) does not have any selectable options. The two top areas are blank.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/9716dbb0

* **Is it Repeatable?**: Always

Creating a new game (in creative to expedite acquiring OSS) produced the same issue. Both fields are empty and clicking left and right have no effect. Clicking X and Checkmark also have no effect.

![image](https://user-images.githubusercontent.com/8552292/51782230-8ce89680-20ea-11e9-9990-a4574573b922.png)

**Comment by 016Nojr** [comment]
Pack update coming in a few days which fixes this
