### ISSUE TITLE
Wireless Terminal Crash 

### ISSUE THREAD

**Issue by Keaton1188** [FTBTeam/FTB-Continuum#527]
* **Modpack Version**:  1.6.0

* **Issue**:  Having some crashes with the Wireless Terminal / rendering issues / teleporting to another user and crashing 

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/02d03814

* **Is it Repeatable?**:  

* **Mod/s Affected**:  AE2? 

* **Known Fix**:  Was also an issues on SB2 and reported here - https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/198

**Comment by sparkysamza** [comment]
@Sunekaer any chance you can add the fix to this modpack also?

**Comment by JoshuaVandaele** [comment]
I have the same issue on the modpack Ragnamod V.

**Comment by cooljackgi** [comment]
here too ...
game is crashing completly

**Comment by 016Nojr** [comment]
Fixed in pack update coming in a few days
