### ISSUE TITLE
Tinker tanks don't form

### ISSUE THREAD

**Issue by Catonyx** [FTBTeam/FTB-Continuum#528]
* **Modpack Version**: 1.6.0

* **Issue**: Tinker tanks don't form despite being constructed correctly: https://github.com/SlimeKnights/TinkersConstruct/issues/3719

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Tinker's Construct version 2.12.0.113

* **Known Fix**:  Upgrade to TiC version 2.12.0.115

**Comment by 016Nojr** [comment]
Fixed in pack update coming in a few days
