### ISSUE TITLE
Simply Jetpacks 2 Hardened Jetpack need Fluxed Armour Plating from Simply Jetpacks 2

### ISSUE THREAD

**Issue by WarGearLord** [FTBTeam/FTB-Continuum#529]
I wanted to build a Hardened Jetpack and a Jetpack needs Thrusters, but you can craft only the Fluxed Armour Platings from Redstone Arsenal but the crafting recipe needs the Fluxed Armour Platings from Simply Jetpacks 2
![2019-01-29_12 16 40](https://user-images.githubusercontent.com/47142826/51904939-43d16480-23c0-11e9-8f05-a8b942164afc.png)
![2019-01-29_12 16 43](https://user-images.githubusercontent.com/47142826/51904983-5c417f00-23c0-11e9-9705-f3e120312afc.png)

* **Modpack Version**: 1.6.0

* **Issue**: The Hardened Jetpack Thruster need Fluxed Armour Plating from Simply Jetpacks 2 but you 
                  can only craft the Fluxed Amour Plating from Redstone Arsenal.
* **Link to Log or Crash File Paste**: There is no crash/log file, because its an item you can´t build.
* **Is it Repeatable?**: you can´t craft this item (Fluxed Armour Plating from Simply Jetpacks 2)

* **Mod/s Affected**: Redstone Arsenal, Simply Jetpacks 2

* **Known Fix**: you can´t craft this item so... There is no Fix.

**Comment by gewoonnico** [comment]
I have provided a temporary fix for this in #531. In case you wanted to be able to craft it now :)

**Comment by 016Nojr** [comment]
This has been fixed in a pack update coming in a few days
