### ISSUE TITLE
crashing randomly, i believe efab is to blame??????

### ISSUE THREAD

**Issue by reapersremorse** [FTBTeam/FTB-Continuum#53]
* **Modpack Version 1.0.2
* **Issue honestly dont know, crashes randomely
      related to efab

* **Link to Log or Crash File Paste 
    main/ last log: https://paste.feed-the-beast.com/view/5bad566d
    old: https://paste.feed-the-beast.com/view/35cf00f4
    old: https://paste.feed-the-beast.com/view/b80ed83c

* **Is it Repeatable?**: kinda.... watch video https://youtu.be/Q0qfg9ZFpV4
video may take a bit to be completely uploaded, youtube likes to take their time.

**Comment by Kuktar** [comment]
Next time for the video of the crash please post a url with time were crash happens. Watching through all 35 mins isn't something FTB enjoys doing. There's a check box underneath the copy url button that will create the special link for you.

**Comment by reapersremorse** [comment]
sorry about that, i had not gone to sleep yet and did not think before posting. thanks for the advice and i will remember for the next time i need to post a bug.

**Comment by tfox83** [comment]
This has been reported to the modev and is currently being fixed.

**Comment by reapersremorse** [comment]
Thanks for the info @
i checked my kava and everything so i was wondering what the issue was.

**Comment by tfox83** [comment]
Fixed in Dev
