### ISSUE TITLE
Crude oil can still gives infinite resourses

### ISSUE THREAD

**Issue by donkebab** [FTBTeam/FTB-Continuum#530]
* **Modpack Version**: <FTB continumm 1.6.0  Forge 14.23.5.2796>

* **Issue**: <infinite crude oil in distilation tower - crude oil can>

* **Is it Repeatable?**: <yes i made brand new world (creative) and made distilation tower and placed crude oil can inside and it filled whole tank with crude oil and all the producsts. Also this same report was made on november last year (https://github.com/FTBTeam/FTB-Continuum/issues/495) and they solved it in next patch (that im curently playing on) yet i still have same thing.>

**Comment by 016Nojr** [comment]
If the bug still exists in the next pack update I cant fix it since the mod isnt getting updates for 1.12 anymore
