### ISSUE TITLE
Item ID mismatch for SimplyJetpacks2

### ISSUE THREAD

**Issue by gewoonnico** [FTBTeam/FTB-Continuum#531]
* **Modpack Version**: 1.6.0

* **Link to Log or Crash File Paste**: /

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: SimplyJetpacks2, EFab

## **Issue**
Item IDs in oreDictionary for SimplyJetpacks2 items are incorrectly implemented into the scripts which change recipes.

In the _/config/AppliedEnergistics2/_ folder there are two **items.csv** files containing all the oreDictionary IDs loaded into Minecraft: one in the directory itself and one in the subdirectory _aerecipes_.

Within these files you have either entries _simplyjetpacks:metaitemmods_ 18-30 or 15-27. 
IDs 18-30 seems to be the correct range. **The scripts utilising these IDs are configured using the wrong range**, hence the uncraftable recipes.

## **Known Fix**
All oreDictionary IDs used in the scripts with the name _simplyjetpacks:metaitemmods_ are off by 3. Simply fix these values and you're done.

**I have updated the scripts with the correct values so other people can progress:**
[simplyJetpacks.zs.txt](https://github.com/FTBTeam/FTB-Continuum/files/2825431/simplyJetpacks.zs.txt)
[efab.zs.txt](https://github.com/FTBTeam/FTB-Continuum/files/2817065/efab.zs.txt)

Simply download the files, remove the .txt extension, overwrite the files in your _(/minecraft)/scripts/_ folder and enjoy!

This fixes recipes for Digital Upgrade, all tier Thrusters and all tier Armor Plating.

**NOTE: When doing this on a server you have to make sure people's clients also get this fix. It will work, but JEI won't show the fixed recipes otherwise.**

## **Related issues**
#515, #517, #518, #529

**Comment by blizzard4591** [comment]
Thank you so much for this!

BUT: There is a bug still remaining, you forgot to replace the Item ID of the Glowstone Elevation Unit (was: 15, should be: 18)

This is your current script:
> #glowstone elevation unit
recipes.remove(<simplyjetpacks:metaitemmods:15>);
recipes.addShaped(<simplyjetpacks:metaitemmods:15>, [[<ore:ingotElectrumFlux>, <ore:ingotLumium>, <ore:ingotElectrumFlux>], [<ore:ingotLumium>, <ore:blockGlassHardened>, <ore:ingotLumium>], [<ore:ingotElectrumFlux>, <ore:ingotLumium>, <ore:ingotElectrumFlux>]]);

But it should be:
> #glowstone elevation unit
recipes.remove(<simplyjetpacks:metaitemmods:18>);
recipes.addShaped(<simplyjetpacks:metaitemmods:18>, [[<ore:ingotElectrumFlux>, <ore:ingotLumium>, <ore:ingotElectrumFlux>], [<ore:ingotLumium>, <ore:blockGlassHardened>, <ore:ingotLumium>], [<ore:ingotElectrumFlux>, <ore:ingotLumium>, <ore:ingotElectrumFlux>]]);

(notice the 18)

**Comment by gewoonnico** [comment]
> 
> 
> Thank you so much for this!
> 
> BUT: There is a bug still remaining, you forgot to replace the Item ID of the Glowstone Elevation Unit (was: 15, should be: 18)

You're totally right. I have updated the file in this issue, thanks for pointing that out!

**Comment by manwhowantssayTY** [comment]
Signing up for this site to say thank you!

Thank you very much!

**Comment by plugerduck** [comment]
this might me a stupid question  but how do you remove the .txt extension for the files ?

**Comment by CassiusHammer** [comment]
Just signed up to say thank you for your fix!

**Comment by fmohican** [comment]
@gewoonnico Thanks for fix!


> this might me a stupid question  but how do you remove the .txt extension for the files ?

Yes, you should remove `.txt` and replace files, the right extension its `.zs`

**Comment by Crystal98TR** [comment]
Thanks so much, very helpful and clean.

**Comment by 016Nojr** [comment]
This has been fixed in a pack update coming in a few days
