### ISSUE TITLE
Solderer replaced with Placeholder for Quest

### ISSUE THREAD

**Issue by DarkestKnightz** [FTBTeam/FTB-Continuum#532]
* **Modpack Version**: 1.6 on ToastyNetworks

* **Issue**: The solderer is replaced with a place holder for the quest "Cyber Storage" making uncompletable.
![capture](https://user-images.githubusercontent.com/13803786/52059332-908b7b80-2537-11e9-9d68-68855376a3d1.PNG)

* **Link to Log or Crash File Paste**: No Crash

* **Is it Repeatable?**: By opening the quest book

* **Mod/s Affected**: Better Questing

* **Known Fix**: Change quest requirements

**Comment by Timothiess** [comment]
This was meant to be fixed in 1.6 but it is not for me

**Comment by grecolons** [comment]
I can't complete the quest. Got that exact same issue.

**Comment by 016Nojr** [comment]
Fixed in pack update coming in a few days
