### ISSUE TITLE
Infinite Copper and Tin

### ISSUE THREAD

**Issue by sharky564** [FTBTeam/FTB-Continuum#534]
* **Modpack Version**: FTB Continuum 1.5.2

* **Issue**: 4 bronze is made from 3 copper and 1 tin. 1 bronze blend uses 1 bronze ingot in the crusher. 1 bronze blend produces 6 small piles of copper dust and 2 small piles of tin dust, so 2 pulverized bronze produces 12 small piles of copper dust and 4 small piles of tin dust, which can then be converted to 3 bronze and 1 tin. Thus, 4 bronze can make 6 copper and 2 tin, which makes 8 bronze, etc. This is relatively RF-light as well. Looks like an oversight.

* **Known Fix**: Halve the yields of the bronze blend in the industrial centrifuge.

**Comment by fmohican** [comment]
The bug still in 1.6.0

**Comment by 016Nojr** [comment]
Unfortunately I am unable to remove recipes in the Centrifuge, so this cant be fixed unless we get a mod update. But unfortunately 1.12 isnt supported by Tech Reborn anymore
