### ISSUE TITLE
Shift clicking coal into survival generator crashes game.

### ISSUE THREAD

**Issue by cedarbeans** [FTBTeam/FTB-Continuum#536]
* **Modpack Version**: 1.6.0
* **Issue**: While coal is already in the survival generator, shift clicking additional coal into the generator crashes the game
* **Link to Log or Crash File Paste**: It gave no error or crash log.

* **Is it Repeatable?**: yes

* **Mod/s Affected**: Extra Utilities 2

* **Known Fix**: none

**Comment by drcrazy** [comment]
Same issue with resonator

**Comment by ghost** [comment]
Can confirm I also have this issue. Repeated 3 times. Version 1.6.0 on july 22nd and july 23rd.

**Comment by 016Nojr** [comment]
If the bug isnt fixed in the pack version coming in a few days I cant fix it since the mod isnt getting updates for 1.12 anymore.
