### ISSUE TITLE
OSS Block

### ISSUE THREAD

**Issue by Xela10001** [FTBTeam/FTB-Continuum#537]
* **Version 1.6.0**: 

* **OSS quest options will not show up. Clicking the arrows is useless and the red X and yellow tick are greyed out so I can't actually click them. I have tried placing a few items inside those 2 boxes at the bottom (namely octuple cobblestone) but nothing happens**: 

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/f9d22f34
* **It is repeatable, i just went into a brand new creative world and (after switching to survival to be able to place it down) had the same issue**: 

* **Better Questing Version 3.5.282**: 

* **Apparently this has been fixed in the next version:
https://minecraft.curseforge.com/projects/better-questing/files/2658341

"Fixed submission station GUI being unusable"**: 

![2019-02-09_15 58 27](https://user-images.githubusercontent.com/47480171/52522990-2afc6500-2c84-11e9-9c06-53816153890f.png)

**Comment by Xela10001** [comment]
i saw the other issue about this, but it did not have the known fix that is in this one

**Comment by randknu** [comment]
This problem still persists. I tried to manually update BetterQuesting but it just crashes, maybe i'm doing something wrong.

**Comment by 016Nojr** [comment]
Fixed in pack update coming in a few days
