### ISSUE TITLE
Efab Sound Bug

### ISSUE THREAD

**Issue by Xela10001** [FTBTeam/FTB-Continuum#539]
* **Modpack Version**: 1.6.0

* **Issue**: Crafting with steam + gearboxes will make an extremely loud and annoying sound. I think its the sound file repeating every x ticks, with x being an extremely small amount of time. I tested it in a creative world, any crafting recipe that uses steam but doesnt use gearboxes is perfectly fine. But if the recipe requires gearboxes and steam, this bug will happen. Also, if you pause the game with ESC you will hear the sounds you are supposed to hear while the game is paused instead of the bugged and repetitive noise.

(unrelated) - Also, in this testing i saw that if a recipe uses steam and power, the sound of steam will reset every time the sound of power from the rf control(s) plays. This happened when i tried crafting a Mega Torch.

* **Link to Log or Crash File Paste**: Not a crash

* **Is it Repeatable?**: Yes, just set up a efab with gearboxes and boilers and try to make refined iron or any recipe that requires gearboxes + steam to make. You can also see that if you try to make something that only uses steam, like sand into silicon, you will see this bug does not happen.

* **Mod/s Affected**: Efab 0.1.1

* **Known Fix**: <!-- Turn off game sound, but it gets annoying fast.

**Comment by 016Nojr** [comment]
If the bug isnt fixed in the pack version coming in a few days I cant fix it since the mod isnt getting updates for 1.12 anymore.
