### ISSUE TITLE
Missing recipe for Pulverized Nickel from small piles

### ISSUE THREAD

**Issue by dentatar** [FTBTeam/FTB-Continuum#543]
* **Modpack Version**: 1.6.0

* **Issue**: I can craft 4 small piles of Nickel dust (techreborn:smalldust:34) from 1 Pulverized Nickel (thermalfoundation:material:69) but not vise versa.

* **Is it Repeatable?**: Yes. Tested on stock 1.6.0 Continuum

* **Mod/s Affected**: I think this is not handled correctly by UniDict. Small dusts are from Tech Reborn and Pulverized dusts are from Thermal Foundation.

* **Known Fix**: I tried downgrading and upgrading this 3 mods but nothing helped. So i ended up with this temporarily fix through scripts:
```
#fix pulverized nickel from small dust
recipes.addShaped(<thermalfoundation:material:69>, [[<techreborn:smalldust:34>, <techreborn:smalldust:34>], [<techreborn:smalldust:34>, <techreborn:smalldust:34>]]);
```

Also pulverized nickel recipe works fine if i just wipe the config folder and let it generate itself from scratch. But i can't find anything useful there related to this issue. Will probably dig more later.

**Comment by starkgate** [comment]
@VenomLightning Where did you put this fix? I'm running into the exact same problem on FTB Ultimate Reloaded. Probably because I'm updating the mods manually, somehow

Edit: Found it. Just create a new script file in `FTB Ultimate Reloaded\scripts`

**Comment by 016Nojr** [comment]
Fixed in pack update coming in a few days
