### ISSUE TITLE
Wireless terminal baubles crash

### ISSUE THREAD

**Issue by Patrikwa** [FTBTeam/FTB-Continuum#545]
Modpack Version: 1.6

Issue: I created the Bauble version of the wireless terminal (from "Wireless Crafting Terminal 2"), tried putting it on my head baubles slot and it crashed. 
Whenever i log back in on my private server (with no one else but me playing), it instantly crashes as soon as i try to open my inventory.

Bonus Issue (might be related?): Trying to reproduce in creative single player world, JEI shows the item but the creative search function cannot find the Wireless Crafting Terminal item. I crafted the item and put it in the baubles slot and no crashes.

Link to Log or Crash File Paste: https://paste.feed-the-beast.com/view/5769f977

Is it Repeatable?: Yes, as soon as I open my inventory.

Mod/s Affected: Wireless Crafting Terminal 2

Known Fix: Nope, i would really like to find a workaround so I can continue playing, right now I'm stuck!

**Comment by Jokke89** [comment]
can confirm. Tried putting it in baubles because it said so in description. Had to use nbt editor to remove the universal terminal from my baubles. But it keeps getting back in to baubles inventory

**Comment by sawyer83** [comment]
Did anyone ever make any headway with this issue? I now have the same problem. It wouldn't be a big deal if every time I deleted the player file, it just comes right back after reopening the save.

**Comment by ghost** [comment]
I haven't been able to fix the actual issue, but you can get around it by dying but not picking up your items yet, then filling all your baubles slots with other baubles. Then when you pick up your items again it won't go back into the bauble slot again. If you're using a gravestone mod the default setting shoves your items in the exact slots they were in, but most of those mods can turn that mode off by right-clicking/shift-right-clicking your grave before you pick it up. There'll be a message telling you if it worked.

**Comment by sawyer83** [comment]
Wow, I messed around for hours with NBT data, deleting files to see them mysteriously re-appear, when all I had to do was kill myself; The thought never crossed my mind. Thank you. I did on the other hand, find another solution. The pack, backs it's self up every hour or so. I was able to restore my world to just minutes before the accident

**Comment by LattestCarrot159** [comment]
Had the exact same thing with me, just did /kill and won't put it in the baubles spot for now on.

**Comment by 016Nojr** [comment]
If the bug isnt fixed in the pack version coming in a few days I cant fix it since the mod isnt getting updates for 1.12 anymore.
