### ISSUE TITLE
Thermal Dynamics covers appear completely black

### ISSUE THREAD

**Issue by Lalarian** [FTBTeam/FTB-Continuum#548]
Hello!
This issue had been posted before, and has been tagged as fixed. But I am having this problem right now, wiht Thermal Dynamics ThermalDynamics-1.12.2-2.5.4.18-universal.jar
![2019-03-07_20 55 29](https://user-images.githubusercontent.com/5146616/53985246-6f601100-411b-11e9-9800-883117a7a27f.png)

**Comment by Lalarian** [comment]
I have now found what actually causes this problem:
You just need to enable shadres for having the covers right. Every shader I tried, including the internal one, made the covers black. I don't think that's intended, is it?

**Comment by 016Nojr** [comment]
Covers are working fine for me, without touching shaders
