### ISSUE TITLE
Iridium ore uncraftable from UU matter

### ISSUE THREAD

**Issue by Xavion3** [FTBTeam/FTB-Continuum#55]
In 1.0.2, by default tech reborn's iridium ore is craftable from UU matter, I know it might be intentional, but I also know things were overlooked. Without it it makes UU matter significantly less useful and iridium much harder to get, the simplest way being using UU matter to create platinum dust to create iridium requiring dozens of UU matter and 10+ minutes of centrifuging per ingot.

The tier 6 void miner is useless for the goal at first requiring stacks of iridium to get due to the fusion reactor and other components needed, leaving very little options beyond centrifuging for hours to get enough iridium to do anything.

A fix would just be to add a recipe for the enabled form of iridium ore in the classic I shape, or you could confirm it's intentional that iridium is massively harder to deal with than normal I guess. Some kind of note in the matter fabricator quest or somewhere on the intended route to getting iridium in that case could be nice then, the ores are incredibly rare and hunting down the uu matter -> platinum dust -> iridium nugget -> iridium ingot recipe in JEI wasn't very obvious.

**Comment by 016Nojr** [comment]
What I did when beta testing was getting platinum dust from nickel ore.

**Comment by Xavion3** [comment]
Yeah, that could work. This combined with whatever is going on with #57 really guts UU matter however. Once you get access to fusion it starts unlocking with both the fusion recipe and the tier 6 void ore miner being available, but platinum is unsustainable for that point it feels. You'd need 15+ stacks of platinum wouldn't you? The fusion coils need something like 10 iridium each. I guess if you could acquire a *lot* of nickel, but it still seems awkward.

It's partially a case of the matter fabricator already being supposed to be a late game high power method of producing resources, but as is it's pretty much exclusively useful for titanium because it's a lot easier to get titanium from a few UU than from bauxite. Even that drops off if you can get plenty of bauxite ore. Just leaves the matter fabricator in a really weird place for something so expensive I feel.

I also have no idea if this is an oversight or not, it very well could be. It was due to an oversight by nobody checking the recipes in game that all modded planks were uncraftable, and this is a lot more subtle than that.

**Comment by tfox83** [comment]
Initially modded planks were not supposed to be craftable, only with a TE sawmill which we moved up to earlier game for that reason.  A last minute update to TE/mod tweaker (to fix larger issues) changed the recipe load times and we missed that issue.  When fixing we decided to go ahead and make all planks craftable via crafting table.
I will look at the UU matter issue in the next update, thanks

**Comment by tfox83** [comment]
added traditional UU matter-iridium ore recipe (I shaped)
