### ISSUE TITLE
NullPointerException with Advanced Rocketry

### ISSUE THREAD

**Issue by lays24mc** [FTBTeam/FTB-Continuum#550]
* **Modpack Version**: 

1.6.0

* **Issue**: 

When I start my server, crashed this with NullPointerException by Advanced Rocketry (fresh install) 

* **Link to Log or Crash File Paste**: 

https://pastebin.com/j03UjkKC
(no Crashlog, only latest.log)

* **Is it Repeatable?**: 

* **Mod/s Affected**: 

Advanced Rocketry

* **Known Fix**:

**Comment by 016Nojr** [comment]
If the bug isnt fixed in the pack version coming in a few days I cant fix it since the mod isnt getting updates for 1.12 anymore.
