### ISSUE TITLE
Quest can't 'detect'

### ISSUE THREAD

**Issue by zellgoma** [FTBTeam/FTB-Continuum#552]
![Untitled](https://user-images.githubusercontent.com/49331707/55665370-69814c80-57fb-11e9-9f4c-042306c6af62.jpg)
* **Modpack Version**: FTBContinuum-1.6.00-1.12.2.zip - (Release) - (current)

* **Issue**: Second quest shows the item as crafted but will not detect it or give out the reward.

* **Link to Log or Crash File Paste**: No crash visible.

* **Is it Repeatable?**: Issue happens with every world made.

* **Mod/s Affected**: No additional mods.

* **Known Fix**: None known.

**Comment by snake-4** [comment]
Let me tell you the best known fix; Click the arrow facing right on the right of the Detect/Submit button, you will see there are tasks to be done.
