### ISSUE TITLE
Shift Clicking Items into a Golden Bag of Holding Crashes Game

### ISSUE THREAD

**Issue by OrionCummings** [FTBTeam/FTB-Continuum#553]
* **1.6.0**

* **Whenever I shift click items into the golden bag of holding the game crashes. More specifically, whenever I do this and 1) there is already that item in there (ex: redstone when mining), and 2) if the bag is full, but the stack of the item I am trying to put in is not full.
[*Here's an image of my inventory/golden bag*:](https://i.imgur.com/FP6iTnw.png)**

* **https://paste.feed-the-beast.com/view/ed5aa80d**

* **Yes**

* **Extra Utilities 2 Golden Bag Of Holding**

* **I have no idea**

**Comment by mtimyself** [comment]
ExtraUtils needs an update. They finally fixed the shift clicking client crash.
https://github.com/rwtema/Extra-Utilities-2-Source/issues/226#issuecomment-484933703

**Comment by 016Nojr** [comment]
Updated in new pack version coming in a few days
