### ISSUE TITLE
Server pack extraction errors

### ISSUE THREAD

**Issue by StephenLujan** [FTBTeam/FTB-Continuum#554]
* **Modpack Version**: 1.6.0

* **Issue**:
 Can't extract server pack. Tried on two different computers, both with windows and 7zip. 
1 data error, and a bunch of header errors extracting different jars. Server would not run, complaining about the same jar files.
File location:
https://media.forgecdn.net/files/2658/289/FTBContinuumServer_1.6.0.zip

* **Is it Repeatable?**: yes

**Comment by 016Nojr** [comment]
Pack update coming in a few days, check if that server pack works for you.
