### ISSUE TITLE
Actually Additions: Farmer & Trees

### ISSUE THREAD

**Issue by mtimyself** [FTBTeam/FTB-Continuum#557]
* **Modpack Version**: 1.6.0

* **Issue**: AA Farmer tills dirt, plants saplings (all of which turn into Oak no matter which ones were provided) but can not harvest trees.

I do not think trees are supposed to be supported in the Farmer at all. Saplings should not be accepted.

**Comment by 016Nojr** [comment]
If the bug isnt fixed in the pack version coming in a few days I cant fix it since the mod isnt getting updates for 1.12 anymore.
