### ISSUE TITLE
Impossible Quest "Waterproof"

### ISSUE THREAD

**Issue by Mangomaracuja** [FTBTeam/FTB-Continuum#558]
* **Modpack Version**: 1.6.0

* **Issue**: The Quest Waterproof is impossible, because the FluidTerminal of extracells is required. But it has no recipe. I just give it to me per command for progress

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: by opening the questbook

* **Mod/s Affected**: Better Questing

* **Known Fix**: Change quest requirements

![2019-05-03_01 42 12](https://user-images.githubusercontent.com/16819445/57113558-60759380-6d45-11e9-8d5b-ce41a7971b17.png)

**Comment by 016Nojr** [comment]
Fixed in a new pack version coming in a few days
