### ISSUE TITLE
quantity of dragon scale and dragon breath

### ISSUE THREAD

**Issue by comical-uk** [FTBTeam/FTB-Continuum#560]
Hi

Not an issue, but would it be possible to get your thoughts on the number of dragon scales and dragon breath required for the creative items.

I had a look through the recipes and got up to 2,300 bottles of dragon breath, so I think I may be missing something

 is it intended to add EMC values for these or is it intended to get the manually

thanks

**Comment by drcrazy** [comment]
It looks like EMC removed intentionally. Overall pack idea is to make it hard. Unfortunately, in this case it is not hard but rather grindy.  Dragon breath is less issue as you are able to spam click with bottles. Scales are pure PITA.

**Comment by comical-uk** [comment]
yeah, not sure if an rftools spawner could help with the scales

its just getting the dragon to fire its breath too!

**Comment by drcrazy** [comment]
spawner can spawn ender dragons. She will fly to 0.0 x.z coordinates and will stay there. So either use one of other planets or make sure that nothing important located around 0.0 in The Overworld
