### ISSUE TITLE
recipe to make IFR Infinity drill require IFR Laser drill

### ISSUE THREAD

**Issue by comical-uk** [FTBTeam/FTB-Continuum#561]
Version 1.6

The recipe in JEI (ore at least mine) for the IFR Infinity Drill, requires the IFR Laser drill, there doesnt seem to be a recipe for the laser drill however

I've done a search through the issues but I cant find any mention of it, was there any updated scripts for this

Thanks

**Comment by 016Nojr** [comment]
Both drills are not obtainable on purpose
