### ISSUE TITLE
Openblocks page 2 crash

### ISSUE THREAD

**Issue by ImpeccablePenguin** [FTBTeam/FTB-Continuum#562]
* **Modpack Version**: 1.6.0

* **Issue**: When searching @openblocks and going to page two, it crashes

* **Link to Log or Crash File Paste**:
The game crashed whilst rendering ingredient
The game crashed whilst rendering ingredient
Error: java.lang.ArrayIndexOutOfBoundsException: -1

* **Is it Repeatable?**: yes

* **Mod/s Affected**: JEI and Openblocks

* **Known Fix**: unknown

**Comment by 016Nojr** [comment]
If the bug isnt fixed in the pack version coming in a few days I cant fix it since the mod isnt getting updates for 1.12 anymore.
