### ISSUE TITLE
Advanced Rocketry Gear R

### ISSUE THREAD

**Issue by dburva** [FTBTeam/FTB-Continuum#566]
Guys I ve been building a Robot-Space Station,finaly yesterday it ve finished.Today I was trying to warp and suddenly a oddity was discovered by me.Stars were skipping my legendary robot then I realized Robot dimension is reverse , it is moving like a car that on the Gear R(Idk how to say this so it is the most simple way :D) 
Ps:I can't build it again because it is so big.
![2019-06-12_18 32 37](https://user-images.githubusercontent.com/48226211/59365628-8711eb80-8d41-11e9-8420-2a286b0cc547.png)
![2019-06-12_18 32 38](https://user-images.githubusercontent.com/48226211/59365636-89744580-8d41-11e9-8e45-3296e2ad7aa4.png)
![2019-06-12_18 33 01](https://user-images.githubusercontent.com/48226211/59365652-909b5380-8d41-11e9-825f-c93040c293d0.png)

**Comment by harry-upton** [comment]
Your ship will warp in the direction that the Warp Controller block is facing. Simply turn the warp controller block around so it is facing the other way to resolve this problem.
