### ISSUE TITLE
no recipe for capacitors immersive engineering

### ISSUE THREAD

**Issue by PresidentBailey** [FTBTeam/FTB-Continuum#568]
* **Modpack Version**: 1.6.0

* **Issue**: no recipe for capacitors for immersive engineering

**Comment by sawyer83** [comment]
I may be wrong but I believe that all energy storage item where removed, in favor of using only the three tiers of power cells provided by the RF tools power mod.

**Comment by 016Nojr** [comment]
Correct, we use RF Tools Power for storage
