### ISSUE TITLE
Shipping Bin bug

### ISSUE THREAD

**Issue by fmohican** [FTBTeam/FTB-Continuum#569]
* **Modpack Version**: 1.6.0

* **Issue**: Check this video https://youtu.be/wtP-hskNmTU , Shipping bin remove items if input is automated, also give you nothing back :P

* **Link to Log or Crash File Paste**: Isn't any crash, just a bug where you lost items 

* **Is it Repeatable?**: yes

* **Mod/s Affected**: PamCraft, Thermal Foundation

* **Known Fix**: -

**Comment by 016Nojr** [comment]
If the bug isnt fixed in the pack version coming in a few days I cant fix it since the mod isnt getting updates for 1.12 anymore.
