### ISSUE TITLE
[Suggestion] Silicon Compatibility (Empowerer)

### ISSUE THREAD

**Issue by fmohican** [FTBTeam/FTB-Continuum#570]
* **Modpack Version**: 1.6.0

* **Issue**: Add other silicon to Electronic Circuit Recipe's (Empowerer)

* **Link to Log or Crash File Paste**: -

* **Is it Repeatable?**: -

* **Mod/s Affected**: Actually Additions

* **Known Fix**: -

![javaw_iyOPT8xb6S](https://user-images.githubusercontent.com/8583317/61181952-ad26f600-a635-11e9-951e-9f267ce78756.png)

![javaw_awrpfGpeJ0](https://user-images.githubusercontent.com/8583317/61181990-20306c80-a636-11e9-9477-8055520346ea.png)

**Comment by 016Nojr** [comment]
Intentional behaviour
