### ISSUE TITLE
Analog Crafter crashing Server

### ISSUE THREAD

**Issue by BernardoSCaetano** [FTBTeam/FTB-Continuum#574]
* **Modpack Version**: 1.6.0

* **Issue**: Analog Crafter crashes server when SHIFT-Click insertion for a sum bigger than capacity

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Extra Utilities 2

* **Known Fix**: Likely code mechanism to make some quick math and not allow more than 9 stacks input

<img width="567" alt="Screenshot 2019-07-30 at 21 10 31" src="https://user-images.githubusercontent.com/47446166/62159050-2189b680-b311-11e9-9815-5a97bee49b13.png">

**Comment by MateuszKaput** [comment]
Maybe try update Extra Utilities 2 to 1.9.9 version

**Comment by 016Nojr** [comment]
If the bug isnt fixed in the pack version coming in a few days I cant fix it since the mod isnt getting updates for 1.12 anymore.
