### ISSUE TITLE
Opening  chest crash game

### ISSUE THREAD

**Issue by MateuszKaput** [FTBTeam/FTB-Continuum#575]
* **Modpack Version**: 1.6
* **Issue**: After update extra utilities 2 to 1.9.9 version I can't open Diamond Compartment because my game crash Here is crash report: 
* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/f7a04415

* **Is it Repeatable?**: yes

**Comment by MateuszKaput** [comment]
I just get backup from few hours before and it is fixed but I lost this time.
If somone know whats happen just write here.

**Comment by 016Nojr** [comment]
Mod isnt supporting 1.12, and there hasnt been any other reports of this
