### ISSUE TITLE
Serveral "Betterquesting" Bug / Fixes

### ISSUE THREAD

**Issue by ghost** [FTBTeam/FTB-Continuum#578]
* **Modpack Version**: FTB Continuum 1.6.0

* **Issue**:  
**1.** Digital Style/Cyber_Storage The Item Placeholder is unobtainable 
**2.** Digital Style/Waterproof The ME Fluid Terminal is not change to the AE2 one
**3.** Digital Style/Base_on_the_Go Item Placeholder need to change to Infinity Booster Cards

* **Link to Log or Crash File Paste**: /

* **Is it Repeatable?**: 
It's in every world

* **Mod/s Affected**: 
The programming of the Betterquesting mod

* **Known Fix**: 
FTB Continuum\config\betterquesting for fixing the default for every new world (rename to **DefaultQuests.json**)
[DefaultQuests.txt](https://github.com/FTBTeam/FTB-Continuum/files/3465357/DefaultQuests.txt)

FTB Continuum\saves\YOUR WORLD\betterquesting for fixing it in your world
[QuestDatabase.txt](https://github.com/FTBTeam/FTB-Continuum/files/3465359/QuestDatabase.txt)
(rename to **QuestDatabase.json**)
**1.** I removed the Item Placeholder
**2.** Changed the ME Fluid Terminal
**3.** Change Placeholder to 16 Infinity Booster Cards

**Comment by 016Nojr** [comment]
Fixed in a pack update coming in a few days
