### ISSUE TITLE
Applied Energistic 2 network turning off and on

### ISSUE THREAD

**Issue by MateuszKaput** [FTBTeam/FTB-Continuum#579]
* **Modpack Version**: FTB Continuum 1.6.0

* **Issue**: My network somtimes turning off and turning on. I found this [https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3197](url), There is a fix idea  
 "Add a dense energy cells (the one from AE2) to your system" but in Continuum I don't see dense cells at all.

Here is a video with turning off in 26 second.
https://www.youtube.com/watch?v=yUuSQ469LeQ&feature=youtu.be

What can I do with it?

* **Is it Repeatable?**: Yes
* **Mod/s Affected**:  Applied Energistics 2

* **Known Fix**: add dense energy cells?

**Comment by ghost** [comment]
replied on linked video

**Comment by 016Nojr** [comment]
Energy cells wont be added in since there is another way to deal as you can read in the YT comment
