### ISSUE TITLE
Server Unrecognized VM option

### ISSUE THREAD

**Issue by Negri234279** [FTBTeam/FTB-Continuum#580]
sh ServerStart.sh
Starting server
Unrecognized VM option 'UseParNewGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

I have 5Gb on this VM
It has also happened to me in other modpack

https://cdn.discordapp.com/attachments/399969621471395852/612429705122938881/unknown.png

**Comment by rune-san** [comment]
Please provide your full crash log. Chances are you are using an unsupported version of Java.

**Comment by Negri234279** [comment]
Using the most current version, should I use Java 8?

**Comment by rune-san** [comment]
Correct. Only Java 8 is supported. This holds true for any pack based on Minecraft 1.12.

**Comment by Negri234279** [comment]
Another question I have is how to make my personal mod package called for example 'The best mods', that name comes out discord, as with some FTB pack and minecraft does not come out

**Comment by Mervus** [comment]
On Debian 10 i cant install Java 8 it always installs 11. Can someone help me?.

**Comment by rune-san** [comment]
There's a couple of ways, including using NVIDIA's build that they're maintaining in Buster Backports for their CUDA toolset, but my preference has been to add the AdoptOpenJDK repository and use the openjdk8 package that's maintained there.

[Here's a good link on adding the repository and updating your default Java version in Buster.](https://linuxize.com/post/install-java-on-debian-10/)

**Comment by Mervus** [comment]
Oh Thanks!
