### ISSUE TITLE
AE2 and Just enough item issue

### ISSUE THREAD

**Issue by MrDracoor** [FTBTeam/FTB-Continuum#582]
* **Modpack Version**: 1.6.0

* **Issue**: In the pattern Terminal (AE2) if any item is putted in the system from a void ore miner you cant search in the search bar from Just enough items. You press a button and it directly disappear. in a system where nothing happens the search function works

* **Link to Log or Crash File Paste**: 
* **Is it Repeatable?**: Yes

* **Mod/s Affected**: AE2 and Just enough items

* **Known Fix**:

**Comment by 016Nojr** [comment]
If the bug isnt fixed in the pack version coming in a few days I cant fix it since the mod isnt getting updates for 1.12 anymore.
