### ISSUE TITLE
item dupe bug with Steve's Minecarts

### ISSUE THREAD

**Issue by Maskyoftruth** [FTBTeam/FTB-Continuum#586]
up-to-date Continuum 1.6.0 from FTB Team on the FTB launcher

Minecraft 1.12.2 survival

No crashing occuring

When I Left drag-click across the Advanced Crafter GUI in my Steve's Cart(reinforced hull) dragging over crafting cells will duplicate the item being drug.

I can consistently replicate and dupe with the Steve's Carts advanced crafting GUI in the cart.

Encountered this while attempting to maximize item collection digging up cobble in a mine.
Not sure if this matters, but I had created the cart, took it apart, and re-made it with the addition of the Advanced Crafter addon.

**Comment by 016Nojr** [comment]
If the bug isnt fixed in the pack version coming in a few days I cant fix it since the mod isnt getting updates for 1.12 anymore.
