### ISSUE TITLE
crash when loading existing world

### ISSUE THREAD

**Issue by blazeshard** [FTBTeam/FTB-Continuum#587]
Modpack Version**: 1.6

Issue: when losing an existing map my game crashes. this does not happen with newly created map. this started when power was cut to my computer when loading the map.

Link to Log or Crash File Past: https://paste.feed-the-beast.com/view/ea5532c3

Is it Repeatable: yes I have tried to lose the map mutable times and it does not work

Mod/s Affected: I can not find any mod that is causing it.

**Comment by 016Nojr** [comment]
If this happened after the power was unexpectedly cut to your computer it's most likely corrupted, this is a rare case, but it's nothing I'm able to fix.
