### ISSUE TITLE
Simply Jet packs Recipe bug

### ISSUE THREAD

**Issue by Dark-lazer13** [FTBTeam/FTB-Continuum#588]
Modpack Version: 1.6.0

Issue: The recipe for Hardened and Reinforced thrusters is impossible to complete

Link to Log or Crash File Paste: N/A

Is it Repeatable?: Yes

Mod/s Affected: Simply  Jetpacks 2, Thermal Expansion, Redstone Arsenal

Known Fix: No known Fix
![bug thing 2](https://user-images.githubusercontent.com/59812519/78200745-98a5ba80-745d-11ea-83e1-5a913664b342.png)
![bug thing](https://user-images.githubusercontent.com/59812519/78200752-9a6f7e00-745d-11ea-87bb-b8f042a12ced.png)

**Comment by Dark-lazer13** [comment]
They both are required for quests

**Comment by Dark-lazer13** [comment]
it seems it has affected other simply jetpack 2 items as well such as the glow stone elevation unit

**Comment by 016Nojr** [comment]
This has been fixed in a pack update coming in a few days
