### ISSUE TITLE
MineTogether's Privacy Policy is set TRUE by default

### ISSUE THREAD

**Issue by jamierocks** [FTBTeam/FTB-Continuum#589]
https://github.com/FTBTeam/FTB-Revelation-2/issues/365

https://dist.modpacks.ch/modpacks/1/FTB%20Continuum-1.6.0/config/minetogether/gdpr.txt is the current file for 1.6.0.

Should be set false by default.

**Comment by 016Nojr** [comment]
Fixed in pack update coming in a few days
