### ISSUE TITLE
Wrong Forge Version

### ISSUE THREAD

**Issue by Keaton1188** [FTBTeam/FTB-Continuum#59]
* **Modpack Version**:  Any

* **Issue**:  This is server/client related, Continuum is not using a recommended version of forge this causes issues with sponge + stability, we have had to use forge version 2655 for the server to actually boot up as well as work with sponge.

* **Is it Repeatable?**:  Yes

* **Mod/s Affected**:  Sponge/Forge/Version! 

* **Known Fix**: 
 - FTB to update Continuum to a version of forge that is stable (better if recommended)
- Forge to tag a version to recommended
- Sponge to upgrade to match recommended version

**Comment by tfox83** [comment]
we do not support sponge at this time, sorry.
