### ISSUE TITLE
pulverizer missing

### ISSUE THREAD

**Issue by audibleranger** [FTBTeam/FTB-Continuum#590]
* **Modpack Version 1.6.0**:  1.6.0

* **Issue**: The pulverizer is missing in JEI. I thought I have seen several other recipes too, but i cant remember them.

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: sure

* **Mod/s Affected**: JEI 4.14.3.246

* **Known Fix**:

**Comment by audibleranger** [comment]
saddle removed? if not its also missing

**Comment by audibleranger** [comment]
compactor is missing too

**Comment by rune-san** [comment]
Firstly, I'd like to mention that if these were truly missing items, you would want to open an issue on each of these items, along with appropriate evidence.

Addressing the main point, I just want to add the "Mission Statement" for FTB Continuum.

> FTB Continuum is an expert style modpack packed with some of the latest tech mods by Feed the Beast!  Majority of the recipes and intended progression that you are used to has been changed.  Continuum introduces new, never before used mods to make things even more difficult and challenging.

The point here is that if the recipe is missing, you likely aren't supposed to have access to it, and are supposed to be finding an alternative way of completing your task. That is definitely the situation with the Compactor and Pulverizer.

If you're expecting to play with whatever familiar tools you're used to, then FTB Continuum isn't the pack for you. :)

**Comment by audibleranger** [comment]
I see. i will do it with other machines. Nevertheless its weird that pulverizer recipes show up when looking for iron recipes, But I think I already saw an issue for this.
