### ISSUE TITLE
1.6.1 Smeltery Glass Casting

### ISSUE THREAD

**Issue by MirceaZisu** [FTBTeam/FTB-Continuum#594]
* **Modpack Version**: 1.6.1

* **Issue**: After having melted glass in the TiC Smeltery, I am unable to cast it into a casting table, nor in a basin. I think it's due to the lack of TiC glass.

* **Link to Log or Crash File Paste**: Does not crash.

* **Is it Repeatable?**: Yep. Smelt glass or sand in the smeltery, and attempt to cast it from a drain + faucet into a casting table or basin.

* **Mod/s Affected**: Possibly Forestry and TiC liquid glass conflicting.

* **Known Fix**: None that I know of.

**Comment by 016Nojr** [comment]
If the bug isnt fixed in the pack version coming in a few days I cant fix it since the mod isnt getting updates for 1.12 anymore.
