### ISSUE TITLE
Twitch

### ISSUE THREAD

**Issue by vshibe** [FTBTeam/FTB-Continuum#595]
* **Modpack Version**: Twitch Pack 1.6.0

* **Issue**: The Twitch launcher doesnt have 1.6.1 making Aternos usage impossible

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: N/A

* **Known Fix**: Update the mod on twitch? Not sure if its complicated but would be a big help for me and friends and probably some others.

**Comment by fabm3n** [comment]
Just use the FTB Launcher
