### ISSUE TITLE
ftb continuum server crashes (solved)

### ISSUE THREAD

**Issue by nixelyus** [FTBTeam/FTB-Continuum#596]
I have been trying to open a ftb continuum server but everytime i open the server it crashes and stops running

https://pastebin.pl/view/b0f43555 this is crash report thanks for help already

**Comment by rune-san** [comment]
I've heard of this happening before because of a localization issue. Is your system set to English or something else?

**Comment by nixelyus** [comment]
it is in different language i will try to change it then i will comment back

**Comment by nixelyus** [comment]
so much thanks bro it worked :)
