### ISSUE TITLE
CTD when trying to view "blocks" statistics

### ISSUE THREAD

**Issue by visionaryness** [FTBTeam/FTB-Continuum#599]
* **Modpack Version**: 1.7.0

* **Issue**: game crashes to desktop whenever i click the "blocks" button in the statistics page

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/8fcb1b1f

* **Is it Repeatable?**: yes

* **Mod/s Affected**: vanillafix mentioned forestry specifically on the crash screen

* **Known Fix**:

**Comment by 016Nojr** [comment]
If the bug isnt fixed in the pack version coming in a few days I cant fix it since the mod isnt getting updates for 1.12 anymore.
