### ISSUE TITLE
Can't convert between different kinds of Crude Oil

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Continuum#6]
* **Modpack Version**: 
1.0.0
* **Issue**: 
The Fluid Dictionary Converter doesn't give the option to convert between the Immersive Petroleum and the Thermal Foundation versions of Crude Oil

**Comment by tfox83** [comment]
its a known bug that has been reported, still awaiting a fix if there will be one

**Comment by tfox83** [comment]
was told it wont be fixed.
