### ISSUE TITLE
A Random Crash Report (Engineers Workshop Reborn)

### ISSUE THREAD

**Issue by eric9613** [FTBTeam/FTB-Continuum#60]
* **Modpack Version**: 1.0.2

* **Issue**: I was working on the my world and i open the worktable after using the efab after making treated wood

* **Link to Log or Crash File Paste**:  https://paste.feed-the-beast.com/view/0f905062

* **Is it Repeatable?**:  no i tried again and did not do anything so i dont know what crash it

* **Mod/s Affected**: 

* **Known Fix**:

**Comment by modmuss50** [comment]
Seems to be a bug with EngineersWorkshopReborn (my mod 👍). I will take a look at it and see what is up.

**Comment by modmuss50** [comment]
Fixed and pushed to curse.

**Comment by tfox83** [comment]
in next udpate
