### ISSUE TITLE
reinforced metal and stolen gift have same item id?

### ISSUE THREAD

**Issue by visionaryness** [FTBTeam/FTB-Continuum#600]
* **Modpack Version**: 1.7.0
* 
* **Issue**: Reinforced metal from Steve's Carts 2 is pushed by servos/pulled by retrievers that have the Stolen Gift item in the filter

* **Link to Log or Crash File Paste**: no log file

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Steve's Carts 2, Thermal Dynamics

* **Known Fix**:

**Comment by 016Nojr** [comment]
I cant find stolen gift in the game?

**Comment by visionaryness** [comment]
the stolen gift is a junk item dropped by mobs during steve's carts christmas season

**Comment by 016Nojr** [comment]
Ah, I'll look into it, but numerical IDs have been removed/isnt working the same way as they did back in 1.8>. I'll see if I can find out something about it.
