### ISSUE TITLE
No Capacitors in game and kinetic dynamos not working from immersive engineering

### ISSUE THREAD

**Issue by as1anp3rsuas10n** [FTBTeam/FTB-Continuum#601]
* **Modpack Version**: <1.7.0>

* **Issue**: <There are no capacitors in game and the kinetic dynamos aren't working>

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: <Yes>

* **Mod/s Affected**: <immersive Engineering>

* **Known Fix**:

**Comment by 016Nojr** [comment]
Working fine for me, there are capacitors in the game
