### ISSUE TITLE
impossible to craft any clathrate items

### ISSUE THREAD

**Issue by visionaryness** [FTBTeam/FTB-Continuum#602]
* **Modpack Version**: 1.7.0

* **Issue**: cannot craft resonant clathrate, destabilized clathrate, or energized clathrate, and resonant clathrate is needed to travel to one of the planets. the recipes require the pulverizer, which is disabled in the modpack.

* **Link to Log or Crash File Paste**: no crash

* **Is it Repeatable?**: yes

* **Mod/s Affected**: thermal foundation, advanced rocketry

* **Known Fix**: add a recipe that does not require the pulverizer

EDIT: expanded to include all clathrate items even though resonant clathrate is the only one required

**Comment by 016Nojr** [comment]
You dont craft clathrates, you mine the corresponding ores, Resonant clathrate is achieved by mining Resonant End Stone
