### ISSUE TITLE
Certus quartz ore missing oredictionary name

### ISSUE THREAD

**Issue by Jimmy469** [FTBTeam/FTB-Continuum#62]
* **Modpack Version**: 1.0.2

* **Issue**: Certus quartz ore doesn't have the expected oredictionary entry (or any entry, for that matter), whereas charged certus does. This affects things that look for the ore* prefix when interacting with blocks (miner bees, specifically, although other tools/machines might be affected too)

See: https://imgur.com/a/hJneSBi

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: AE2. Unsure if it's a bug in AE2's side or pack configs.

* **Known Fix**: add
`val oreCertus = <ore:oreCertusQuartz> \n
oreCertus.add(<appliedenergistics2:quartz_ore>`
to one of the scripts.

**Comment by Jimmy469** [comment]
This appears to have been done intentionally on line 108 of 01_unification.zs. If it is intentional, then disregard/close this, although perhaps it should also be done to charged certus.

**Comment by tfox83** [comment]
It was done intentionally to prevent switching charged/regular via barrels/storage drawers etc.
