### ISSUE TITLE
Cant get into game

### ISSUE THREAD

**Issue by cms623** [FTBTeam/FTB-Continuum#63]
* **Modpack Version**:  Continuum 1.02

* **Issue**: after installing mod pack and going to play via native launcher and clicking play I get the message the version you are trying to play inherits properties from an unknown problem

* **Link to Log or Crash File Paste**: 

* **Is it Repeatable?**: have tried to play multiple times this happens every time

**Comment by tfox83** [comment]
I am closing this issue due to lack of logs and information.
