### ISSUE TITLE
Iron Backpacks glitch

### ISSUE THREAD

**Issue by veko35** [FTBTeam/FTB-Continuum#64]
When I open my backpack with right click everything is okay but then when I use the default "I" bind and put my stuff into the backpack the next time I open it from wherever my stuff is missing. Please check and fix it. Thank you.

**Comment by aaronhowser1** [comment]
I suggest posting this on the [Iron Backpacks issue tracker](https://github.com/gr8pefish/IronBackpacks/issues)

**Comment by tfox83** [comment]
Fixed in dev
