### ISSUE TITLE
Config Conflict With Better Questing

### ISSUE THREAD

**Issue by Morganamilo** [FTBTeam/FTB-Continuum#65]
* **Modpack Version**: v1.0.2

* **Issue**: The Better Questing book and excavate are both bound to grave. This makes it impossible to use this hotkey until one is changed. I believe the book should be high priority and the key should not need to be changed to work.

* **Is it Repeatable?**: Confirmed with one other person
* **Mod/s Affected**: Better Questing and whatever excavate is from

* **Known Fix**: Change the default excavate key

**Comment by aaronhowser1** [comment]
By default, OreExcavation does not use a key, it's always active. I'm not sure if the modpack has modified default controls, but I suppose rebinding it to not have a key would work.

**Comment by tfox83** [comment]
@aaronhowser1 is correct, this method is intended.

**Comment by Morganamilo** [comment]
> but I suppose rebinding it to not have a key would work.

Indeed it does as I mentioned in known fixes. 

My point is, the quest book, one of the of the most important items in the game. Is unusable until rebinding controls, as Minecraft disables both actions when there is a conflict. What I was asking for is the defaults to be changed so there is no conflict.

>is correct, this method is intended.

So are you saying you put the conflict there on purpose?
