### ISSUE TITLE
Shader witch optifine = world is black

### ISSUE THREAD

**Issue by killerwowlf** [FTBTeam/FTB-Continuum#67]
* **1.0.2**: 

* **if i install optifine in this modpack and try too use shader packs the whole world is black. Without shader evrythink is fine. **: 

* **game dont crash, just a black world**: 

* **Yes, i can repeat the issue**: 

* **Mod/s Affected**: 

* **need help to fix**:

**Comment by Kuktar** [comment]
I'm using optifine hd3 with the opengl internal shaders that come with
nvidia. It's working fine.

Can you provide the name of the shaders or maybe some screenshots of your
settings. Ftb has other bugs to work on. Optifine isn't in the pack so most
likely you added it. I can try to help in the meantime

**Comment by ByteTemplar** [comment]
You need to edit the Advanced rocketry file to disable its custom sky.
Its located:
\config\advRocketry\advancedRocketry.cfg

Then edit line 55:
B:overworldSkyOverride=false

For future proofing, might need to edit lines 40 and 43:
B:PlanetSkyOverride=false 
B:StationSkyOverride=false

**Comment by tfox83** [comment]
We do not support optifine or shaders
