### ISSUE TITLE
[Question]Quest about Engineer's Workshop Reborn

### ISSUE THREAD

**Issue by SihenZhang** [FTBTeam/FTB-Continuum#68]
* **Modpack Version**: 
1.0.2
* **Issue**: 
The quest about Engineer's Workshop Reborn says that a crafting table applied a single Storage Upgrade will have **9** slots. But in fact, there are only **6** slots.
![](https://i.imgur.com/OXAeY2W.png)
![](https://i.imgur.com/mSs2Rxr.png)

**Comment by aaronhowser1** [comment]
I'll fix it to say 6 slots in the next update
