### ISSUE TITLE
Prismarine dupable with Factorizer

### ISSUE THREAD

**Issue by Xavion3** [FTBTeam/FTB-Continuum#69]
Currently on 1.0.2

There's two elements at play here, the first is that the Factorizer recognises Prismarine as being made of 9 prismarine despite only being 4. Prismarine Bricks is also recognises as made of 9 and actually is. The second is that since Chisel allows you to convert between all the different versions of prismarine blocks the ability to turn prismarine bricks back into prismarine will always be dupeable so long as both recipes exist.

As far as fixes go there's something wanting on the TE end, but you'd have to decide here how to deal with the Chisel-TE issue still. Whether just removing it from the factorizer, removing crafting recipes for some of the types so you can only change get the alternate forms via chiselling so it has a set 4 or 9 cost or preventing chiselling between the forms.

If I could I'd recommend one of the first two, prevent the factorizer working with it or just remove recipes for dark prismarine and either prismarine or prismarine bricks depending on whether you want 4 or 9 prismarine per block. 9 would be easier if TE doesn't update before the next update as it'd allow the factorizer to stay compatible.

TE is already fixing the basic issue of the 4/9 thing per here https://github.com/CoFH/Feedback/issues/1071 .

**Comment by Jimmy469** [comment]
A similar bug exists for nether quartz as well.

**Comment by tfox83** [comment]
will wait to get the TE fix and go from there, thanks

**Comment by tfox83** [comment]
Ended up removing the machine as it opens up a lot of issues that break more than fix (This machine was added by CoFH just before release of the pack)

**Comment by ghost** [comment]
Removing the machine made making the void miner tier3 extremely hard as it requires a shit ton of Prismarine Shard which was previously obtained by disassembling walls of the Ocean monument.
Please make Prismarine Bricks (and quartz block) grindable.
