### ISSUE TITLE
All quests can be reclaimed when a new player joins the party

### ISSUE THREAD

**Issue by LaTrissTitude** [FTBTeam/FTB-Continuum#70]
* **Modpack Version**: 1.0.2

* **Issue**: Glitch about quest reward duplication when a new member joins a quest party

* **Link to Log or Crash File Paste**: no log as it doesn't crash

* **Is it Repeatable?**: Yes, just join a new member in the quest party after completing a few quests and everyone should be able to reclaim every reward.

* **Mod/s Affected**: The questing mod maybe? not sure at all.
* **Known Fix**: --

**Comment by aaronhowser1** [comment]
They can be reclaimed by the entire party, not just the new member? You should put this in the [Better Questing issue tracker](https://github.com/Funwayguy/BetterQuesting/issues) too

**Comment by LaTrissTitude** [comment]
every member of the party

**Comment by tfox83** [comment]
fixed in 1.3.0
