### ISSUE TITLE
[1.0.2] Incorrect Pam's Harvestcraft IDs for Garden Drops

### ISSUE THREAD

**Issue by Vollauro** [FTBTeam/FTB-Continuum#71]
* **Modpack Version**: 1.0.2

* **Issue**: Numerous Item IDs under the drops section in the Pam's Harvestcraft's harvestcraft.cfg config file are incorrect. This causes the corresponding items to not drop when their respective gardens are broken.
shadedGarden has **harvestcraft:whseeditemushroomseeditem** and **harvestcraft:tealeafseeditem**
tropicalGarden has **harvestcraft:coffeebeanseeditem**
windyGarden has **harvestcraft:mustardseedsseeditem**

* **Mod/s Affected**: Pam's Harvestcraft.

* **Known Fix**: Change the incorrect item IDs to the correct item IDs
        **harvestcraft:whseeditemushroomseeditem** should be **harvestcraft:whitemushroomseeditem**
        **harvestcraft:tealeafseeditem** should be **harvestcraft:teaseeditem**
        **harvestcraft:coffeebeanseeditem** should be **harvestcraft:coffeeseeditem**
        **harvestcraft:mustardseedsseeditem** should be **harvestcraft:mustardseeditem**

**Comment by tfox83** [comment]
fixed in dev, thanks
