### ISSUE TITLE
[Suggestion] Remove a couple OpenBlocks items and replace them with others

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Continuum#72]
* **Modpack Version**: 1.0.2

* **Issue**: A lot of things in OpenBlocks have much better alternatives in other mods, like graves and the /dev/null.  [Tomb Many Graves](https://minecraft.curseforge.com/projects/tomb-many-graves-2) and [/dank/null](https://minecraft.curseforge.com/projects/dank-null) have better implementations of their items than OpenBlocks'.

**Comment by tfox83** [comment]
going to close this for now as the pack is now in a released state
