### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Nyagi** [FTBTeam/FTB-Continuum#73]
FTBContinuum-1.02-1.12.2.zip
Installation:
For some reason twitch wont actually start the download for this pack (or any pack for that matter), and FTB wont open up either.
I realize this isn't really the place to be reporting this but i don't know where else this would even be reported
Thanks in advance~

"Cannot find child addon: 236730"

**Comment by Kuktar** [comment]
Try signing out and back in of twitch launcher. This happened to me
recently.

**Comment by tfox83** [comment]
You will need to report this to Twitch Desktop support. Thanks
