### ISSUE TITLE
[Quest Issue]Quest About Hemp Seed

### ISSUE THREAD

**Issue by SihenZhang** [FTBTeam/FTB-Continuum#74]
* **Modpack Version**: 
1.0.2
* **Issue**: 
The quest about Hemp Seed says that hemp seeds will give much more **Seed Oil**.
![](https://i.imgur.com/W31WjiI.png)
Actually, hemp seeds will give more **Plant Oil** but **NOT Seed Oil**.

**Comment by tfox83** [comment]
fixed in dev
