### ISSUE TITLE
Quest log empty after crash

### ISSUE THREAD

**Issue by Shmee** [FTBTeam/FTB-Continuum#76]
* **Modpack Version**:  1.0.2

* **Issue**: Quest log is empty

![screenshot](https://i.imgur.com/DRkCN0Z.png)

The game might have been open during a blue screen I had yesterday. Is there any way to refresh/reset the quests?

**Comment by tfox83** [comment]
I suggest reinstalling the pack fresh and move your saved worlds/options files over and try again.

**Comment by aaronhowser1** [comment]
you could also use the command `/bq_admin default load` to reload the quests
