### ISSUE TITLE
Disabling Applied Energistics 2 channels causes default "normal-mode" crafting recipes to not be removed.

### ISSUE THREAD

**Issue by Lomztein** [FTBTeam/FTB-Continuum#78]
* **Modpack Version**: FTB Continuum 1.1.0

* **Issue**: Disabling Applied Energistics channels in config causes crafting recipes to not be set up correctly. Seems to occur due to channel-related items no longer existing, causing an exception when expert-mode crafting recipes that includes said non-existing items are added. While expert-mode recipes are still there, the default recipes are available as well, due to channels being disabled, as shown here: https://i.imgur.com/TgNqODJ.png

    Recipes that in requires something that doesn't exist without channels seems to just not exist any more, when channels are disabled.

* **Link to Log or Crash File Paste**: This shows up in-game when a world is loaded with channels disabled: https://i.imgur.com/AmhEQvy.png. I can't seem to find any logs related to it, though they might just have been drowned out by all the logging that happens when a world is loaded.

* **Is it Repeatable?**: Yes, by changing "features/networkfeatures/B:Channels to false in AppliedEnergistics2/AppliedEnergistics2.cfg config file.

* **Mod/s Affected**: Applied Energistics 2

* **How to Fix**: I suppose the simplest solution would be to remove crafting dependency on channel-dependent items. However this solution could quickly spiral out of control. An alternative, but perhaps impossible solution, could be to have the removed items still exist, but just be non-functional, so that they may be used in crafting recipes, though that might be a task for AE's devs instead.

I understand this is not something you'd might _want_ to fix, since channels could be considered an expert-level feature, and I'll respect that decision if that is so. I personally don't like the channel system, since I feel that it puts a very hard limit on the complexity and size of a network, which working around generally isn't all that fun in my opinion, and often leads to messy and unclean solutions, which also typically only prolong the inevitable running out of channels for the increasingly complicated autocrafting operations.

God I hope this is understandable, it's like 3 AM and I should have been asleep two hours ego. If something needs clearification, I'll be happy to oblige, _tomorrow_.

**Comment by tfox83** [comment]
Sorry with a pack of this many changes I cannot support config changes of that level.  It was designed to use channels in this pack. Sorry.
