### ISSUE TITLE
Server locks up when adding an Efab Crafting Grid to an Efab Multiblock

### ISSUE THREAD

**Issue by Jimmy469** [FTBTeam/FTB-Continuum#79]
* **Modpack Version**: 1.0.2 and 1.1.0

* **Issue**: When I add an Efab Crafting Grid to an existing Efab multiblock, my server (in SP, the client as well) locks up indefinitely. When placed, the crafting grid looks like a slab (like the TiCon slab crafting tables from 1.7), instead of a full block.

* **Link to Log or Crash File Paste**: https://paste.feed-the-beast.com/view/b6cc7c0b (from my client in SP). Subsequent stall reports (every 30s) have the server stalled at the same place, with most of the thread pool waiting on the same lock (See https://paste.feed-the-beast.com/view/8f56c58f after a few minutes).

* **Is it Repeatable?**: In my save, it happens as soon as I add the first Efab to a large, existing multiblock. Save file here: https://s3-us-west-1.amazonaws.com/jimmyminecraftbackups/Jimmy.zip

* **Mod/s Affected**: Efab

* **Known Fix**: Unknown.

**Comment by tfox83** [comment]
This will be fixed in next version of eFab

**Comment by tfox83** [comment]
Fixed in Dev
