### ISSUE TITLE
Bring back Crafting Station from Tinkers

### ISSUE THREAD

**Issue by alexsch01** [FTBTeam/FTB-Continuum#8]
The Crafting Station make Tinkers complete and disabling it removes the experience for everyone (BaconDonut on stream)

**Comment by tfox83** [comment]
Once the outstanding dupe bugs are fixed and the crafting lag is mitigated I would be glad to re-enable it :)

**Comment by thundr** [comment]
For those of us that want to follow the progress on the mod's tracker, what bugs are you referring to? 
https://forum.feed-the-beast.com/threads/dupe-bug-in-tc-crafting-table.269531/
This one solved months ago?
https://github.com/SlimeKnights/TinkersConstruct/issues/3399
This one solved as well?

Is there another you are referring to?

**Comment by 016Nojr** [comment]
This issue happened after that

**Comment by thundr** [comment]
So, again, do you have an issue tracker link?

**Comment by alexsch01** [comment]
ok @tfox83 question..: What kind of dupe bug is it and does FastBench mod fix the lag (if the dupe bug is with inventories directly next to crafting station, why don't you just disable that feature of tinkers)?
