### ISSUE TITLE
Treated Wood Planks - Fluid Transposer Recipe

### ISSUE THREAD

**Issue by mtimyself** [FTBTeam/FTB-Continuum#81]
* **Modpack Version**: 1.1.0

* **Issue**:
Any wood log plus 125mb of Creosote should make Treated wood (which is half the Creosote price of EFab). http://prntscr.com/jm5f5f
The Fluid Transposer does not accept wood logs into the input slot.

**Comment by tfox83** [comment]
They are intended to go through eFab, those have been blocked, I cannot control some recipes from not showing in JEI from some mods, TE being one of them.
