### ISSUE TITLE
Better Questing interface is blank.

### ISSUE THREAD

**Issue by pyure** [FTBTeam/FTB-Continuum#84]
* **Modpack Version**:  1.0.2

* **Issue**: Better Questing interface is blank.

![image](https://user-images.githubusercontent.com/8617528/40522280-198183c2-5f9e-11e8-817c-972c29ca628f.png)

Possibly related to or duplicate of https://github.com/FTBTeam/FTB-Continuum/issues/76

I re-downloaded the pack and copied my save-files in.  Problem persists with save, but not with a new world.

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Always happens when attempting to use the interface (including after restarting minecraft and re-downloading pack)

**Comment by pyure** [comment]
I've also attempted to replace the json files in the betterquesting folders with their backups.  For instance, QuestDatabase.json should have nodes for every quest as far as I can tell from the backup.  But the current file only contains

>  {
>   "build:8": "3.5.256",
>   "format:8": "2.0.0",
>   "questDatabase:9": {},
>   "questLines:9": {},
>   "questSettings:10": {
>     "betterquesting:10": {
>       "livesdef:3": 3,
>       "home_anchor_y:5": 0.0,
>       "livesmax:3": 10,
>       "home_anchor_x:5": 0.5,
>       "editmode:1": 1,
>       "hardcore:1": 0,
>       "home_image:8": "betterquesting:textures/gui/default_title.png",
>       "home_offset_x:3": -128,
>       "home_offset_y:3": 0
>     }
>   }
> }

Upon restarting the modpack, the "proper" contents get replaced with above again.

**Comment by pyure** [comment]
I've noticed that the contents even of the backup are not valid json.  I've compared the file against a questDatabase.json from a fresh install, and its missing 10,000 lines.

Replacing my save-folder questDatabase.json with a fresh one from the re-downloaded pack fixed the blank interface (but sacrificed all progress)

I'm working to see if I can restore my progress.

**Comment by Kuktar** [comment]
I fucking hate better questing. i hate that ftb decided to use it instead of better advancments.


https://i.imgur.com/bqrmbbJ.png

mine is blank all the time

**Comment by pyure** [comment]
I was able to restore my progress by replacing QuestProgress.json with backup/pre-251/QuestProgress_backup_pre-251.json

@tfox83 as far as I'm concerned you can close this as resolved, but I recommend making something from above a KB item.

**Comment by Kuktar** [comment]
Lucky you. I just tried this and it's still blank.

**Comment by aaronhowser1** [comment]
Try using the command `/bq_admin default load` maybe. The quests are stored in the save, and that command replaces the save's quest with the config's quest.

@Kuktar that looks to be an issue with Vivecraft (which I assume is what that is). You might want to also try changing BQ themes or, if possible with Vivecraft, zoom in with the scroll wheel equivalent on a Vive wand. You could also post an issue on the [Better Questing](https://github.com/Funwayguy/BetterQuesting/issues) or [Vivecraft](https://github.com/jrbudda/Vivecraft_112/issues) issue trackers.

**Comment by Kuktar** [comment]
Thanks aaronhowser1 I will try that!
