### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kuktar** [FTBTeam/FTB-Continuum#85]
So in the modpack in the JEI window when you look at the various ores it says for instance (iron ore spawns from y0 to y64) how did that get put into the modpack. I modified what levels the ores spawn at and can not find how to change that tooltip. Thank you in advance for any help.

**Comment by aaronhowser1** [comment]
These are added by scripts with CraftTweaker. Here's the one that adds the Crafting Station disabled tooltip:

`#<tconstruct:tooltables>.addTooltip(format.darkRed("Disabled due to dupe bugs!"));`

**Comment by Kuktar** [comment]
awesome thank you
