### ISSUE TITLE
Lexica Technica triggers wrong

### ISSUE THREAD

**Issue by derNiklaas** [FTBTeam/FTB-Continuum#86]
* **Modpack Version**: 1.0.2

* **Issue**: You can trigger the Lexica Technica with another IE:tool (for example with the Engineer's Hammer)  

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: IE, Better Questing

* **Known Fix**: N/A

**Comment by aaronhowser1** [comment]
Fixed in next update
