### ISSUE TITLE
IE power pack can't be attached to chestplates

### ISSUE THREAD

**Issue by malte0811** [FTBTeam/FTB-Continuum#89]
IE report: BluSunrize/ImmersiveEngineering#2900
Issue is as per title. This is caused by line 78 of ImmersiveEngineering.zs: 
`recipes.remove(<immersiveengineering:powerpack>);`
The recipe for attaching power packs to chestplates (and removing them again) has a power pack as the default output, so it is removed along with the normal recipe for the power pack. A fix would be to replace the line with
`recipes.removeByRecipeName("immersiveengineering:armor/powerpack");`.

**Comment by tfox83** [comment]
Fixed, thanks for the report and suggestion
