### ISSUE TITLE
Remove Pulverizer recipes using mods.thermalexpansion.Pulverizer.removeRecipe(IItemStack) 

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Continuum#90]
* **Modpack Version**: 1.1.0

* **Issue**: `mods.thermalexpansion.Pulverizer.removeRecipe(IItemStack)` lets you remove recipes from the Pulverizer without having to readd them to other machines. This would remove confusion about the recipes I think, as well as remove JEI clutter.

**Comment by tfox83** [comment]
this has not worked since the overhaul to TE.  Once his build with his own recipes is public I can remove them via that method.
