### ISSUE TITLE
Remove ETech block recipes that use their crystals

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Continuum#91]
* **Modpack Version**: 1.1.0

* **Issue**: Ionite, for instance, still has a recipe that lets you make it from Ionite Crystals, which adds confusion about how to get it. I know the tooltip is there, but only on the Ionite Block and not the crystals or the other Ionite variants.

**Comment by tfox83** [comment]
removed, thanks for the report
