### ISSUE TITLE
Re-add late game ProjectE items

### ISSUE THREAD

**Issue by aaronhowser1** [FTBTeam/FTB-Continuum#93]
* **Modpack Version**: 1.12

* **Issue**: A lot of ProjectE items were removed, even though they're extremely late game. Interdiction Torches, Nova Catalysts/Cataclysms, the Stones, stuff like that have no real reason to be removed. Even the more OP stuff should be added back in imo, assuming they'd be gated with the other ProjectE items. Having most of the items disabled removes the satisfaction of getting to the late game. I understand removing items like the Watch of Flowing Time and other's that could be laggy or buggy, but the fun stuff should be added back in, even if they're OP. They're supposed to be OP, they're the last things you're going to be crafting in the modpack.

* **Mod/s Affected**: ProjectE

**Comment by reaganmcf** [comment]
I agree, one of my favorite parts of Project Ozone was getting the OP ProjectE items, it's what keeps you going throughout the pack

**Comment by tfox83** [comment]
I am overhauling the PE stuff, will be available in a couple updates from now

**Comment by tfox83** [comment]
added back tools and some items for now
