### ISSUE TITLE
server issue

### ISSUE THREAD

**Issue by harrynhj** [FTBTeam/FTB-Continuum#94]
* **Modpack Version**: 1.1.0

* **Issue**: can not join the server with version 1.1.0

* **Link to Log or Crash File Paste**: 
Internal Exception: com.google.common.util.concurrent.UncheckedExecutionException:
net.minecraftforge.fml.common.L oaderExceptionModCrash: Caught exception from Minecraft Forge (forge)

* **Is it Repeatable?**: yes

* **Mod/s Affected**: forge? not sure

**Comment by Suripe** [comment]
I have the same problem.

**Comment by tfox83** [comment]
Did you update forge, I am not able to reproduce this.
