### ISSUE TITLE
logWood ore excavation

### ISSUE THREAD

**Issue by spdkils** [FTBTeam/FTB-Continuum#95]
* **Modpack Version**: 1.02

* **Issue**: logWood is not enabled for ore excavation. I assume this is just an oversight, since it's pretty tedious to get it, and requires enderperls etc.

* **Link to Log or Crash File Paste**: No crash

* **Is it Repeatable?**: Yup

* **Mod/s Affected**: Ore Excavator

* **Known Fix**: Enable logWood. in the ore excavation file(Blacklist reversed)

**Comment by hresad** [comment]
I wouldn't be so sure that it's an oversight since they give you the option of automating a wood farm with Steve's Cart even before you go to the nether to get manyullyn.

**Comment by spdkils** [comment]
Sure, but Steve's carts is actually the odd man out in this mod. Not to many recipe tweaks. ( I think treated wood may be in order... but.. yeah, just to gate that.)

**Comment by tfox83** [comment]
Make a tree farm.  We never intended for wood to be in the config.
