### ISSUE TITLE
Renable AE energy cell

### ISSUE THREAD

**Issue by modmuss50** [FTBTeam/FTB-Continuum#96]
The AE energy cell is required when doing large auto crafts as the normal buffer isnt enough.

Suggestion taken from:

https://twitter.com/Soaryn117/status/999443205555982336

**Comment by tfox83** [comment]
I just tested with a controller and multiple full high voltage powercells, I couldn't get anything to not function unless I am missing something?

**Comment by tfox83** [comment]
Closing as I am not seeing an issue in my testing thus far.

**Comment by zeryl** [comment]
Just to re-bump this, I have this issue today.  End-game, cryo-stabilized fluiducts, from 1.4mil fusion reactor, I cannot use an ME IO Port to move a full fluid drive, to another drive, without a brown-out in ME.  Perhaps this can help you locate the issue.
