### ISSUE TITLE
Bag of Holding loses contents if moved in inventory while in Creative

### ISSUE THREAD

**Issue by kerfufflator** [FTBTeam/FTB-Continuum#97]
* **Modpack Version**: Continuum 1.0.2

* **Issue**: The Bag of Holding from Extra Utilities 2 will have its inventory erased if you move the bag to a different slot in your inventory while in creative. Hitting any key bind that reorganizes the inventory will do it as well.

* **Link to Log or Crash File Paste**: n/a

* **Is it Repeatable?**: Yes

* **Mod/s Affected**: Extra Utilities 2

**Comment by NamitSingh14** [comment]
This has been an issue ever since the bag of holding was introduced. I think you should report this to the mod author as this is not a modpack issue.

**Comment by tfox83** [comment]
This has been a known issue since 1.10, going to close this as its a creative issue.
