### ISSUE TITLE
Environemental tech block's wont spawn

### ISSUE THREAD

**Issue by Sergent78** [FTBTeam/FTB-Continuum#98]
* **Modpack Version**: 1.0.2

* **Issue**: Environemental tech block's ( Litherite / Erodium / Kyronite / Pladium / Ionite / lonsdaleite ) wont spawn on planete with the same name, using Advanced Rocketery 

* **Link to Log or Crash File Paste**: No crash / Log

* **Is it Repeatable?**: Go to "Litherite" planete, explore the world, no Litherite spawn

* **Mod/s Affected**: Environementale Tech / Advanced Rocketery / Quest Book

* **Known Fix**: I don't know.

**Comment by idyllist123** [comment]
Same case for me but im in the server upgraded from 1.0.2 to 1.1.0

**Comment by Sergent78** [comment]
i forgot to say i'm playing on server, my bad ^^"

**Comment by tfox83** [comment]
In a fresh world I TPd to DIM30 which is the Litherite planet and its spawning fine for me, same with the other ET resources on the other planets.

![image](https://user-images.githubusercontent.com/4246308/40801574-1712ef98-64c8-11e8-81ce-7f6b720891d5.png)

**Comment by KuroPeach** [comment]
in a server?@tfox83 I cant't found it too at a server,version 1.1.0
