### ISSUE TITLE
Efab Crafting for Electronic Circuit and Advanced Electronic Circuit not Working

### ISSUE THREAD

**Issue by hk21702** [FTBTeam/FTB-Continuum#99]
* **Modpack Version**:  1.1.0

* **Issue**: Efab crafting for Electronic Circuit and Advanced Electronic Circuit not working. All conditions met, and the craft button is allowed to be clicked, and animations/sounds start for a split second and then everything stops. Items stay in the table, and no output is given. https://gyazo.com/38d937b9c31aec08a6440d91ea9adc5e - Gif of what I'm describing. 

* **Link to Log or Crash File Paste**: N/A

* **Is it Repeatable?**: Yes. Repeatable on a server, and in single player.

* **Mod/s Affected**: EFab, Tech Reborn

* **Known Fix**: None besides using the Empowerer method but that's slow

Edit: Electronic Circuit crafting in EFab also does not work.

**Comment by Menasos** [comment]
When you hover over "start" it says you need 5000rf/t because you have 4gear boxes, which would be 20 RF Storage blocks.
I had this problem and it took me a while to figure out what it was.
Hope this was able to help you out o/

**Comment by hk21702** [comment]
Oh okay. Didn't realize. Tested and it works.
